### ISSUE TITLE
prompt=none support

### ISSUE THREAD

**Issue by amvanbaren** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1001]
@jricher I'm building an OpenID Connect auth service for two clients (a website and a REST api). Once the user has filled out  the registration form and is signed up, there is no need to ask for consent. I tried to implement the "prompt=none" in combination with the id_token_hint parameter, but I keep getting "interaction_required null null" as error message.
Is "prompt=none" supported by the server?

**Comment by jricher** [comment]
Yes, it's supported, but for it to come back with a positive response you need to whitelist the site that's being requested.

**Comment by amvanbaren** [comment]
Thanks @jricher, works like a charm!
