### ISSUE TITLE
ClientDetailsEntityJsonProcessor does not read AccessTokenValiditySeconds property from json content

### ISSUE THREAD

**Issue by danielgpm** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1002]
The [ClientDetailsEntityJsonProcessor](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-common/src/main/java/org/mitre/openid/connect/ClientDetailsEntityJsonProcessor.java) does not read the values of `accessTokenValiditySeconds` and `refreshTokenValiditySeconds` coming from the json configuration. 

For instance: A json file containing client configuration with:
> {
>  "client_id": "client-1",
> "client_name": "client X",
>  "redirect_uris": [
>    "http://some.website.com/"
>  ],
... 
> "access_token_validity_seconds": 86401,
>  "refresh_token_validity_seconds": 86401,
> ..
}

will results in a ClientDetailsEntity object with default values (0) for both properties.

**Expected:** the ClientDetailsEntityJsonProcessor class should read and set all the valid properties from the json configuration.

**Comment by jricher** [comment]
That processor is only used for the dynamic client registration, which doesn't allow the client to specify these values. They should be filled in with defaults from the system instead.

The client API available to admins (from `/api/clients`) does allow you to set the values, but it doesn't use this processor class.
