### ISSUE TITLE
Extending Entities

### ISSUE THREAD

**Issue by merric** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1003]
I'm working on implementing an overlay for a custom IDP server. I have the spring contexts up and the server working, but I'm at a loss to how to actually change the data model without overlaying the entire project. I may be missing a small piece. 

What I've done so far is create a test overlay for UserInfo. I've clone the entire class and interface to may project. I've added one new field and accounted for the field across the class. I've added the field in the database. I've annotated my entity with @Primary thinking it will be the one used. 

Unfortunately that doesn't seem to be the class used at any point in the server. The imports of the server files still point to the original entity so it seems like my class would never be used. 

My biggest question is how to implement even small changes like additions of columns or small refactors of the data model with the overlay without changing the core server code.

**Comment by jricher** [comment]
The UserInfo object is meant to be extended in an overlay just like you're describing. However, you also need to overlay the repository that shuffles the classes in and out of the DB. That's what you mark with @Primary, not the entity. Also make sure that the new repository class you have is actually instantiated as a bean, either by setting the component scan in the XML configuration or explicitly declaring it as its own bean in the XML configuration.

**Comment by merric** [comment]
I really appreciate your quick reply. I'll work on that right now. 

I had one last question. Do you think I would also need to overlay the Server and the Interceptor? They have methods that expect return types of the old entity. I would assume it would autocast it or fail if the repository returns a the new entity.

**Comment by praseodym** [comment]
As an example, you could take a look at our overlay that also extends UserInfo: https://github.com/WISVCH/connect

**Comment by merric** [comment]
Thanks, Mark! That confirms the strategy we were using. Got it working with some test columns yesterday.
