### ISSUE TITLE
RQP Claims error - Claims redirect did not match the registered values.

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1004]
When performing claims gathering flow and the requesting user has already acquired an AAT and a permission ticket, a RQP claims command is called as such:

<code>http://uma.noshchartingsystem.com/uma-server-webapp/rqp_claims?ticket=94acfdf9-30c5-4e22-9a0b-080f04624b3b&redirect_uri=https://noshchartingsystem.com/nosh-sso/uma_auth&client_id=e312607b-3614-429a-8086-0c9d5fb9ee17&state=4f961f409b9c17b5cbb4cdd9a9fe8127</code>

The result is an initial redirect to the external login page of the UMA server.  After entering that, then it throws this response:
<code>{"error":"invalid_grant","error_description":"Claims redirect did not match the registered values."}</code>

I've verified that the registered client ID has the redirect URI (in this case: https://noshchartingsystem.com/nosh-sso/uma_auth) already registered.  So why is it not being matched?

**Comment by jricher** [comment]
The claims redirect uri and the redirect URI are different values. The UI hasn't been updated to allow access to that value yet (in the works right now) so you'll need to use the API for that.
