### ISSUE TITLE
Claims redirect URI declaration in dynamic client registration

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1005]
I tried to declare a claims_redirect_uris entry (since it is a separate field) through dynamic client registration.  It appears that it did not save the entry.  As mentioned in issue #1004, only API access will allow entry of the claims redirect URI.  Will there be the ability for dynamic clients to declare the claims redirect URI in the future?

**Comment by jricher** [comment]
This has been fixed on a branch and will be ported into the main base soon.
