### ISSUE TITLE
RPT endpoint returns "needs_info"

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1006]
RPT endpoint returns "needs_info" error despite successfully getting an AAT, permissions ticket, and "claims_submitted" response from RQP claims endpoint (used external login).  The RPT endpoint was called with the AAT and permissions ticket immediatly after the RQP claims endpoint.  I've verified that the email address entered in the external login is identical to that which was declared as a required claim ("email") for various policies and scopes as shown below.

Below is the response:

<code>{"error":"need_info","error_details":{"requesting_party_claims":{"redirect_user":true,"ticket":"16c087ed-3017-45b2-8198-2cde489d05f5","required_claims":[{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":[]}]}}}</code>

Below is the ../api/resourceset/1 as an example:

<code>{"id":1,"name":"Patient","uri":null,"type":null,"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1"],"iconUri":"https://noshchartingsystem.com/i-patient.png","owner":"noshtest","clientId":"64945dfa-a856-4880-b9c6-e4196629ed3b","policies":[{"id":1,"name":null,"claimsRequired":[{"id":1,"name":"email","friendlyName":null,"claimType":null,"value":"shihjay2@noshchartingsystem.com","claimTokenFormat":[],"issuer":[]},{"id":2,"name":"email_verified","friendlyName":null,"claimType":null,"value":1,"claimTokenFormat":[],"issuer":[]},{"id":3,"name":"sub","friendlyName":null,"claimType":null,"value":"d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","claimTokenFormat":[],"issuer":[]}],"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1"]},{"id":2,"name":null,"claimsRequired":[{"id":4,"name":"email","friendlyName":null,"claimType":null,"value":"shihjay2@noshchartingsystem.com","claimTokenFormat":[],"issuer":[]},{"id":5,"name":"email_verified","friendlyName":null,"claimType":null,"value":1,"claimTokenFormat":[],"issuer":[]},{"id":6,"name":"sub","friendlyName":null,"claimType":null,"value":"d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","claimTokenFormat":[],"issuer":[]}],"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1"]},{"id":3,"name":null,"claimsRequired":[{"id":7,"name":"email","friendlyName":null,"claimType":null,"value":"shihjay2@noshchartingsystem.com","claimTokenFormat":[],"issuer":[]},{"id":8,"name":"email_verified","friendlyName":null,"claimType":null,"value":1,"claimTokenFormat":[],"issuer":[]},{"id":9,"name":"sub","friendlyName":null,"claimType":null,"value":"d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","claimTokenFormat":[],"issuer":[]}],"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1"]},{"id":4,"name":null,"claimsRequired":[{"id":10,"name":"email","friendlyName":null,"claimType":null,"value":"shihjay2@noshchartingsystem.com","claimTokenFormat":[],"issuer":[]},{"id":11,"name":"email_verified","friendlyName":null,"claimType":null,"value":1,"claimTokenFormat":[],"issuer":[]},{"id":12,"name":"sub","friendlyName":null,"claimType":null,"value":"d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","claimTokenFormat":[],"issuer":[]}],"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1"]},{"id":5,"name":null,"claimsRequired":[{"id":13,"name":"email","friendlyName":null,"claimType":null,"value":"shihjay2@noshchartingsystem.com","claimTokenFormat":[],"issuer":[]},{"id":14,"name":"email_verified","friendlyName":null,"claimType":null,"value":1,"claimTokenFormat":[],"issuer":[]},{"id":15,"name":"sub","friendlyName":null,"claimType":null,"value":"d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35","claimTokenFormat":[],"issuer":[]}],"scopes":["http://uma.noshchartingsystem.com/nosh/fhir/Patient?identifier\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Medication","http://uma.noshchartingsystem.com/nosh/fhir/Practitioner","http://uma.noshchartingsystem.com/nosh/fhir/Patient?_id\u003d1","http://uma.noshchartingsystem.com/nosh/fhir/Patient/1"]}]}</code>

**Comment by jricher** [comment]
Your required claims don't have an issuer, I doubt the matcher is going to work like that. Or are you using a custom matcher? 

How did you get the policy set up? The ui should only allow for entering an email address on a domain that's hosting an oidc server. Did you change that?

**Comment by shihjay2** [comment]
Policies were set using the resource_set_registration_endpoint through CURL and the resource server was a registered client of the UMA server.

Initially I tested the UI as a way to set an email address (claim) but I wanted to figure out a way to do it through CURL or an API which I couldn't find documentation for.  So I tracked the changes on the databases and reverse engineered it so I could make add the claim as a direct database call (since the resource server is on the same machine as the UMA server) corresponding to the policy_id.  I inserted the name ('email', 'sub', 'email_verified')  and the claim value to the claim table,  I also updated the policy scope table with the correct owner_id matching the policy_id.

The domain name "noshchartingsystem.com' also happens to host an oidc server, but it never came up with any errors initially when I ran the UI test first.

**Comment by shihjay2** [comment]
I did notice that when I added a claim to the policy in earlier versions (this was in October, 2015), it looked like the issuer was not assigned.  I retested it on the 1.25 snapshot version through the UI and it does designate the issuer.

Once I got that policy corrected, I tested the RPT procedure again and I'm still getting an error but this time has the issuer listed.  Not sure if there is something else going on that's not being designated correctly.

<code>
{"error":"need_info","error_details":{"requesting_party_claims":{"redirect_user":true,"ticket":"c4f369c1-b6d9-47b5-a613-0bbcedec4620","required_claims":[{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"email_verified","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]},{"name":"sub","friendly_name":null,"claim_type":null,"claim_token_format":[],"issuer":["http:\/\/uma.noshchartingsystem.com\/uma-server-webapp\/"]}]}}}
</code>

**Comment by jricher** [comment]
If you try to back fill this into the database without using the API or interface, it's probably not going to work very well for you. The webfinger interface will only work for a very specific setup, and it looks like what you have isn't doing that.

**Comment by shihjay2** [comment]
If some of the settings were edited afterwards using the UI, which I have
done to fill the issuer value, would it still not work correctly through
the webfinger interface?  One of my earlier replies was the addition of the
issuer variable through the UI and it still gives off the needs_Info error
as indicated previously.
Furthermore what is the API endpoint to establish a resource policy as it's
not documented in the wiki?   I would like to use the API if possible.

**Comment by jricher** [comment]
I think you're still misunderstanding how the policy engine as deployed currently works, let me see if I can explain further. The current UI/API works by taking in an email address, using webfinger to look up the OpenID Connect Issuer for that domain, and then setting a policy such that any account that comes in with that particular email address in the `email` claim along with the issuer discovered in the webfinger lookup in the `iss` claim to be valid. 

It looks like you're trying to use the address `shihjay2@noshchartingsystem.com` as your RqP address. This translates, using webfinger, to the URL `https://noshchartingsystem.com/.well-known/webfinger`, which doesn't exist. That's why the lookup fails. Your server is running on https://uma.noschartingsystem.com/uma-server-webapp/`, which is both a different hostname and a different path. You can have the lookup forward from one to the other, but you've got to set that up with a discovery document. Said document also needs to be available from HTTPS, not HTTP.

**Comment by shihjay2** [comment]
That's strange.  I used the command
<code>https://noshchartingsystem.com/.well-known/webfinger?resource=acct%3Ashihjay2%40noshchartingsystem.com&rel=http%3A%2F%2Fopenid.net%2Fspecs%2Fconnect%2F1.0%2Fissuer</code>
And here is the response.
<code>{"subject":"acct:shihjay2@noshchartingsystem.com","links":[{"rel":"http://openid.net/specs/connect/1.0/issuer","href":"https://noshchartingsystem.com/openid-connect-server-webapp/"}]}</code>
So webfinger works for the domain noshchartingsystem.com, I believe.

Maybe I'm not understanding the purpose of have an AS if it has to be on the same domain as the requesting party email address based on what you said.  I had the impression that the UMA server (AS) could be on a different domain (which I plan to do in the future) and I have an OIDC-based IdP that is managing physician logins on a different server.  Again, I'm planning to create a system where there are multiple AS's (patients) and referencing a remote IdP (physicians).

**Comment by jricher** [comment]
They can be on different domains in the protocol, but our implementation is very limited as to what kinds of policies it can express. These policies consist of webfinger and email being on the same domain.
