### ISSUE TITLE
Webfinger "too picky"

### ISSUE THREAD

**Issue by jmandel** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1008]
The following fails:

1. Visit https://client.webfinger.net
2. Enter "alice@healthauth.org"

(Alternatively, visit https://client.webfinger.net/lookup?resource=alice%40healthauth.org)

Results in:

> 21:52:49 Looking up WebFinger data for acct:alice@healthauth.org
> 21:52:49 GET https://healthauth.org/.well-known/webfinger?resource=acct%3Aalice%40healthauth.org
> 21:52:49 400 Bad Request
> 21:52:49 Falling back to WebFist protocol
> 21:52:49 GET https://webfist.org/.well-known/webfinger?resource=acct%3Aalice%40healthauth.org
> 21:52:50 Error getting JRD: Get https://webfist.org/.well-known/webfinger?resource=acct%3Aalice%40healthauth.org: urlfetch API error 12

I know http://openid.net/specs/openid-connect-discovery-1_0-21.html#IssuerDiscovery says OIDC technically only requires a server to respond with a link relation of `http://openid.net/specs/connect/1.0/issuer`, but IMO a request without `rel` should work :-)

Especially since https://tools.ietf.org/html/rfc7033#section-4.3 says:
```
   When issuing a request to a WebFinger resource, the client MAY
   utilize the "rel" parameter to request only a subset of the
   information that would otherwise be returned without the "rel"
   parameter.  When the "rel" parameter is used and accepted, only the
   link relation types that match the link relation type provided via
   the "rel" parameter are included in the array of links returned in
   the JRD.  If there are no matching link relation types defined for
   the resource, the "links" array in the JRD will be either absent or
   empty.  All other information present in a resource descriptor
   remains present, even when "rel" is employed.
```

**Comment by jricher** [comment]
Thanks, right now the server's discovery endpoints require the rel= property with the OIDC value, but that can easily be relaxed.

**Comment by jmandel** [comment]
Merci!
