### ISSUE TITLE
 Invalid redirect

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1009]
Hi,

I was testing simple-web-app connecting to overlay server locally and everything seems to be fine. But When I deploy overlay to one of our dev environment , I randomly get this error from server. It works some times if I restart simple-web-app. Some how DefaultRedirectResolver.redirectMatches could not parse my redirect url or something because my protocol (http) ,hostname (localhost) and my approved redirects for the client path starts with \ same as my redirect uri in the request. Locally it works great and I dont have any issues. I am having the same database copy locally and on dev server. I am using staticClientConfiguration in simple-web-app and has redirect-uri as below

    <property name="redirectUris">
                            <set>
                                <value>http://localhost:8089/simple-web-app/openid_connect_login</value>
                            </set>
                        </property>

ERROR from server:

Error: invalid_grant

There was an error processing your request. The server's message was:

 Invalid redirect: http%3A%2F%2Flocalhost%3A8089%2Fsimple-web-app%2Fopenid_connect_login does not match one of the registered values: [http://localhost:8080/]

When I inspect the authorization request in simple-web-app connecting to my dev server:

https://mydomain/authserver/authorize?response_type=code&client_id=clientid&scope=openid+email+address+profile+phone&redirect_uri=http%3A%2F%2Flocalhost%3A8089%2Fsimple-web-app%2Fopenid_connect_login&nonce=bcd7994c79f3&state=39574afef63ae

Thanks
Mallikarjun

**Comment by jricher** [comment]
Read the error that the server's giving you more closely: it's saying that your new redirect URI, which starts with `http://localhost:8089/`, doesn't match any of the registered redirect URIs, which in your case only has `http://localhost:8080/'. The port numbers matter and must match exactly.

**Comment by mpeddagolla** [comment]
Hi, appreciate for your reply. I have actually verified that method which checks for approved redirect URI and it doesn't seem to include the port. This is what I see in the actual compare which will only check for protocol and host. But still I have added 'http://localhost:8089' to client redirect uri list just to make sure but still doesn't work. I just started using this library since last week so I am  still exploring.

    protected boolean redirectMatches(String requestedRedirect, String redirectUri) {
		try {
			URL req = new URL(requestedRedirect);
			URL reg = new URL(redirectUri);

			if (reg.getProtocol().equals(req.getProtocol()) && hostMatches(reg.getHost(), req.getHost())) {
				return StringUtils.cleanPath(req.getPath()).startsWith(StringUtils.cleanPath(reg.getPath()));
			}
		}
		catch (MalformedURLException e) {
		}
		return requestedRedirect.equals(redirectUri);
	}

Error I see on dev server

    Error: invalid_grant

    There was an error processing your request. The server's message was:

    Invalid redirect: http%3A%2F%2Flocalhost%3A8089%2Fsimple-web-app%2Fopenid_connect_login does not match one of the registered values: [http://localhost:8080/, http://localhost:8089/]


I tried to replicate the same locally by giving a wrong approved redirect and this is what I get locally

Error: invalid_grant

There was an error processing your request. The server's message was:

    Invalid redirect: http://localhost:8089/simple-web-app/openid_connect_login does not match one of the registered values: [http://psmk:8080/]

the difference I see is that on dev server, redirect URI is still encoded and that is what you see in the error message but in my local it is not and if I change my local database to have http://localhost:8080/ as one of the approved redirect url then it will work.

Thanks
Mallikarjun

**Comment by jricher** [comment]
Looks like it might be an error in your client, sending the redirect_uri double encoded for some reason. I haven't seen that with our client code at all.

The comparator definitely takes ports into consideration.

**Comment by mpeddagolla** [comment]
I am using the sample simple-web-app client. I am guessing if it has to do with apache encoding the twice. Locally it works with out apache but it only happes when deployed to one of or dev servers which is behind apache. I will update you.

http://tkurek.blogspot.com/2013/06/252f-instead-of-2f-in-url-apache.html

Thanks
Mallikarjun

**Comment by jricher** [comment]
We've deployed the server behind Apache for many years without this issue, but we usually use AJP and not the rewrite proxy for it.

**Comment by mpeddagolla** [comment]
After turning off encoding on the http-https rewrite on apache the issue is fixed.
