### ISSUE TITLE
Processing requests that are PlainJWT

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1010]
I noticed that `ConnectOAuth2RequestFactory` does the following when a PlainJWT object is processed:

```java
if(!responseTypes.getRequestObjectSigningAlg().equals(Algorithm.NONE)) {
    throw new InvalidClientException("Client is not registered for unsigned request objects (request_object_signing_alg is " + responseTypes.getRequestObjectSigningAlg() + ")");
}
```

How is one supposed to set the `RequestObjectSigningAlg` field, when the parameter type that is expected is of type JWSAlgorithm, which does not have a NONE field? 

I have a DAO that attempts to load clients from an XML configuration file as an example:

```
<util:set id="oidcClients">
    <bean class="org.mitre.oauth2.model.ClientDetailsEntity"
          p:id="1"
          p:clientId="client"
          p:clientSecret="secret"
          p:clientName="Test Client"
          p:dynamicallyRegistered="false"
          p:accessTokenValiditySeconds="3600"
          p:idTokenValiditySeconds="600"
          p:allowIntrospection="true">

        <property name="scope">
            <set>
                <value>openid</value>
                <value>profile</value>
                <value>email</value>
                <value>address</value>
                <value>phone</value>
                <value>offline_access</value>
            </set>
        </property>

        <property name="grantTypes">
            <set>
                <value>authorization_code</value>
                <value>implicit</value>
                <value>refresh_token</value>
            </set>
        </property>

        <property name="redirectUris">
            <set>
                <value>https://op.certification.openid.net:60233/authz_cb</value>
                <value>http://localhost:8081/</value>
            </set>
        </property>
    </bean>

</util:set>
```

There is no way for me to set that field to NONE, because Spring complains about a type mismatch.

**Comment by jricher** [comment]
Use Algorithm.NONE instead, perhaps? I've not used XML-backed data stores like this. I know it works fine with the databases. 

Using unsigned request objects should be a rare exception, though -- I'd ask why you're actually trying to do it at all.

**Comment by mmoayyed** [comment]
I did try that. Then received:

```
 Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'com.nimbusds.jose.Algorithm' to required type 'com.nimbusds.jose.JWSAlgorithm' for property 'requestObjectSigningAlg'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [com.nimbusds.jose.Algorithm] to required type [com.nimbusds.jose.JWSAlgorithm] for property 'requestObjectSigningAlg': no matching editors or conversion strategy found
```

My only objective is to pass conformance tests on openid. There is a test for "Support request request parameter with unsigned request [Basic, Implicit, Hybrid, Dynamic] (OP-request-Unsigned)"

**Comment by mmoayyed** [comment]
Perhaps rather than checking for NONE, the condition could be adjusted to check for NULL only?

**Comment by mmoayyed** [comment]
In other words, if there is no signing alg associated with the client, let the flow resume. I am not sure I totally understand what the behavioral difference between NULL and NONE signifies here.

**Comment by jricher** [comment]
No, you don't want the server to fall back to accepting unsigned requests as a default, NONE needs to remain an explicit parameter. I'm not sure what's causing the issue because we've run (and passed) all the conformance tests, including that one. Did you try just using the string "none" instead of an object and seeing if the conversion would work?

**Comment by mmoayyed** [comment]
I could try. Sure. Let me check.

**Comment by mmoayyed** [comment]
Excellent. "none" works. Thanks for the suggestion.

**Comment by kiakj** [comment]
What "column" did you change to "none", I'm having similar problems.

**Comment by merric** [comment]
@kiakj , 

For my limited understanding you can set a default value in Crypto-Config.xml and custom values under a specific client's CLIENT_DETAILS row.

**Comment by kiakj** [comment]
I added "none" to request_object_signing_alg column in the client_details_TEMP table.  Still having the same problem from the op.certification.openid.net tool.

**Comment by kiakj** [comment]
Got it to work!  @merric Thanks!
