### ISSUE TITLE
Client generates dynamic registration request with empty response_types

### ISSUE THREAD

**Issue by wstrange** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1011]
I am not 100% sure this is a bug or an error with the provider implementation (OpenAM 13.0).

Using the mitre simple web app, I can see it generates a registration request as follows:

{"redirect_uris":["http://localhost:8080/simple-web-app/openid_connect_login"],"client_name":"Simple Web App","token_endpoint_auth_method":"client_secret_basic","scope":"openid email address profile phone","grant_types":[],"response_types":[],"jwks_uri":"http://localhost:8080/simple-web-app/jwk","request_object_signing_alg":"RS256"}"

Note the grant_types and response_types are zero length lists. The spec says these fields are OPTIONAL.
The error that I see on OpenAM is that it creates the client but has no values for response_type, so subsequent requests fail.

Another dynamic reg client that I tested omits the response_types all together - and it "works" in the sense that OpenAM fills in default values. I think the OpenAM does not like the fact that a value is being supplied - but is empty. It should probably reject the request.

I suppose this comes down to a spec interpretation thing. Should an empty list be treated the same as not being present at all.

**Comment by jricher** [comment]
Looks like we could tighten up the JSON generation from the client so that it omits these fields, as I believe that's the correct interpretation. You can also supply values to these two fields and it will probably work as well with that server.

**Comment by jricher** [comment]
Quick tests seem to indicate this did it but try a build against the latest HEAD release to see if this behaves like you're expecting.

**Comment by wstrange** [comment]
Yup - that seems to have done the trick!

Thanks for the quick fix.
