### ISSUE TITLE
Degrading performance of token endpoint due to ApprovedSite entity access token mappings

### ISSUE THREAD

**Issue by strangeweaver** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1012]
Hi,

We have noticed through our suite of performance tests that the performance of the token endpoint degrades over time when put under a load of 1-10 concurrent users ramped up over 10 seconds on a development box. Performance degrades to the point where the token endpoint takes 10s of seconds to repsond. After putting the application through a profiler we isolated the issue to the DefaultOAuth2ProviderTokenService.createAccessToken and more specifically to the merge operation performed on the ApprovedSites.approvedAccessTokens Set. This operation is a bottleneck both from a CPU and database perspective. 

It is heavy from a CPU perspective because the access token value needs to be passed through a JWT parsing process each time the value goes to and comes from the database. It is heavy from a database perspective because under heavy load the number of access tokens for an ApprovedSite grows quickly and each time a new access token is created all access tokens for the given site are retrieved, the Set is then updated and merged back to the database.

The solution to this issue is to remove the approvedAccessTokens member from the ApprovedSite entity and add an approvedSite member to the accessToken. Furthermore a namedQuery can be added to the OAuth2AccessTokenEntity accessible via the JpaOAuth2TokenRepository which can be used for querying access tokens by approved site for use in DefaultApprovedSiteService.remove method.

The only gap then would appear to be in the MITREidDataServices_x_x which make calls to the accessor methods of ApprovedSites.approvedAccessTokens. Can it be safely removed from the MITREidDataServices_x_x classes? An Alternative solution may be to mark the accessor methods deprecated and remove calls to them other than in the DataServices classes?

Thanks, Colm

**Comment by strangeweaver** [comment]
Please see pull request 

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/1013

For basic outline of changes. I would appreciate your input. Also I just noticed this has been addressed in httpants pull request going back to July 2015, The changes outlined in #1013 may be a less invasive though.

**Comment by jricher** [comment]
The MITREidDataServices classes are are used in the data import and export APIs, required to maintain system consistency during upgrades between versions. We can't break that API or people won't be able to export data from running systems or import data into new versions.

This (#1013) is the second pull request to implement this nearly exact change (the other is #874). We may target this for inclusion in version 1.3 once work begins on that branch, as we'll have a bit more flexibility in altering the data models without breaking existing deployments and customizations.

**Comment by strangeweaver** [comment]
Hi Justin,

Thanks for that, had kind of figured it would be the case. I've closed the pull request #1013 as it doesn't make sense to have two near identical ones sitting around. 

would implementing bi-directionality in the mappings be a flyer for version 1.2.x ? 

Given the approvedAccessTokens mapping is already "Lazy" this approach should have minimal impact and would give us the performance gains required in the DefaultOAuth2ProviderTokenService.createAccessToken by using the OAuth2AccessTokenEntity --> ApprovedSite side of the mapping.

**Comment by httpants** [comment]
Just wanted to mention the #874 change maintained the existing import/export json format, even thought it changed the JPA model.

**Comment by httpants** [comment]
This issue was discussed in #862
