### ISSUE TITLE
Questions related to creating users

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1014]
As part of our deployment, we need to support creating users in authorization server if username is not already exist. What that means is user is redirected to our registration page and then post a new user request to authorization server via resource server. Basically creating entries in spring security tables (users, authority) and user_info table in authorization server database and creating a end point to create user in authorization server. I will be using overlay to implement this. 

My question is creation of new user is initiated by our resource server than our web client(In the regular login flow, our webclient will request authorization code from authorization server and upon successful authentication invokes resource server providing code retrieved from authorization server. There by Resource server gets the access token using code and then fetch user_info etc).

 So, if that is the case what would be the authorization_grant I suppose to use to post this new user request to authorization server?  We want to know if there is a good way leveraging oauth between resource server and authorization server.

Thank you
Mallikarjun

**Comment by jricher** [comment]
For something like this I would recommend using a `client_credentials` grant with a specially privileged scope that other clients aren't allowed to ask for. You can do this by registering a scope as "restricted" in the admin UI.

**Comment by mpeddagolla** [comment]
Appreciate for your reply.  I will update the ticket with more info when I am done with this.
