### ISSUE TITLE
Custom expiration time for access_token in client_credential flow

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1017]
Hi Jricher,
            We have a requirement to customize access_token expiration time,Insteadof creating based on what we have in client_details table access_token_validity_seconds colum.
Shall we have time in request itself for specific requests when using client_credential flow.

Note : We have cutomized multiple audience and added user info in custom claim's when using client_credential flow.

Please help/suggest me to resolve this.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
I would say that you'll need to write a custom token granter for this to work, I don't see any lighter touch way to do this. From there it's up to you whether you want to do a custom parameter or a scope to handle the timing differences. 

Also, it raises a red flag to me that you're returning user information from a client_credentials flow, since the user isn't present in such situations. I hope you're not using that for authentication.

**Comment by selvarajkumarasamy** [comment]
We created custom token granter and acheived multiple audience and custom expiration time.
In client_credential flow just we are enhancing the user basic detais(name and authorites).

please correct me if anything wrong.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
But with client_credentials, you have no indication that the user is present since they haven't authenticated to the AS. How are you deciding *which* user's information to add to the token? That's the part that doesn't make sense.

**Comment by selvarajkumarasamy** [comment]
Yes your question is correct. We are passing user name in request for some usecase we need this.
We customizied ClientCredentialsTokenEndpointFilter and acheived.
Request has subject attribute then only we are getting user details.

**Comment by jricher** [comment]
Are you using this for authentication at the client?

**Comment by selvarajkumarasamy** [comment]
No.Just for getting user details

**Comment by jricher** [comment]
Is there a reason that's not a parameter on the user details request, then? I'm struggling to see your use case and I'm concerned that you might be doing something very insecure with it, so I'm trying to understand. The answer of how to do it remains the same, regardless of whether I think it's a good idea or not.

**Comment by dfcoffin** [comment]
I too am confused by what you are attempting to achieve adding user information to the client_credentials request flow.  The client_credentials flow grants the requester an access token that allows them to access resources they either own or have been authorized to access by customers.  It sounds like you are using the client_credentials flow to bypass obtaining user authorization to access their resources.  Am I missing something?

**Comment by merric** [comment]
We are doing something similar. We are using client credentials grant to allow the resource server (client) to access any user's profile. We created a new scope to do this so only specific clients will have access to the system's global profiles.

**Comment by jricher** [comment]
@merric has the right idea -- use a special scope, not a user value in the token. Your token should represent the *client* and not a specific user. The server also allows for you to set up the scope as "restricted", meaning dynamically registered client's can't even request it.

**Comment by selvarajkumarasamy** [comment]
Yes.. Thanks for the update,we also plan to do the same.
