### ISSUE TITLE
Custom Tests

### ISSUE THREAD

**Issue by merric** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1018]
Hey Justin, 

I was wondering if you knew of an elegant way of pulling in your existing spring contexts for testing in an overlay?

**Comment by jricher** [comment]
I'm not sure who Richard is, and I'm not sure what you're asking. If you want to know how to have your spring configuration in an overlay, then you just need to overlay the configuration files. If you're asking how to externalize the configuration from the .war, then you just need to overlay the configuration files and have them import external resources (several production deployments do this).

**Comment by merric** [comment]
I'm really sorry about the misspelling. Really poor oversight. I was after the second explanation I believe. If I pull all your contexts into my overlaid context will that not cause looping since you are pulling the local config in yourself?

**Comment by jricher** [comment]
No worries on the name mistake, it happens. An overlay *replaces* the existing file, so if you overlay something to pull in a local file instead, it will not cause a loop unless the local file references the original somehow. Look at how it's done with the MIT production server: 

https://github.com/MIT-Mobile/oidc.mit.edu/blob/master/oidc-mit-overlay/src/main/webapp/WEB-INF/data-context.xml

This points to spring XML files in /etc/mitreid-connect which need to exist there for it to boot properly. Is that what you're looking for?
