### ISSUE TITLE
Let SimpleGrantedAuthorityStringConverter turn into GrantedAuthorityStringConverter? 

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1021]
If one has extended/implemented the GrantedAuthority interface, there now needs to be additional converters to take that extension into String. Could the existing SimpleGrantedAuthorityStringConverter become generic enough to work on the interface instead of the actual class?

**Comment by mmoayyed** [comment]
I thought to have my extensions extend SimpleGrantedAuthority instead so the converter might work, but turns out that SimpleGrantedAuthority is marked final.

**Comment by mmoayyed** [comment]
I tried writing my own converters, but it seems like no matter what I do, SimpleGrantedAuthorityStringConverter  always kicks in and causes a class-cast error. How should one create and register custom converters?

**Comment by mmoayyed** [comment]
Looks like this is hardcoded directly in the authN holder entity:

```
    @Convert(
        converter = SimpleGrantedAuthorityStringConverter.class
    )
```

**Comment by jricher** [comment]
Converting to a string would be fine with the generic GrantedAuthority, but coming back would be problematic as you need to construct the appropriate class. It might be possible to make this pluggable with a factory that defaulted to the SimpleGrantedAuthority class, if you'd like to try that approach in a pull request.
