### ISSUE TITLE
Overriding default server properties with PropertyPlaceholderConfigurer

### ISSUE THREAD

**Issue by strangeweaver** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1022]
Hi,

The main mechanisms for overriding default server configuration are

1) overlay components (e.g. ConfigurationPropertiesBean)
2) create new @Primary components

A  PropertyPlaceholderConfigurer could provide greater flexibility to the existing override mechanisms. This would permit use of the @Value annotation to inject property values into components from a properties file.

Has any thought been given to this possibility? Would you be open to accepting a PropertyPlaceholderConfigurer based configuration as part of a pull request?

**Comment by mmoayyed** [comment]
It would be much better if Qualifiers were used.

**Comment by praseodym** [comment]
I agree a properties file would be nice for parts of the configuration, but it was decided against previously. See e.g. https://github.com/mitreid-connect/simple-web-app/pull/5#issuecomment-106606785

**Comment by strangeweaver** [comment]
Thanks for the link. I note, however, that the issue referenced is in relation to simple-web-app and the use of properties from a client application.

My question is specifically in relation to the configuration of openid-connect-java-spring-server not a client. 

Taking as an example JWTBearerAuthenticationProvider which has a timeSkewAllowance variable hardcoded to 300. It seems somewhat heavy handed to overlay that class entirely just to change the time skew permissable. if a PropertyPlaceholderConfigurer were used then the timeSkewAllowance variable could be annotated with @Value. Thereby minimising the footprint of the overlay and easing any potential version migration issues.

**Comment by jricher** [comment]
@strangeweaver for your specific use case it would be better to make the element configurable and configure the bean instance instead of overlaying the entire class. We don't have plans to use properties files in the main project, for the reasons linked above.
