### ISSUE TITLE
Handle Max Login Attempt

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1025]
Hi Jricher,          
                We have plan to handle max login attempt,if user try's with invalid credentials 3 or 5 times. User account will be locked for next 24 hours, user can't login.
Shall we customize Max login Attempt for a user ? Do you have any concern or idea ?

Thanks

**Comment by jricher** [comment]
Log ins to the server are handled through Spring Security and can be configured however you wish.
