### ISSUE TITLE
Example to use openid-connect-server as OAuth2 liabrary for custom OAuth2 provider

### ISSUE THREAD

**Issue by vish-k** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1036]
Hello,
I am planning to implement OpenID connect provider. I want to plug in my own client store, passive and active(for resource owner grant) user authentication, token store and admin UI.

Is there a sample available to use openid-connect-server just as OAuth2 library to build custom provider ? I looked at the overlay sample but it uses the openid-connect-server-webapp but it is not suitable for my case because we use custom framework and custom java container.

Thanks in advance for your help.

**Comment by jricher** [comment]
You'll want to just use the server library directly and build your own application from scratch on top of it. There are no examples of this other than the existing web app, which is built this way.
