### ISSUE TITLE
Configure JHipster to SSO using OpenID-Connect

### ISSUE THREAD

**Issue by ag3ng** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1038]
I just creating simple website using JHipster with database MySQL. And now, I also setup OpenID-Connect Server using MySQL too and working perfect using simple-web-app as a client. my question is Can I use OpenID-Connect Server as a authentification (SSO) for my JHipster Website? If can, how to configure it?
Thanks!!

**Comment by jricher** [comment]
It's possible, but you'll need an OpenID Connect client library for your application's platform.

**Comment by ag3ng** [comment]
Yes, I found it in target\simple-web-app-1.0.0-BUILD-SNAPSHOT\WEB-INF\lib\openid-connect-client-1.2.2.jar.. Can you please explain how to use it in JHipster?
Thanks!!

**Comment by jricher** [comment]
Yes, that's the client code from this library. I don't know what the requirements are for your platform nor how to configure it. I would suggest you check their forums instead of here.

**Comment by ag3ng** [comment]
Oke.. thanks Jricher..
