### ISSUE TITLE
Indexes break persistent HSQL instances

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1042]
HSQL doesn't have "create index if not exits", so we'll need another option for persistent instances. Maybe pull the indexes out to a separate file?

**Comment by leonard84** [comment]
Why not use a Database Migration Tool like [Liquibase](http://www.liquibase.org/), if you use it in conjunction with [Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html) it is super easy and it solves many issues regarding database migration/initialization.
