### ISSUE TITLE
id_token and userinfo endpoint when external openid connect auth has been used

### ISSUE THREAD

**Issue by mobilars** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1044]
I've set up a server with an external authentication, and this works great for generating access_tokens. I'm not able to retrieve the id_token, and I guess I might be doing it wrong, but it could also be that id_tokens aren't fully supported when using an external authentication source? Some questions:

1) should I get the id_token and a code in the redirect-url when I ask for response_type=id_token+code in the authorize-end-point? (I only get a code)

2) Should I be able to retrieve the id_token when I send the code to the token-endpoint? I only get the access_token. I've got openid in the scope-request. 

3) If I try accessing the userinfo endpoint using the access_token, I get 'not found'. The database's user_info table doesn't have my external id_token, so I guess that's natural? 

Is there a workaround or can I extend some class to present the id_token that was fetched from the external oauth-server to the client?

**Comment by jricher** [comment]
You'll need to save the incoming UserInfo objects to a custom UserInfoService that you can then serve back. I would suggest copying the UserInfo on first login. See the UserInfoFetcher classes for details on that end, and wire that in to write to your service.

Without that, neither the id token nor the userinfo response will be made.

**Comment by mobilars** [comment]
Thanks.
