### ISSUE TITLE
Expected CSRF token not found.

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1048]
Hi Jricher,
              We have found the error "Expected CSRF token not found. Has your session expired?" ,when clear the browser cache and try to login.

HttpSessionSecurityContextRepository - No HttpSession currently exists
HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: null. A new one will be created.
FilterChainProxy - /j_spring_security_check at position 2 of 13 in additional filter chain; firing Filter: 'AuthorizationRequestFilter'
FilterChainProxy - /j_spring_security_check at position 3 of 13 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
FilterChainProxy - /j_spring_security_check at position 4 of 13 in additional filter chain; firing Filter: 'HeaderWriterFilter'
FilterChainProxy - /j_spring_security_check at position 5 of 13 in additional filter chain; firing Filter: 'CsrfFilter'
CsrfFilter - Invalid CSRF token found for http://localhost:8080/identity-service/j_spring_security_check
HttpSessionSecurityContextRepository - SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.

We have tested demo server(https://mitreid.org ) also the same issue.

Error: 403 Forbidden
There was an error processing your request. The server's message was:
 Expected CSRF token not found. Has your session expired?

Please help me to solve this.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
That's behaving as expected. You need to refresh the login page to get a new CSRF token generated and injected into the page.

Without this, you could have external parties fake the login in a non-interactive fashion by POSTing the fields to the login page.

**Comment by selvarajkumarasamy** [comment]
![demo-server](https://cloud.githubusercontent.com/assets/13680389/14017243/2cf12c90-f1ec-11e5-8308-883a0d4abc9a.png)

**Comment by jricher** [comment]
Right, you cleared the session and the error is that the session has expired. This is correct behavior.
