### ISSUE TITLE
User Impersonation

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1051]
Hi,Jricher,
               We have impersonation feature in existing application,means Admin user login into the application,can do Impersonation as different user using their credentials.Admin user also don't know about other user credentials but by clicking a link((Username+Password) encrypted in base64) provided by the application,auto login will happen.

In this case, how to achieve the auto-login
1.We should invoke authorize endpoint.
2.Re-authentication required for new user.
3.Session Creation Required.
4.How Redirection and token generation will happen.

Please guide or correct me if anything wrong.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
First off, I want to point out that base64 is not encryption. If all you're doing is encoding the user's username and password in base64, then the admin has the user's username and password, in plain text. This is a really, really, really, really bad idea and I hope that I'm misunderstanding you and you're not actually doing this.

Second, do you need the admin to impersonate the user at the IdP? Or at a downstream RP? If it's at a downstream RP then you'll want a custom ID Token generator that lets the admin pick which user to impersonate. I would also add in a flag to your ID Tokens to mark that they're "impersonation" tokens. If it's at the IdP, you'll have to work out how to make the spring security system work this way. 

In no case should you be passing along the target user's credentials and having the admin log in as them directly, as you seem to be saying above.

**Comment by franciskim7** [comment]
For the downstream RP scenario, is there anything available with MitreID we can leverage now or do we need to build the custom ID token generator on our own still?
