### ISSUE TITLE
Custom header.tag overlay?

### ISSUE THREAD

**Issue by zyrolasting** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1053]
My team needs to style a custom login page with a stylesheet unique to that page. In header.tag, I have the following inside the `<head>` element:

    <c:choose>
        <c:when test="${title=='Log In'}">
            <link href="resources/css/styles.css" rel="stylesheet">
        </c:when>
        <c:otherwise>
            <link href="resources/bootstrap2/css/bootstrap.css" rel="stylesheet">
            <link href="resources/css/bootstrap-sheet.css" rel="stylesheet">
            <link href="resources/css/mitreid-connect.css" rel="stylesheet">
            <link href="resources/css/mitreid-connect-local.css" rel="stylesheet">
            <link href="resources/bootstrap2/css/bootstrap-responsive.css" rel="stylesheet">
            <link href="resources/css/mitreid-connect-responsive.css" rel="stylesheet">
            <link href="resources/css/mitreid-connect-responsive-local.css" rel="stylesheet">
        </c:otherwise>
    </c:choose>

This works, but this happens in a directory representing the base code before overlays (which my team added to `.gitignore`). If I create a `header.tag` in our own custom Maven overlay project in a corresponding WEB-INF/tags directory, the server fails to start with internal errors (I'll repro those errors and put them in a separate comment).

Is header.tag not meant to be overridden? If so, how can I properly override it?

**Comment by jricher** [comment]
All the tags are designed to be overridden, including header.tag if you need it to be.

**Comment by zyrolasting** [comment]
I found and fixed a JSP mistake that caused my initial problem and am now trying to fix paths to static assets. I think I can fix that from here, but thank you so much for the quick response!
