### ISSUE TITLE
Using management console, when session is invalidated and a REST request is made, the user is not taken to the login screen

### ISSUE THREAD

**Issue by Ronnie76er** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1066]
Steps to reproduce:

1. Log in
2. Go to "Manage Approved Sites"
3. Wait for session timeout
4. Go to "Manage Active Tokens"

Since this only requires a XHR, it returns a 401, and the UI is in a weird state. A simple refresh brings the user to the login screen again.

I created a branch with a timeout of 1 minute, which makes it easier to demostrate the behavior: https://github.com/Ronnie76er/OpenID-Connect-Java-Spring-Server/tree/test-session-timeout

**Comment by praseodym** [comment]
The simple fix would be to handle the 401 response in the client-side code by refreshing the page.
