### ISSUE TITLE
help me please with the  callback

### ISSUE THREAD

**Issue by 4bsolut** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1068]
I'm confused what happens when I got the code and state on my callback, how I must get the access token later I manually should do a post to tokenEndpointUri??  can someone guide me in this proccess please please

**Comment by jricher** [comment]
This is pretty basic OAuth/OIDC functionality and not specific to this project. I would suggest a tutorial or book on the topic for details. I'm writing one if it helps you: https://www.manning.com/books/oauth-2-in-action
