### ISSUE TITLE
Resource Owner Password Credentials

### ISSUE THREAD

**Issue by gabuh** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1069]
¿Does this implementation support OAuth2 Resource Owner Password Credentials flow?

Thanks.

**Comment by jricher** [comment]
Yes, but it's disabled by default. You need to override it in `authz-context.xml`.

**Comment by stefli** [comment]
<oauth:authorization-server ...>
		
...
		<oauth:client-credentials/>
		**<oauth:password />**
		...
 />

**Comment by gabuh** [comment]
Ok, thanks for your help!
