### ISSUE TITLE
Exception when access token and id token expire at the same time

### ISSUE THREAD

**Issue by vkennke** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1070]
When both tokens expire at the same time (or more precisely when the DefaultOAuth2ProviderTokenService wants to clear both tokens at the same time) I got the attached exception [1]. I think the problem is that both tokens are fetched by the DefaultOAuth2ProviderTokenService, but the access token is first deleted and because of CascadeType.ALL the id token is deleted along with the access token. Afterwards, there is no id token anymore and so the exception occurs.

[1] http://pastebin.com/pd4t7Mh9

**Comment by jricher** [comment]
ID Tokens are no longer stored.
