### ISSUE TITLE
Authentication/authorization via RESTFul service

### ISSUE THREAD

**Issue by mblascoroca** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1072]
Hello,
I have a non-web application and I need to authenticate it only by a RESTFul service. 

For this reason, I would like to know if I can obtain an authorization code and a token later, via REST request, without using the redirect_uri parameter. 

I think that is not possible if I use the AuthorizationEndPoint ({idp.url}/authorize).  Am I wrong? How could I do it?

Thanks,

**Comment by andreyestevao** [comment]
I have the same question.

**Comment by merric** [comment]
if you are just trying to authenticate the app itself you can use Client Credentials grant type which is support by this project. You would need to add the app as a client and give it a secret and key. Then you can grab the token from the the token endpoint.

**Comment by jricher** [comment]
Does your application work on behalf of a user? Can you launch a browser to get the user to the authorization endpoint? If so, then your app just needs to have registered a `redirect_uri` that it can read. Most mobile and native apps do this using a custom URI scheme, like `org.myapp://oauth/` or something like that. This is pretty common and well defined.

If your app isn't acting on behalf of a user, and you're really just authenticating the app itself, then the client credentials grant that was mentioned above is the right choice. 

It all depends on what you're trying to do.

**Comment by mblascoroca** [comment]
Thanks for your responses.
 
I am trying  to authenticate with two different grant types and I have a problem with one of them (and I can't find the reason)
 
I authenticate my batch application via "password" grand_type and I don't have any problem. First I get the token, and with it, I call the user endpoint to get the user info. It runs ok.
 
However, when I try to use the "client_credentials" grand_type. I get the token too, but when I try to use it to call the user end point, I get an 403 error, and I previously have authorized my client to get this user info. On the other hand, If I request the issued access tokens (via browser), I get all that has been created, but I don't get this one.
 
I'd like to know if there is any endpoint that will answer something different that the 403 error when using the access token obtained through the client_credentials grand_type.
 
Thanks!

**Comment by jricher** [comment]
You can't use the client credentials grant with the user info endpoint because the the client credentials grant doesn't have a user involved, and the user info endpoint doesn't have a user to look up. Other endpoints that you write to access wouldn't have that restriction.

**Comment by andreyestevao** [comment]
Hi, Thanks for answering.

Can I perform a client transparent authentication  with JWT like Google API ? I'm trying to authenticate a web component.

I'm using the simple-web-app as a client  and configuring the OpenID Connect Server Token Endpoint Authentication Method to run with _"Client Secret via symmetrically-signed JWT assertion" or "Asymmetrically-signed JWT assertion"_ for testing. Also, the _"Public Key Set"_
is set _"By URI"__ http://localhost:8080/simple-web-app/jwk_

But, when I call  _/authorize_ url passing the parameters _client_id, response_type and redirect_uri_, the application calls the OpenID Connect WebApp login page before redirecting me and provide the token. Is there any way to authenticate without calling the OpenID Connect WebApp login page (transparent authentication)?

PS: Why every time I try to login with simple-web-app the client id is different? In this way, the Server app will assume the client is a new app every login ... that's right?

**Comment by jricher** [comment]
The simple web app is meant to be user interactive. It doesn't make sense to not involve the user. If you don't involve the user, you won't have access to the userinfo endpoint, as discussed above.

To make the simple-web-app remember its client ID, you need to set up a registered client service on the client: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Client-configuration#registered-client-service

**Comment by jainh** [comment]
Hi @mblascoroca 
Are you able to get token using client credential grant type ? can you please specify steps you had to do perform to reach that point?

**Comment by jainh** [comment]
@jricher Do you know how to: 

1) dynamically register client ( I believe for this i may need one user manually created or admin, and use that credential to create client with new credential programmatically ?)
 2) authenticate client with AS through client_credential grant type ? what is the endpoint ? i need access_token. 
3) I should be able to request refresh token with access_token ?

Things are not clear from the documentation.
Thank you

**Comment by mblascoroca** [comment]
Hi Jainh,

Finally, I've used client_credentials grant type via REST service.
It's easy, you only have to send a request to the token endpoint ("/token") with these parameteres: "client_id" (your app client id), "client_secret" (your app client password), "grant_type" (client_credentials) and "scope" (your scope).
 
And don't forget enable this grant type on the server before sending the request.

**Comment by jainh** [comment]
Hi mblascorcoa

Thank you for the reply. Did you manually register client with the sever ? Or it is possible to register client dynamically through code ? Like add client in white list or something similar.

Thank you

**Comment by jainh** [comment]
I was trying this to get all clients 
curl -H "Content-Type:application/json" -u "admin:password" -X GET -v http://localhost:8080/openid-connect-server-webapp/api/clients
Also, to register client.

**Comment by jainh** [comment]
hi @mblascoroca 

I was able to get access token thanks.

**Comment by wangruochan** [comment]
hi @jainh 
I have the same question with you .
Can you specific  what you have done to finish the 3 steps you mentioned before?
Thanks very much!

**Comment by jainh** [comment]
Hi @wangruochan 

I was able to request access token / refresh token for password: grant_type programmatically. I had to create separate service to populate user database used by MITRE server for client authentication. Make sure your password grant type is enabled for manually registered client.

**Comment by wangruochan** [comment]
Hi @jainh 
Thanks for the reply!
I use  MITRE  as an oauth2 server and I find there is an endpoint for  registing  client dynamically, still l I have no idea how to get token and verify the token in my application,I cant find any info from the documentation.
Can you  specify steps ?
Thank you!

**Comment by jainh** [comment]
For client dynamically registration endpoint is available for the authorization grant flow but not for the client credential or password grant type. However for token endpoint you can call /token and for token introspection call  /introspect  for verification.

**Comment by wangruochan** [comment]
That helps!
Thanks again! @jainh

**Comment by gopikrishnagurram** [comment]
> introspect



> For client dynamically registration endpoint is available for the authorization grant flow but not for the client credential or password grant type. However for token endpoint you can call /token and for token introspection call /introspect for verification.

Can you give me the CURL for /token ?
