### ISSUE TITLE
Timezone based token expiration time

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1073]
Hi Jricher,
          How do we implement time zone based expiration time in identity-service?. Our application's(RP) deployed in different timezone and one identity-service will be deployed(not for each time zone).

Help me to generate token's expiration time using timezone.

Thanks
Selvaraj.K

**Comment by selvarajkumarasamy** [comment]
Hello Jricher,
Please provide me the solution for timezone conflicts.

**Comment by jricher** [comment]
The timezone shouldn't matter as the AS determines when the token expires, and that's only in one timezone.
