### ISSUE TITLE
Simultaneous client and server run

### ISSUE THREAD

**Issue by jengweneg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1075]
Hi,

I need to operate an intermediary server between relying parties and several identity providers

In fact we need to have an architecture whereby en-dusers can use several identities

I was thinking at using mitreid implementation for that intermediate service, working as an id provider on the RP interface and simultaneously working as an RP on the interface with the idenitty providers where the users will get their idenities

I know mitreid can do both client(RP) and server(id Provider)
Can it do it simultanesouly?
In that case how to pass variables from one to another

Basically my example is:

a government application (RP) in which users can connect using their credentials at different service providers but withe government application requirement to only show a single "connect" button on the application page. So that when the user clicks "connect" they get to a page (the intermediate server) where they select the id provider, then they authenticate on that id provider. Afterwhat they come back on the intermediate service with the pofile information takent on the id provider and the government application gets them at their turn

Is it possible to cascade opeind connect in such a way with mitreid?

regards

Basically my example is:

a government application (RP) in which users can connect using their credentials at different service providers but withe government application requirement to only show a single "connect" button on the application page. So that when the user clicks "connect" they get to a page (the intermediate server) where they select the id provider, then they authenticate on that id provider. Afterwhat they come back on the intermediate service with the pofile information takent on the id provider and the government application gets them at their turn

Is it possible to cascade opeind connect in such a way with mitreid?

regards

**Comment by praseodym** [comment]
I think this should be possible, but it will require some coding work to properly configure the server to use OIDC for its own authentication. Most of the work should be a matter of configuring Spring Security correctly.

**Comment by jengweneg** [comment]
Hello Mark,
Do you have clue how to configure Spring Security? i should say the documentation for Spring Security Filter on github is not easy to understand. Which files to modifiy and how? Thanx

Also where should this code be implemented?

Regards and Thanx
Eric

**Comment by praseodym** [comment]
You'll want to create a new WAR overlay that configures the Spring Security authentication chain to use the OIDC client libraries akin to the sample client project.
