### ISSUE TITLE
Connect an LDAP server

### ISSUE THREAD

**Issue by jengweneg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1077]
Hello,

I previously installed an OpenIDconnect Java Spring Server that i am running and i would like to use a backend LDAP store now.
Can i just add the files from here manually? "https://github.com/mitreid-connect/ldap-openid-connect-server"

Or should i move to that implementation as a whole? Please advice how to do without abandoning my previous server

Thanx

**Comment by praseodym** [comment]
You should create your own overlay based on the ldap-openid-connect-server example project and use that to replace your existing instance. The database will stay the same, so you can keep your existing data.
