### ISSUE TITLE
How Can i use Token Introspecting

### ISSUE THREAD

**Issue by pabversist** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1078]
I'm a little confused about token introspecting. in apps like simple-web-app where should it go and how should i configure my servlet-context.xml for it?
P.S : i read Token Introspecting section in documentation but i still can't understand how should i change simple web app to use it

**Comment by jricher** [comment]
Token introspection is for OAuth protected resources, simple-web-app is an OpenID Connect client. Completely different kinds of systems, you don't really use them together.

**Comment by pabversist** [comment]
so i retreive a token in simple web app and use it to access OAuth protected resource..yes?
and if yes my question is how should i send token? using json or form parameter?

**Comment by jricher** [comment]
The simple-web-app client code is an OIDC client, but it could be adapted to also call generic OAuth endpoints since you'll have the access token as well, but you need to make that code. It's recommended by the spec that you send the token in the Authentication: Bearer header.

**Comment by pabversist** [comment]
Sorry but I'm a little confused... is oAuth the only way to protect resource in mitreid-connect or is there another way in mitreid? ( because i thought mitreid uses spring oAuth for resource protection...
if yes can i use spring oAuth for protect my resources?

**Comment by jricher** [comment]
OAuth is for protecting resources, yes. you can use Spring's OAuth library or your own. MITRE's introspection code plugs into Spring's OAuth library, at the moment.

**Comment by 0xGaduo** [comment]
Hi there, 

There are two questions, If my Resource Server want to check then token, could I import `openid-connect-client` to my resource server project? and  to do something like that: [Token-Introspecting-Client-Config](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Token-Introspecting-Client-Config)  ?

another question is How could I test for `/intropect` for HTTP Tool such as `PostMan`, I always got the message : 
```
{
  "error": "unauthorized",
  "error_description": "Bad credentials"
}
```

**Comment by jricher** [comment]
Yes, you can use that in that fashion. To call the introspection endpoint you need to be authenticated as a protected resource. These are stored in the authorization server as "clients" with the special "allows introspection" flag set -- this is a checkbox in the admin UI.

**Comment by 0xGaduo** [comment]
Hi @jricher 

thank you for your response,  so should I apply a client for my Resource Server, and check "allows introspection endpoint", and then setting the client_id and secret to the spring bean, right?
