### ISSUE TITLE
can not push to heroku

### ISSUE THREAD

**Issue by jengweneg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1083]
Hello,

although mvn clean install works well for my openid-connec-server-webapp, i have been failing to push to heroku
Here is what i get. Can someone help?

git push heroku master
Counting objects: 196, done.
Compressing objects: 100% (184/184), done.
Writing objects: 100% (196/196), 620.06 KiB, done.
Total 196 (delta 56), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Java app detected
remote: -----> Installing OpenJDK 1.8... done
remote: -----> Installing Maven 3.3.9... done
remote: -----> Executing: mvn -B -DskipTests clean dependency:list install
remote:        [INFO] Scanning for projects...
remote:        [ERROR] [ERROR] Some problems were encountered while processing the POMs:
remote:        [FATAL] Non-resolvable parent POM for org.mitre:openid-connect-server-webapp:[unknown-version]: Could not find artifact org.mitre:openid-connect-parent:pom:1.2.7-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 10
remote:         @
remote:        [ERROR] The build could not read 1 project -> [Help 1]
remote:        [ERROR]
remote:        [ERROR]   The project org.mitre:openid-connect-server-webapp:[unknown-version] (/tmp/build_109ea45aebcc78f5bb0861757c6de2fc/pom.xml) has 1 error
remote:        [ERROR]     Non-resolvable parent POM for org.mitre:openid-connect-server-webapp:[unknown-version]: Could not find artifact org.mitre:openid-connect-parent:pom:1.2.7-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 20, column 10 -> [Help 2]
remote:        [ERROR]
remote:        [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
remote:        [ERROR] Re-run Maven using the -X switch to enable full debug logging.
remote:        [ERROR]
remote:        [ERROR] For more information about the errors and possible solutions, please read the following articles:
remote:        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
remote:        [ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
remote:
remote:  !     ERROR: Failed to build app with Maven
remote:        We're sorry this build is failing! If you can't find the issue in application code,
remote:        please submit a ticket so we can help: https://help.heroku.com/
remote:
remote:
remote:  !     Push rejected, failed to compile Java app
remote:
remote: Verifying deploy...

**Comment by jricher** [comment]
You need to build the parent project, not just the webapp (the .war file) for it to work, otherwise the dependencies between modules won't happen. I don't know how to tell heroku to build the whole application but only deploy one module of it.

**Comment by jengweneg** [comment]
Oh thanx so much

And how do i build the parent project?

Regards

Eric
