### ISSUE TITLE
Creating new user

### ISSUE THREAD

**Issue by EslamAli86** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1085]
Hello,

I want to extend the UserInfoService to create new users, so I modified the service layer classes UserInfoService and DefaultUserInfoService to add the new functionality as follows:

	@Override
	public UserInfo saveUserInfo(UserInfo userInfo)
	{	
		UserInfo user = userInfoRepository.saveUserInfo(userInfo);		
		return user;
	}

, then modified the data access layer classes UserInfoRepository and JpaUserInfoRepository as follows:

	@Override
        @Transactional(value="defaultTransactionManager")
	public UserInfo saveUserInfo(UserInfo userInfo)
	{
		UserInfo tmp = manager.merge(userInfo);
		manager.flush();
		return tmp;
	}

The problem is that the data access layer modification does not save the new user info and the manager.merge(userInfo) always returns null instead of the new created userInfo, I tried the persist() instead of merge but it does not work neither.

Am I missing something? should I change something somewhere?

Thanks in advance for your help.

**Comment by jricher** [comment]
First, I would suggest adding a new service instead of altering the existing one. Second, it sounds like you don't have the calls to the JPA layer quite right, compare how other objects save. We've got a utility class, JPAUtil, that we use for most objects.

**Comment by merric** [comment]
We ended up adding registration through different controllers, managers, and repositories. This allowed us to keep the core code pristine while giving us the best flexibility for future expansion. If you write your own authentication query (We did this through extending DaoAuthenticationProvider) you can even change how authentication works. We did this because we needed multiple logins per user.

**Comment by jainh** [comment]
@merric, I am also doing this PR separately registering new user by creating new service. But why do you need Authentication manager for registering new user ? To add new user perhaps DAO, jdbctemplate  will be enough to access  users, user_info, authorities table and insert new users right?

**Comment by EslamAli86** [comment]
@jricher @merric, Thanks for your replies, it works now, I followed your suggestions, I used the JPAUtil class to communicate with the database, and created a new service for creating new users, also wrote a new testing suite for testing the user creation different scenarios, I am currently working on extending the RESTful layer to allow the user creation through a RESTful service.

**Comment by karolb91** [comment]
@EslamAli86 Hi. I know that this issue is closed, but do you still have implementation of this service?
