### ISSUE TITLE
client with multiple redirect_uri causes RedirectMismatchException

### ISSUE THREAD

**Issue by vanomania** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1086]
I've deployed openid-connect-server-webapp-1.1.19 and made updates to the clients.sql.  I was able to configure one war using static client registration and got it working.  I'm trying to configure a second war using the same client_id, but different redirect_uri.  So I just added a second entry to `client_redirect_uri` table.  The existence of this second entry is breaking my first webapp that I already had working.  

The ConnectOAuth2RequestFactory properly sets the redirect_uri onto the AuthorizationRequest object with:
```
String redirectUri = claims.getStringClaim("redirect_uri");
if (redirectUri != null) {
    if (!redirectUri.equals(request.getRedirectUri())) {
        logger.info("Mismatch between request object and regular parameter for redirect_uri, using request object");
    }
    request.setRedirectUri(redirectUri);
}
```

But then it gets to org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.authorize() and does some redirect resolution.  

```
// The resolved redirect URI is either the redirect_uri from the parameters or the one from
// clientDetails. Either way we need to store it on the AuthorizationRequest.
String redirectUriParameter = authorizationRequest.getRequestParameters().get(OAuth2Utils.REDIRECT_URI);
String resolvedRedirect = redirectResolver.resolveRedirect(redirectUriParameter, client);
if (!StringUtils.hasText(resolvedRedirect)) {
    throw new RedirectMismatchException(
						"A redirectUri must be either supplied or preconfigured in the ClientDetails");
}
authorizationRequest.setRedirectUri(resolvedRedirect);
```
`authorizationRequest.getRequestParameters()` only has a request parameter with the value of the jwt string,   so a null is returned and passed to the resolver.  If the client only had 1 entry in the client_redirect_uri  table, it would return it.  Otherwise,  it throws the RedirectMismatchException saying null does not match one of the registered values.

I'm not sure if this maybe should be raised with spring, since that's who owns the AuthorizationEndpoint, or if the this library needs to be updated to send the redirect_uri as a parameter.

**Comment by jricher** [comment]
An earlier version of the OIDC spec required the parameters be duplicated, which is what is enforced in the parser now (since we wrote it during that time frame). I can't find that requirement in the current version of the spec, so the requirement will likely be relaxed in a future version.

Speaking of versions, 1.1.x is fairly out of date at this point, we recommend everybody be running against 1.2.x.

**Comment by vanomania** [comment]
The rest of our app is only on Spring 3.2.x,  so we went with the latest before you guys upgraded to spring 4.x

**Comment by vanomania** [comment]
I've switched back to using the org.mitre.openid.connect.client.service.impl.PlainAuthRequestUrlBuilder instead of the Encrypted one.  If I need to,  I can extend the Encrypted one and wire it in.
