### ISSUE TITLE
SpringSecurity 4

### ISSUE THREAD

**Issue by merric** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1088]
Hey Justin, 

I spring security upgrade in your plans for the future? We had some cache control difference between our business app and our IDP, but thought the risk of upgrading the project wasn't worth the gain.

**Comment by jricher** [comment]
The next development cycle of the project (1.3) will be updated. Work should be starting on that in the near future, nobody's had time to start that yet though.

**Comment by jricher** [comment]
Now that 1.3 is open for development, we're happy to take a pull request updating to spring security 4.

**Comment by Thomaswink80** [comment]
Will the the 1.3 version of openid-connect-client also compatible with Spring Boot ?
I was not able to get Woltere's version ( #670) running with the current release of Spring Boot (1.3.5).

**Comment by jricher** [comment]
@Thomaswink80: It's possible, but nothing specifically on the road map right now. The most common deployment of the server project is dropping a .war file into a container such as Tomcat, but if we can allow both without breaking things then I'm in favor of it.

**Comment by barretttucker** [comment]
I've customized the OpenID Connect server to use Java config and Spring boot several times for clients. I'm in the process of packaging and neatening that code and making it in a more Spring Boot auto-configure style, with a magic @EnableOpenIDConnectServer and support for bean overriding, etc. Comments and contributions welcome.

https://github.com/simpledynamics/openid-connect-server-spring-boot

Currently supports Spring Boot 1.3.3. MitreId Connect 1.2.3, and Spring Security 4.2.5
