### ISSUE TITLE
Overriding authentication to use RESTful webservice instead of DB

### ISSUE THREAD

**Issue by rohitiyer91** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1089]
Hi, I have a REST based web service which will be used to query for user authentication. The default implementation of your spring web app uses in-memory DB to authenticate user credentials. Is it possible to override this behavior to send a request to the RESTful webservice instead to perform authentication ?

**Comment by jricher** [comment]
Yes, you'll just need to write a custom Spring Security adapter. That said, a custom REST service for user authentication sounds like a really, really bad idea in design.

**Comment by rohitiyer91** [comment]
thanks for the info. I have a centralized DB which can only be contacted by the webservice(thats by way of design). My only option at the time is to get the OIDC server to talk with the webservice instead of the DB itself. If you think there is a better alternative, I would really appreciate your input.

**Comment by jricher** [comment]
The real question is simple: how are you authenticating your calls to the custom REST service? It sounds ripe for attack.
