### ISSUE TITLE
Adding Spring Security OTP Plugin

### ISSUE THREAD

**Issue by jengweneg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1090]
Hello,

I need to add the Spring Security OTP Plugin to my openid connect web server.

An example app that integrates such a pluggin is here **https://github.com/upcrob/spring-security-otp-test**

Can someone help how to integrate this in order to perform 2 factor authentication on the wmitreid eb server app?
There are gradle flies also that i do not kno how to handle

Thanx

**Comment by jengweneg** [comment]
Actually i need to kno exactly how to modifiy the user-context.xml file and also any other necessary modificaiton

**Comment by jricher** [comment]
Please follow the instructions in the referenced plugin, that's outside the scope of this project (though we allow any Spring Security plugins for primary authentication).
