### ISSUE TITLE
API isn't usable with client credentials flow

### ISSUE THREAD

**Issue by thomasmey** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1091]
Hi,

I tried to access the API with a access token obtained via the client credentials flow.

The access fails in the @PreAuthorize expressions (e.g. ScopeAPI) because the "oauth2" bean has no method called hasRole(). Only a method called clientHasRole is available in the OAuth2SecurityExpressionMethods.

The wiki page of the API also gives no indication what oauth flows are supported. It only mentions that a valid access token is needed, which can also be obtained by the client credentials flow.

So: Bug or feature?

**Comment by jricher** [comment]
This is an intentional feature -- the API isn't supposed to be usable by non-account holders, such as OAuth clients. It needs to be on behalf of an admin user. The wiki page should probably be updated.
