### ISSUE TITLE
Extract payload from access_token

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1093]
Currently we are using password grant type to exchange access_token. When the user access secured endpoints with access_token , is there a way I can parse the access_token and get the payload?

Thank you
Mallikarjun

**Comment by jricher** [comment]
Yes, the access tokens generated by the server are JWTs and can be parsed. If you want more information about the token's context, you can use token introspection.

As a side note, we don't recommend using the password grant type in general for security reasons.

**Comment by mpeddagolla** [comment]
thank you. Appreciate for quick response. We are actually supporting 3 grant types and we had to support password grant type for this specific client. But we will definitely consider again.

Thank you
Mallikarjun
