### ISSUE TITLE
Approval page not POSTing to correct URL

### ISSUE THREAD

**Issue by ondrejvelisek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1097]
Hi all,

I have a problem with web server (apache) in front of MitreID server. Apache is running on `http://localhost:80` and rewrites all requests from `/krb/oidc/...` to `ajp://localhost:8888/...`  When I access `http://localhost/krb/oidc/` it works fine and I get main page of webapp. But if I access `http://localhost/krb/oidc/authorize?...&redirect_uri=http://localhost:8080/&...` I see user consent page which says "You will be redirected to the following page if you click Approve: `http://localhost:8080/`". However after approving I'am redirected to `http://localhost/authorize` and get 404. Apache says it is with POST method. My issuer in config is `http://localhost/krb/oidc/`. Should I set some other property?

I will be glad for any help.

Cheers

Ondrej

**Comment by jricher** [comment]
On the surface, that setup seems fine to me, and it's one I've personally used a number of times on different server deployments. The issuer needs to be the external URL, which it is here so that should be fine. 

What does your reverse proxy directive look like?

**Comment by ondrejvelisek** [comment]
Thanks for quick answer. 

I'm using RewriteRule directive. So it looks like:

<virtualHost *:80>
  ...
  RewriteRule /krb/oidc/(.*)$ ajp://localhost:8888/$1 [P,QSA]

  ## OIDC over fake KRB
  <Location "/krb/oidc/">
    Options FollowSymLinks
    Order allow,deny
    Allow from all
    Require all granted

    # Fake user    
    SetEnvIf _ .* AJP_ENV_REMOTE_USER=xvelisek@META
    SetEnvIf _ .* AJP_EXTSOURCE=META
  </Location>
</VirtualHost>

**Comment by jricher** [comment]
I've set it up using `ProxyPass` directives instead of `RewriteRule`, and that might make the difference.

**Comment by ondrejvelisek** [comment]
Yes. I've tried this instead.
```
ProxyPass  /krb/oidc/ ajp://localhost:8888/
ProxyPassReverse  /krb/oidc/ ajp://localhost:8888/
```
Same result. 

this is apache log
```
localhost:80 127.0.0.1 - - [18/Jul/2016:14:27:25 +0200] "GET /krb/oidc/authorize?response_type=code&client_id=client&redirect_uri=http://localhost:8080/&state=e_LgaYxz3V0TqrrJBxEqAZRT0hnRWURm8zJSJ66bhCs HTTP/1.1" 200 4213 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"

localhost:80 127.0.0.1 - - [18/Jul/2016:14:27:31 +0200] "POST /authorize HTTP/1.1" 404 496 "http://localhost/krb/oidc/authorize?response_type=code&client_id=client&redirect_uri=http://localhost:8080/&state=e_LgaYxz3V0TqrrJBxEqAZRT0hnRWURm8zJSJ66bhCs" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
```

**Comment by ondrejvelisek** [comment]
I've inspect web page and user confirmation form looks like:

`<form name="confirmationForm" action="/authorize" method="post">`

So it seems MitreID Connect server really fill it with wrong value. 

In approval.jsp there is `action="<%=request.getContextPath()%>/authorize"` shouldnt be here something like: `action="<%=serverConfigBean.issuer%>/authorize"`? (I do not know exact syntax) Or should I fill ContextPath somehow?

**Comment by jricher** [comment]
At the root of the page (in the [header tag](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server-webapp/src/main/webapp/WEB-INF/tags/header.tag#L10)) it sets a base URL for the whole page:

` <base href="${config.issuer}">`

This should effectively tell the browser to POST to an absolute URL made by combining the issuer and the form's target `/authorize`. It sounds like that's not happening here. Have you tried different browsers?

**Comment by ondrejvelisek** [comment]
Base tag is properly setted.
`<base href="http://localhost/krb/oidc/">`
I've tried firefox and chrome. Both the same result.

**Comment by ondrejvelisek** [comment]
Yeah. But it should be without the first slash. Relative path.
`<form name="confirmationForm" action="authorize" method="post">`

it works like:
http://localhost/krb/oidc/  +  /authorize  =>  http://localhost/authorize
http://localhost/krb/oidc/  +  authorize  =>  http://localhost/krb/oidc/authorize

**Comment by jricher** [comment]
Interesting! Other URLs don't need to be formatted like that. This is an easy fix though if that takes care of things. Feel free to throw a pull request in if you'd like to claim credit. :)

**Comment by ondrejvelisek** [comment]
Seems it is already fixed in master. ;-)

**Comment by jricher** [comment]
Is it? What version are you running then? Hm, is it the same as #1041?

**Comment by ondrejvelisek** [comment]
Yes, it is the change. I'm running 1.2.6. I did not try the fix though.

Strange thing is that nobody complains earlier. Moreover whole context path value there looks weird for me. When I'm running my mitreId on `ajp://localhost:8888/contextPath/` and my apache proxy on `http://localhost/issuerPath/` authorization endpoint should be `http://localhost/issuerPath/authorize` and also I would expect form submit button will point on `http://localhost/issuerPath/authorize`. Am I right? Now it points on http://localhost/contextPath/authorize.

**Comment by jricher** [comment]
Looks like some servlet container setups do this, and others don't. None of my test setups really replicate the behavior well. The logic in the pull request pointed to up there is probably going to get backported to 1.2 for the next release.
