### ISSUE TITLE
UserInfoInterceptor calls UserInfoRepository.getByUsername(<client_id>)

### ISSUE THREAD

**Issue by ondrejvelisek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1098]
Hi all,

When I call token endpoint and authenticate my client via basicauth, `UserInfoInterceptor` tries to get data about "user" with its client id. So it calls `UserInfoRepository.getByUsername("client_id")` which throws an exception in my implementation. Shouldn't Interceptor distinguishes between user and client request and ends when it is client's? Or did I set up something wrong?

Cheers

Ondrej

**Comment by jricher** [comment]
Sounds like you set up something wrong because the interceptor *should* only fire for user logins. Also, your repository shouldn't throw an exception when it can't find a user, that's not part of the contract.

**Comment by ondrejvelisek** [comment]
Well, it is NumberFormatException because I expect number. However my config is very simple (user-context.xml). Maybe I should somehow restrict perunAuthenticationFilter?
```
	<security:http auto-config="false" use-expressions="true" entry-point-ref="http403EntryPoint" >
		<security:intercept-url pattern="/authorize" access="hasRole('ROLE_USER')" />
		<security:intercept-url pattern="/**" access="permitAll" />
		<security:custom-filter ref="perunAuthenticationFilter" position="PRE_AUTH_FILTER" />
	</security:http>

	<bean id="perunAuthenticationFilter"
		  class="cz.metacentrum.perun.oidc.overlay.PerunAuthenticationFilter">
		<property name="authenticationManager" ref="authenticationManager" />
	</bean>

	<security:authentication-manager alias="authenticationManager">
		<security:authentication-provider ref="preauthAuthProvider" />
	</security:authentication-manager>

	<bean id="preauthAuthProvider"
		  class="org.springframework.security.web.authentication.preauth.PreAuthenticatedAuthenticationProvider">
		<property name="preAuthenticatedUserDetailsService" ref="userDetailsService"/>
	</bean>

	<bean id="userDetailsService" class="cz.metacentrum.perun.oidc.overlay.PerunUserDetailsService"/>

	<bean id="defaultUserInfoRepository" class="cz.metacentrum.perun.oidc.overlay.PerunUserInfoRepository" primary="true"/>

	<bean id="defaultOAuth2AuthorizationCodeService" class="cz.metacentrum.perun.oidc.overlay.PerunAuthorizationCodeService" primary="true" />

	<bean id="defaultIntrospectionResultAssembler" class="cz.metacentrum.perun.oidc.overlay.PerunIntrospectionResultAssembler" primary="true" />
```

**Comment by jricher** [comment]
Catch the number format exception and return null, which indicates the user isn't found.

Further investigation shows that the UserInfoInterceptor *does* get called on calls to the token endpoint, and that should probably be restricted better.

**Comment by ondrejvelisek** [comment]
Thanks.
