### ISSUE TITLE
Introspecting client needs all scopes of the introspected access token hi,

### ISSUE THREAD

**Issue by thomasmey** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1101]

**Comment by jricher** [comment]
This is intentional functionality. Scopes that the introspecting client doesn't have will get filtered out from the results. This can be overridden by creating a new `IntrospectionResultAssembler`.

**Comment by thomasmey** [comment]
Hi,

Given two clients:
* One client only is allowed to call the introspection endpoint
* One implicit flow JavaScript app client.

The access token obtained with the JavaScript app has two scopes: read_resource1 and read_resource2 (the client itself is also assigned to this two scopes)

When now the only-introspection client calls the introspection endpoint with the access token from JavaScript client and the only-introspection client has no scopes assigned the introspection response will contain no scopes at all.

Bug or feature?

**Comment by jricher** [comment]
Intentional feature as stated above.
