### ISSUE TITLE
Server is totally confused by a colon in a scope token

### ISSUE THREAD

**Issue by thomasmey** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1102]
According to rfc6749 a colon in a scope name should be okay (0x3a) - see section 3.3

approve.jsp site seems to display scope tokens with a colon inside as an input text field after the colon sign.

Bug or feature?

**Comment by jricher** [comment]
In the current version, the colon is semantically important as it separates the "base" scope from the parameterized sub-component of the scope. This feature may be deprecated in 1.3 but at the moment it's intentional.
