### ISSUE TITLE
The "Documentation for the Maven project and Java API" link is broken

### ISSUE THREAD

**Issue by jbenhamou** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1106]
This link in the `README.md` file (Documentation for the Maven project and Java API) is broken.

I believe it needs to be updated to point to the [WIKI page](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki)

**Comment by jricher** [comment]
The link is broken because Maven Site is currently broken and nobody's had time to fix it yet: #984
