### ISSUE TITLE
JWT Validation and Authentication

### ISSUE THREAD

**Issue by wangruochan** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1107]
Hi!
I am using  Client Credentials Flow and successfully get the access token:

"eyJhbGciOiJSUzI1NiIsImtpZCI6InJzYTEifQ.eyJzdWIiOiI4ZTk1ZDA4NC05MTk2LTQ2OTgtYjc4Yi1jZWY1NWEzMmYyZGQiLCJhenAiOiI4ZTk1ZDA4NC05MTk2LTQ2OTgtYjc4Yi1jZWY1NWEzMmYyZGQiLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4Mlwvb3BlbmlkLWNvbm5lY3Qtc2VydmVyLXdlYmFwcFwvIiwianRpIjoiNjQxOTBmYTQtOTQ0MS00NTA1LWI5MjgtOGI1MDMwZjE3MWVlIiwiaWF0IjoxNDcwMjk3NjMyfQ.CJQB0VW8GSWZKPtbV4ZL62kDZxFU894DLN-vQMp7tvYm9Q4DjCcVIHuS3WPj2EWSzvFl-EJZxS0cPMsXkkYc7eGDORMALuQ61yTYrIcwlFKaEU_totIrURX8528b-oXqrZPNGT4p76FcJ39k0jTz5yWefDn6VY3zIQPmQs4jog1-0wWnPkOvanvQm9IGHUKgq2oKklDAreyzIDXPYYjXqzIWPk6Dd7TkVYLL57I08HXaaiVDNYni03bNxP5ASngDjFr6eMh_O1zkikfP6Vp0wqUDRHEGRE_8gi5IVlYqh-II1VT7gMW-eUM_IhOb8Awqy9_go42wJX69gAhrKaWPGw"

I find it in JWT format and I am using com.nimbusds.jwt.JWTParser  to parse the token ,but Can i validate the signature?

There are two questions:
1、Am I right to use server public key to validate access_toke?if it can,how to do the validation?
2、How to access to the token endpont when using the "Client Secret via symmetrically-signed JWT assertion",it seems totally different with "Client Secret over HTTP Basic"

Thanks and forgive my bad English!

**Comment by jricher** [comment]
1) Yes, use the server's public key to validate the access tokens generated by the server. The Key ID will be included in the header in the "kid" field.

2) Yes, symmetrically signed JWT assertions are completely different from a client secret. This is defined in the OpenID Connect specification: http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
