### ISSUE TITLE
Reflected XSS vulnerability on consent page

### ISSUE THREAD

**Issue by retomock** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1111]
Hi,

There seems to be a reflected XSS vulnerability on the consent page. See screenshot.
Steps to reproduce:
1. clone the repository (22/8/2016 master branch)
2. run the openid-connect-server-webapp
3. visit 
http://localhost:8080/openid-connect-server-webapp/authorize?response_type=code&client_id=client&scope=openid&redirect_uri=http://localhost/%3Cscript%3Ealert(%27XSS%27)%3C%2fscript%3E&nonce=123&state=456 in Firefox (V48.0 on Linux)
4. login as "user" / "password"
5. a popup saying "XSS" appears

In Chrome the script execution gets blocked: "The XSS Auditor refused to execute a script in 'http://localhost:8080/openid-connect-server-webapp/authorize?response_type=code&client_id=client&scope=openid&redirect_uri=http://localhost/%3Cscript%3Ealert(%27XSS%27)%3C%2fscript%3E&nonce=123&state=456' because its source code was found within the request. The auditor was enabled as the server sent neither an 'X-XSS-Protection' nor 'Content-Security-Policy' header."

![xss-2](https://cloud.githubusercontent.com/assets/21176094/17858749/d5ce704e-687e-11e6-9ae8-e54414d30099.png)

Regards,
Reto

**Comment by jricher** [comment]
Confirmed, looks like we need to set html escaping on the spring JSP tags.

**Comment by jricher** [comment]
http://docs.spring.io/spring/docs/2.5.x/reference/spring.tld.html#spring.tld.htmlEscape

**Comment by jricher** [comment]
Incidentally, this is also a good reason to run the server with strict redirect URI matching turned on, which would have prevented this attack anyway. This will likely be the default in 1.3 and above.

**Comment by jricher** [comment]
Turns out that we can't set that universally or it will break how we're handling display templates. However, this should be the only instance where a value wasn't previously explicitly escaped, so we've done that for just this place now.
