### ISSUE TITLE
Supporting Self-Contained Tokens

### ISSUE THREAD

**Issue by oopdas** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1113]
Does MITReid support self-contained tokens (that are not saved in the DB)?

Self-contained tokens:
http://connect2id.com/blog/connect2id-self-contained-access-tokens

Thanks!

**Comment by jricher** [comment]
You would need to swap out the token service layer of the server, but it could be done with custom extensions on that.

**Comment by oopdas** [comment]
Thanks for the reply!

By swapping out "token service layer", do you mean we implement OAuth2TokenEntityService,  AuthorizationCodeServices, and then replace all the defaultOAuth2ProviderTokenService/defaultOAuth2AuthorizationCodeService with our EntityService/AuthorizationCodeService?

Is there any other class that needs to be swapped out?

Also, I saw OAuth2TokenEntityService has getAccessTokenById(Long id).  I assume we can just return null since it's not applicable to self-contained tokens? Will anything break?

Thanks for the help!

**Comment by jricher** [comment]
Yes, you'd need to implement your own classes for everything that deals with tokens and hits the database today. It's a lot of surgery, and I'm not sure off-hand how deep it would reach, but it should be doable. 

I don't know what would break by returning null from the ById class, but I would assume that at the least several of the data APIs (reachable from /api) won't function properly.
