### ISSUE TITLE
Sign-in with social identity provider (e.g. Google) 

### ISSUE THREAD

**Issue by sdoxsee** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1114]
I've seen https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Sample-Static-Configuration-for-using-Google-Authentication that explains how to use the mitreid connect client libraries to make a spring app client use Google as the (OP) OpenID Connect Provider. I'd like Google sign-in abilities on the OP itself and not for a client app.

What I'd like to do is to allow someone to "link" or "map" their Google user to their mitreid user so that they don't have to use mitreid-specific credentials to log in. Of course they'll need to have a mitreid user to link to but, once that is complete, they could click a "Google Sign-in" button on the mitreid login page to provide an alternate way of creating an authenticated session on the OP. 

I know that keycloak has the ability to do this (although not exactly as I would like and possibly with bugs). However, I'd rather not move to keycloak for the following reasons:
- I'd have to migrate all the existing tokens
- Keycloak seems to be a "heavy", "kitchen-sink" solution making me think that there will be bugs that may get ignored for a long time.
- It currently seems to have a bug with end session endpoints (https://issues.jboss.org/browse/KEYCLOAK-3399) which already works for me in mitreid (https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/972)
- I'm more famliar with spring-based apps like mitreid

My plan is to create a separate microservice web application to handle the mapping. However, if mitreid wanted to have such behaviour as a PR, I could do it there. I just think it might be a bit "heavy" and it would definitely require DB additions.

Thoughts?

**Comment by jricher** [comment]
We already support this by using the client library to log in to the server, but you need to set that up for yourself. We don't want to have that dependency in the main server, but it's easy to do in an overlay. For an example, see the use of uma-server-webapp and its use of ROLE_EXTERNAL_USER there for special processing. Instead of that you can just do external logins for the regular user accounts.

**Comment by sdoxsee** [comment]
Thanks for the advice on this. Didn't respond yet as I'm still working it
all out. As far as I understand it, it's just working out how to map/unmap
the external google identifier to the real user...which will require some
DB changes (or something persistent).
