### ISSUE TITLE
{"error":"invalid_client","error_description":"Client with id 575dd7eb-50b9-441e-9bc7-ee62cf42d721 was not found"}

### ISSUE THREAD

**Issue by leleuj** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1115]
Hi,

I just created an OpenID Connect client on https://mitreid.org/manage/dev/dynreg/new 

The ID is: `6d9e17c6-348f-40cf-b6e6-86fcf3be2081`

Though, when I try to login with it, I always get the error:

`{"error":"invalid_client","error_description":"Client with id 575dd7eb-50b9-441e-9bc7-ee62cf42d721 was not found"}`

The identifier in the error message is not the one I have for my OpenID Connect client and use in my authorize url:

`https://mitreid.org/authorize?response_type=code&client_id=6d9e17c6-348f-40cf-b6e6-86fcf3be2081&redirect_uri=http%3A%2F%2Fwww.pac4j.org%2Ftest.html&scope=openid+profile+email&state=G7ysqBtBQ8GSbW7-sbcBPaOI_JEG-IKYj4ne53Pipdc`

I created another client and got the same error. Am I missing something?

Thanks.
Best regards,
Jérôme

**Comment by jricher** [comment]
I've seen that error as well, and I'm not sure what's the cause of it as I don't see it in other environments. It's been a while since the test server (mitreid.org) was reset, and it probably needs to be cleaned up. It's been through a number of upgrades, including beta releases, with a bunch of people hammering on the server with test configurations and not a lot of oversight.

**Comment by leleuj** [comment]
I'm the creator of [pac4j](www.pac4j.org) and wanted to use it to test my OpenID Connect support once more with mitreid.org: do you plan to fix the problem?

**Comment by jricher** [comment]
The database on mitreid.org has been cleared out, so you can try it again and see if you get the same error. There seem to be a few oddities with that instance, still, but it's generally working.

**Comment by leleuj** [comment]
Thanks. It works now: https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/test/java/org/pac4j/oidc/run/RunMitreIdOrg.java
