### ISSUE TITLE
GET requests allowed to get access tokens

### ISSUE THREAD

**Issue by langnix** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1118]
In the Version 1.25 it is possible, to retrieve tokens by a GET request. 

--

curl -x "" "${openIdHost}/token?grant_type=password&username=$endUser&password=$endPwd"       --user "$clientUser:$clientPwd"

--- 

the spec: https://tools.ietf.org/html/rfc6749#section-3.2 says:
...
The client MUST use the HTTP "POST" method when making access token  requests.
...
therefore the server should not deliver tokens when parameters are passed via GET

**Comment by jricher** [comment]
The client MUST use POST, and the server MUST support POST, but the spec is silent on other methods (such as GET), so implementing this is not against the spec.

**Comment by langnix** [comment]
Thats correct, but I still think a server SHOULD NOT react on GET, especially because it MAY lead to security issues, like "having passwords in access logs".
