### ISSUE TITLE
Connect openid-connect-server-webapp with a external PostgreSQL database

### ISSUE THREAD

**Issue by AI3X09** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1120]
Hey everyone, 

i have a little problem with the openid webapp. 

If i chance the data-context.xml file and want to reload the application in tomcat, it doesnt work.
Additional i loaded the tables in my PostgreSQL database.

        <property name="jdbcUrl" value="jdbc:postgresql://192.168.1.145:5432/openid-connect" />
        <property name="username" value="postgres" />
        <property name="password" value="postgres" />

        <bean id="jpaAdapter" class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter">
                <property name="databasePlatform" value="org.eclipse.persistence.platform.database.PostgreSQLPlatform" />
                <property name="showSql" value="true" />
        </bean>

The other stuff i comment out by the way. 

If someone could tell me what i have to do, i would be very happy :D

**Comment by jricher** [comment]
Do you have a data source bean set up?

```xml
	<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
		<property name="driverClassName" value="org.postgresql.Driver" />
		<property name="jdbcUrl" value="jdbc:postgresql://localhost/oic" />
		<property name="username" value="oic" />
		<property name="password" value="oic" />
	</bean>
```

**Comment by AI3X09** [comment]
Yes, it didnt show up in the comment.
