### ISSUE TITLE
Question about client secret encoding

### ISSUE THREAD

**Issue by ngriesser** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1123]
Hi,

We started our project with version 1.2.0-SNAPSHOT of OpenID-Connect-Java-Spring-Server. At that time client secrets were saved as is in the database (for ex Ktxkn?/sv04*4). 

Now we are trying to migrate to 1.2.6. The client now sends an encoded version of the secret (in our case Ktxkn%3F%2Fsv04_4) using UriUtils.encodePathSegment. The server considers it as incorrect, as it uses UriUtils.encodeQueryParam which results in Ktxkn?/sv04_4.

What is the right way to make secrets match again? 

Kind regards,
Nadège

**Comment by jricher** [comment]
The change you mention is to bring the server in strict alignment with the OAuth spec, which requires URL percent encoding. This hadn't affected many users since the server issues client IDs and secrets that don't have any characters that would require encoding. The secret like the one you have (which I'm guessing was hand-generated somewhere externally?) does have special characters and would require encoding. To make it work, you'll need to use compliant versions of the code on either side of the transaction, both client and server.

**Comment by ngriesser** [comment]
Our password policy forces us to have special characters in passwords, so you are right it was generated externally.
We now have 1.2.6 on either side client and server.
I tried saving it again using the GUI under Home / Manage Clients / Edit Client. It is still saved as "Ktxkn?/sv04*4" in the database.
Is it a bug that the client uses encodePathSegment and the server encodeQueryParam in 1.2.6?

**Comment by jricher** [comment]
I would check your policies, first. Your password policy *should* only be applied to user passwords, not to software keys like this. There are likely many more bits of entropy in the server-generated client secret than the ones you're generating that follow your user-password policy rules. 

It should be saved as the exact string in the database, as above, and only the comparison is done using the encoder. A mismatch between the encoders might be the issue, try swapping one or the other and see if that clears the issue. If so, we'll put out a patch that aligns the two.

**Comment by ngriesser** [comment]
The following change helped :
In openid-connect-common in org.mitre.oauth2.service.impl.UriEncodedClientUserDetailsService
line 71 changed from
`String encodedPassword = UriUtils.encodeQueryParam(Strings.nullToEmpty(client.getClientSecret()), "UTF-8");`
to 
`String encodedPassword = UriUtils.encodePathSegment(Strings.nullToEmpty(client.getClientSecret()), "UTF-8");`
as UriUtils.encodePathSegment is used in org.mitre.openid.connect.client.OIDCAuthenticationFilter (line 335)
Hope this was the right swap. :)

**Comment by jricher** [comment]
Closed by #1125
