### ISSUE TITLE
Rest API returning 401 

### ISSUE THREAD

**Issue by magaram2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1128]
I am running into a situation where my rest service returns a 401 even though it is fully authenticated. I was able to test GET http://localhost:8080/openid-connect-server-webapp/clients successfully from postman using the same access token.

However when I test my rest service I get a 401

{
"error": "unauthorized",
"error_description": "Full authentication is required to access this resource"
}

//Rest service snippet
@RestController
@Component
@RequestMapping(value = "/api/SampleService")
@PreAuthorize("hasRole('ROLE_USER')")
public class MySampleService {
...

@RequestMapping(value = "/getAll", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity getAll(Authentication auth) {
...
}

////Spring wiring/////

``` xml
<security:http pattern="/api/**" use-expressions="true" entry-point-ref="oauthAuthenticationEntryPoint" create-session="never">
    <security:custom-filter ref="openIdConnectAuthenticationFilter" before="PRE_AUTH_FILTER" />
</security:http>

<security:authentication-manager alias="authenticationManager">
    <security:authentication-provider ref="openIdConnectAuthenticationProvider" />
</security:authentication-manager>

<bean id="openIdConnectAuthenticationProvider" class="org.mitre.openid.connect.client.OIDCAuthenticationProvider">
    <property name="authoritiesMapper">
        <bean class="org.mitre.openid.connect.client.NamedAdminAuthoritiesMapper">
            <property name="admins" ref="namedAdmins" />
        </bean>
    </property>
</bean>
```

**Comment by jricher** [comment]
OpenID Connect isn't for protecting APIs, it's for protecting interactive websites with a log in. OAuth is for protecting APIs. You can protect a web application with both, but the configuration is going to be different. 

In the OpenID Connect case, you need to set up a "client". That's what our library provides. In the OAuth case, you need to set up a "protected resource", and we don't provide that. We do provide a token introspection service that can hook in to the Spring Security OAuth library for that purpose.
