### ISSUE TITLE
clientId and clientSecret just sent in the authenticate

### ISSUE THREAD

**Issue by Faury** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1131]
Hello,

I'm trying to use the client to connect to a IBM Tivoli Server. I managed to authenticate in their specific login page and got an authentication code, my problem starts when the client try to get the token, it appears that for every post the Tivoli demands that I send the clientId and the clientSecret again doesn't matter if I'm already authenticated. But the mitreid client just send them in the authenticate.

There's some kind of config that I can do to force the client to always send the clientId and the clientSecret when communicating with the SSO server or I just can do it changing the code?

Thanks in advance

**Comment by ernani** [comment]
Make sure that the client is sending the client_id and client_secret via POST and not via Basic Authentication headers, not sure if the client can do that.

**Comment by jricher** [comment]
The client will always send the client ID and secret in requests to the token endpoint. This is required on every POST, as there are not (and should not be) sessions on the token endpoint of the server. The client library can send the ID and secret in either HTTP Basic (the default) or in the form parameters by changing the "tokenEndpointAuthMethod" flag to either SECRET_BASIC or SECRET_POST: http://mitreid-connect.github.io/apidocs/org/mitre/oauth2/model/ClientDetailsEntity.AuthMethod.html

**Comment by ernani** [comment]
Oh, you beat me to it.

I was about to reply that I've found that info here:

http://mitreid-connect.github.io/openid-connect-common/apidocs/index.html?serialized-form.html

**Comment by Faury** [comment]
Sorry if I took too long to answer, but the SECRET_POST option solved the token issue. But now I have another problem not sure if the best is close this one and open another issue. 

Mitreid wants the /jwk location what my server doesn't have (it also doesn't have /userinfo), the token is signed with a certificate. So I can decode using Java code.

Is there a way to configure to skip this step or do my own token validation?

Thanks by the support.

**Comment by jricher** [comment]
Your server needs to publish its key in JWK format:

http://openid.net/specs/openid-connect-core-1_0.html#DynamicMTI

This client will only work with servers conforming to that format, unless you provide your own keystore library.

**Comment by ernani** [comment]
You can also export the pubkey of the cert and use pem-jwk to export the
cert to a json structure and host it somewhere as a JWKS endpoint.

Regards!

**Comment by claudefalbriard** [comment]
During the testing, I found an interesting conflict between the IBM IdP provider and the MITREID client.  Why is the call to /userinfo declared as mandatory, if the returning data fields are already part of the OIDC ID token, indeed its where we find a deeper level of information about the identity logged. At our IdP server there is no implementation available for /userinfo. In the MITREID client, is there a setup parameter, that could be updated to skip the /userinfo step, or to replace it by a similar call, like /introspect, one of the available functions that supports token revalidation? If no setup parameter available, is it possible to adjust it at a source level and recompile the package? 
Regarding the JWK endpoint, which is also missing at our IdP, is it possible to reference it on a local URI, or even fetch the RSAPublicKey from a locally stored JWK, or JWKS.  The Nimbus JOSE library delivers good conversion support to provide the public key required for JWT signature validation. This must be added as an extension, or is it configurable?

**Comment by claudefalbriard** [comment]
Sorry, my fault. I just found a previous issue report from 2013, which describes how to remove the optional /userinfo call, see:  
[](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/510) (no need for /userinfo, should be OK)
"The userinfo endpoint doesn't exist on all servers, client should silently skip it if the userinfo property isn't configured on the server configuration bean".
Out team will give it a testing today.
