### ISSUE TITLE
Fix field definition in the model object

### ISSUE THREAD

**Issue by JessicaCar** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1133]
Hello, 

We are developing our SSO with Mitreid OpenID Connect. We have detected that ACR Default Values field is not saved in database from the Edit client screen . We have seen that it is because in openid-connect-server-webapp / src / main / webapp / resources / js / Client.js the field  defaultAcrValuesCollection and defaultAcrValues should be called defaultACRvaluesCollection and defaultACRvalues to be saved correctly in database.

You want we do push for change or want to do it you.

Thank you very much.

Jessica Carpintero.

**Comment by jricher** [comment]
This would be great as a pull request, or we can try to fix it. This wasn't caught as nothing in the core server uses that field yet.
