### ISSUE TITLE
What will be returned if grant_type=client_credentials sent as query parameter?

### ISSUE THREAD

**Issue by xperiandri** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1134]
We have a [discussion](https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/347#issuecomment-253825958) about **Client credentials grant** request.
A tried to send a request in form of query parameters instead of `x-www-form-urlencoded`  and got a message that `grant_type` us not specified. So I couldn't find what is wrong for a long time.
Do you think it reasonable to check for this case and return an appropriate error message?

**Comment by jricher** [comment]
Requests to the token endpoint should be an HTTP POST with parameters in the form body.

 — Justin

**Comment by xperiandri** [comment]
It is a successful scenario.
What will be a result of unsuccessful scenario?
