### ISSUE TITLE
Question around nimubus jose + jwt version

### ISSUE THREAD

**Issue by CSGJavaDev** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1145]
Hi,

It looks like in the OpenID Connect server webapp it is using version 4.3 of the nimbus jose + jwt library. Would there be any adverse effects if a later version of this library (say 4.9) was dropped in instead?

Thanks!

**Comment by jricher** [comment]
Shouldn't be, and if you can submit a pull request we can include it in the 1.3 development branch.
