### ISSUE TITLE
Introspecting id token should not return `Bearer` as `token_type`

### ISSUE THREAD

**Issue by sofiaguyang** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1147]
Here is an example response when introspecting an id token:

```
{
  "active": true,
  "scope": "",
  "expires_at": "2016-11-15T13:45:27+0800",
  "exp": 1479188727,
  "sub": "109d9952-8eae-48a4-8516-4af6fde52616",
  "user_id": "109d9952-8eae-48a4-8516-4af6fde52616",
  "client_id": "client1",
  "token_type": "Bearer"
}
```

I believe id token should not be returned with `Bearer` as `token_type` because the id token is not meant to be used as Bearer token. 

Notice how the refresh token does not have the `token_type` attribute:

```
{
  "active": true,
  "scope": "openid offline_access",
  "expires_at": "2016-11-22T13:47:02+0800",
  "exp": 1479793622,
  "sub": "109d9952-8eae-48a4-8516-4af6fde52616",
  "user_id": "109d9952-8eae-48a4-8516-4af6fde52616",
  "client_id": "client1"
}
```

**Comment by jricher** [comment]
ID Tokens are currently stored as access tokens, so they get the same kinds of attributes as regular access tokens in this response.

**Comment by sofiaguyang** [comment]
@jricher Yes I am aware that id tokens are stored in the same table as access tokens. However, what's happening is our clients are able to use the id token as Bearer token when accessing resource server. 

What can be done is: during creation of id token, we can set the id token's token type to be `ID Token` via `OAuth2AccessTokenEntity.setTokenType`. Then in `DefaultIntrospectionResultAssembler`, we can omit the token_type if the value is `ID Token`.

**Comment by jricher** [comment]
ID Tokens are no longer stored in the database and so, currently, can't be introspected in 1.3+. If introspection ability for ID tokens is added back in (through the assertions processor framework, most likely), then we can make sure this field isn't set.
