### ISSUE TITLE
Postgres install file, missing columns

### ISSUE THREAD

**Issue by cornelius-agrippa** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1148]
Hello there,

I was trying to work with openid-connect-server-webapp using postgres and I noticed psql_database_tables.sql, table client_details, doesn't contain the following columns that are present in HSQL's installation file (hsql_database_tables.sql):

software_statement VARCHAR(4096),
code_challenge_method VARCHAR(256)

This is my first time using a public github so please excuse my ignorance if this isn't the best way to report issues like this.

EDIT: I made a pull request for this.

Best regards

**Comment by jricher** [comment]
Development happens on the HSQL version and gets ported to the other databases later on, so things can sometimes get out of sync. Thanks for the patch, and we'll get that incorporated.

**Comment by cornelius-agrippa** [comment]
Nice. Thank you very much for your work.
