### ISSUE TITLE
Redirect URI to localhost

### ISSUE THREAD

**Issue by jtabouret** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1149]
Hi,

We are in the process of building our OIDC client/server using the MITREid suite. We have deployed the openid-connect-server-webapp overlay on AWS and I am testing the client that is running on my local machine.

In the client configuration I kept localhost:8080 as the default redirect URI.

As a result once the authorization has been granted by the end user, the authorization code is sent to localhost:8080... and is obviously ends up being handled by the server.

This is the logs available after authorization is granted:
`DEBUG: org.springframework.security.oauth2.provider.endpoint.FrameworkEndpointHandlerMapping - Returning handler method [public org.springframework.web.servlet.View org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.approveOrDeny(java.util.Map<java.lang.String, java.lang.String>,java.util.Map<java.lang.String, ?>,org.springframework.web.bind.support.SessionStatus,java.security.Principal)]
DEBUG: org.springframework.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.RedirectView: unnamed; URL [http://localhost:8080/login?code=NSB8hB&state=2f1c9b6013631]] in DispatcherServlet with name 'spring'`

Unfortunately I currently cannot use an IP that would refer to my local machine.

But I noticed that the IdP available at https://mitreid.org allows clients to specify localhost:8080 as a valid redirect URI.

Would you have any advice on how I should configure my server so that localhost actually points to the RP's IP ?

Thank you in advance for your help.

**Comment by jricher** [comment]
I'm not sure what you're trying to accomplish here or why this isn't working for you as currently implemented. `localhost` is always from the perspective of the current user's browser. There's nothing to configure on the server to make that work.

**Comment by jtabouret** [comment]
Thank you for your quick reply !

Actually the request doesn't reach my browser. It is immediately handled by the server.

After the authorization process, the server properly redirects to the RP's redirect URI:

`DEBUG: org.springframework.security.oauth2.provider.endpoint.FrameworkEndpointHandlerMapping - Returning handler method [public org.springframework.web.servlet.View org.springframework.security.oauth2.provider.endpoint.AuthorizationEndpoint.approveOrDeny(java.util.Map<java.lang.String, java.lang.String>,java.util.Map<java.lang.String, ?>,org.springframework.web.bind.support.SessionStatus,java.security.Principal)]
DEBUG: org.springframework.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.RedirectView: unnamed; URL [http://localhost:8080/login?code=NSB8hB&state=2f1c9b6013631]] in DispatcherServlet with name 'spring'`

Right after that, the request is handled by the server that looks for the /login view.

`DEBUG: org.springframework.web.servlet.DispatcherServlet - DispatcherServlet with name 'spring' processing GET request for [/login]`

And as it finds it, it redirects to the server's login page.

`DEBUG: org.springframework.web.servlet.DispatcherServlet - Rendering view [org.springframework.web.servlet.view.JstlView: name 'login'; URL [/WEB-INF/views/login.jsp]] in DispatcherServlet with name 'spring'`

Does it means that I should redirect to a path that is not defined by the IdP ?

**Comment by jtabouret** [comment]
Sorry I made a mistake in my previous explanation.

Actually the request hits my browser but the redirect location is not pointing to localhost:8080 (as the app says after the authorization process) but to the OIDC server hostname.

I wonder if AWS elastic beanstalk may rewrite the content of the `location` header before sending the response?

Anyway it don't think it can be related to the webapp since it doesn't know about the server hostname.

**Comment by jricher** [comment]
Sounds like it has something to do with the AWS proxying, it might be rewriting the localhost on the way out because the MITREid server will send it out as-is.

**Comment by jtabouret** [comment]
Yes, it is AWS that is rewriting localhost on the way out.

Configuring the client with a random hostname added to my local /etc/host as an alias for 127.0.0.1 did the trick.

Sorry for this misleading issue.
Thank you very much for help !
