### ISSUE TITLE
Invalidate server session

### ISSUE THREAD

**Issue by rustykrun** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1151]
Where to invalidate the session on the server, after the access token is delivered so that the user is redirected to the login page for each request to the token endpoint?

**Comment by jricher** [comment]
The requests to the token endpoint do not involve the user logging in, as they're in the back channel. But if you are referring to the authorization endpoint, then you can force a login by simply sending "prompt=login" to the server as a parameter in the authorization request. 

Alternatively, you could configure your sessions to be extremely short lived at the IdP.
