### ISSUE TITLE
Refresh Token behaviour

### ISSUE THREAD

**Issue by ICEMANno1** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1152]
Hi,
I was playing around with the behavior and settings regarding refresh tokens. Here is a long (sorry) summary of what I realized.

General behavior regarding refresh tokens:
- A client can get as many access tokens as he wants (depending on the consent settings), as long as the end user has a active session
- Per access token the client can get a refresh token (if he's allowed to)
- Whenever an access token expires, the client can use a refresh token to get a new access token

In the Mitre UI, you can do the following settings:
1. "Refresh tokens for this client are re-used"
2. "Active access tokens are automatically revoked when refresh tokens are used"
3. "Refresh tokens do not time out"

Here's how the Mitre behaves with the three settings:
- Setting 1: Either the Refresh Token can be re-used as many times as wanted or will be renewed with a new one every time used
- Setting 2&3: Self explaining to me

I was wondering if the following behavior is working as intended?
If you set a timeout of a refresh token and set the 1st setting to re-use, the refresh token can be used as often as needed until the timeout. If you change the setting to not reuse but set a timeout, with every use of the refresh token a new one is generated, the old one is revoked and the new one gets the timeout of the setting in 3. Therefore the client can use this behavior to have unlimited refresh token time.

Was this intended like this?

I would expect with a set timeout and the the setting set to no re-use, the timeout of all refresh token related to each other should have one timeout.

Thanks for the help,
Dominik

**Comment by jricher** [comment]
Yes, this is intended behavior. New refresh tokens reset the timeout clock. If you want to have a universal timeout even for newly-issued refresh tokens, you'd have to modify the token services layer to do that. If this were added in the server, it would need to be done as an option (another checkbox above).

**Comment by ICEMANno1** [comment]
OK, thanks for the clarification. I was just wondering, because with the setting 1. set to do no re-use, you (as a client application) can produce the option 3 by your own with always using a refresh token slightly before the timeout of it.
