### ISSUE TITLE
Duplicate key name 'at_tv_idx'

### ISSUE THREAD

**Issue by isedrof** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1155]
Trying to make a connection with MySQL i got this error : 

Error creating bean with name 'org.springframework.jdbc.datasource.init.DataSourceInitializer#0': Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #49 of resource class path resource [db/tables/mysql_database_tables.sql]: CREATE INDEX at_tv_idx ON access_token(token_value(767)); nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Duplicate key name 'at_tv_idx'

**Comment by jricher** [comment]
You're not supposed to execute the SQL files every time with a persistent database like MySQL. Run the files once to set up the tables, then launch the application.

**Comment by isedrof** [comment]
I commented the 5 last lines and it worked.
But when i try to add another User (username + password) and try to log to the server with those identifying information , i got this Error 

![error](https://cloud.githubusercontent.com/assets/22192862/20931470/75423e80-bbd1-11e6-96b2-15652115c802.PNG)

**Comment by jricher** [comment]
Sounds like you've got a duplicate item in your database, probably from being initialized improperly. I would suggest dropping the database and re-creating it using the `.sql` file directly, and not re-running it on startup every time.

**Comment by isedrof** [comment]
I don't think that the problem is here, because before i added the new User i was able to log into the server by the default information ("admin" + "password")
and when you say not re-running it on startup every time, we have to delete lines which execute the "MySQL_database.sql" ?

**Comment by jricher** [comment]
Yes, you're not supposed to run those every time the server starts. Those scripts are really designed for the in-memory HSQL database that gets created from scratch every time the server starts, which we use for testing and development.

**Comment by isedrof** [comment]
I understand better.
But in my case, the problem is a little different, when i open catalania.out (tomcat logs) i find: 
```

INFO : org.mitre.openid.connect.config.JsonMessageSource - No locale loaded, trying to load from ServletContext resource [/resources/js/locale/fr/messages.json]
ERROR: org.mitre.openid.connect.config.JsonMessageSource - Unable to load locale
java.io.FileNotFoundException: Could not open ServletContext resource [/resources/js/locale/fr/messages.json]
```

and in the bottom i get this line : 

`INFO : org.mitre.openid.connect.web.AuthenticationTimeStamper - Successful Authentication of user at Tue Dec 06 16:46:54 CET 2016`

**Comment by jricher** [comment]
Those errors and messages are completely unrelated to your database, or each other. The first set says that it can't find the french translation of the server -- which makes sense, because unless you've written one, there isn't one. If you have written one, please submit it back as a pull request. :)

The second one says that the login was successful.
