### ISSUE TITLE
Client Implicit Flow!

### ISSUE THREAD

**Issue by jimmy-khalifa** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1157]
Hey,
We have an identityServer3 and I am trying to make a J2EE app use the SSO. I have a problem reaching the server proparly because the built url uses response_type=code (I saw it hard coded in the project openid-connect-client in the class SignedAuthRequestUrlBuilder --> buildAuthRequestUrl 
`claims.claim("response_type", "code");`
This is the request url I get
`https://server/connect/authorize?response_type=code&client_id=app&scope=openid+email+profile &redirect_uri=http://localhost:9470/app/openid_connect_login&nonce=4f3861a74a5e&state=38f11deb0460a`
and I get `The client application is not known or is not authorized.`
when I use response_type=id_token token i get redirected to the login page 
`https://server/connect/authorize?response_type=id_token token&client_id=app&scope=openid+email+profile &redirect_uri=http://localhost:9470/app/openid_connect_login&nonce=4f3861a74a5e&state=38f11deb0460a`
I tried adding 
`<property name="grantTypes"><set value-type="java.lang.String">			<value>implicit</value></set></property>` But naturally it doesn't have any effect.
Does this mean we can't make an implicit flow !! Or am I missing something ?

Thank you

**Comment by jricher** [comment]
The implicit flow is only for in-browser javascript clients. As our client library is for server-side java applications, it does not support the implicit flow. If you're trying to use the implicit flow with a J2EE application, you're not using OAuth/OIDC appropriately. The IdentityServer3 project should support the authorization code flow as well, so configure your server to use that for this client.

**Comment by jimmy-khalifa** [comment]
Thank you for your reply. As you said the configuration of our IdentityServer accepts only the Implicit Flow. I will add the configuration for my application to Authorization Code.
Thanks so much that was helpful 👍
