### ISSUE TITLE
Invalid refresh token

### ISSUE THREAD

**Issue by jainh** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1164]
There is a scenario
Two clients with same name but different redirect registered with Mitre server. User logs in from one client create token and it expire then later refresh, similarly same user logs in using second client create token and it expire then later refresh which result in invalid_refresh token, Also in UI i don't see refresh token corresponding to that. There is no setting in UI that says refresh token expired (It is as default). 

So, my question is when does refresh token gets removed from UI or by server ?

**Comment by jricher** [comment]
Refresh tokens are tied to the client that they were issued to. If I'm reading your report right, you're expecting a refresh token from one client to be usable by a second one? That's not going to work, and that's by design. 

As to the question you asked directly: the refresh tokens can expire if they're set up to do so, this is configured on a per-client basis. They can also be removed by the admin and end-user UI.

**Comment by jainh** [comment]
@jricher I agree token from one client cannot be used by another. But, what is being observed that server deleting refresh token (even if it is set no-time-expired or any manual management) when user uses refresh token from the client #2 ( token was generated from the same client #2 not other #1). Message says "Found 1 orphaned authentication holders". I am not sure why refresh token is getting deleted automatically.

**Comment by jainh** [comment]
@jricher One more question if refresh token request is being made with wrong client credentials result in clearing up SecurityContextHolder which in turn remove refresh token used in the request form database or server ?

**Comment by jricher** [comment]
If you use a refresh token with the wrong client credentials then the token gets removed from the repository as that's a security violation:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L325

**Comment by jainh** [comment]
@jricher  Thank you make sense.
