### ISSUE TITLE
Connection leak problem

### ISSUE THREAD

**Issue by vsapram** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1165]
While i am clearing the tokens in oauth server, i see at times null pointer exception at this line

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L108

After that, the exception is leading to wards the connection leak. Any idea what could be the problem?

**Comment by vsapram** [comment]
Is there any other alternative for this?

**Comment by jricher** [comment]
The token cleaning system was just updated, please try this again. I haven't seen an exception or a connection link in the deployments I've run.
