### ISSUE TITLE
MySQL HTTP Error: 503

### ISSUE THREAD

**Issue by bunyaminsg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1166]
I am trying to use mysql instead of hsql, however I got HTTP 503 Service Unavailable error. I have a running mysql server and I did the configurations. Also the webapp was working before changing it to mysql. Can you help? 

Also, do you have plans to create examples on how to use MySQL, MongoDB, etc. with mitreid? We suffer from lack of documentation and support.

**Comment by jricher** [comment]
You've likely got something wrong in your configuration files, most notably `data-context.xml` that sets up the database. The examples are all in there for MySQL, and there are many production systems that run on MySQL. Your server's logs likely have more information as to what's wrong. Did you initialize the database with the appropriate schema file? 

MongoDB is not currently supported as a data platform.

**Comment by bunyaminsg** [comment]
I run all of the mysql scripts and loading_temp_tables.sql manually to make sure. I have all the tables in a db named oic, my mysql server run on port 3306 and in my data-context.xml I commented the hsql part, uncommented mysql and removed initialize scripts (since I execute them manually). Here is the mysql part of data-context.xml:

```
<!--  The following is for connecting to a MySQL database that has been initialized with 
			src/main/resources/db/mysql/mysql_database_tables.sql -->
	<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
		<property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
		<property name="jdbcUrl" value="jdbc:mysql://localhost:3306/oic" />
		<property name="username" value="root" />
		<property name="password" value="f3S5o4c6!" />
	</bean>



	<bean id="jpaAdapter" class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter">
		<property name="databasePlatform" value="org.eclipse.persistence.platform.database.MySQLPlatform" />
		<property name="showSql" value="true" />
	</bean>
```

**Comment by jricher** [comment]
That all looks fine. Did you add the MySQL database driver as a project dependency? The version is managed but the actual dependency isn't pulled in by the base project.

**Comment by bunyaminsg** [comment]
I didn't notice the error before, now I saw this:
`
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'driverClassName' threw exception; nested exception is java.lang.RuntimeException: Could not load class of driverClassName com.mysql.cj.jdbc.Driver
`

This dependency is declared in the parent pom.xml file: 

```
</dependency>
			<!-- Database -->
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>5.5.53</version>
			</dependency>
                        ...
```

I only changed the version to `5.5.53`. Am I supposed to add any other dependency?

**Comment by jricher** [comment]
That's not a dependency, that's dependency management. It sets the version to be used but doesn't pull in the actual dependency. You'll need to add the dependency (without the version tag) in the server or server-webapp project.

**Comment by bunyaminsg** [comment]
I have the below on dependencies of server-webapp, but error is the same.

```
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
</dependency>
```

If this is not the dependency you mention, could you give me the code segment that I should add?

**Comment by jricher** [comment]
That should do it, check your resulting .war file to see if the connector .jar is in there. If not, something is wrong with your build process. Otherwise, I don't know.

**Comment by bunyaminsg** [comment]
Both `spring-jdbc` and `mysql-connector` are in the war file.

**Comment by bunyaminsg** [comment]
I found it, 

```
<bean id="dataSource" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
		<property name="driverClassName" value="com.mysql.cj.jdbc.Driver" />
		<property name="jdbcUrl" value="jdbc:mysql://localhost:3306/oic" />
		<property name="username" value="root" />
		<property name="password" value="****" />
	</bean>
```

Here the mysql jdbc driver is imported from `com.mysql.cj.jdbc.Driver`, I changed it to `com.mysql.jdbc.Driver` and it worked. I think it was a typo. You may want to change it in your source file.

**Comment by praseodym** [comment]
The cj variant only works with connector v6 and newer: https://dev.mysql.com/doc/connector-j/6.0/en/connector-j-api-changes.html

**Comment by bunyaminsg** [comment]
Its version was 5.1.34 in the parent pom.xml. The configurations are not compatible with each other then.

**Comment by jricher** [comment]
Ah, good eye everyone -- looks like that change sneaked in with a bunch of others in a recently merged pull request, so all the MySQL production systems that I know (all the production 1.2.x branch ones anyway) didn't see that change. I'll pull it back to `com.mysql.jdbc.Driver` for now and we can consider a newer version of the connector in 1.3.
