### ISSUE TITLE
Exception in clearExpiredTokens scheduled Job

### ISSUE THREAD

**Issue by mpeddagolla** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1170]
Hi,

We are using 1.2.4 version currently and lately we are seeing exceptions being thrown from the clearExpiredTokens scheduled Job. Below is the log we are seeing. Any idea on why this might be happening? I have never replicated this locally but in prod we see them quiet often.

> 05:13:10.337 [taskScheduler-4] ERROR o.s.s.s.TaskUtils$LoggingErrorHandler - Unexpected error occurred in scheduled task. (TaskUtils.java:95) 
> java.lang.IllegalArgumentException: AuthenticationHolderEntity not found: org.mitre.oauth2.model.AuthenticationHolderEntity@5267bdea
> at org.mitre.oauth2.repository.impl.JpaAuthenticationHolderRepository.remove(JpaAuthenticationHolderRepository.java:58) ~[openid-connect-server-1.2.4.jar:na]
> at org.mitre.oauth2.repository.impl.JpaAuthenticationHolderRepository$$FastClassBySpringCGLIB$$b0f655b9.invoke(<generated>) ~[spring-core-4.1.9.RELEASE.jar:na]
> at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:718) ~[spring-aop-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.mitre.oauth2.repository.impl.JpaAuthenticationHolderRepository$$EnhancerBySpringCGLIB$$75b15c6c.remove(<generated>) ~[spring-core-4.1.9.RELEASE.jar:na]
> at org.mitre.oauth2.service.impl.DefaultOAuth2ProviderTokenService.clearExpiredTokens(DefaultOAuth2ProviderTokenService.java:489) ~[openid-connect-server-1.2.4.jar:na]
> at sun.reflect.GeneratedMethodAccessor746.invoke(Unknown Source) ~[na:na]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
> at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) ~[spring-context-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-4.1.9.RELEASE.jar:4.1.9.RELEASE]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_111]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_111]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
> at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

Thank you
Mallikarjun

**Comment by mpeddagolla** [comment]
This is happening when trying to remove the orphaned AuthenticationHolders returned from getOrphanedAuthenticationHolders.

**Comment by jricher** [comment]
I've never seen this error before. I wonder if it's a timing or cache issue with the cleanup -- it's finding authentication holders that are scheduled for deletion then not finding them by the time it cleans up. Which database are you running on? Are you doing any cacheing or clustering?

**Comment by mpeddagolla** [comment]
Thank you for your reply. Yeah, I was doing more investigating and I think you are right. We have 2 instances running and they both are performing the job. Which explains why it fails immediately after finding them since the other instance might have cleaned up at the same time. Is there a way we can disable the scheduled jobs using some configuration?

**Comment by jricher** [comment]
If you have two instances running, you should only have the tasks running on one of them. You can disable them by just clearing out the contents of the `task-config.xml` file on one of them.

**Comment by mpeddagolla** [comment]
yeah, perfect. Thank you.

**Comment by mpeddagolla** [comment]
Just so you know we are trying to fix this by completely disable the spring schedulers (comment the task-config.xml)  on both instances and instead have a quartz job which when triggered will run these cleanup since we have handle on beans and methods. We preferred this since quartz is cluster aware.

**Comment by pdu-avaleo** [comment]
Hey, is it in your opinion proper solution for this problem?

Ihmo that's still a bug and I don't understand why you closed it.

**Comment by jricher** [comment]
The accepted solution has been to have the scheduled tasks run on only one instance. Since the clustering happens outside the app itself, this seems to be the best and most reproducible approach. We're open to other suggestions, but this does in fact fix the problem that was reported.

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Clustering

**Comment by pdu-avaleo** [comment]
It depends from how you define problem.

In most orchestration systems you don't have feature like "make 1 instance special" and it introduces many problems with high scalability and availability. There are better ways to solve this issue.

If you would like to say:
> The MTIREid Connect server is designed to scale horizontally with multiple parallel instances
you can't make assumptions that there is only one instance responsible for managing data.

**Comment by jricher** [comment]
As I said above, we're open to suggestions and better solutions than the one that's there today, and look forward to the pull request.

**Comment by pdu-avaleo** [comment]
What's the point of me solving the issue if the issue tracker and documentation says there is no issue?
Please open it back, then I'll do the code change.

**Comment by pdu-avaleo** [comment]
Additionally, here is another way to reproduce the issue:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/0b1f9000db3e45834c330d15da8d3c19626bfd9f/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L113

Call /tokens/access when another instance does the cleaning.
