### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by jainh** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1173]
Hi 

Do you have any benchmarking done on this project to share ? I remember one of my team members did run on this project, but she doesn't have the report now available, however number she remembers is too low to believe. She told me not more than 100 requests/second on refresh token endpoint. It was from one instance of the server.

Otherwise, latter i need to run benchmarking.

**Comment by jricher** [comment]
We don't have benchmarks widely available because they depend on a lot of different aspects like which database you're running under, how you've got your clustering set up, how big of a server you've got (CPU and RAM specifically), even which servlet container and Java version you're running under.

**Comment by jainh** [comment]
I agree, it does vary and depend on infrastructure hardware and software dependencies. She ran on i5, 4GB RAM a morden computer with Java 8 and in memory implementation of persistent storage.

**Comment by jricher** [comment]
Well yes, if you're going to run everything in a single box on 4GB of ram to share the DB is going to probably be a bit slow. Also, using 100 refresh tokens a second is a *huge* scale -- refresh tokens don't get used very often in the wild, and other operations would be much more important to profile.

With all that said, we take the approach with this project of tackling the problems of functionality in order:

1. Make it work
1. Make it work _correctly_
1. Make it work _quickly_

That last one has been solved as it needs to in particular environments.
