### ISSUE TITLE
API appears to hex encode the client secret

### ISSUE THREAD

**Issue by morungos** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1175]
I'm trying to initialize/write a specific client secret through the API, rather than letting one be generated, and it seems there's some weird hex encoding/decoding happening in the API, which doesn't match the documented examples. I'm using version 1.2.6.

The output from an `/api/clients` always looks like it's hex encoded. It looks like a POST to `/api/clients` might encode the secret as hex before it stores it, because the secret shown in the "Display/edit client secret:" is also hex encoded, i.e., it is not the same as the one that was passed in the JSON. This implies it may be impossible to write a secret through the API. 

If I generate a new secret, what's shown in the feedback dialog is not hex encoded, but the API and "Display/edit client secret:" values are hex encoded. This makes it hard to see what the secret really is. 

Is there any extra encoding happening in this API, specifically for secrets, that I need to know about?

**Comment by jricher** [comment]
There's no special encoding, so this sounds like a bug. Can you give examples of the plain text and the incorrectly encoded version?

**Comment by morungos** [comment]
Sure. My import JSON starts:

```
{
  "clientId": "7fe4291b-b32f-4822-b224-4f0231471bf7",
  "clientSecret": "AOPOR6JvMG4Sr073T7GPxoi88B_kYOqzVg2fMPdt7bcCzj7z1Rzev4P82i-aItz5B1LcexyZH8Bqwpa3P7rs4SY",
  ...
```

But when imported, `GET /api/clients` returns:

```
[{"id":36,
  "clientId":"7fe4291b-b32f-4822-b224-4f0231471bf7",
  "clientSecret":"414F504F52364A764D4734537230373354374750786F693838425F6B594F717A566732664D506474376263437A6A377A31527A657634503832692D6149747A3542314C636578795A483842717770613350377273345359",
  ...
}]
```

**Comment by morungos** [comment]
Right, I'm making progress on this, and the problem partly lies in a few DB changes I had to make, due to the schema issues for MySQL, and specifically in the discussions in #999, recommending using `BLOB` fields because otherwise the schema won't work in InnoDB. It looks like `BLOB` fields are being transparently hex-coded by JPA. It turns out the `BLOB` fixes will get the schema and tables loaded, but appear to cause secrets to fail. 

As this is something of a blocker for InnoDB, but I'll try using `TEXT` instead of `BLOB` and report back. 

When done, I'll also comment on #999, because `BLOB` isn't a good fix for that either.

**Comment by jricher** [comment]
Interesting that it's a DB issue, as there are a number of deployments using MySQL already out there that don't have this problem. I would imagine that the client can't authenticate at all once this is in place.

**Comment by morungos** [comment]
That was it exactly. It didn't matter what secrets you use, they can never be consistent. Changing to `TEXT` for the long `VARCHAR` fields that blow MySQL's size limits, and all is good. I suppose it makes sense, as `BLOB` is supposed to be binary. 

This is all a consequence of the problem flagged in #999, and changing to texty (not binary) fields for long values resolves this issue. So I suggest closing.

**Comment by jricher** [comment]
I just built and deployed against MySQL and I did not run into this problem. I was able to use the MySQL database schema file with no alterations.
