### ISSUE TITLE
Securing public API's with OpenID Connect

### ISSUE THREAD

**Issue by brocoly27** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1177]
Hi Folks, 

I'm not sure if this is the right place to post this, but I'd like to request for your opinion in regards a scenario we have. Our team is evaluating the possibility of implementation of OpenID connect and I've been playing around with the mitreid project for a few weeks which is the best implementation I have found.

Currently, we have a set of public Restful API's that are not secured and I'd like to know if we can use openId Connect to achieve this. 

OpenID Connect can be used to authenticate into web applications, mobile applications, and much more, but how can OIDC help me in securing APIs?

Thanks, appreciate your inputs.

**Comment by jricher** [comment]
OpenID Connect does not protect API's, it's used only for log in. However, it's built on OAuth, which does protect API's. So your client application would get an access token to use at the API, and the API would use something like token introspection (supported by this implementation) to figure out what the incoming token was good for.

**Comment by brocoly27** [comment]
Thanks Justin, your explanation gave me some good idea on how I can start from here.

Correct me if I'm wrong, but a typical scenario would be:

1. Client needs to have access to a protected resource (Restful service in a Resource Server).
1.5. Does the client needs be to registered? If so, what endpoint?
2. Client needs to request a token to the OIDC server and the server returns that token.
`POST /token HTTP/1.1`
`grant_type=client_credentials`
3. The Client sends the token to the Resource Server and the Resource Server calls OICD `/ introspect` to validate the token so that finally the RS returns the protected resource requested by the Client.

I'm not completely sure about the last point, but I guess something like that should be the flow.
Please, feel free to correct if I'm missing something.

Thank you in advance.

**Comment by miguelsauza** [comment]
@brocoly27 i recommend you start reading all about the protocol oauth2/oidc from:

[The OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6749)
[OAuth 2.0](https://oauth.net/2/)

The main topics you need to understand are: protocol flows, authorization grants.

**Comment by jricher** [comment]
1. Yes the client needs to be registered.
2. That's correct if you're using the "client credentials" grant, which is only applicable if there's no user involved. If there's a user you're accessing the API for, use the "authorization code" grant type instead.
3. Yes, the resource server calls token introspection to get information about the token. The resource server also needs to be registered in the authorization server with the "allow introspection" flag set on it (there's a checkbox in the admin UI).
