### ISSUE TITLE
LDAP Overlay

### ISSUE THREAD

**Issue by isedrof** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1180]
Hi guys,.

I'm using the LDAP overlay and i can authenticate users already registrated in my LDAP Directory.

I have one question, Is rhe LDAP Overlay, have to be linked to the MitreID Project ?

I guess it's an obvious question but i don't know really if i have to establish this link or not, because for example, all classes in the master project doesn't figure on LDAP overlay.

Maybe i have a problem with this notion of overlay. could you please give more clarification ?

**Comment by jricher** [comment]
A Maven Overlay is a way of taking an existing `.war` file based project and injecting your own code into it. So yes, this is how your custom project is "linked" to the MITREid base project. This method is the recommended form of customizing the MITREid Connect server project. Read more here: https://maven.apache.org/plugins/maven-war-plugin/overlays.html
