### ISSUE TITLE
Mobile apps support

### ISSUE THREAD

**Issue by shingz96** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1181]
Is this library suitable to support OAuth2 flow for mobile apps as the client secret is not confidential in mobile apps. Will this able to work well with apps use [AppAuth-Android library](https://github.com/openid/AppAuth-Android) like support custom uri scheme and loopback ip redirect

**Comment by jricher** [comment]
Yes, it should work fine. Just don't use a client secret. The upcoming 1.3 version of the server (still in development) will support PKCE that's used by AppAuth and recommended as best practice.
