### ISSUE TITLE
How to add ObjectClass to user-contect.xml

### ISSUE THREAD

**Issue by isedrof** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1183]
When i try to search a user with "ldapsearch" request and going throught a TechnicalAccount, i get the attribut i'm looking for (indeed, there's no problem with User Rights).

> ldapsearch -x -h 192.168.0.220 -p 389  -D "uid=testService,ou=TechnicalAccounts,o=comp" -W -b "o=comp"  '(&(objectClass=person)(uid=user1))' mail

But when i try to do the same in MitreID Server, although i can authenticate my user but no data can be reclaimed.
What i've remarked is that, "objectClass=person" does not figure in xml file or java classes, and i'm wondring if the problem does not come from here

**Comment by isedrof** [comment]
I'm not able to retrive user information registred in the LDAP Directory

**Comment by jricher** [comment]
You need to configure and perhaps rewrite the user info services that talk to the LDAP server. That all is based on the spring LDAP project for library support, which is separate from this project. The LDAP server project in this repository is provided as an example of a customization and isn't meant to be a drop-in solution.

**Comment by isedrof** [comment]
I don't think so, because i've said in my previous posts, i can retrieve the  service account information.
That means that the UserInfo is well configured. but when i try to do the same with a simple User in vain.

**Comment by jricher** [comment]
You can retrieve the account information *outside* the app, but not *inside*. Therefore: something is wrong with the configuration. 

It's not well configured if it doesn't work in the code but it works on the command line.

**Comment by isedrof** [comment]
I can send you a configuration to see what is Wrong  ?



2017-02-01 17:28 GMT+01:00 Justin Richer <notifications@github.com>:

**Comment by jricher** [comment]
Sure, post your user-context.xml file and it might be possible to see.

**Comment by isedrof** [comment]
Here's the LDAP part of user-context.xml : 

Technical Account is : ServiceTest
Test user account is : user1

```
<!-- LDAP -->
	
	<security:ldap-server url="ldap://192.168.1.220:38/o=comp" manager-dn="uid=ServiceTest,ou=TechnicalAccounts,o=comp" manager-password="123456" />
 

	<bean id="ldapAuthProvider" class="org.springframework.security.ldap.authentication.LdapAuthenticationProvider">
		<constructor-arg>
			<bean class="org.springframework.security.ldap.authentication.BindAuthenticator">
				<constructor-arg ref="contextSource" />
				<property name="userDnPatterns">
					<list>
						<value>uid={0}</value>
					</list>
				</property>
			</bean>
		</constructor-arg>
		<constructor-arg>
			<bean class="edu.mit.kit.userdetails.MappedLdapAuthoritiesPopulator">
				<property name="admins">
					<set>
						<!-- list admin usernames here -->
						<value>user1</value>
					</set>
				</property>
			</bean>
		</constructor-arg>
	</bean>	
		
	<bean id="contextSource" class="org.springframework.ldap.core.support.LdapContextSource">
		<property name="url" value="ldap://192.168.1.220:389" />
		<property name="base" value="ou=ORG,ou=Users,o=comp" />
		
	</bean>
 

	<bean id="ldapTemplate" class="org.springframework.ldap.core.LdapTemplate">
		<constructor-arg name="contextSource" ref="contextSource" />
	</bean>
	
	<bean id="ldapUserInfoRepository" primary="true" class="edu.mit.kit.repository.impl.LdapUserInfoRepository">
		<property name="ldapTemplate" ref="ldapTemplate" />
	</bean>
		
	<!-- end LDAP -->
```

**Comment by jricher** [comment]
You're setting up your searches completely differently from each other. Your commandline search has a base of `o=comp` but your configuration has a base of `ou=ORG,ou=Users,o=comp` in the `contextSource` bean. Check there first. You also might want to add `objectClass=person` to your base there to make it `objectClass=person,o=comp` instead. 

Also, your two ldap server URLs are set to different ports in the above, but I'm assuming that that might be a typo.
