### ISSUE TITLE
Why userinfo endpoint is not accessible?

### ISSUE THREAD

**Issue by shingz96** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1185]
Error message of " Full authentication is required " is always shown even with correct access token given.

Is it that the /userinfo endpoint required not only access_token?

Hope there is a demo tutorial in java showing the flow from requesting an authorization request until exchange the access token and using it for accessing the userinfo.

**Comment by jricher** [comment]
The access token needs to have at least the `openid` scope, are you sure it does?

**Comment by shingz96** [comment]
ya, it have

**Comment by jricher** [comment]
Then it should work just fine and it routinely does, there must be something else that's going wrong.

**Comment by shingz96** [comment]
I purposely try with invalid token, it will show error message of "Invalid token" 
```
{
  "error": "invalid_token",
  "error_description": "Invalid access token: yJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJ1c2VyIiwiYXpwIjoiY2xpZW50IiwiaXNzIjoiaHR0cDpcL1wvMTkyLjE2OC4yMTEuMjIwOjgwODBcL29wZW5pZC1jb25uZWN0LXNlcnZlci13ZWJhcHBcLyIsImV4cCI6MTQ4NjA4OTA0MywiaWF0IjoxNDg2MDg1NDQzLCJqdGkiOiI3YWRiYzhlNi0yNTllLTQ0ODktOTkzOC02OTkyODI4OWM0N2YifQ.Zk0Npwjh1fftW4GAbSiqqRQKB5AB4GYzkDI9JLXv9_khjTbg6qlaESCRd-55cWF1cUAba1LfLXWoIzTf0VHB1pVFuJLQtt2IKdyvPYNBW31U2hk7HoJSprz2vw3rhi8UmK9Em2hmNAKTlhqiS5YhiVwVRNCn9i6JT1ksnZz1fI4FMgcCaCZaJPhdGjouDMYemiKsMXzFZr9tB1zFyAbnipon3JHR0BFp2EwzgBm2fEJoT118lt9AZM64krolD3mYgUmj_l6B2E5NtFkWApg8yp33xlI81MN8w3fGBwSQDfvVwn4rzuLQaViRj9r0LfVT_Yf9klGXbcaFfAQTXwzr2g"
}
```

but if i put in the correct access token, it show
```
 {
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}
```

**Comment by jricher** [comment]
Don't know what to say, it works fine in every instance I have seen as long as the access token is valid and it's got the openid scope in it. What have you changed in your setup? Start there to see what might be amiss.

**Comment by shingz96** [comment]
erm i did not configure much just change base issuer url in sever-config.xml, and change database to sql in data-context.xml.

Will signing stuff be a issue?

**Comment by alfoch** [comment]
Hi, same problem for me.

After some debugging, i've found that the OAuth2AuthenticationProcessingFilter was before the SecurityContextPersistenceFilter that reset authentication informations obtained by the OAuth2 filter .

Set `<security:custom-filter ref="resourceServerFilter" before="PRE_AUTH_FILTER" />` instead of `<security:custom-filter ref="resourceServerFilter" before="CHANNEL_FILTER" />`  
for the userinfo endpoint in application-context.xml solve the problem for me.

Hope it helps.

**Comment by jricher** [comment]
@alfoch What version did you make that change in? In the upgrade to Spring Security 4.2 we recently changed filter orders, but previous versions (including the 1.2.x series) should not have this problem and have been tested and deployed successfully as-is.

**Comment by alfoch** [comment]
You're right, I've used snapshot version (for spring security upgrade).

**Comment by jricher** [comment]
The snapshot version should still function, if this is a bug in the current `master` branch then please file a pull request with your change.

**Comment by shingz96** [comment]
yeah after trying the fixes provided by @alfoch , it work. i am using the master branch code as well

**Comment by sschu** [comment]
I assume the filter order has to be changed for the other endpoints as well. Preventing the `OAuth2AuthenticationProcessingFilter` from clearing the security context on cookie-authenticated requests should probably be done as I proposed in #1190.

**Comment by jricher** [comment]
Strangely, this was changed in 0d162b1423269685adbd1d77cbf6c0c90a62cd14 in order to make things work with Spring Security 4.2 -- it wasn't working with the filters in the old location, and #1188 changes it back to the old location. This will clearly need more investigation to see what's going on with everyone's different setups.

**Comment by jricher** [comment]
We've reversed the previous change and set the new flag on the SECOAUTH component. This seems to work in our test environment for both API access and UI access. Will leave issues open for comment for a bit if people can confirm.
