### ISSUE TITLE
Concurrent Login

### ISSUE THREAD

**Issue by shingz96** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1186]
Is the login support Concurrent Login?

**Comment by jricher** [comment]
What do you mean by that? It could mean:

 - Having more than one user log in to the IdP with different browsers at the same time
 - Having more than one user log in to the IdP with the same browser at the same time
 - Having more than one user log into an RP at the same time

The first one the software can do, the other two it does not.

**Comment by shingz96** [comment]
Different browser same as different computer right?

**Comment by jricher** [comment]
Correct, it's the same answer if the browsers are on different computers.
The software by default uses a built-in database for storing users for authentication and for user information. To customize it and attach it to a different user store, look at the configuration in `user-context.xml` and work from there.
