### ISSUE TITLE
HSQL database setup fails with file-backed storage (due to missing existence check on index creation)

### ISSUE THREAD

**Issue by sschu** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1189]
This is easily solved by using `CREATE INDEX IF NOT EXISTS` instead of `CREATE INDEX` similar to the table setup part in `hsql_database_tables.sql` in `openid-connect-server-webapp`.

**Comment by jricher** [comment]
Previous versions of HSQLDB didn't allow that syntax on indexes, but it looks like the current version does, so we can add that in.
