### ISSUE TITLE
How to Enable Bearer Token Authentication with OAuth2? 

### ISSUE THREAD

**Issue by claudefalbriard** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1195]
Our tests with a Bearer token passage using a JSON argument [ "Authorization" : "Bearer _access token_" ] resulted in a 403 response code (=not allowed).  
The protection of the resource is triggered by an "oauthAuthenticationEntryPoint" pointing to the class “org.mitre.oauth2.introspectingfilter.IntrospectingTokenService”.  The class defines the link to the /introspect function at the central IdP server. I've also validated the OIDC realm default value used for OAuth 2.0, the under-laying layer of OIDC.

**Questions:**  
. Are any further setup parameters required to enable the OAuth Bearer token processing? 
. How to trace the intercept and MITREID Oauth validation? 

Our security-server.xml setup file: 
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:sec="http://www.springframework.org/schema/security" xmlns:util="http://www.springframework.org/schema/util"
	xmlns:oauth="http://www.springframework.org/schema/security/oauth2"
	xsi:schemaLocation="http://www.springframework.org/schema/beans	
						http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
						http://www.springframework.org/schema/context 
						http://www.springframework.org/schema/context/spring-context-4.1.xsd
						http://www.springframework.org/schema/security 
						http://www.springframework.org/schema/security/spring-security-4.0.xsd
						http://www.springframework.org/schema/security/oauth2
						http://www.springframework.org/schema/security/spring-security-oauth2.xsd
						http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.1.xsd">

	<sec:http pattern="/css/**" security="none" />
	<sec:http pattern="/js/**" security="none" />
	<!-- <sec:http pattern="/restService" security="none" /> -->

	<sec:http auto-config="false" use-expressions="true"
		disable-url-rewriting="true" entry-point-ref="oauthAuthenticationEntryPoint"
		pattern="/**">
		<sec:custom-filter before="PRE_AUTH_FILTER" ref="resourceServerFilter" />
		<sec:logout />
	</sec:http>

	<bean id="oauthAuthenticationEntryPoint"
		class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint">
		<property name="realmName" value="W3IDRealm" />
	</bean>

	<sec:authentication-manager alias="authenticationManager" />

	<!-- Begin OAuth2 Introspect configuration -->

	<oauth:resource-server id="resourceServerFilter" token-services-ref="introspectingService" />
		
	<bean id="introspectingService"	class="org.mitre.oauth2.introspectingfilter.IntrospectingTokenService">
		<property name="introspectionConfigurationService">
			<bean
				class="org.mitre.oauth2.introspectingfilter.service.impl.StaticIntrospectionConfigurationService"
				id="introspectionConfigurationService">
				<property name="introspectionUrl" value="${oidc.introspectEndpointUri}" />
				<property name="clientConfiguration">
					<bean class="org.mitre.oauth2.model.RegisteredClient">
						<property name="clientId" value="${oidc.clientId}" />
						<property name="clientSecret" value="${oidc.clientSecret}" />
					</bean>
				</property>
			</bean>
		</property>
	</bean> 
```

Thanks in advance for your advice how to activate the Bearer token authentication.

**Comment by jricher** [comment]
At first glance that looks fine. Is your client (that's used in the config above) registered with the "allow introspection" flag set? Does it have the scopes registered to it that the token has (and the API it's protecting needs)?

**Comment by claudefalbriard** [comment]
I've checked the server side configuration, which in our case is a Tivoli FIM platform and the introspection flag was set to "enabled" (a default setting). Indeed I've already tested the /introspect function using a WAS TAI#. This registry is done when associating a client-id and client-secret during the boarding process. 

The scope is set to the value "openid" (by default). The access token was copied from OIDC login authentication flow at the calling server and the token value was moved into the REST POST header sent to the back-end server.
    
Is it possible to trace the header parse and execution of OAuth flow at the MITREID intercept filter?

**Comment by jricher** [comment]
Is your app making the introspection call at all, and failing? Or is it not calling at all? If it's the former, it might be a configuration issue somewhere. If it's the latter, something's wrong with how your app is set up such that the filter's not getting triggered at all.

Yes, you can trace the execution of the filter by hooking your application up to a debugger and walking through it. I'd start with breakpoints inside the `IntrospectingTokenServices` class to see if it's getting called at all.

**Comment by claudefalbriard** [comment]
Thanks for hints.  We started to trace with the breakpoint to the class "IntrospectingTokenService" 
but the class did not call any further methods, only the "setIntrospectionConfigurationService". I've manually tested the /introspect call to our server using an Apache  HTTPS POST with the forms arguments client_id, client_secret and token, which returned a set of access token related information, or active=false for expired tokens. I've also started a -Djavax.net.debug=all trace which showed reception of the Bearer token and TLSv1.2 connectivity between the consumer (front-end) and resource (back-end). My doubt is how to activate the  "IntrospectingTokenService" to call the /introspect function.

**Comment by jricher** [comment]
Sounds like you don't have your spring security filters set up properly on the resource server (API) side if it's not getting triggered. Turn up debugging on spring security and see where the error is coming from.

**Comment by claudefalbriard** [comment]
After several attempts to add the Spring Security OAuth2 package, we are not able to setup the class IntrospectingTokenService (as described in the documentation [ [here](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Token-Introspecting-Client-Config
) ] ) . Do you have a example code that shows how to "wire" the Spring OAuth2 security  and add the Introspect service (or by annotations, or by .xml definition).  Thanks in advance for your support.

**Comment by claudefalbriard** [comment]
The servlet, a REST resource, executes successfully,  but unprotected. The resource is not invoking the Spring Mitreid Oauth2 /introspect function, defined at the resource server. Our tests shows no errors at the log file (attached below). Please guide what definitions need to adjusted to activate the /introspect.  

Our configuration (spring-security.xml): 
`<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:context="http://www.springframework.org/schema/context"
	xmlns:sec="http://www.springframework.org/schema/security" xmlns:util="http://www.springframework.org/schema/util"
	xmlns:oauth="http://www.springframework.org/schema/security/oauth2"
	xsi:schemaLocation="http://www.springframework.org/schema/beans	
						http://www.springframework.org/schema/beans/spring-beans-4.1.xsd
						http://www.springframework.org/schema/context 
						http://www.springframework.org/schema/context/spring-context-4.1.xsd
						http://www.springframework.org/schema/security 
						http://www.springframework.org/schema/security/spring-security-4.0.xsd
						http://www.springframework.org/schema/security/oauth2
						http://www.springframework.org/schema/security/spring-security-oauth2.xsd
						http://www.springframework.org/schema/util http://www.springframework.org/schema/util/spring-util-4.1.xsd">

	<sec:http pattern="/css/**" security="none" />
	<sec:http pattern="/js/**" security="none" />

	<sec:http auto-config="true" use-expressions="true"
		disable-url-rewriting="true" entry-point-ref="oauthAuthenticationEntryPoint"
		access-decision-manager-ref="accessDecisionManager" pattern="/rest/service/sample/restService">
		
		<sec:anonymous enabled="false" />
		<sec:access-denied-handler ref="oauthAccessDeniedHandler" />
		<sec:expression-handler ref="oauthWebExpressionHandler" />
		<sec:custom-filter before="PRE_AUTH_FILTER" ref="resourceServerFilter" />
	</sec:http>

	<bean id="oauthAuthenticationEntryPoint"
		class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint">
		<property name="realmName" value="W3IDRealm" />
	</bean>

	<bean id="oauthAccessDeniedHandler"
		class="org.springframework.security.oauth2.provider.error.OAuth2AccessDeniedHandler" />

	<bean id="accessDecisionManager" class="org.springframework.security.access.vote.UnanimousBased">
		<constructor-arg>
			<list>
				<bean class="org.springframework.security.oauth2.provider.vote.ScopeVoter" />
				<bean class="org.springframework.security.access.vote.AuthenticatedVoter" />
				<bean
					class="org.springframework.security.web.access.expression.WebExpressionVoter">
					<property name="expressionHandler" ref="oauthWebExpressionHandler" />
				</bean>
			</list>
		</constructor-arg>
	</bean>

	<oauth:web-expression-handler id="oauthWebExpressionHandler" />

	<sec:authentication-manager alias="authenticationManager">
	</sec:authentication-manager>

	

	<oauth:resource-server id="resourceServerFilter"
		resource-id="W3IDRealm" token-services-ref="introspectingService" />

	<sec:global-method-security
		pre-post-annotations="enabled" proxy-target-class="true">
		<sec:expression-handler ref="oauthExpressionHandler" />
	</sec:global-method-security>

	<oauth:expression-handler id="oauthExpressionHandler" />

	<bean id="introspectingService"
		class="org.mitre.oauth2.introspectingfilter.IntrospectingTokenService">
		<property name="introspectionConfigurationService" ref="staticIntrospectionConfigurationService">
		</property>
	</bean>

	<bean
		class="org.mitre.oauth2.introspectingfilter.service.impl.StaticIntrospectionConfigurationService"
		id="staticIntrospectionConfigurationService">
		<property name="introspectionUrl" value="${oidc.introspectEndpointUri}" />
		<property name="clientConfiguration">
			<bean class="org.mitre.oauth2.model.RegisteredClient">
				<property name="clientId" value="${oidc.clientId}" />
				<property name="clientSecret" value="${oidc.clientSecret}" />
			</bean>
		</property>
		
	</bean>


</beans>`

Execution Log (final part only):
`DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Looking for resource handler mappings
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#2'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#3'
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/resources/**", locations=[ServletContext resource [/resources/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@f0ae2fc0]
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/css/**", locations=[ServletContext resource [/css/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@15190552]
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/js/**", locations=[ServletContext resource [/js/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@65e3ab31]
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Looking for resource handler mappings
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#0'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#1'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#2'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.web.servlet.handler.SimpleUrlHandlerMapping#3'
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/resources/**", locations=[ServletContext resource [/resources/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@f0ae2fc0]
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/css/**", locations=[ServletContext resource [/css/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@15190552]
DEBUG: org.springframework.web.servlet.resource.ResourceUrlProvider - Found resource handler mapping: URL pattern="/js/**", locations=[ServletContext resource [/js/]], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@65e3ab31]
DEBUG: org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.liveBeansView.mbeanDomain' in any property source
DEBUG: org.springframework.web.servlet.DispatcherServlet - Published WebApplicationContext of servlet 'appServlet' as ServletContext attribute with name [org.springframework.web.servlet.FrameworkServlet.CONTEXT.appServlet]
INFO : org.springframework.web.servlet.DispatcherServlet - FrameworkServlet 'appServlet': initialization completed in 4801 ms
DEBUG: org.springframework.web.servlet.DispatcherServlet - Servlet 'appServlet' configured successfully
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Adding [servletConfigInitParams] PropertySource with lowest search precedence
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Adding [servletContextInitParams] PropertySource with lowest search precedence
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Adding [jndiProperties] PropertySource with lowest search precedence
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Adding [systemProperties] PropertySource with lowest search precedence
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Adding [systemEnvironment] PropertySource with lowest search precedence
DEBUG: org.springframework.web.context.support.StandardServletEnvironment - Initialized StandardServletEnvironment with PropertySources [servletConfigInitParams,servletContextInitParams,jndiProperties,systemProperties,systemEnvironment]
DEBUG: org.springframework.web.filter.DelegatingFilterProxy - Initializing filter 'springSecurityFilterChain'
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'org.springframework.security.filterChainProxy'
DEBUG: org.springframework.web.filter.DelegatingFilterProxy - Filter 'springSecurityFilterChain' configured successfully
DEBUG: org.springframework.web.servlet.DispatcherServlet - DispatcherServlet with name 'appServlet' processing POST request for [/rest/service/sample/restService]
DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Looking up handler method for path /restService
DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping - Returning handler method [public java.lang.String com.ibm.sampleoidcservice.RestController.restService(javax.servlet.http.HttpServletRequest)]
DEBUG: org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'restController'
INFO : com.ibm.sampleoidcservice.RestController - Calling rest service
OK DEU CERTO
DEBUG: org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor - Written [{"status":"OK"}] as "text/plain" using [org.springframework.http.converter.StringHttpMessageConverter@f7015b76]
DEBUG: org.springframework.web.servlet.DispatcherServlet - Null ModelAndView returned to DispatcherServlet with name 'appServlet': assuming HandlerAdapter completed request handling
DEBUG: org.springframework.web.servlet.DispatcherServlet - Successfully completed request
`

**Comment by claudefalbriard** [comment]
I confirm use of the required annotations for Spring OAuth2 support, using:  

@EnableWebSecurity
@EnableResourceServer 

We still do not see a parsing of the Bearer token extracted from the HTTP headers part of the REST POST request. Watching the source code of the Spring Oauth2 package, this function should be activated by the class OAuth2AuthenticationProcessingFilter and which also implements the TokenExtract and Bearer token detection function.

What needs to be added, beside the Token Introspecting Client Config [ described[ here]( https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Token-Introspecting-Client-Config ) ] to activate Bearer token extraction and place a call to the Mitreid Introspect function passing the required arguments: client-id, client-secret and token value?

**Comment by jricher** [comment]
Wait, are you using annotation based configuration or XML based configuration? I'm not sure how well they mix when used together in a project.

**Comment by claudefalbriard** [comment]
Thanks for the feedback. I've documented the setup, code and log under a Stackoverflow report [ [here](http://stackoverflow.com/questions/42725605/how-to-protect-a-resource-using-spring-security-oauth2-and-mitreid-connect-intro) ]. Early tomorrow we will do a revision and try to focus on one strategy, like configuration by annotation.

**Comment by claudefalbriard** [comment]
Our team built an annotation based configuration which helped to debug the setup by use of Java breakpoints. The Bearer token authentication using Oauth2, integrated into the OIDC flow, and using /introspect is now perfectly working. You find the Java code (protected resource) published under the Stackoverflow forum ([here](http://stackoverflow.com/questions/42725605/how-to-protect-a-resource-using-spring-security-oauth2-and-mitreid-connect-intro)). Thanks for all the support efforts from the author at MITREID.
