### ISSUE TITLE
refresh_token grant not available

### ISSUE THREAD

**Issue by rickysahu** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1196]
I cannot get a refresh token as an option in grant types and cannot add a offline_access scope to my scopes. Whenever i add the offline_access scope and save, it disappears
<img width="450" alt="screen shot 2017-02-24 at 5 57 54 pm" src="https://cloud.githubusercontent.com/assets/5804854/23324326/07f82cf8-fabb-11e6-86d1-ea62ccca76eb.png">

**Comment by jricher** [comment]
I can't replicate this behavior. Is "offline_access" set as a restricted scope on your server?
