### ISSUE TITLE
Configure a Mutual Authentication instead od Login/Pwd 

### ISSUE THREAD

**Issue by isedrof** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1197]
I want to enable a mutual authentication in mitreId connect instead of login/pwd authentifcation

Any ideas about the steps to fllow, i have found a lot of tuturial about this, but the difficulty i have it to make it work with MitreID app.
It's an obvious remark, but for example i can't find the web.xml file to configure filtres. 
I saw this : https://github.com/MIT-Mobile/oidc.mit.edu/blob/master/oidc-mit-overlay/src/main/webapp/WEB-INF/user-context.xml 
But it talks about Kerberos, and it's not what i'm looking for.

Can guide me please ?

**Comment by isedrof** [comment]
When i was talking about mutual authentification i meant an authentication
by certificate.
I want to authenticate my users by certificate rather than Login/password.
Can you just give me some ideas to help me to put this  ?



2017-03-01 16:00 GMT+01:00 Justin Richer <notifications@github.com>:

**Comment by jricher** [comment]
The documentation pointed to above is the right place to start.
