### ISSUE TITLE
Cross Domain SSO (External Token Exchange)

### ISSUE THREAD

**Issue by AlexanderSenf** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1198]
I have the opposite situation as in https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/907:

I have an IdP which allows users to log in using our own usernames/passwords, and the token /introspect endpoint has been enhanced to return authorization information for these users.

I now need to be able to accept JWT tokens issued by one specific external IdP. I think the best option would be if my own IdP could exchange an external token for a local token (we have the necessary mapping between external and internal user IDs). I am just a a loss how to configure MitreID to enable this.

One alternative I could think of would be to modify the /introspect endpoint to accept the external tokens; that my client applications should theoretically be able to work with either login source. 

My questions: can MitreID work for either of these scenarios? (Which would be preferable?) And how would I go about adding this to, for example, the example OpenID Connect Maven overlay project?

**Comment by jricher** [comment]
You'll want to use token exchange. The server currently supports this draft: https://tools.ietf.org/html/draft-richer-oauth-chain-00

We don't yet support the new draft from the IETF #1055
