### ISSUE TITLE
Revoking access_tokens retrieved through implicit flow

### ISSUE THREAD

**Issue by jtaylor10** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1201]
From what I can tell, this isn't possible but maybe it is and I'm missing it.

I have an in browser app that talks to my instance of the mitreid server. It uses the implicit workflow to retrieve an access token for the user. Now I want to "log out" the user (revoking their access token) - forcing them to navigate over to the mitreid UI and making them click logout is not an option here.

The `/revoke` endpoint seems to require client credentials (client id/secret) to do this. I was thinking that if I have the access token, I could send it as both the `Authorization` header and the `token` parameter and it would allow that. Is this the proper way of doing this? Or how is an app that acquired an access token through the implicit workflow expected to revoke the token when it's done?

I'm hoping I'm just doing something wrong here....

**Comment by jricher** [comment]
I think it's important to think about what you mean by "log out" here. Possession of a valid access token should never be taken as the sole indicator of log in, and your application should really be doing its own session management after talking with the OpenID server. So to log out of your application, you can simply kill the session and throw out your copy of the ID token and access token. If you want to ensure the access token is no good anymore, that's exactly what the revocation endpoint is for (and you're right, the client does authenticate in that call). However, that doesn't "log out" the user, it merely invalidates the access token which, you'll recall, isn't an indicator of being logged in. 

If you want to log the user out of the ID server as well, then you'll need to navigate them over to the ID server. There's a draft specification for this kind of session management but it hasn't been implemented fully in this server yet.
