### ISSUE TITLE
Create new clients using REST API (POST /api/clients) and AngularJS

### ISSUE THREAD

**Issue by khaled-ansary** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1203]
I am developing an AngularJS2 App to create new client using REST api of  MitreID connect Server. I found the following link to create a new client https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/API#post-apiclients .  At first, I send a json post request to the server with the following format (empty data)
{
        "clientId": "",
        "clientSecret": "",
"scope": [
            "openid",
            "phone",
            "email",
            "address",
            "profile"
        ],
        "grantTypes": [
            "authorization_code"
        ],
        "responseTypes": [
            "code"
        ]
}
But I don't get access deny message. Then I created a client and have used the clientId and clientSecret to create the new client but still failed. Could anyone guide me regarding this? Am I doing any wrong process?

**Comment by jricher** [comment]
The API you're using requires admin access, either through a current session (and browser cookie) or through an OAuth access token tied to the admin account. Our UI uses the former. Your choice depends on the nature of your application and how you'd want to manage its connection to the server.

**Comment by Bogad** [comment]
Hello @jricher, please how to generate an oauth access token tied to the admin account.
I need to use an oauth2Resttemplate with a client having client credentials flow to access to Mitreid API (/api/clients for example)
Thanks

**Comment by jricher** [comment]
If it's a client credentials flow it won't have access to the admin account, you'd need to use a delegated token in that case.
