### ISSUE TITLE
It seems you need to add Cascade.PERSIST to DefaultUserInfo class

### ISSUE THREAD

**Issue by hdchen0331** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1209]
When I use the JpaUtil to save a DefaultUserInfo instance, I encountered following exception.

java.lang.IllegalStateException: During synchronization a new object was found through a relationship that was not marked cascade PERSIST: org.mitre.openid.connect.model.DefaultAddress@67e12cdf.

Doesn't the field address need to be annotated with Cascade.PERSIST?

**Comment by jricher** [comment]
Probably a bug -- in practice most deployments I've personally done aren't using the physical address block for users.

**Comment by Oceanedge** [comment]
Seems this change triggers issue: [1391](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/1391). I'll add more on that issue.
