### ISSUE TITLE
Getting "Unsupported grant type: password" when trying to get a token using grant_type=password

### ISSUE THREAD

**Issue by fdimauro** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1213]
Using Curl I am unable to get a token with grant_type =password.

Here is the curl statement I am using:

curl --user client -k -d "grant_type=password&username=pwmadmin&password=********&scope=openid" -H  "Content-Type: application/x-www-form-urlencoded" http://localhost:9999/oic/token

and the response:

{"error":"unsupported_grant_type","error_description":"Unsupported grant type: password"}

I have enabled Grant Type "password" in the "Manage Clients" GUI but it has no effect.

**Comment by jricher** [comment]
Did you enable the password based token granter? Look in authz-config.xml for info. It's disabled by default because the password grant is horribly insecure.

**Comment by fdimauro** [comment]
I was incorrect about the password encryption. I was using the wrong password.

I am using the password token in a Spring Boot Service to call in to a OAuth2 secured Spring Boot System. The calls into this service are authenticated using a different mechanism before a call into the OAuth2 secured system. We need to do this to support legacy access into our new secure system.

**Comment by fdimauro** [comment]
Thanks for your assistance!
