### ISSUE TITLE
Provider is not returning a nonce in id_token

### ISSUE THREAD

**Issue by ondrejvelisek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1217]
Hello there,

Is it possible that MitreID provider does not follow this part of spec - ID Token validation: 
> If a nonce value was sent in the Authentication Request, a nonce Claim MUST be present and its value checked to verify that it is the same value as the one that was sent in the Authentication Request. The Client SHOULD check the nonce value for replay attacks. The precise method for detecting replay attacks is Client specific.

When I send nonce in authentication request it does not appear in id_token from token request. Tested manually (request copy-paste request) and also with Apache OpenID connect module.

Maybe it is realted to this issue https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/465? Any other ideas where is the problem? I would be very gratefull. 

Cheers

Ondrej

More info:

MitreID version: 1.2.6

auth req:
https://perun.elixir-czech.cz/oidc/authorize?response_type=code&scope=openid%20email%20profile&client_id=a47539f3-01c4-484b-a18f-c627672c265d&state=8D37Y5dyqYBgj2xAbN-EnTRr_4M&redirect_uri=https%3A%2F%2Fcloud255-250.cerit-sc.cz%2Foauth2callback&nonce=qBB0JPmWqJV2yL3sdpPB_IBB-S2BEQfBWkDBUygCmX8

auth res:
/oauth2callback?code=Vs5yNK&state=8D37Y5dyqYBgj2xAbN-EnTRr_4M

token req:
url=https://perun.elixir-czech.cz/oidc/token
grant_type=authorization_code&code=Vs5yNK&redirect_uri=https%3A%2F%2Fcloud255-250.cerit-sc.cz%2Foauth2callback&state=8D37Y5dyqYBgj2xAbN-EnTRr_4M
content_type=application/x-www-form-urlencoded, basic_auth=xxx

token res (id_token decoded):
{"access_token":"xxx","token_type":"Bearer","expires_in":3599,"scope":"openid email profile",
"id_token":"{
  "kid": "rsa1",
  "alg": "RS256"
}.{
  "sub": "5d16d564135a4363ada44b809169275ead3244bf@elixir-europe.org",
  "aud": "a47539f3-01c4-484b-a18f-c627672c265d",
  "auth_time": 1490699657,
  "kid": "rsa1",
  "iss": "https://perun.elixir-czech.cz/oidc/",
  "exp": 1490701136,
  "iat": 1490700535,
  "jti": "9f871952-3dde-47cc-948e-68f3473e5ae0"
}.properSignature
"}

**Comment by jricher** [comment]
That issue was closed and fixed years ago, and from the tests I just did, the server does in fact return the nonce in the ID token. You seem to be sending it properly above, so I'm not sure what would cause it to not return. Do you have any custom token services that might be overriding the nonce functionality? The claim is added by this code: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/78b9b6ced4b64208b314f16e86567520ff0f1cdc/openid-connect-server/src/main/java/org/mitre/openid/connect/service/impl/DefaultOIDCTokenService.java#L140

**Comment by ondrejvelisek** [comment]
You were right. I did not save nonce due to bug. I use authentication extensions to store some custom information and instead of adding I replaced the whole Map. Mitre works properly. Thank you! You can close this issue.
