### ISSUE TITLE
NullPointerException in DefaultOAuth2AuthorizationCodeService.consumeAuthorizationCode

### ISSUE THREAD

**Issue by cpineda-worldremit-com** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1218]
When calling /auth/token for exchanging a code for a token there is a null pointer exception happening sporadically. There are two oidc servers sharing a db.

Library version: org.mitre:oppenid-connect-server:1.2.6

Stacktrace:

org.mitre.oauth2.service.impl.DefaultOAuth2AuthorizationCodeService.consumeAuthorizationCode (DefaultOAuth2AuthorizationCodeService.java:105)[-]
org.mitre.oauth2.service.impl.DefaultOAuth2AuthorizationCodeService$$FastClassBySpringCGLIB$$d4e7d2fc.invoke (<generated>)
org.springframework.cglib.proxy.MethodProxy.invoke (MethodProxy.java:204)[+]
org.mitre.oauth2.service.impl.DefaultOAuth2AuthorizationCodeService$$EnhancerBySpringCGLIB$$3f0d2182.consumeAuthorizationCode (<generated>)
org.springframework.security.oauth2.provider.code.AuthorizationCodeTokenGranter.getOAuth2Authentication (AuthorizationCodeTokenGranter.java:71)[-]
org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken (AbstractTokenGranter.java:70)
org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant (AbstractTokenGranter.java:65)
org.springframework.security.oauth2.provider.CompositeTokenGranter.grant (CompositeTokenGranter.java:38)
org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken (TokenEndpoint.java:132)
sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java)[-]
sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke (Method.java:498)
org.springframework.web.method.support.InvocableHandlerMethod.doInvoke (InvocableHandlerMethod.java:220)[+]
javax.servlet.http.HttpServlet.service (HttpServlet.java:648)
org.springframework.web.servlet.FrameworkServlet.service (FrameworkServlet.java:846)
javax.servlet.http.HttpServlet.service (HttpServlet.java:729)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:230)[-]
org.apache.catalina.core.ApplicationFilterChain.doFilter (ApplicationFilterChain.java:165)
org.apache.tomcat.websocket.server.WsFilter.doFilter (WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)
org.apache.catalina.core.ApplicationFilterChain.doFilter (ApplicationFilterChain.java:165)
org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilterInternal (ResourceUrlEncodingFilter.java:53)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter (AbstractAuthenticationProcessingFilter.java:200)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.security.oauth2.provider.client.ClientCredentialsTokenEndpointFilter.successfulAuthentication (ClientCredentialsTokenEndpointFilter.java:131)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.mitre.openid.connect.filter.AuthorizationRequestFilter.doFilter (AuthorizationRequestFilter.java:99)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.mitre.oauth2.web.CorsFilter.doFilterInternal (CorsFilter.java:56)
org.springframework.web.filter.OncePerRequestFilter.doFilter (OncePerRequestFilter.java:107)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[-]
org.apache.catalina.core.ApplicationFilterChain.doFilter (ApplicationFilterChain.java:165)
org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal (WebRequestTraceFilter.java:105)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter `(FilterChainProxy.java:317)[+]`
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter (OAuth2ClientContextFilter.java:60)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal (CharacterEncodingFilter.java:197)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal (MetricsFilter.java:107)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
org.springframework.boot.web.support.ErrorPageFilter.doFilter (ErrorPageFilter.java:117)[+]
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter (ApplicationFilterChain.java:192)[+]
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)[+]
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run (TaskThread.java:61)
java.lang.Thread.run (Thread.java:745)

**Comment by jricher** [comment]
Do you have the token cleanup services turned on on both servers? This can cause database issues sometimes. See `task-config.xml` for details.

**Comment by cpineda-worldremit-com** [comment]
Yes, token cleanup services are running in both servers.

**Comment by jricher** [comment]
Turn them off on one server and see if that helps.

**Comment by cpineda-worldremit-com** [comment]
I have turned off the cleanup services and it has fixed this issue.

**Comment by jricher** [comment]
Thanks. We really should have a wiki page talking about this and other clustering issues. Would you be willing to help start and edit that?
