### ISSUE TITLE
OpenID Connect as RP

### ISSUE THREAD

**Issue by aruvenu** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1219]
Hi,
I have a requirement in which I need to implement OIDC connect as http module which would serve as the relying party and OpenAM as OpenID Connect Provider. COuld you please let me know which all folders out of the entire project would be needed for this particular scenario. I have already seen that OpenID connect client folder uses spring security filter for authentication. Are there any other dependent folders, since there are a lot of files. I am not able to make out which is necessary for the basic functionality. Since I am new to this, I wanted to separate the necessary code and dependencies to understand the flow of the program. 
Any help is appreciated
Thanks and Regards
Arathi

**Comment by jricher** [comment]
The client is configured as a Spring Security filter, designed to be integrated into a Spring Security protected Java application. It's not a matter of just grabbing files and putting them into a directory, you need to add openid-connect-client as a dependency to your project and configure it. Documentation for the client is available: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Client-configuration
