### ISSUE TITLE
NullPointerException in IntrospectionEndpoint.verify

### ISSUE THREAD

**Issue by thomasmey** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1222]
Hi,

When calling the IntrospectionEndpoint under load I sometimes see a NPE in IntrospectionEndpoint.verify(String, String, Authentication, Model) line: 166

This is due to accessToken.authenticationHolder being null.

Code:
```
// get the user information of the user that authorized this token in the first place
String userName = accessToken.getAuthenticationHolder().getAuthentication().getName();
```

The accessToken is not null and the record exists on the database, but the referenced authenticationHolder record is missing in the database.

accessToken	OAuth2AccessTokenEntity  (id=320)	
	authenticationHolder	null	
	client	ClientDetailsEntity  (id=318)	
	expiration	Date  (id=322)	
	id	Long  (id=323)	
	idToken	null	
	jwtValue	SignedJWT  (id=382)	
	permissions	HashSet<E>  (id=385)	
	refreshToken	null	
	scope	HashSet<E>  (id=387)	
	tokenType	"Bearer" (id=389)	

any ideas how this could happen?

Version 1.2.5

**Comment by jricher** [comment]
That's very strange indeed. The authentication holder should *never* be null for an active token, and the service and storage layers should ensure that. 

One possible culprit is the token cleanup services. Do you have multiple servers pointed to the same database? If so, you'll need to turn off cleanup on all but one of them (in task-config.xml). Other than that, I don't know and haven't seen this behavior before.

**Comment by thomasmey** [comment]
Yes, I my test I did use 4 nodes all running the cleanup service.
Also strange is that the database entry for above "access_token" is still 40 minutes valid...

**Comment by thomasmey** [comment]
I only did notice because the /introspect endpoint will return with status code 500 and Content-Type: text/html;charset=UTF-8, i.e. a webpage instead of a JSON, which did confuse my introspection caller component.
Maybe API endpoints should always return JSON even in case of error?

Btw. is the introspection endpoint part of the OpenID Connect specs?

**Comment by jricher** [comment]
Introspection is supposed to return only JSON, as it's an API. The error handler must not be catching things appropriately there, but that's certainly an unexpected condition. 

Introspection is defined in RFC7662, not in OpenID Connect, but they're compatible with each other.

**Comment by thomasmey** [comment]
This error also happens when running on a single node only.

I'll try to set a database constrain to enforce the mandatory auth_holder on an access token. Maybe I than can catch the invalid insert or delete statement.

**Comment by thomasmey** [comment]
I think the DefaultOAuth2ProviderTokenService has a similar problem as commit 7725fcfa2b2ea3625b7df84e6bd8e5cb22375201.

OAuth2AccessTokenEntity.createAccessToken(OAuth2Authentication authentication) should also run beneath one transaction to avoid an inconsistent state between. what do you think about this?

**Comment by jricher** [comment]
It's entirely possible -- we've tried to keep transactional stuff out of the service layer, since it's JPA specific and there are non-JPA repository layers that people have added in. However, it might really be helpful here so we'll look into that.

**Comment by thomasmey** [comment]
I added @Transactional to the createAccessToken method and did run my load test for some hours and this time the NPE didn't occur anymore.
