### ISSUE TITLE
/introspect authentication failure when client token endpoint auth method is AuthMethod.SECRET_JWT

### ISSUE THREAD

**Issue by hdchen0331** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1225]
When the client token endpoint auth method is set to AuthMethod.SECRET_JWT, the default client user detail service will issue a random password each time.
This results in authentication failure while invoking /introspect endpoint because the password doesn't match the stored value (See org.springframework.security.authentication.dao.DaoAuthenticationProvider additionalAuthenticationChecks())

**Comment by jricher** [comment]
How are you authenticating to the introspection endpoint? You need to use the same method that you use for the token endpoint -- in this case, you must create a JWT signed with the client secret. 

That randomization is used to make sure that the basic authentication and form post authentication fail properly -- it was the only way we had to hook into the basic auth provider that didn't leave a back door. It doesn't affect the JWT assertion processing, and I've just confirmed that this does in fact work for the introspection endpoint.

**Comment by hdchen0331** [comment]
Understood. Thanks for your quick response.
