### ISSUE TITLE
Not able to do Register

### ISSUE THREAD

**Issue by rvrkrishna24** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1227]
I am quite new to OpenId connect, As per my observation MitreId is the only implementation available. I have checked no where it is mentioned about the registration process.  My requirement is I need to use OpenID Connect protocol to create Users. I have deployed your server code, that up and running fine. But how to proceed not able to understand. Can someone guide as how to proceed with the server code avail.?

May be am checking wrong way. Please its bit urgent.

**Comment by jricher** [comment]
This project does not support user account management (see #660 and other related issues). It's designed to be used alongside an existing identity structure, which may be as simple as an LDAP server.
