### ISSUE TITLE
End Session Endpoint

### ISSUE THREAD

**Issue by jtabouret** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1229]
Hi,

Our OIDC server is a Maven overlay of a MitreID webapp (v1.3.0) and we would like to implement "global logout", that is to say, when a user logs out from one RP, it triggers a logout from the OIDC server as well as all other RPs the user is connected to.

I found out that an issue has already been opened about this topic [here](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/891). And it seems that [sdoxsee repository](https://github.com/sdoxsee/OpenID-Connect-Java-Spring-Server/tree/master/openid-connect-server/src/main/java/org/mitre/openid/connect/web) offers an implementation for that (see [this issue](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/972)).

I would like to know what is the status of sdoxsee's project compared to mitreid-connect. Because this `EndSessionEndpoint` has been available for 2 years but hasn't been merged with MitreID yet.

Is there another MitreID version that embed those features ? Or is that a fork that has no relationship with MitreID ?

Thank you
Julien

**Comment by jricher** [comment]
The proposed solution in #972 wasn't very clean or complete, so we didn't incorporate it. We've kept the pull open for reference for an eventual implementation. We've started work on this feature in a dev branch but have neither completed nor merged it with the main project.

**Comment by jtabouret** [comment]
Hello Justin,

Thank you very much for your reply!

I understand that it is not complete yet so it probably won't be release before several months I guess.

But what about a lighter version of the feature ? That is to say an endpoint to invalidate the user session in the MitreID server (whereas full feature would logout from other RPs). Would there be a chance to have that available with the next release ?

Currently, since `_csrf` is required, it's only possible to logout from the UI which is not really applicable in our project. That's why such an endpoint would be interesting to us.

Thanks,
Julien

**Comment by sdoxsee** [comment]
We've been using the pr "as is" for over a year now to allow an RP initiated logout...and it works very well. To implement more of the spec is beyond what I need but I'd be happy to clean up the pr (even if it isn't the full spec) if it could be merged. I'd rather have it part of the main code base than our own overlay. @jricher, are there any particular changes you'd suggest I make to make it mergeable? I was hoping to follow through on some suggestions by others on the pr and also to use constructor injection. What do you think?

**Comment by jricher** [comment]
We just added an implementation of the end session endpoint in [a few recent commits](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/compare/0efa77b5800c26ef8033525e2b184f4030d6ca01...9baacc0eaf9f15c55a45a49d1c7bd4b4d003e4ab).

We based some of the content on #972 but it's largely a new implementation of the specification. For instance, we don't look up the ID token in storage but instead treat it as an assertion (which may be and likely is expired anyway -- remember, the ID token is not a session).

I'd like to ask folks to try out the latest checkout to see if this implementation works. If so, we can pull it into the next version relatively soon.

**Comment by sdoxsee** [comment]
@jricher awesome. I'll give your implementation a try. Thanks!

**Comment by sdoxsee** [comment]
On second thought, our implementation is working for us and we haven't upgraded to 1.3.0 yet. With everything going on I'm going to leave this for someone else to test for now and I'll try it out in 1.3.1+ when we get around to upgrading.

**Comment by jtabouret** [comment]
Sorry I did not reply faster but I was away from office last week. And I didn't expect you to be so fast!

So I tested this new "endsession" feature, passing the `id_token_hint` param along with or without the `post_logout_redirect_uri` param (I didn't test the `state` param).

1. if the token is already expired, the user does not need to confirm the logout, which is great.

2. the redirection does not seem to work. I was always sent to the confirmation page (_Log Out_ title with or without _You have been logged out of the identity server._ message). The redirection I specified was like `http%3A%2F%2Fhostname`

3. the confirmation message is probably a bit technical as regular end-users may wonder what an _identity server_ is. I think it would be easier to understand if you replace that with the name displayed on the home page (set via property `topbarTitle` in `server-config.xml`)

As far as we are concerned the redirection capability is a requirement so we won't be able to use this version as is. Do you think it can be fixed ? (unless I made a mistake)

Thank a lot anyway.

**Comment by jricher** [comment]
Did you register the `post_logout_redirect_uri` with your client? The server will only redirect if the following conditions are met:

 - The `id_token_hint` is sent
 - the ID token is issued by this server and has a valid signature (it can be expired)
 - The `post_logout_redirect_uri` is sent
 - The client identified by the `id_token_hint`'s `aud` parameter has this URI included in its `post_logout_redirect_uris` list

If _any_ of those fail, the server will drop the user onto the logout confirmation page, because otherwise the server would be acting as an open redirector to an untrusted URL.

All the messages can be customized by extending the text in `messages.json`, as documented here: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Language-Files

But if you've got a suggestion for a better default message, please send a pull request to patch the default messages.json file.

**Comment by jtabouret** [comment]
Hi Justin,

I didn't notice this new property. Once added the redirect URL to the client configuration, everything is working fine. Thank you !

So as far I am concerned, this new `endsession` endpoint is good to go.

Also I wanted to report an issue I encounter while building the overlay project.

_openid-connect-server-webapp_ relies on Bootstrap v2.3.2 which cannot be compiled with LESS v2. In Eclipse, the Wro4j Maven plugin indicates `Error in LESS: NameError: #grid > .core > .span is undefined in bootstrap` and the issue has been reported a long time ago on [stackoverflow](http://stackoverflow.com/questions/26628309/less-v2-does-not-compile-twitters-bootstrap-2-x).

I tried to create a copy of `navbar.less` and modify the problematic rule but it had no effect. Maybe the Wro4j plugin compiles the less files before Maven builds the overlay ? I turned the DEBUG mode on but couldn't find any clue...

Also I can check that my local environment relies on LESS v2.7.1 but I have no idea how to specify another version (for example 1.7.5) to use with Wro4j.

Would you have any advice on how to solve this issue ? Or maybe would it be possibly to update to a version of Bootstrap that can be compiled with LESS v2 ?

Thank you in advance.

**Comment by jtabouret** [comment]
FYI, I was able to build the overlay project by switching to LESS v1.7.5.
Moroever, I guess this won't be an issue once the v. 1.3.1 artifacts will be available on Sonatype.
So I guess you can ignore my request.

Regards.

**Comment by jricher** [comment]
In the future please report unrelated issues as new issues instead of expanding old threads, it makes it easier for us to track. :)

Maven builds the Less files before the overlay, and overlaying doesn't automatically re-run the compiler. If you want custom Less in your overlay you need to have the overlay itself also run a less compiler. You can run any system you want, but is easiest, I've found, to just use the wro4j system. 

We eventually need to upgrade to the new bootstrap but there hasn't been enough of a pull to do that switch yet.

**Comment by sdoxsee** [comment]
I should say that I'm using the new end session endpoint now and it's working well. Thanks for doing this.
