### ISSUE TITLE
DiscoveryEndpoint does not include baseUrl in the device_authorization_endpoint

### ISSUE THREAD

**Issue by mcsideveloper** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1230]
The OIDC Configuration metadata returned from the discovery endpoint is missing the baseUrl in the device_authorization_endpoint value.

For example, https://mitreid.org/.well-known/openid-configuration, returns "device_authorization_endpoint":"devicecode", but should return "device_authorization_endpoint":"https://mitreid.org/devicecode"

Can be fixed by concatenating baseUrl and DeviceEndpoint.URL in DiscoveryEndpoint.java
Change `		m.put("device_authorization_endpoint", DeviceEndpoint.URL);
` to 
`		m.put("device_authorization_endpoint", baseUrl + DeviceEndpoint.URL);
`

**Comment by jricher** [comment]
Good catch, thanks. Should be an easy enough fix -- feel free to put in a pull request if you'd like.
