### ISSUE TITLE
How to build a relying party in PHP?

### ISSUE THREAD

**Issue by hirwajluc** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1234]
Hello,

I have been able to implement a NodeJS and Ruby relying party on mitreid, is there an example of PHP relying party that works with mitreid? Please help me I would like to implement a PHP relying party as well but with the ones I found like [https://github.com/france-connect/fs_exemple_php](https://github.com/france-connect/fs_exemple_php) it refused to work it gives an HTTP Error 500, I tried another one [https://github.com/jumbojett/OpenID-Connect-PHP](https://github.com/jumbojett/OpenID-Connect-PHP) but still am getting the same error. Can you please help me with php implementations.

Thanks

**Comment by jricher** [comment]
Unless the errors you're getting are coming from the MITREid Connect server, you should be asking those questions on the pages for those projects instead.
