### ISSUE TITLE
Can an access token contain scope-values

### ISSUE THREAD

**Issue by gueuselambix** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1239]
Hi,

the access token mitreid provides is a JWT. Can it contain the scope values, so the resource server is not required to perform the token introspection?
I thought introspection was optional, because the resource server could validate the access token based on its signature (except for revocation of course), but it needs the scope values to authorize the request.

**Comment by jricher** [comment]
You can create a custom token enhancer to add in scopes or other custom claims. This is the current implementation you'd need to override:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/openid/connect/token/ConnectTokenEnhancer.java

**Comment by bodewig** [comment]
Would it be possible to make `ConnectTokenEnhancer` a bit more subclass friendly? After all it is doing a few things I don't want to repeat in my own implementation.

Right now I subclass `ConnectTokenEnhancer` and add

```java
    @Override
    public OAuth2AccessToken enhance(OAuth2AccessToken accessToken,
                                     OAuth2Authentication authentication) {
        try {
            OAuth2AccessTokenEntity token = (OAuth2AccessTokenEntity) super.enhance(accessToken, authentication);

            JWT withoutScope = token.getJwt();
            JWTClaimsSet newClaimSet = new JWTClaimsSet.Builder(withoutScope.getJWTClaimsSet())
                .claim("scope", String.join(" ", accessToken.getScope()))
                .build();
            JWSAlgorithm signingAlg = jwtService.getDefaultSigningAlgorithm();
            JWSHeader header = new JWSHeader(signingAlg, null, null, null, null, null, null, null, null, null,
                                             jwtService.getDefaultSignerKeyId(),
                                             null, null);
            SignedJWT signed = new SignedJWT(header, newClaimSet);

            jwtService.signJwt(signed);

            token.setJwt(signed);
            return token;
        } catch (java.text.ParseException canNotHappen) {
            throw new RuntimeException("failed to parse JWT", canNotHappen);
        }
    }
```

which repeats and undos things it really shouldn't touch.

What about adding something like an empty `addCustomClaims` method and invoke it with the builder as parameter before calling `build`. If this sounds OK, I'll be happy to create a PR.

**Comment by jricher** [comment]
@bodewig That sounds like a good extension hook to me, go ahead and send the PR and we'll review. Thanks!

**Comment by bodewig** [comment]
Took a bit longer as I wanted to write a test and was/am pretty unfamiliar with the code base :-) 

--> #1270

**Comment by AndyBowes** [comment]
Hi Guys,
which version of MitreID was this fix included in & is there any configuration required to use this ConnectTokenEnhancer?
