### ISSUE TITLE
Refresh token request without a refresh token parameter causes a NullPointerException

### ISSUE THREAD

**Issue by mattiuusitalo** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1242]
POST https://localhost/authserver/token?grant_type=refresh_token&client_id=CLIENT

Causes a NullPointerException right about here
[https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L318](url)

Unfortunately this makes an ugly HTTP 500 response.

**Comment by jricher** [comment]
Are you including the refresh token in the grant POST body?

It does look like that line might need to be armored against bad calls.

**Comment by mattiuusitalo** [comment]
No, the refresh token is not included in the call in any way.

**Comment by jricher** [comment]
Well ... you need to include that to make it work.

**Comment by mattiuusitalo** [comment]
In our normal case the refresh token is in the URL parameters and that works fine.

This issue was found while testing how our authentication server handles bad requests.

**Comment by jricher** [comment]
Ah, gotcha -- I misunderstood the issue being reported. Yes, that section likely does need to be made safer against bad calls. Apologies!

**Comment by mattiuusitalo** [comment]
Should've made the original post a bit clearer. Sorry about that.
