### ISSUE TITLE
allow_introspection column is 0 (false) by default

### ISSUE THREAD

**Issue by brocoly27** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1244]
Hi Everyone,
I've been playing with this implementation of the OID spec and this is what I have so far.

Using the code flow, I was able to authenticate the user (the access token was already provided)
Now, what I'm planning to do is to validate incoming requests. The end user sends a request to my protected resource (Rest API) and they are passing in the header their access_token. 

Once I get the bearer token from the header, the Resource Server sends another request to the Auth Server invoking the introspection endpoint to check whether their access token is valid or not.

But when I received the response, I get 403 error, I checked the code and seems like by default the introspection feature is set as 0, but if I go to the DB and change it to 1, now I get the response from the introspection endpoint.

Is this the way is suppose to work? Why the introspection is "disabled" by default?

Thank you.

**Comment by jricher** [comment]
Yes, this is working as intended. Introspection is off by default. Protected resources are stored as `client` objects on the server but they really do serve a separate function in an OAuth ecosystem. You'll need to do one of two things:

1. If you're an admin and statically registering the resource, go into the client editor and select "Allow introspection" in the UI. Save the client and it'll work.
2. If you're not an admin, then go to the self-service resource registration page and register your resource there. You'll still get a client ID and secret and all that, but underneath it'll be set to use introspection. It will also not be allowed to ask for tokens on its own.
