### ISSUE TITLE
SAML2 for authentication

### ISSUE THREAD

**Issue by gueuselambix** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1245]
Hi,
we want to use our SAML2 IdP for authentication for the MITREid-connect. Has anyone done this before?
Which library did you use? 

Could you use the SAML2-attributes as input for the oidc-userinfo?

**Comment by jricher** [comment]
SAML authentication inbound should be no problem as you'd just need to set up a Spring Security filter to handle that.

Mapping the SAML attributes into the UserInfoRepository would be trickier, as you'd need to grab them off of a login and cache them for later. It's doable, but you wouldn't have access to those attributes until the user logged in the first time.

**Comment by gueuselambix** [comment]
I got the authentication part working now via [spring-security-pac4j](/pac4j/spring-security-pac4j) & [pac4j-saml](http://www.pac4j.org/docs/clients/saml.html)
I am also able to add Roles to the user based on SAML2-attributes.

Could you give me some pointer (or some example code) on how to implement this UserInfoRepository to map those SAML2-attributes?

**Comment by gueuselambix** [comment]
I will close this issue as SSO was my main goal, which I achieved using pac4J
I will use [LdapUserInfoRepository](https://github.com/mitreid-connect/ldap-openid-connect-server/blob/master/ldap-server-overlay/src/main/java/edu/mit/kit/repository/impl/LdapUserInfoRepository.java) as my respository.
