### ISSUE TITLE
Is it possible that AllowIntrospection be true by default?

### ISSUE THREAD

**Issue by mapetrovic** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1248]
I made 3 microservices, server (mitreId server) and two clients (UserProvider and UserDetails). UsrProvider service has it's own database with some users. Both clients register to server.
When UserDetails service send request with access token to get some users from UserProvider, then UserProvider go for introspection and falls because introspection is set to false (although I set allowIntrospection to true in RegisteredClient bean). And now I need to go to server UI and manually set AllowIntrospection to true. After that introspection is possible and client is authenticated. 
Is it possible that introspection is by default allowed when client is registered?
And, is there any other way of clients communication beside token introspection?

**Comment by jricher** [comment]
If you use the resource registration page it will set allow-introspection to true by default. Otherwise it's false and needs to be set manually by an admin.

**Comment by mapetrovic** [comment]
Thank you very much for help.  :-)
I will have to investigate how to use registration page..
