### ISSUE TITLE
Accessing /authorize endpoint via access token fails

### ISSUE THREAD

**Issue by sbke** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1249]
Hi, we want to access the /authorize via an app that already has a valid access token. That app is used as external user-agent instead of a browser (other apps would open this app when authorizing). My understanding is that instead of going through /login we can use the access token of the app to get access to the authorize screen. When I try to do so the Principal in authorize (AuthorizationEndpoint) is empty so it fails and thwos an InsufficientAuthenticationException.

I am not sure if it's something that I am doing wrong or rather not understanding correctly or if this use case isn't implemented yet or not working properly.  I'll add the curl calls I used to test this, hoping it helps to understand my problem:
aquiring the access token:
curl -u client:secret -F grant_type=password -F username=user -F 'password=password' -X POST http://localhost:8080/token

trying to access the authorize endpoint with the token:
curl --header 'Authorization: Bearer 123_access_token' 'http://localhost:8080/authorize?response_type=code&client_id=client&state=xyz&redirect_uri=http://localhost:8080/&scope=email'

p.s. I'm not sure if this is the right point to address this issue, but I wasn't sure where else to ask.

**Comment by jricher** [comment]
The authorization endpoint is not set up to listen to OAuth access tokens because the whole point of the authorization endpoint is to have the user present and the point of an access token is that the user isn't present. It's a mismatch in use and the software and protocol are working as intended. 

I'm not sure what use case you're trying to solve here but this is not a good way to go about it.

**Comment by sbke** [comment]
In our use case we got a main app where the user has to to login once so the main app gets an access token. Now we got a third party app that needs an access token. This request will be forwarded to our main app. The main app (instead of the browser) will present the authorization screen and here the user can decide which scopes the third party app gets access to.
Since the user is logged in via the main app we don't want him to have to login again.

**Comment by jricher** [comment]
What you're describing isn't doing OAuth anymore, at least not in a traditional flow. You could probably use the OAuth chained grant to do it. We don't yet support the new draft standard but plan to: #1055 

For now we support this draft: https://tools.ietf.org/html/draft-richer-oauth-chain-00

You'd need to allow your client app to call the token chaining grant.
