### ISSUE TITLE
Two questions about code flow

### ISSUE THREAD

**Issue by chenshengxiong** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1250]
Hi,
(1) Which class handles the /authorize endpoint and send redirect（login url） to client?
(2) After user input username/password and click submit in login page, which controller will handle it and check the username and password?
Thanks!

**Comment by jricher** [comment]
None of these are internal to the project but are instead in libraries.

The Spring Security OAuth library provides the `AuthorizationEndpoint` implementation in the current version. 

Spring Security handles logging in with username and password through various `AuthorizationManager` and `AuthorizationProvider` classes.
