### ISSUE TITLE
POST 405 Method Not Allowed

### ISSUE THREAD

**Issue by patfrat** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1252]
Hello,
I have configured, then compiled with Maven the ldap-openid-connect-server.war
And  deployed it to Tomcat8 webappas
My Ldap server is working great

But when i want to login to the OpenID server, i receive this error after submitting the login form

Request URL:https://.../login
Request Method:POST
Status Code:405 Method Not Allowed

What could be wrong ?

**Comment by jricher** [comment]
The login form is probably missing some CSRF bits. The LDAP overlay isn't fully supported but more of an example project, so it's possible there are some things that didn't get fixed in the last upgrade. I'd compare it to the files in the base project, which does work.

**Comment by patfrat** [comment]
When i post the login form i got these parameters
username:mylogin
password: mypassword
_csrf:mycsrfhash
submit:Login

**Comment by patfrat** [comment]
And got this error on /var/log/tomcat/8/catalina.out file
WARN : org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported

**Comment by patfrat** [comment]
Could it be a wrong configuration of user-context.xml by my side that generate this 405 response ?
@see https://stackoverflow.com/questions/29174002/post-of-spring-edit-form-on-tomcat-8-fails-with-405-while-on-tomcat-7-works

**Comment by patfrat** [comment]
I am using also a Nginx Proxy to bind https://openid.myserver.com to http://localhost:8080/ldap-openid-connect-server/ and the login form POST to https://openid.myserver.com/login

**Comment by patfrat** [comment]
This is not my Nginx proxy nor the csrf token ... I have tested without Nginx. So, how can i debug this 405 error, Method POST not allowed with the ldap overlay ?

**Comment by patfrat** [comment]
> The login form is probably missing some CSRF bits. The LDAP overlay isn't fully supported but more of an example project,

I have successfully used a previous version with the ldap overlay. It will be great to provide a working example.

**Comment by naingtu** [comment]
I ran into the same issue and get it resolved after replacing http configuration with the following section.

	<security:http authentication-manager-ref="authenticationManager"> 
		<security:intercept-url pattern="/authorize" access="hasRole('ROLE_USER')" />
		<security:intercept-url pattern="/**" access="permitAll" />
		
		<security:form-login login-page="/login" authentication-failure-url="/login?error=failure" authentication-success-handler-ref="authenticationTimeStamper" />
		<security:custom-filter ref="authRequestFilter" after="SECURITY_CONTEXT_FILTER" />
		<security:logout logout-url="/logout" />
		<security:anonymous />
		<security:expression-handler ref="oauthWebExpressionHandler" />
		<security:headers>
			<security:frame-options policy="DENY" />
		</security:headers>
		<security:csrf />
	</security:http>

**Comment by jricher** [comment]
@naingtu Can you please submit that as a pull request to the LDAP project?

**Comment by patfrat** [comment]
@naingtu 
In which file do you modify this configuration ? user-context.xml ?
Do you remove anthers rows on this file ?
It's not working by my side

**Comment by naingtu** [comment]
@jricher I've created a pull request https://github.com/mitreid-connect/ldap-openid-connect-server/pull/4 for this fix.
@patfrat  please review the pull request.

**Comment by patfrat** [comment]
@naingtu GG +1 on your pull request

**Comment by jricher** [comment]
Thanks for the patch! Looks to be a handful of things that were missed in the upgrade to 1.3, so it's nice having it in line with the rest.

**Comment by patfrat** [comment]
Thanks !
