### ISSUE TITLE
Customizing the Login Page look and feel based on referring URI.

### ISSUE THREAD

**Issue by davidjohnhart** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1254]
I've managed to get the MITREID Connect server working using a Maven overlay. What I'd like to do next is give the login page a different look and feel based on the referring URI. I'm of course open to better solutions here, but the ideal solution would let us customize the login page on the fly without having to redeploy the MITREid server. This would allow us to add customized login pages for different customers quickly without disrupting our operations.

I appreciate any help.

**Comment by jricher** [comment]
If you create a custom version of login.jsp, you should be able to do everything you're asking for.

**Comment by davidjohnhart** [comment]
I'll start off by saying I'm new to Spring / Spring Security... I've created a custom version of the login.jsp page in the Maven overlay and I've put some custom code into the .jsp but I'd rather have that code in a controller. Is there a way to hook into the LoginController?

**Comment by jricher** [comment]
The login controller in this case is provided by Spring, so to handle that directly you'll need to hook in at that level. But it's definitely doable. In the current `[user-context.xml](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server-webapp/src/main/webapp/WEB-INF/user-context.xml#L39)` you'll see the line:

```xml

	<mvc:view-controller path="/login" view-name="login" />

```

This is what maps the "/login" URL to the `login.jsp` file. If you remove that line and instead hook up your own controller (wiring in the `@Controller` bean and all that) you should be able to handle this. The one trick is that it's the Spring Security login filter that handles the POST to "/login" with the user credentials, not the controller.

**Comment by davidjohnhart** [comment]
Thanks Justin. I commented out the code you mentioned in the previous post, and added a LoginController class in the overlay project (code below) and it worked. Thanks for your suggestion.

```
package org.mitre.openid.connect.web;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import javax.servlet.http.HttpServletRequest;

@Controller
public class LoginController {
	@RequestMapping({"login", "login/"})
	public String showLoginPage(ModelMap m, HttpServletRequest request) {
			
		m.addAttribute("test", "attribute1");
		
		return "login";
	}
}
```
