### ISSUE TITLE
id_token_hint and EndSessionEndpoint

### ISSUE THREAD

**Issue by st4sik** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1255]
Hi,
I have any problem with EndSessionEndpoint.
My TC:
1. User sends id_token_hint to '/endsession'
2. Check id_token_hint with 'SelfAssertionValidator'
3. do 'logout' of current user.
4. Remove access_token for current user and client from DB/Memory.
Earlier, I could use OAuth2TokenEntityService.readAccessToken for getting id_token and
OAuth2TokenEntityService.revokeAccessToken for removing. 
Now, I'd like to remove access_token after logout.
Code from EndSessionEndpoint, where I would like do step 4:
```
			UserInfo ui = userInfoService.getByUsername(auth.getName()); 
			if (idTokenClaims != null) {
				String subject = idTokenClaims.getSubject();
				// see if the current user is the same as the one in the ID token
				// TODO: should we do anything different in these cases?
				if (!Strings.isNullOrEmpty(subject) && subject.equals(ui.getSub())) {
					// it's the same user
				} else { 
					// it's not the same user
				}
			}
```

Please, could you help me?

**Comment by jricher** [comment]
The ID token is no longer stored in the database so it doesn't need to be revoked in that way. Revoking the access token is separate from logout and you can use the token revocation endpoint from your client to proactively revoke it.

**Comment by st4sik** [comment]
Ok, but why do we use 'the token revocation endpoint'? if we could use id_token_hint, get id_token/access_token, and do 'logout' and use OAuth2TokenEntityService.revokeAccessToken.
For example:
All sessions management on IDP. Any user uses '/endsession', IDP does 'logout' for this user and revocation access token without 'revocation endpoint'.
We would like to combine the two mechanisms in '/endsession':
1. org.springframework.security.web.authentication.logout.SecurityContextLogoutHandler or new SecurityContextLogoutHandler().logout(request, response, auth) for 'logout' user
2. OAuth2TokenEntityService.revokeAccessToken for removing this access_token for this client, because user can use this token and this token is still exist in the system (if we don't use revocation endpoint)

**Comment by jricher** [comment]
The lifetimes of the tokens are not tied to each other, nor are they tied to the length of the session at the IDP. Your access token *should* keep working after you log out. If you want to throw away the access token as well, use the revocation endpoint as noted above.
