### ISSUE TITLE
invalid_grant issue

### ISSUE THREAD

**Issue by smilingears** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1256]
Hi. I am new OpenID Connect. 

I tried to run open both OpenID-Connect-Java-Spring-Server and simple-web-app on Tomacat 9. i believe that the grant type is set to implicit. however, i ran into problem as below. 

Error invalid_grant
There was an error processing your request.

Invalid redirect: http://localhost:8080/simple-web-app/openid_connect_login does not match one of the registered values: [http://localhost/, http://localhost:8080/]

Can anybody help me out?  I did not change anything in the code or server setting.

thanks

**Comment by smilingears** [comment]
on the browswer: the URL shows
http://localhost:8080/openid-connect-server-webapp/authorize?response_type=code&client_id=client&scope=openid+email+address+profile+phone&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fsimple-web-app%2Fopenid_connect_login&nonce=3cbbd24fd25ff&state=37a494eaf49c1

**Comment by smilingears** [comment]
can anybody write a flow instruction regarding how to use these these two apps?

thanks

**Comment by jricher** [comment]
First, you're using the authorization code grant, not the implicit. Implicit is designed only for in-browser apps and even then it should be used with caution. 

Second, the error you're getting back tells you exactly what's wrong: the redirect URI that you gave doesn't match the ones given. The server does strict matching as of version 1.3. If you're using a static configuration with the example client application, simple-web-app, you need to make sure it's registered with the right values. If you use dynamic registration it will register its full URL.

**Comment by smilingears** [comment]
thanks. made the change on the server side and got the flow working

**Comment by rhinmass** [comment]
For anyone else encountering this, you need to log into the openID connect server as admin; go to Manage Clients; Click Edit; Add "http://localhost:8080/simple-web-app/openid_connect_login" to the list of  "Redirect URI(s)" ; Click Save
