### ISSUE TITLE
Spring Boot Resource Server Setup Issues

### ISSUE THREAD

**Issue by davidjohnhart** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1258]
I have a MITREid Connect server running and I am able to connect to it using a simple Spring Boot web app using the @EnableOAuth2Sso annotation and this application.yml configuration:

```
security:
  oauth2:
    client:
      clientId: mywebclient
      clientSecret: mywebsecret
      accessTokenUri: http://localhost:9200/my-openid-connect-server/token
      userAuthorizationUri: http://localhost:9200/my-openid-connect-server/authorize      
      clientAuthenticationScheme: header 
    resource:
      userInfoUri: http://localhost:9200/my-openid-connect-server/userinfo
```
After I confirmed that the webapp was working I tried to get a Resource server working. The Resource server is only to be accessed only by machine to machine communication. I added a new client to the MITREid server and added the @EnableResourceServer annotation to app entry point and the related maven dependencies to the pom.xml file:

```
 <dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-security</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.security.oauth</groupId>
	<artifactId>spring-security-oauth2</artifactId>		 
</dependency>
```
Using Curl I am able to get a Bearer token from the MITREid server using:

`curl -XPOST -k myclient:mysecret@localhost:9200/my-openid-connect-server/token -d grant_type=client_credentials -d scope=read`

And verified the token is valid using:

```
curl -i -u "myclient:mysecret" -d "token=eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJTZXJ2aWNlMSIsImF6cCI6IlNlcnZpY2UxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjkyMDBcL3Qyc3lzdGVtcy1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImlhdCI6MTQ5ODU2OTU4NCwianRpIjoiOGIxNDA1NDAtNmE1NS00YTgzLTg3YjAtZWZlMTEwNTE1Y2I0In0.Pzx7_vARXijIOEzGUoWq9lwQ2JFMJGEi2lLTEB0ejNMauysFPWtujhwESHDP7qLH58lpzm0YWfsclGIDKosgM0E12nag4WnZOx_jsS2zqE0tz1Mf3X2-aoN7GGCSSr-W5y6K4rWm1MyjI60o03F1qA7bU9xdLiiF1xhYuE2UELJdJdmd-rvSRqBJ9LrDiSnwFQbO5u05OCGgx52T5fJRiUkZabDtwT8Gdsl-90-JC5liGlb1CCmlS1IyutZxoUuJl_eKh63QPwVp5U2FTBEf-2A6dGCEQlb2siSE_QIxCBnjAa3w6KIkq7GRiGMa9Jdk7VSNWYk7Ln5N-bC04HOP2g" -H "Content-Type: application/x-www-form-urlencoded" http://localhost:9200/my-openid-connect-server/introspect
```

I've tried many different application.yml configurations for the Resource Server (latest example is below), but it doesn't seem like the resource server is even trying to communicate with the MITREid server (no logged messages on the MITREid side)

```
security:
  oauth2:
    client:
      clientId: myclient
      clientSecret: mysecret
    resource:
      token-info-uri: http://localhost:9200/my-openid-connect-server/jwk     
      token-type: Bearer
      #jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        #key-uri: http://localhost:9200/my-openid-connect-server/jwk
```
When I try to access on of the endpoints on the Resource server using the Bearer token I get a 401 unauthorized status and this message from the Resource server:

AuditEvent [timestamp=Tue Jun 27 09:21:52 EDT 2017, principal=access-token, type=AUTHENTICATION_FAILURE, data={type=org.springframework.security.authentication.BadCredentialsException, message=eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJTZXJ2aWNlMSIsImF6cCI6IlNlcnZpY2UxIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjkyMDBcL3Qyc3lzdGVtcy1vcGVuaWQtY29ubmVjdC1zZXJ2ZXJcLyIsImlhdCI6MTQ5ODU2OTU4NCwianRpIjoiOGIxNDA1NDAtNmE1NS00YTgzLTg3YjAtZWZlMTEwNTE1Y2I0In0.Pzx7_vARXijIOEzGUoWq9lwQ2JFMJGEi2lLTEB0ejNMauysFPWtujhwESHDP7qLH58lpzm0YWfsclGIDKosgM0E12nag4WnZOx_jsS2zqE0tz1Mf3X2-aoN7GGCSSr-W5y6K4rWm1MyjI60o03F1qA7bU9xdLiiF1xhYuE2UELJdJdmd-rvSRqBJ9LrDiSnwFQbO5u05OCGgx52T5fJRiUkZabDtwT8Gdsl-90-JC5liGlb1CCmlS1IyutZxoUuJl_eKh63QPwVp5U2FTBEf-2A6dGCEQlb2siSE_QIxCBnjAa3w6KIkq7GRiGMa9Jdk7VSNWYk7Ln5N-bC04HOP2g}]

Any configuration advise is appreciated. 

Thanks,
Dave

**Comment by sdoxsee** [comment]
Why is your key-uri commented out? Also, what version of spring security oauth2 are you using? The newest milestone should support the key-uri in  a jwk format...the older release doesn't. For your resource server, you shouldn't need client config nor anything but the key-uri. If you want it to work with older spring security oauth2 then you need to do key fetch manually or convert to a pem format.

See https://github.com/spring-projects/spring-boot/issues/4437 for jwk issue
See https://github.com/sdoxsee/stackoverflow-38507565/blob/master/resource/src/main/java/com/mycompany/myapp/config/MicroserviceSecurityConfiguration.java for manually grabbing jwk

**Comment by davidjohnhart** [comment]
We are using the 1.5.4.RELEASE version of spring security oauth2. I believe this version should have the support for the key-uri issue. I had found the spring-projects/spring-boot#4437 issue in my research but that configuration never worked for me. 

Originally I only had this in the application.yml file:

```
security:
  oauth2:
    resource:
      jwt:
        # Tells the JWT framework to fetch the public key from the authorization server during startup
        # Note: The authorization server needs to be running...
        key-uri: http://localhost:9200/my-openid-connect-server/jwk
```
But with this configuration I always received the error shown below when the resource server built. I'm far from an expert with Spring Boot and I couldn't find an explanation or solution for the error. From my original reading I expected this configuration to work. 

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Unsatisfied dependency expressed through field 'tokenStore'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtTokenStore' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.TokenStore]: Factory method 'jwtTokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtTokenEnhancer' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtTokenEnhancer' threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/security/jwt/crypto/sign/Signer

**Comment by jricher** [comment]
This is really an issue with spring-security-oauth, but I think your "token info uri" needs to point to the introspection endpoint of the authorization server, not the key set. So with your setup that would be `http://localhost:9200/my-openid-connect-server/introspect`
