### ISSUE TITLE
Is the implementation vulnerable to attacks described in a paper?

### ISSUE THREAD

**Issue by daniel-e** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1261]
Hi,
in Aug 2016 a paper "[A Comprehensive Formal Security Analysis of OAuth 2.0](https://arxiv.org/abs/1601.01229)" was released by Daniel Fett and Ralf Küsters. They describe four attacks:

- 307 Redirect Attack
- IdP Mix-Up Attack
- State Leak Attack
- Naive RP Session Integrity Attack

Have you seen that paper? Is the OpenID connect reference implementation vulnerable to these attacks?

**Comment by jricher** [comment]
Yes, we have seen this paper. The MITREid Connect implementation is not particularly susceptible to these attacks, though things like the IdP mix-up attack affect any client that uses dynamic discovery of systems.
