### ISSUE TITLE
Need dual data source

### ISSUE THREAD

**Issue by dvishwanathan** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1262]
Hello Jricher,

Greetings!!!. This is Vishwanathan. I have the requirement to handle the data from two data source(master and replica) which mean server should persist the data in master db and get the data from read replica db. I want to apply the same in mitreid. 
Is that possible to integrate this? Shall i proceed further to create PR?
Thoughts?

Note : Data synch take care by AWS service.

Thanks & Regards,
Vishwanathan.D

**Comment by jricher** [comment]
MITREid Connect uses a JPA abstraction layer, so the details of the underlying persistence don't affect the server's code at all. If you can set up your replication between the databases, as others have done already, it shouldn't require any kind of change to the existing code (or a PR).

**Comment by dvishwanathan** [comment]
Yes Jricher. Already we implemented dual data source feature in 1.2.6 version using overlay concept. 
We applied dual data source concept in some of MITREid connect server  jpa repositories such as JpaUserInfoRepository,JpaAuthenticationHolderRepository.. etc. Here the thing is we can not move to upgraded version. 
why we were implemented this MITREid have lot of get call at the time of authentication. 

Could you please share your suggestion.

Note : Now both data source pointing same db url.

Thanks & Regards,
Vishwanathan.D

**Comment by jricher** [comment]
Sounds like your changes aren't about having multiple data sources but about other optimizations. Feel free to submit a pull request for those and we'll review them.
