### ISSUE TITLE
Postgres database initialization error

### ISSUE THREAD

**Issue by A40978** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1264]
When initializing the Postgres DB context we get an error due the fact that the initialization scripts configured in the data-context.xml specify a <jdbc:script location="classpath:/db/psql/loading_temp_tables.sql"/> which does not exist in the resources.
And since the temporary tables are not created the insert script fails.

**Comment by jricher** [comment]
You shouldn't need the temporary tables in a Postgres setup, they're more for running the in-memory testing database -- just run the table creation scripts in the postgres directory.

**Comment by A40978** [comment]
Thank you. But in this case shouldn't the insert scripts perform the insertion statements on the tables and not on the temporary tables as it's being done in the scripts?

**Comment by jricher** [comment]
The insert scripts are really only needed in the cases where the database gets re-created at startup. Some people still like them, and the temporary tables allow us to add in information but check first to see if it's already been created or not.  We might trim a lot of that in the future as it does seem to confuse people -- you're not the first to ask about it.

**Comment by A40978** [comment]
I understand. Thank you

**Comment by jricher** [comment]
No, the temporary tables allow the scripts to be run multiple times, like each time the database loads, in case you accidentally run them twice. If you look at the bottom of the insert scripts you'll see there's a bunch of merge statements, and you need temp tables for those to work.
