### ISSUE TITLE
Requesting help with authenticating from a login API endpoint

### ISSUE THREAD

**Issue by aliiitarek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1285]
Hello Justin,

I am trying to use a personal login endpoint to authenticate the user. Upon login from this endpoint, I get all the data I need to populate the UserInfo object. 
The rest of the flow -verifying the client and storing the token information and everything else- should be stored in a mysql database with the schema in `mysql_database_tables.sql` so it should work the same as in the base project.

I am sadly a newbie with spring security.

I implemented a `customAuthentication` + `customAuthenticationProvider` + `customUserDetails`. 

_Kindly note that I did not create a `customUserDetailsService` because I don't want to get the userDetails using `loadUserByUsername(String username)` I will immediately authenticate them from my login endpoint in the `customAuthenticationProvider` and if he is successfully authenticated I fill the userDetails with the response from my login API call._

In the `customAuthenticationProvider` I authenticate the request. I fill the `customAuthentication` with my `customUserDetails`. Then fill the `SecurityContextHolder.getContext().setAuthentication()` with the newly created `customAuthentication` object.

Clarifying Questions:
(0) Since I have my user's passwords somewhere else and I am logging in using a personal login API endpoint, I no longer need the `users` and `authorities` tables, right?

(1) [Filling UserInfo] Should I store the `customUserDetails` in the `user_info` table to persist this data? Or should I just make the _principle_ of `customAuthentication` be the `customUserDetails`? You mentioned in #1208 that one must implement UserInfoRepository that maps your database objects to UserInfo objects, since my user information is not a database but rather acquired upon hitting my login-endpoint, can I do a similar mapping and populate the `DefaultUserInfo` upon login? I fear that this data should be persisted in the `user_info` table or can I just populate this userInfo object after each login? 

I apologize if these are stupid questions. I hope what I am trying to do and where I am currently at is clear.

This is my user-context.xml:

```
        <bean id="customAuthenticationProvider" class="CustomAuthenticationProvider"/>

	<security:authentication-manager id="authenticationManager">
		<security:authentication-provider ref="customAuthenticationProvider" />
	</security:authentication-manager>

	<mvc:view-controller path="/login" view-name="login" />

	<security:http authentication-manager-ref="authenticationManager">
		<security:intercept-url pattern="/**" access="permitAll" />

		<security:form-login login-page="/login" authentication-failure-url="/login?error=failure" authentication-success-handler-ref="authenticationTimeStamper" />
		<security:custom-filter ref="authRequestFilter" after="SECURITY_CONTEXT_FILTER" />
		<security:logout logout-url="/logout" />
		<security:anonymous />
		<security:expression-handler ref="oauthWebExpressionHandler" />
		<security:headers>
			<security:frame-options policy="DENY" />
		</security:headers>
		<security:csrf />
	</security:http>

```
Hope you can find the capacity to answer me and of course thank you either way.

**Comment by aliiitarek** [comment]
I insert the DefaultUserInfo object in the `user_info` table in my `CustomAuthenticationProvider` if it that user didn't exist before. If he exists I get the id of the user from the `user_info` table (because I don't have it since I am authenticating the user from an private login-endpoint).

Now the problem that I am facing is that tables like `authentication_holder_request_parameter` and

**Comment by aliiitarek** [comment]
I now fill the `DefaultUserInfo` in the `CustomAuthenticationProvider`. If that user exists in the `user_info` table I update the table, else I add a new entry.

My question now is: 
Is there anything else that I should handle since my authentication is from an external login-endpoint?

Questions:
(A) Should the `authentication_holder_extension` and the `authentication_holder_request_parameter` keep piling up with data for every new login, shouldn't we erase them periodically?
(B) Should I maintain the `authorities` table as well or is filling the `CustomAuthentication` object enough?

**Comment by jricher** [comment]
A: They do get cleaned out (or should) when the authentication holder objects that they're attached to get deleted. 

B: You don't use the "authorities" table with a custom or external user authentication, that's just for the Spring Security internal authentication based on a database.

**Comment by aliiitarek** [comment]
Thank you Justin for taking the time to reply.

It is working, and I got a chance to crawl the codebase and see a lot of the mechanics. Extraordinary work getting this out, very clean, thank you again. If only I was more well versed in spring (security), I might have avoided asking silly questions.

**Comment by aliiitarek** [comment]
Justin general question,

Consider this scenario:
A user logs in successfully from an external login end-point, and after the client gets id_token, access token and refresh token of this user, the user was blocked by the authorizing system (the system providing the external login). Now the openid-connect-server needs to inform all clients registered for this user to revoke their access tokens or at least reactively invalidate their refresh tokens.

Questions:
(1) Why does the IdP server store the access_tokens in the `access_token` table? Since it can decrypt this token using its key and validate whether to accept the client API call to a resource or deny access. Or does the IdP server store these access tokens just for reference?
(2) Same as (1) but for the Refresh token, now I see from the codebase that the IdP server `getsAllRefreshTokenForUser()` when a `/refresh` request is sent. Why can't the encrypted refresh_token contain all the required information the server needs to avoid storing these tokens?
(3) Is there a standard way to handle the scenario in the beginning of this comment? or do I try to solve this cache-invalidation problem myself.

Hope you can aid me, and of course thank you either way.

**Comment by jricher** [comment]
Please don't re-open closed tickets to post new issues. 

1) Our tokens weren't always structured, so we started by storing the whole value. This hasn't led to problems so we haven't changed it. Also the tokens aren't encrypted by default, but they are signed. We could get away with storing a token reference, but that wouldn't get rid of the table because there's lots of other information that we don't want to put into the token. Other systems do put everything in the token and there are very real trade-offs with this design.

2) Same answer as 1, plus refresh tokens aren't (currently) signed as they're only sent back to the AS.

3) Your scenario is unclear. If you mean the user is logging in to the IdP using an external server, then the AS is acting as a *client* in this case and you have in effect three parties: ExtIdP -> IdP -> RP, where ExtIdp -> IdP is an AS/Client pair, and IdP -> RP is another AS/Client pair. In both cases, the AS can invalidate the access tokens without informing the client. The tokens will just stop working when the client tries to use them again. This is possible because we're doing a token validity lookup and not just packing everything into the token itself -- remember those tradeoffs I mentioned in (1)? This is one of them. 

4) The token enhancer should be responsive to the authentication request, which is passed in. Use that, just like it's already checked for the `openid` scope's presence.

**Comment by aliiitarek** [comment]
Thank Justin for your thorough answers. And I thought compacting the issues was better, but I will follow what is custom of course, I apologize.

Now concerning (3), they way you understood me is correct.
The problem is one of scaling. If I try to distribute the MITREID IdP on multiple nodes. The mysql storage consistency will be a problem. Specially since usually one adds cache to each node. 

So to be more concert: (5) How does the current state of the IdP server scale?

**Comment by aliiitarek** [comment]
Found [this](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Clustering) Thank you
