### ISSUE TITLE
State parameter mismatch on return. Expected null got 31cb460ca6202

### ISSUE THREAD

**Issue by aliiitarek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1286]
I ran the `simple-web-app` on tomcat `localhost:8092/` and JMX port = 1192, and `openid-connect-server-webapp` on tomcat `localhost:8080`and JMX port = 1099 both running from IntelliJ. 

I did not edit anything in both project except the base URL of both the client and the server to be `localhost:8092/` instead of `localhost:8092/simple-web-app` and `localhost:8080/` instead of `localhost:8080/openid-connect-server-webapp` to run correctly on IntelliJ. and the redirect url of the client in the server database to be `http://localhost:8092/openid_connect_login`

Now when I try to login with username: `user` and password: `password` I get a `State parameter mismatch on return. Expected null got 31cb460ca6202`.

Simple debugging leads to the fact that the sessionID return by the server to the client with the state and the code is changed so the client in `handleAuthorizationCodeResponse` in `OIDCAuthenticationFilter` line 317 
```
// check for state, if it doesn't match we bail early
String storedState = getStoredState(session);
```
the storedState is null because the session's id has been changed in the server.
Specifically at the server: The session id in the received request `GET /authorize` is correct. In the redirect to `GET /login` the session id is changed. Finally in the response to the client with the `code` and `state` a third session id.

How do I fix this?
Thank you in advance.

**Comment by jricher** [comment]
Sounds like a problem with your server deployment as sessions aren't handled in any special way by the application. Please check with IntelliJ or whatever part of the stack runs your software to see what you might have misconfigured. The MITREid Connect apps are working as intended -- if you change out the session information, you're not going to be able to trust the connection back to the browser and it *should* fail, as it does.

**Comment by kules** [comment]
I encountered the same issue and in my case the cause is that the client application is using `host name` for some requests and `ip address` for other requests. The client server uses separate sessions for the host name requests and the ip address requests. The `state parameter mismatch` occurred when ip address is used to send the authorization request but localhost is used in the redirect uri.

**Comment by jricher** [comment]
Oh, were you going to `http://127.0.0.1:8092/simple-web-app`? If so then you need to configure your client software to reflect that URL instead of using `localhost`.

**Comment by aliiitarek** [comment]
Thank you @kules and @jricher for your time and assistance. It worked.
