### ISSUE TITLE
Expired access_token not being deleted.

### ISSUE THREAD

**Issue by mrquangtran** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1287]
Does anyone know why expired access_token are not being deleted?

In my case, the expired one gets deleted but very slowly.  It seems like it doesn't delete all at once.

The access_token builds up and affects the performance of the application.

**Comment by jricher** [comment]
Is your server running the deletion tasks in the `task-config.xml` file? These are set to run every 5 minutes and delete them in batches. Unless you're creating many, many thousands of access tokens every minute, all the time, then this should never be outstripped. Do keep in mind that the tokens aren't deleted until after expiration, and the system defaults to 1h for access token lifetimes.

**Comment by mrquangtran** [comment]
Yes.  But it seems like under heavy load when I have a load test running it stops deleting.  What I don't understand is why it doesn't delete all records that have expired at the 5 minute interval and just deletes only a set number of records?  In our load test, we see the number of entries building up to 30000 records.  This has a huge performance hit on the database as it takes longer and longer to query the table.

Do you know if there will be a fix for this issue?

**Comment by jricher** [comment]
If you tell it to just do all tokens, you're likely to see things run worse. The limits were put there because the large batch delete jobs were harming performance with the rest of the system. You can increase the number of records per run that it deletes, or have your deletion system run more often, if your system can handle that.
