### ISSUE TITLE
Is it possible to get and store token in web browser's local storage

### ISSUE THREAD

**Issue by mapetrovic** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1288]
Hi master,
I have question..
Is it possible to somehow get token from client that is registered in server, and store that token in web browser's local storage, to send it from client to resources server?
Just to say, client is dynamically registered to mitreid server.

**Comment by mapetrovic** [comment]
Hi master, 
I have question.. 
Is it possible to somehow get token from client that is registered in server, and store that token in web browser's local storage, to send it from client to resources server?

**Comment by jricher** [comment]
Yes, that's possible. People usually use the implicit flow for in-browser clients like this.

**Comment by jricher** [comment]
Oh, I should add that the client library for this project is *not* for in-browser clients, but for server-side Java applications. So if you're looking to use the client library for this, the answer is no. If you're looking to do it with tokens from the server part of the project, then yes, but its' up to you in your client to handle that.
