### ISSUE TITLE
Use Flyway for database migrations

### ISSUE THREAD

**Issue by almalki** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1289]
It would be good to use flyway([https://flywaydb.org/](https://flywaydb.org/)) or similar tool for database migrations. Changing the db scripts makes it harder for existing deployments to keep track of db changes.

**Comment by jricher** [comment]
Currently, we don't make structural changes on patch releases. The supported method for upgrades with database structure changes is through the import/export API.
