### ISSUE TITLE
The logout enpoint of the mitreID (provided by the Spring Security) does not work with CSRF

### ISSUE THREAD

**Issue by szabe74** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1293]
It works from mitreID Admin page (same domain, same endpoint), but does not work from another webapp (same domain, different endpoint).

Click on the Logout button a form is submited to the **/logout** endpoint. Even I set the correct CSRF input hidden tag it does not work and responses a spring security error: **Invalid CSRF Token.**
In my opinion the root cause is that the Spring Security generates the CSRF token based on the full URL (domain + endpoint) but my app try to call it from another endpoint even it is same domain and running same Tomcat so the CSRF filter cannot find the token.

**What is your suggestion, how can I resolve this issue correct way?**

Anyway I have a workaround what is working now but it is not so nice:
- before submit to /logout endpoint with POST, my app requests the Login page with AJAX and parse the token from the DOM of the login page then provide the right token to the logout endpoint
- now this CSRF token is correct because it was generated with the same domain and endpoint as the /logout 

Thank you for your suggestions in advance..
Br: Béla

**Comment by jricher** [comment]
This is on purpose. You shouldn't be able to call the logout button from another app.

**Comment by szabe74** [comment]
Maybe it is a misunderstanding, but I do not want to call the logout button. I want to call the logout endpoint of the MitreID what is an Identity Provider so this should work.

**Comment by jricher** [comment]
There is no logout endpoint, per se. If you're looking for the "end session endpoint" that's a different location, at `/endsession`. This is in line with the OIDC session management draft specs.

**Comment by e8pigke** [comment]
In the simple-web-app there is a Logout link. When I click this link I'm directed to http://localhost:8080/simple-web-app/j_spring_security_logout and get a 404.

@jricher  Are you saying that the simple-web-app shouldn't have a Logout link?
