### ISSUE TITLE
CSS broken when using "Deploy with Jetty" step in the build instructions

### ISSUE THREAD

**Issue by dhardiker** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1294]
Using the "Deploy with Jetty" step in the build instructions  (https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Build-instructions), some of the CSS files don't load.

Some examples of CSS resources that work:
* http://localhost:8080/openid-connect-server-webapp/resources/css/bootstrap-sheet.css
* http://localhost:8080/openid-connect-server-webapp/resources/css/mitreid-connect.css

These don't work, with a HTML 404 response:
* http://localhost:8080/openid-connect-server-webapp/resources/bootstrap2/css/bootstrap.css
* http://localhost:8080/openid-connect-server-webapp/resources/bootstrap2/css/bootstrap-responsive.css

I can see that the "target/openid-connect-server-webapp-1.3.2-SNAPSHOT/resources/bootstrap2/css/bootstrap.css" file is present and has valid CSS in it. I'm not sure why Jetty isn't serving it as I'm not familiar with the framework config / magic in use.

**Comment by jricher** [comment]
The bootstrap files are built by a LESS compiler and dropped into the deployment directory, so it might take some extra magic to make sure that that piece fires during the Jetty build sequence as well. I'm not as familiar with Jetty so I can't say for sure what that would be, but I imagine hooking the LESS compiler to an additional build step should do it.

**Comment by lpghartz** [comment]
I'm seeing this, too. The bootstrap files are being build correctly via wro, and are present in the WAR:

Archive:  openid-connect-server-webapp.war
  Length      Date    Time    Name
---------  ---------- -----   ----
       97  2017-08-30 19:02   META-INF/MANIFEST.MF
        0  2017-08-30 19:02   META-INF/
        0  2017-08-30 19:02   WEB-INF/
        0  2017-08-30 19:02   WEB-INF/classes/
        0  2017-08-30 19:02   WEB-INF/classes/db/
        0  2017-08-30 19:02   WEB-INF/classes/db/hsql/
        0  2017-08-30 19:02   WEB-INF/classes/db/mysql/
        0  2017-08-30 19:02   WEB-INF/classes/db/oracle/
        0  2017-08-30 19:02   WEB-INF/classes/db/psql/
        0  2017-08-30 19:02   WEB-INF/lib/
        0  2017-08-30 19:02   WEB-INF/tags/
        0  2017-08-30 19:02   WEB-INF/views/
        0  2017-08-30 19:02   js/
        0  2017-08-30 19:02   resources/
        0  2017-08-30 19:02   resources/bootstrap2/
        0  2017-08-30 19:02   resources/bootstrap2/css/
        0  2017-08-30 19:02   resources/bootstrap2/img/
        0  2017-08-30 19:02   resources/bootstrap2/js/
        0  2017-08-30 19:02   resources/css/
        0  2017-08-30 19:02   resources/images/
        0  2017-08-30 19:02   resources/js/
        0  2017-08-30 19:02   resources/js/lib/
        0  2017-08-30 19:02   resources/js/locale/
        0  2017-08-30 19:02   resources/js/locale/en/
        0  2017-08-30 19:02   resources/js/locale/sv/
        0  2017-08-30 19:02   resources/js/locale/zh/
        0  2017-08-30 19:02   resources/js/locale/zh_CN/
        0  2017-08-30 19:02   resources/js/locale/zh_TW/
        0  2017-08-30 19:02   resources/template/
    16491  2017-08-30 17:30   WEB-INF/application-context.xml
      826  2017-08-30 19:01   WEB-INF/classes/keystore.jwks
   682213  2017-08-30 17:38   WEB-INF/lib/bcpkix-jdk15on-1.55.jar
   747794  2017-08-30 17:38   WEB-INF/lib/httpclient-4.5.3.jar
   323824  2017-08-30 17:38   WEB-INF/lib/httpcore-4.4.6.jar
   232248  2017-08-30 17:38   WEB-INF/lib/jackson-core-asl-1.9.13.jar
   780664  2017-08-30 17:38   WEB-INF/lib/jackson-mapper-asl-1.9.13.jar
   162116  2017-08-30 17:38   WEB-INF/lib/javax.persistence-2.1.1.jar
   414240  2017-08-30 18:32   WEB-INF/lib/jstl-1.2.jar
   163136  2017-08-30 19:00   WEB-INF/lib/openid-connect-common-1.3.2-SNAPSHOT.jar
   189646  2017-08-30 18:32   WEB-INF/lib/org.eclipse.persistence.antlr-2.5.1.jar
  5045112  2017-08-30 18:31   WEB-INF/lib/org.eclipse.persistence.core-2.5.1.jar
     2700  2017-08-30 17:30   WEB-INF/assertion-config.xml
      917  2017-08-30 19:01   WEB-INF/classes/db/mysql/mysql_database_index.sql
     4467  2017-08-30 17:38   WEB-INF/lib/aopalliance-1.0.jar
    87776  2017-08-30 18:31   WEB-INF/lib/commons-io-1.3.2.jar
   231952  2017-08-30 17:38   WEB-INF/lib/gson-2.8.0.jar
  1515894  2017-08-30 18:32   WEB-INF/lib/hsqldb-2.3.4.jar
    64612  2017-08-30 17:38   WEB-INF/lib/jackson-annotations-2.9.0.pr2.jar
   286650  2017-08-30 17:38   WEB-INF/lib/jackson-core-2.9.0.pr2.jar
  1292863  2017-08-30 17:38   WEB-INF/lib/jackson-databind-2.9.0.pr2.jar
   294027  2017-08-30 17:38   WEB-INF/lib/nimbus-jose-jwt-4.34.2.jar
   271208  2017-08-30 18:31   WEB-INF/lib/org.eclipse.persistence.asm-2.5.1.jar
  1365645  2017-08-30 18:32   WEB-INF/lib/org.eclipse.persistence.jpa.jpql-2.5.1.jar
  1118609  2017-08-30 17:38   WEB-INF/lib/spring-core-4.3.7.RELEASE.jar
   588073  2017-08-30 17:38   WEB-INF/lib/spring-security-config-4.2.2.RELEASE.jar
   598978  2017-08-30 17:38   WEB-INF/lib/spring-test-4.3.7.RELEASE.jar
     1960  2017-08-30 17:30   WEB-INF/local-config.xml
     1246  2017-08-30 17:30   WEB-INF/locale-config.xml
     3631  2017-08-30 17:30   WEB-INF/server-config.xml
     2088  2017-08-30 17:30   WEB-INF/spring-servlet.xml
     1989  2017-08-30 19:02   WEB-INF/tags/actionmenu.tag
      390  2017-08-30 19:02   WEB-INF/tags/copyright.tag
     1909  2017-08-30 19:02   WEB-INF/tags/footer.tag
     3026  2017-08-30 19:02   WEB-INF/tags/header.tag
     1732  2017-08-30 19:02   WEB-INF/tags/navmenu.tag
      562  2017-08-30 19:02   WEB-INF/tags/sidebar.tag
     4413  2017-08-30 19:02   WEB-INF/tags/topbar.tag
     2119  2017-08-30 17:30   WEB-INF/task-config.xml
     2413  2017-08-30 17:30   WEB-INF/ui-config.xml
     2885  2017-08-30 17:30   WEB-INF/user-context.xml
      904  2017-08-30 19:02   WEB-INF/views/about.jsp
    12930  2017-08-30 19:02   WEB-INF/views/approve.jsp
    11276  2017-08-30 19:02   WEB-INF/views/approveDevice.jsp
      836  2017-08-30 19:02   WEB-INF/views/contact.jsp
     1537  2017-08-30 19:02   WEB-INF/views/deviceApproved.jsp
     2244  2017-08-30 19:02   WEB-INF/views/error.jsp
     2519  2017-08-30 19:02   WEB-INF/views/home.jsp
     1983  2017-08-30 19:02   WEB-INF/views/login.jsp
     2271  2017-08-30 19:02   WEB-INF/views/logoutConfirmation.jsp
     1691  2017-08-30 19:02   WEB-INF/views/manage.jsp
     1125  2017-08-30 19:02   WEB-INF/views/postLogout.jsp
     2645  2017-08-30 19:02   WEB-INF/views/requestUserCode.jsp
     1151  2017-08-30 19:02   WEB-INF/views/stats.jsp
     2525  2017-08-30 17:30   WEB-INF/web.xml
      802  2017-08-30 17:30   WEB-INF/wro.properties
      851  2017-08-30 17:30   WEB-INF/wro.xml
    **21701  2017-08-30 19:02   resources/bootstrap2/css/bootstrap-responsive.css
   125324  2017-08-30 19:02   resources/bootstrap2/css/bootstrap.css**
     8777  2017-08-30 17:30   resources/bootstrap2/img/glyphicons-halflings-white.png
    12799  2017-08-30 17:30   resources/bootstrap2/img/glyphicons-halflings.png
    28631  2017-08-30 17:30   resources/bootstrap2/js/bootstrap.min.js
      944  2017-08-30 17:30   resources/css/bootstrap-sheet.css
       61  2017-08-30 17:30   resources/css/mitreid-connect-local.css
      290  2017-08-30 17:30   resources/css/mitreid-connect-responsive.css
     1318  2017-08-30 17:30   resources/images/heart_mode.png
      817  2017-08-30 17:30   resources/images/logo_placeholder.gif
    22996  2017-08-30 17:30   resources/images/openid_connect_large.png
    52062  2017-08-30 17:30   resources/images/openid_connect_large@2x.png
     1774  2017-08-30 17:30   resources/images/openid_connect_small.png
     4953  2017-08-30 17:30   resources/images/openid_connect_small@2x.png
     4941  2017-08-30 17:30   resources/js/blacklist.js
    45298  2017-08-30 17:30   resources/js/client.js
    70852  2017-08-30 17:30   resources/js/lib/backbone.js
   284394  2017-08-30 17:30   resources/js/lib/jquery.js
     3001  2017-08-30 17:30   resources/template/grant.html
    17935  2017-08-30 17:30   resources/template/rsreg.html
     4173  2017-08-30 17:30   resources/template/whitelist.html
     3027  2017-08-30 17:30   WEB-INF/authz-config.xml
     1111  2017-08-30 19:01   WEB-INF/classes/db/hsql/hsql_database_index.sql
     9431  2017-08-30 19:01   WEB-INF/classes/db/hsql/hsql_database_tables.sql
     1232  2017-08-30 19:01   WEB-INF/classes/db/hsql/scopes.sql
     2076  2017-08-30 19:01   WEB-INF/classes/db/hsql/users.sql
     1278  2017-08-30 19:01   WEB-INF/classes/db/mysql/scopes.sql
     1668  2017-08-30 19:01   WEB-INF/classes/db/mysql/users.sql
    14666  2017-08-30 19:01   WEB-INF/classes/db/oracle/entity-mappings_oracle.xml
      860  2017-08-30 19:01   WEB-INF/classes/db/oracle/oracle_database_index.sql
     1901  2017-08-30 19:01   WEB-INF/classes/db/oracle/scopes_oracle.sql
     2004  2017-08-30 19:01   WEB-INF/classes/db/oracle/users_oracle.sql
     1113  2017-08-30 19:01   WEB-INF/classes/db/psql/psql_database_index.sql
     1254  2017-08-30 19:01   WEB-INF/classes/db/psql/scopes.sql
     1522  2017-08-30 19:01   WEB-INF/classes/db/psql/users.sql
     2686  2017-08-30 17:30   WEB-INF/crypto-config.xml
     6967  2017-08-30 17:30   WEB-INF/data-context.xml
     1946  2017-08-30 17:30   WEB-INF/endpoint-config.xml
     2920  2017-08-30 17:30   WEB-INF/jpa-config.xml
   133942  2017-08-30 18:32   WEB-INF/lib/HikariCP-2.6.1.jar
   263965  2017-08-30 17:38   WEB-INF/lib/commons-codec-1.9.jar
  2521113  2017-08-30 17:38   WEB-INF/lib/guava-21.0.jar
     4722  2017-08-30 17:38   WEB-INF/lib/jcip-annotations-1.0-1.jar
    16515  2017-08-30 17:38   WEB-INF/lib/jcl-over-slf4j-1.7.25.jar
    77882  2017-08-30 17:38   WEB-INF/lib/json-smart-1.3.1.jar
   489884  2017-08-30 18:32   WEB-INF/lib/log4j-1.2.17.jar
   309879  2017-08-30 19:01   WEB-INF/lib/openid-connect-server-1.3.2-SNAPSHOT.jar
  1364195  2017-08-30 18:32   WEB-INF/lib/org.eclipse.persistence.jpa-2.5.1.jar
  1139269  2017-08-30 17:38   WEB-INF/lib/spring-context-4.3.7.RELEASE.jar
   476938  2017-08-30 18:32   WEB-INF/lib/spring-orm-4.3.7.RELEASE.jar
   476766  2017-08-30 17:38   WEB-INF/lib/spring-security-oauth2-2.1.0.RELEASE.jar
   267116  2017-08-30 18:31   WEB-INF/lib/spring-tx-4.3.7.RELEASE.jar
   915615  2017-08-30 17:38   WEB-INF/lib/spring-webmvc-4.3.7.RELEASE.jar
   360509  2017-08-30 17:30   resources/js/lib/moment-with-locales.js
    14897  2017-08-30 17:30   resources/js/whitelist.js
     2385  2017-08-30 17:30   resources/template/blacklist.html
    47919  2017-08-30 17:30   resources/template/dynreg.html
     8720  2017-08-30 17:30   resources/template/scope.html
     4938  2017-08-30 17:30   META-INF/maven/org.mitre/openid-connect-server-webapp/pom.xml
     3408  2017-08-30 19:01   WEB-INF/classes/db/hsql/clients.sql
     1995  2017-08-30 19:01   WEB-INF/classes/db/hsql/loading_temp_tables.sql
      482  2017-08-30 19:01   WEB-INF/classes/db/hsql/security-schema.sql
     2641  2017-08-30 19:01   WEB-INF/classes/db/mysql/clients.sql
     8815  2017-08-30 19:01   WEB-INF/classes/db/mysql/mysql_database_tables.sql
      482  2017-08-30 19:01   WEB-INF/classes/db/mysql/security-schema.sql
     3491  2017-08-30 19:01   WEB-INF/classes/db/oracle/clients_oracle.sql
     2237  2017-08-30 19:01   WEB-INF/classes/db/oracle/loading_temp_tables_oracle.sql
    11025  2017-08-30 19:01   WEB-INF/classes/db/oracle/oracle_database_tables.sql
      488  2017-08-30 19:01   WEB-INF/classes/db/oracle/security-schema_oracle.sql
     2397  2017-08-30 19:01   WEB-INF/classes/db/psql/clients.sql
     8632  2017-08-30 19:01   WEB-INF/classes/db/psql/psql_database_tables.sql
      482  2017-08-30 19:01   WEB-INF/classes/db/psql/security-schema.sql
     2291  2017-08-30 19:01   WEB-INF/classes/log4j.xml
  3955990  2017-08-30 17:39   WEB-INF/lib/bcprov-jdk15on-1.58.jar
    41203  2017-08-30 17:38   WEB-INF/lib/slf4j-api-1.7.25.jar
    12244  2017-08-30 18:32   WEB-INF/lib/slf4j-log4j12-1.7.25.jar
   380004  2017-08-30 17:38   WEB-INF/lib/spring-aop-4.3.7.RELEASE.jar
   762747  2017-08-30 17:38   WEB-INF/lib/spring-beans-4.3.7.RELEASE.jar
   263286  2017-08-30 17:38   WEB-INF/lib/spring-expression-4.3.7.RELEASE.jar
   427740  2017-08-30 18:32   WEB-INF/lib/spring-jdbc-4.3.7.RELEASE.jar
    85108  2017-08-30 18:32   WEB-INF/lib/spring-security-acl-4.2.2.RELEASE.jar
   395913  2017-08-30 17:38   WEB-INF/lib/spring-security-core-4.2.2.RELEASE.jar
    19654  2017-08-30 18:32   WEB-INF/lib/spring-security-taglibs-4.2.2.RELEASE.jar
   383927  2017-08-30 17:38   WEB-INF/lib/spring-security-web-4.2.2.RELEASE.jar
   817936  2017-08-30 17:38   WEB-INF/lib/spring-web-4.3.7.RELEASE.jar
    61884  2017-08-30 17:30   resources/bootstrap2/js/bootstrap.js
       61  2017-08-30 17:30   resources/css/mitreid-connect-responsive-local.css
     4132  2017-08-30 17:30   resources/css/mitreid-connect.css
     1742  2017-08-30 17:30   resources/images/heart_mode@2x.png
    94051  2017-08-30 17:30   resources/images/mitreid-connect.ico
    12721  2017-08-30 17:30   resources/js/admin.js
    23626  2017-08-30 17:30   resources/js/dynreg.js
     9396  2017-08-30 17:30   resources/js/grant.js
    10117  2017-08-30 17:30   resources/js/lib/backbone.validations.js
     6242  2017-08-30 17:30   resources/js/lib/bootpag.js
     4724  2017-08-30 17:30   resources/js/lib/bootstrap-sheet.js
     7291  2017-08-30 17:30   resources/js/lib/bootstrapx-clickover.js
    10189  2017-08-30 17:30   resources/js/lib/html5.js
    85908  2017-08-30 17:30   resources/js/lib/i18next.js
     8830  2017-08-30 17:30   resources/js/lib/purl.js
     5730  2017-08-30 17:30   resources/js/lib/retina.js
    52919  2017-08-30 17:30   resources/js/lib/underscore.js
    29468  2017-08-30 17:30   resources/js/locale/en/messages.json
    24805  2017-08-30 17:30   resources/js/locale/sv/messages.json
    26513  2017-08-30 17:30   resources/js/locale/zh/messages.json
    26513  2017-08-30 17:30   resources/js/locale/zh_CN/messages.json
    26476  2017-08-30 17:30   resources/js/locale/zh_TW/messages.json
     1264  2017-08-30 17:30   resources/js/profile.js
    14048  2017-08-30 17:30   resources/js/rsreg.js
    12037  2017-08-30 17:30   resources/js/scope.js
    14973  2017-08-30 17:30   resources/js/token.js
     4980  2017-08-30 17:30   resources/template/admin.html
    63179  2017-08-30 17:30   resources/template/client.html
     5616  2017-08-30 17:30   resources/template/token.html
      112  2017-08-30 19:02   META-INF/maven/org.mitre/openid-connect-server-webapp/pom.properties
---------                     -------
 34472468                     201 files


For some reason, though, they're not being served. Jetty sees all the other files in the bootstrap2 hierarchy (the js files, etc), and it serves all the *other* css files correctly. There's something tripping up those specific files from serving. 

I'm not familiar with Jetty in the Maven environment, but it sure looks like its something specific to the jetty environment, not the build, given the files are in the WAR correctly.

**Comment by dhardiker** [comment]
I believe the CSS files are being compiled - they're present as valid CSS in the target directory, and they appear in the war too.

```
~/W/g/m/O/openid-connect-server-webapp ❯❯❯ unzip -t target/openid-connect-server-webapp.war | grep bootstrap.css
    testing: resources/bootstrap2/css/bootstrap.css   OK
~/W/g/m/O/openid-connect-server-webapp ❯❯❯                                                                                                                                                                                             
```

I've not installed Tomcat and tried running the war directly in it - only following the Jetty instructions. I do note that when running it through Jetty as above it outputs:

```
[INFO] Started o.e.j.m.p.JettyWebAppContext@79f1e22e{/openid-connect-server-webapp,file:///Users/redacted/Work/github/mitreid-connect/OpenID-Connect-Java-Spring-Server/openid-connect-server-webapp/src/main/webapp/,AVAILABLE}{file:///Users/redacted/Work/github/mitreid-connect/OpenID-Connect-Java-Spring-Server/openid-connect-server-webapp/src/main/webapp/}
[INFO] Started ServerConnector@75469ba6{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
[INFO] Started @39273ms
[INFO] Started Jetty Server
```

If the CSS files are also served from "src/main/webapp/" then that would be an issue, because the LESS files are not compiled into that folder - at least not by following the instructions.

**Comment by dhardiker** [comment]
I've got it working. It seems that the CSS files *are* being served from "src/main/webapp/" and I have to copy the compiled LESS files:

```
~/W/g/m/O/openid-connect-server-webapp ❯❯❯ mvn clean package
~/W/g/m/O/openid-connect-server-webapp ❯❯❯ cp -r target/openid-connect-server-webapp-*/resources/bootstrap2 src/main/webapp/resources/
~/W/g/m/O/openid-connect-server-webapp ❯❯❯ mvn jetty:run
```

Then everything works.

I don't know what the standard way to approach a solution for this would be, but perhaps you either want Jetty to pull resources from the target folder where the LESS files are compiled to, or have the LESS files also compile into the "src/main/webapp" folder.

Both of those approaches have negative side effects however ...

**Comment by lpghartz** [comment]
Interestingly, that suggests jetty isn't actually running from the WAR file, and is running from the src directory, which is actually definitely wrong -- there's a reason the build moves things into target. It means you're not running the actual intended deployment. The jetty plugin, though, is configured in the POM to be pointing at the WAR, so I'm confused how it would be finding anything in the src directory. It shouldn't even know about it.

**Comment by dhardiker** [comment]
I can imagine why you might want it to run from the source - as that increases dev speed. That works fine for raw served files (like CSS, JS and images) but less so for anything compiled (Java, Coffeescript, LESS).

It's not clear what the intended dev cycle is for this project so I'm not opinionated on the shape of any solution. In any case, this seems like a maven bug of some sort!

**Comment by jricher** [comment]
`uma-server-webapp` is a different module in the project, it shouldn't be running from there. If it is, there's something wrong with the Jetty configuration. My own dev environment uses Tomcat and tcServer so I'm less familiar with how Jetty works on a day to day basis.

**Comment by baladasoji** [comment]
mvn jetty:run-war 
ensures that Jetty loads the application from war instead of loading it from sources
This fixed my bootstrap problem

**Comment by jricher** [comment]
That's good to know, could you please add those instructions to the project wiki?

**Comment by baladasoji** [comment]
Done
