### ISSUE TITLE
openid-connect-server-webapp : Requests redirecting to same instance always even when StickySession is set to OFF in load balancer

### ISSUE THREAD

**Issue by SivaNernur** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1296]
Hi 

I am trying to get openid-connect-server-webapp run as stateless.

The "openid-connect-server-webapp" with MySql works fine with Apache Load Balancer, balancing two Tomcat Instances.  But, 

ISSUE is the following
Even With Sticky Session OFF in my Load Balancer -  
1. All my requests are hitting same tomcat instance.
2. If i bring the instance downs where all my requests are directed to, i had to login again.

Even if bring one instance is down,  my requirement is i should NOT be asked to login again. 
My requests should be distributed across instances.

Can anyone please suggest what am i missing to set up "openid-connect-server-webapp" in non-sticky session environment and make this stateless.

Details:
1. I am Using MySql Database.
2. My deployment uses same clients.sql in "openid-connect-server-webapp\src\main\resources\db\mysql\"
INSERT INTO client_grant_type_TEMP (owner_id, grant_type) VALUES
	('client', 'authorization_code'),
	('client', 'urn:ietf:params:oauth:grant_type:redelegate'),
	('client', 'implicit'),
	('client', 'refresh_token');

3. I am using Apache Load Balancer.
4. Deployed "openid-connect-server-webapp" on 2 tomcat instances in my laptop.
Configured "openid-connect-server-webapp" to run on port 80 as apache can receive requests and redirect to registered nodes as part of balancing the load.

Thanks & Regards
Siva

**Comment by jricher** [comment]
The server application itself is not stateless. You need to have shared Tomcat state between instances in order for it to work. It's not enough to share cookies between instances, you need the stored session information shared between tomcat instances as well. See the Tomcat information here: https://tomcat.apache.org/tomcat-6.0-doc/cluster-howto.html as well as general clustering information for the MITREid Connect server app in the documentation: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Clustering

**Comment by SivaNernur** [comment]
This solved my issue. Thank you Justin
