### ISSUE TITLE
Custom ConfigurationPropertiesBean implementation

### ISSUE THREAD

**Issue by SantoshKumar4** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1297]
I am wanting to have custom ConfigurationPropertiesBean by using overlay  as I need to dynamically set the issuer based on  current IP. Can ConfigurationPropertiesBean be interface based?

Thanks

**Comment by jricher** [comment]
You don't need an interface to do this, just subclass it and override the getters. To inject your own, override `server-config.xml` to instantiate your class or use a BeanFactory to inject it dynamically.

**Comment by SantoshKumar4** [comment]
Thanks. It worked.
