### ISSUE TITLE
SSO without prompting user

### ISSUE THREAD

**Issue by aliiitarek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1300]
In #304:
> If you simply want to have one account be able to log in to multiple applications (single sign-on), you can already do that with the base OIDC protocol and that's implemented.

Can a user log in to multiple applications on the same device without prompting login? Is it correct that the identity provider will provide a session id and if apps share that among them and use it in requests they won't get authenticated?

And for login merely calling the `/endsession` endpoint will invalidate the session id.

**Comment by jricher** [comment]
For devices, it depends on how you implement the apps on the device. You just need to make sure the user's browser has a consistent session with the IdP. If they're using a shared browser session (like the system browser or a secure browser tab -- not an embedded browser view in each app), then you can get this behavior with OIDC as-is. 

Closing this issue as it's not about this project specifically.
