### ISSUE TITLE
Wrong ennforcement of jwtClaims.getIssuer().equals(client.getClientId()?

### ISSUE THREAD

**Issue by kaibjornstad** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1305]
https://tools.ietf.org/html/rfc7523#section-4

“Below is an example JSON object that could be encoded to produce the
   JWT Claims Set for a JWT:

     {"iss":"https://jwt-idp.example.com",
      "sub":"mailto:mike@example.com",
      "aud":"https://jwt-rp.example.net",
      "nbf":1300815780,
      "exp":1300819380,
      "http://claims.example.com/member":true}
“

Code ref:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/openid/connect/assertion/JWTBearerAuthenticationProvider.java#L151

**Comment by jricher** [comment]
The code is correct as per the OIDC spec which it implements:

http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
