### ISSUE TITLE
id_token should contain the RS as audience

### ISSUE THREAD

**Issue by st4sik** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1306]
http://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation:

>  Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. 
> The aud (audience) Claim MAY contain an array with more than one element. 
> The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client.

> aud
> REQUIRED. 
> Audience(s) that this ID Token is intended for.
> It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. 
> It MAY also contain identifiers for other audiences. 
> In the general case, the aud value is an array of case sensitive strings.
> In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

We have a specific TC with resource_id as 'aud' for validation id_token on client side.
 
We need to add resource_id as 'aud' in id_token. For this, we want to use this API

```
ClientDetailsEntity client;
client.getResourceIds();
```

But, we don't understand how we can use client.setResourceIds()? There is one solution is
to use ClientApi for adding resource_id on client through client.setResourceIds().  Can we use this or not?

**Comment by jricher** [comment]
The ID token is not meant to be used as an access token -- use the access token for that. 

Our code doesn't use the "resourceIds" field of the spring library.
