### ISSUE TITLE
Miminum memory requirements to avoid java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by patfrat** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1321]
Hello, 

When requesting /api/tokens/refresh?_=.... i encounter a 500 error
HTTP 500 - Handler processing failed; nested exception is java.lang.OutOfMemoryError: Java heap space from Tomcat 8

What is your minimum requirements about the memory size to allow to OpneID Connect Java Spring Server ?

Thank you in advance

**Comment by jricher** [comment]
Depends on your data size. Most of our production servers run in at least 4G of RAM, in my experience. It's a big application, you can't use old versions of Java's tiny footprint.

**Comment by patfrat** [comment]
Thank you for your reply !
