### ISSUE TITLE
How do I get the json web key?

### ISSUE THREAD

**Issue by zhoujie123** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1323]
On the client side, you get the public key of the server through the jwkurl, so it should be obtained through HTTPClient, but why is it directly available in the publishClientJwk method of the ClientKeyPublisher class?

**Comment by jricher** [comment]
_Housekeeping note: Please don't edit the text of your issue to create a new issue -- close the old one first and create a new issue._

The `ClientKeyPublisher` is for publishing the *client's* key, not fetching the server's. The client can also have a key for use with signed and encrypted requests.

**Comment by zhoujie123** [comment]
Thank you for your answer. I didn't take into account the server-side need to get the client's public key to decrypt the token.------------------ 原始邮件 ------------------
发件人: "Justin Richer";<notifications@github.com>;
发送时间: 2017年11月20日(星期一) 中午12:53
收件人: "mitreid-connect/OpenID-Connect-Java-Spring-Server"<OpenID-Connect-Java-Spring-Server@noreply.github.com>;
抄送: "zh_coder"<631463730@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [mitreid-connect/OpenID-Connect-Java-Spring-Server] How do I getthe json web key? (#1323)




Housekeeping note: Please don't edit the text of your issue to create a new issue -- close the old one first and create a new issue.
 
The ClientKeyPublisher is for publishing the client's key, not fetching the server's. The client can also have a key for use with signed and encrypted requests.

**Comment by zhoujie123** [comment]
Thank you for your answer. I didn't take into account the server-side need to get the client's public key to decrypt the token.
