### ISSUE TITLE
Signed request fails when client is registered with multiple redirect URIs  

### ISSUE THREAD

**Issue by kules** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1328]
Error message displayed is:

> Invalid redirect: null does not match one of the registered values: <list of redirect uris>

Error is thrown in `org.springframework.security.oauth2.provider.endpoint.DefaultRedirectResolver#resolveRedirect` and `requestedRedirect` param is null. Could be related to #1182 .

And what is the use of supporting client with multiple redirect URIs?

**Comment by jricher** [comment]
According to RFC6749 the client MUST send a redirect URI if it has multiple redirect URIs registered. This is working as intended.
