### ISSUE TITLE
token storage problem

### ISSUE THREAD

**Issue by zhoujie123** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1329]
Hi.
  I would like to ask a question about AccessToken storage, accessToken created in the project DefaultOAuth2ProviderTokenService class, but since accessToken used jwt, then he still need to store? I think this is not necessary. What is the purpose of your accessToken storage?

**Comment by jricher** [comment]
We put things in the storage besides what goes in the JWT, such as scopes and other details. They're not fully stateless. They can also be revoked and the revocation status can be checked by a client with introspection.
