### ISSUE TITLE
A question of token request

### ISSUE THREAD

**Issue by zhoujie123** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1333]
When the RP requests Token, if the client_secret_jwt way to use the request. Then he needs to sign it (based on the OpenID documentation, and your project code). I always think RP only save the public key used to sign and encrypt, so if according to the document and your project, PR need a private key right? If so, is this private key the OP's private key? Or generated by the client itself?

**Comment by bodewig** [comment]
You use HMAC (a symmetric signature algorithm) with your client secret as the key, see http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
