### ISSUE TITLE
MITREid Connect server backed by an external LDAP user store "Authentication Failed: Token Endpoint did not return an id_token"

### ISSUE THREAD

**Issue by johndoe8181** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1334]
Hello Sir/Madam,

We are not able to setup the following [ldap-openid-connect-server](https://github.com/mitreid-connect/ldap-openid-connect-server) project to work with [simple-web-app](https://github.com/mitreid-connect/simple-web-app), it is throwing HTTP 401 "Authentication Failed: Token Endpoint did not return an id_token". Please provide guidance/enlightenment as to what are we missing, very much appreciated. Thank you.

p/s: We are able to login into the **ldap-openid-connect-server** but when we tried via **simple-web-app**, at the "Approval Required for Test Client" screen, once we clicked on "Authorize" button the application crashes with HTTP 401 "Authentication Failed: Token Endpoint did not return an id_token".

**Comment by jricher** [comment]
That could be a lot of things, but did your client request the `openid` scope, and did you approve it? Both of those applications are really just demo apps and aren't always very well kept up with the core project.

**Comment by johndoe8181** [comment]
thank you for your response. we are actually looking to customize the authentication part by referencing the **ldap-openid-connect-server** project (we would ideally like to point the authentication to invoke an external server via RESTful API). If by somehow there are any detailed tutorial/FAQ section what needs to be done, would really appreciate a lot if you could point us to it.
