### ISSUE TITLE
Token request 

### ISSUE THREAD

**Issue by zhoujie123** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1335]
Why RP request authorization also need to obtain issuer parameters? In the handleAuthorizationRequest method in the OIDCAuthenticationFilter class, should the grant request not only contain the following parameters?

"Https://server.example.com/authorize?"+
"Response_type = code" +
"& Client_id = s6BhdRkqt3" +
"& Scope = openid + profile" +
"& Redirect_uri = https% 3A% 2F% 2Fclient.example.org% 2F" +
"& Nonce = 34fasf3ds" +
"& State = af0ifjsldkj" +
"& Foo = bar";

**Comment by jricher** [comment]
I don't understand what this issue is asking. The filter does put those parameters in the request and doesn't include the issuer in the outgoing request. Closing this issue unless it can be explained better.
