### ISSUE TITLE
 Invalid CSRF token found for http://localhost:8080/openid-connect-server-webapp/login

### ISSUE THREAD

**Issue by saiejp** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1336]
I have just downloaded the project in the past days, built it locally and am running it using jetty. I have changed the configuration to use a MySQL database to persist data but apart from that, it's totally standard. When I try to login from the Chrome browser, I consistently get the following: 

HTTP ERROR 405
Problem accessing /openid-connect-server-webapp/error. Reason:

    Request method 'POST' not supported

I have turned debugging on and see the following:

EBUG: org.springframework.security.web.FilterChainProxy - /resources/images/mitreid-connect.ico at position 7 of 8 in additional filter chain; firing Filter: 'ExceptionTranslationFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /resources/images/mitreid-connect.ico at position 8 of 8 in additional filter chain; firing Filter: 'FilterSecurityInterceptor'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/resources/images/mitreid-connect.ico'; against '/resources/**'
DEBUG: org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Secure object: FilterInvocation: URL: /resources/images/mitreid-connect.ico; Attributes: [permitAll]
DEBUG: org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Previously Authenticated: org.springframework.security.authentication.AnonymousAuthenticationToken@9055c2bc: Principal: anonymousUser; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@b364: RemoteIpAddress: 0:0:0:0:0:0:0:1; SessionId: null; Granted Authorities: ROLE_ANONYMOUS
DEBUG: org.springframework.security.access.vote.AffirmativeBased - Voter: org.springframework.security.web.access.expression.WebExpressionVoter@673218b2, returned: 1
DEBUG: org.springframework.security.web.access.intercept.FilterSecurityInterceptor - Authorization successful
DEBUG: org.springframework.security.web.access.intercept.FilterSecurityInterceptor - RunAsManager did not change Authentication object
DEBUG: org.springframework.security.web.FilterChainProxy - /resources/images/mitreid-connect.ico reached end of additional filter chain; proceeding with original chain
DEBUG: org.springframework.security.oauth2.provider.endpoint.FrameworkEndpointHandlerMapping - Looking up handler method for path /resources/images/mitreid-connect.ico
DEBUG: org.springframework.security.oauth2.provider.endpoint.FrameworkEndpointHandlerMapping - Did not find handler method for [/resources/images/mitreid-connect.ico]
DEBUG: org.springframework.security.web.access.ExceptionTranslationFilter - Chain processed normally
DEBUG: org.springframework.security.web.context.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/token'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/jwk**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/.well-known/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/resources/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/register/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/resource/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/userinfo**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/api/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/devicecode/**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/introspect**'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/revoke**'
DEBUG: org.springframework.security.web.FilterChainProxy - /login at position 1 of 13 in additional filter chain; firing Filter: 'SecurityContextPersistenceFilter'
DEBUG: org.springframework.security.web.context.HttpSessionSecurityContextRepository - No HttpSession currently exists
DEBUG: org.springframework.security.web.context.HttpSessionSecurityContextRepository - No SecurityContext was available from the HttpSession: null. A new one will be created.
DEBUG: org.springframework.security.web.FilterChainProxy - /login at position 2 of 13 in additional filter chain; firing Filter: 'AuthorizationRequestFilter'
DEBUG: org.springframework.security.web.util.matcher.AntPathRequestMatcher - Checking match of request : '/login'; against '/authorize'
DEBUG: org.springframework.security.web.FilterChainProxy - /login at position 3 of 13 in additional filter chain; firing Filter: 'WebAsyncManagerIntegrationFilter'
DEBUG: org.springframework.security.web.FilterChainProxy - /login at position 4 of 13 in additional filter chain; firing Filter: 'HeaderWriterFilter'
DEBUG: org.springframework.security.web.header.writers.HstsHeaderWriter - Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@6f038401
DEBUG: org.springframework.security.web.FilterChainProxy - /login at position 5 of 13 in additional filter chain; firing Filter: 'CsrfFilter'
DEBUG: org.springframework.security.web.csrf.CsrfFilter - Invalid CSRF token found for http://localhost:8080/openid-connect-server-webapp/login
DEBUG: org.springframework.security.web.context.HttpSessionSecurityContextRepository - SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
WARN : org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported
DEBUG: org.springframework.security.web.context.SecurityContextPersistenceFilter - SecurityContextHolder now cleared, as request processing completed

I also see this sporadically when using the MS Edge browser but a refresh of the page normally corrects the issue. I'm sure I have some configuration setting wrong somewhere but have been going around in circles for days and would appreciate some clues as to what I have done wrong ?

**Comment by saiejp** [comment]
After going back to a basic installation and it seems I was being bitten by browsers caching and the fact that I thought I could simply open a HTTPS port for the oauth implementation. It seems that if I start the server on http port 8080 and use an icognito session, I can login, redirect etc. so I shot myself in the foot. Is there a guide somewhere to starting the server on a HTTPS port as it's obviously not just a case of telling jetty to do this ?

**Comment by saiejp** [comment]
For anyone who comes across similar issues, I couldn't get the CSRF stuff to work consistently so for now I have disabled in in user-context.xml with the following change:

		
		<security:csrf disabled="true"/>

In terms of configuration to run with https,  I set up the jetty configuration on both http and https ports and made the following change to server-context.xml

		
		<property name="issuer" value="https://localhost:8583/openid-connect-server-webapp/" />

I haven't had any further issues since but intend to return to the csrf issue down the road.

**Comment by saiejp** [comment]
I'll update if/when I get back to the csrf issue.

**Comment by erran** [comment]
@saiejp We're experiencing a similar issue at work but are not able to disable CSRF. Did you ever get past that issue?

[![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)](https://www.xkcd.com/979/)

**Comment by saiejp** [comment]
I'm afraid I didn't get back to this. I have been running since with as it got me past the issues I was facing. Sorry...

		
		<security:csrf disabled="true"/>

**Comment by erran** [comment]
No problems @saiejp, thanks for the response. In our case this isn't acceptable. I'll try to respond here for people who see this issue in the future. 👌

**Comment by saiejp** [comment]
@erran This would be good. We tried a few things and simply couldn't get it to work. In the recent past, we have had issues with Chrome doing strange things so it might be worth giving FireFox and/or MS Edge a try ? We also had issues with the fact that we were using localhost causing different behaviors....perhaps there is something there ? Unfortunately other priorities have meant this has been left behind from our perspective but it would be great to understand what is causing the issue.

**Comment by erran** [comment]
> I'll try to respond here for people who see this issue in the future. 👌

@saiejp Ok, we managed to solve this for our use case we needed to add support for passing a CSRF token to [graphql-spring-boot](https://github.com/graphql-java/graphql-spring-boot) which one of our developers did by creating his own controller/html template for `graphiql-spring-boot-autoconfigure`. He did this to expose the CSRF token to the HTML/JavaScript ensuring it was being `POST`ed to the graphql API calls the browser made.

**Comment by saiejp** [comment]
@erran thanks for the feedback. This seems to have been a very specific issue for you using graphql. I was getting this just using the normal dialogs with the mitreid server for login and configuration. Do I take it you did not have any issues with that ?
