### ISSUE TITLE
token_endpoint_auth_signing_alg_values_supported cannot include 'none'

### ISSUE THREAD

**Issue by krishnakanth23** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1338]
Hi
I am using openId hosted in my local. While I am trying to connect from couchbase sync gateway it is giving error 

token_endpoint_auth_signing_alg_values_supported cannot include 'none'

and then sync gateway is not able to obtain client for provider.

Please can anyone help me out as when debugging I am getting below values for token_endpoint_auth_signing_alg_values_supported 

token_endpoint_auth_signing_alg_values_supported=[HS256, HS384, HS512, RS256, RS384, RS512, ES256, ES384, ES512, PS256, PS384, PS512]

there is no none among that.

**Comment by jricher** [comment]
Sounds like this is an error in the gateway that you're using, closing this issue.
