### ISSUE TITLE
Customizing the consent/authorization flow of an Authorize request to the OpenId-Connect Server

### ISSUE THREAD

**Issue by saiejp** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1341]
When an application issues an Authorize request to the standard server with a request=<jwt object>, I have a requirement to customize this to a) validate the contents of the request b) present a number of options to the user and then c) return to the standard process to be redirected back to the originator of the Authorise request with a code, state etc.

I have created a custom filter to tie into the process, however, I'm not sure this is the correct way  as it's not clear how I can present a list of options to the user. 

What is the bet way to achieve this ?

**Comment by jricher** [comment]
To customize what you show to the user you need to customize the authorization page, `authorize.jsp`. And you'll probably want to customize the controller that serves it.

**Comment by saiejp** [comment]
Many thanks for the very quick response. Could you point me to the controller source ?

**Comment by saiejp** [comment]
Seems to me to be org.mitre.oauth2.web.OAuthConfirmationController. I'll plough on on that basis.

**Comment by saiejp** [comment]
And the logic that deals with the response from approve.jsp is org.mitre.openid.connect.token.TofuUserApprovalHandler

**Comment by saiejp** [comment]
Thanks for you help. We have now successfully customized this.
