### ISSUE TITLE
Authentication Failed: No client configuration found for issuer

### ISSUE THREAD

**Issue by SuchithShivakumar** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1354]
Hi,

I am getting ERROR: org.mitre.openid.connect.client.OIDCAuthenticationFilter - No client configuration found for issuer: with my issuer.

Thanks.

**Comment by jricher** [comment]
For the client library, you need to have a service wired in that gets the right client configuration for each issuer. Did you register your client? Do you have the client configuration set up properly?

**Comment by SuchithShivakumar** [comment]
Thanks Justin, I was able to resolve the issue. I am pretty much new to OIDC connect. Can you help me out understand the flow by providing some documentation work for MITREID.

**Comment by jricher** [comment]
The documentation for this project is linked from the main page.
