### ISSUE TITLE
Support of both RS256 & HS256 algorithm client validation

### ISSUE THREAD

**Issue by kjijrkcas** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1360]
Hi,

I am looking for configuration where my mitreid-connect server can provide support for both RS256 & HS256 algorithm.

Currenly my server support only RS256 algorithm.

Is there any configuration need to change on server web? 

Thanks

**Comment by jricher** [comment]
It already does support both, and which one is used depends on how the client is configured and what you're trying to do with it. Are you looking at the signatures for ID tokens, userinfo, client authentication, or something else? These are all configured separately and all support RS256 and HS256 as options.

**Comment by kjijrkcas** [comment]
Thanks Justin.

Actually I am looking for option where one is configured on RS256 and one on HS256. And want to support the both client at same time. 

Can you please share some sample reference or link where I can check the configuration.

Thanks.

**Comment by jricher** [comment]
This is all already supported in the server. You can configure each on a per-client basis, see the "Crypto" tab in the admin interface.
