### ISSUE TITLE
Implementing Identity for Web Application Developed using Struts 2.0

### ISSUE THREAD

**Issue by mchoiceD** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1361]
Hi, 

We are implementing SSO for our application which is built using Struts 2.0 framework. We have been told to use a well established library such as MitreId for java, which respects the OAuth 2.0 and OpenID standards correctly. 

I want to know how to setup our application as relay party using MitreId and how to get authorization code and access token using MitreId to perform API call to the resource server.

Thanks.

**Comment by jricher** [comment]
We have a client library for setting up an OIDC client, which is built on Spring Security and can be used with any Spring Security application. This will also give you an OAuth access token that you could use to set up calls to your resource server. We have a demo application that you might want to look at (https://github.com/mitreid-connect/simple-web-app) as well as client documentation with more details (https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Client-configuration). As for the details of connecting directly with Struts, that's outside the scope of this OSS project.
