### ISSUE TITLE
Possible to add custom business logic? 

### ISSUE THREAD

**Issue by mrshawn191** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1362]
<img width="708" alt="skarmavbild 2018-02-16 kl 11 18 56" src="https://user-images.githubusercontent.com/5851638/36303114-3b652636-130b-11e8-9501-736c44117684.png">

Is this possible to achieve? Basically i want to turn my server into an open id server provider. Where my customers can login via my server. 

My question is where do i implement custom logic against external services that the user wish to authenticate against?

**Comment by jricher** [comment]
Yes, you just need to change how users log into the MITREid Connect server itself. Since this server is a Spring Security application, you have a lot of options for doing that, including even using the MITREid Connect client library to do a second-stage OIDC login. Most of the configuration you'd need to change is in the `user-context.xml` file.

**Comment by mrshawn191** [comment]
May I ask what is the simplest way to plugin mitre-connect to an already established java project?

**Comment by jricher** [comment]
It completely depends on which part of the MITREid Connect project you're looking to use and in what capacity within the existing project.

**Comment by mrshawn191** [comment]
Thanks also may i please ask,

I wish to use mitreid connect server to integrate with my existing spring boot + spring oauth2 server. 

Is this possible to achieve? I was thinking if you can include MITREid project so that the openid endpoints should be exposed such as ".well-known/openid-configuration" etc.. 

I dont quite understand how to plug it in.. i've added the xml from the exampels server.config.xml etc.. but the endpoints doesn't seem to get exposed

**Comment by jricher** [comment]
Probably not in that way, at least not easily. The server is a stand-alone spring project, which is deployed as a .war file. If you have an existing oauth2 server, then you'd have a very large task ahead of you to integrate them directly. As I said above, you can use an external OIDC server (or any other identity system) to log into the MITREid Connect server, but that's with them deployed separately.
