### ISSUE TITLE
Dynamic client registration with grant_type password not possible, why?

### ISSUE THREAD

**Issue by col-panic** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1364]
It is not possible to register a dynamic client with grant_type password (remark: this grant_type is disabled by default). Why is this the case? I could not find information in https://tools.ietf.org/html/rfc7592 on why this should be not possible?

I see that the check on this grant_type even happens after the parsing of a software statement. If it is not okay to allow this by default - could it probably be allowed in the case of requesting the grant_type via a validated software statement (see https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/1220)?

**Comment by col-panic** [comment]
Additional thoughts on this:
* If grant_type password is not enabled by default, and has to be manually enabled in authz-config - why not by default allow to add the grant_type if it is not effective by default anyways.
* If keeping it like it is - a change of the resp. answered message would be nice from `"The password grant type is not allowed in dynamic registration on this server."`to `"The password grant type is not enabled and/or allowed in dynamic registration on this server. "`

**Comment by jricher** [comment]
The password grant type is not allowed in OpenID Connect, and is discouraged in OAuth. We will not be enabling it by default in the project any time soon. Better error messages are always welcomed if you'd like to add them!

**Comment by col-panic** [comment]
Thanks for your comment! 

I see, but would you generally approve to my thoughts - and possibly accept a patch - that given I enable the password support via override in authz-config, this also allows the usage of the password grant_type for dynamic registration? Its still not enabled by default - but could be enabled this way. 

Do you possibly have a link concerning the fact that its discouraged?

**Comment by jricher** [comment]
No, because the password grant type is meant to be used only when there's a high degree of trust in the client application:

https://tools.ietf.org/html/rfc6749#section-1.3.3

Dynamically registered clients are, by their nature, not highly trusted.

**Comment by col-panic** [comment]
Thank you very much for your time and explanation! :)
