### ISSUE TITLE
Access token with restricted system scope granted to ROLE_USER

### ISSUE THREAD

**Issue by col-panic** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1369]
Web documentation on restricted system scopes says

 _Restricted scopes are only usable by system administrators and are unavailable to dynamically registered clients and protected resources_

Using a simple user (resource owner credentials flow with empty client scopes), without ROLE_ADMIN, however, I can still retrieve an access token with the requested restricted system scope.

**Comment by jricher** [comment]
The documentation should be more clear. non-admin users can't create a client with a restricted scope. Admin users can register clients with any scope. Once a client is registered, any user can approve any scopes that it has been registered with.
