### ISSUE TITLE
WARN : org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported

### ISSUE THREAD

**Issue by Jokenbol** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1371]
I'm trying to add to this great "Openid Connect Java Spring Server" an API that can manage all the users if you are admin ( I know that it's not implemented but I thought I will be great to have it ). It took me a while but I figured out how the system works and I follow the way, you create the ClientAPI to create my own UserAPI. I can get All the users from user_info table, get a singleUser, I can edit and create a new user; from a FORM.
Now, my problem is, when I create the object from the form I cannot send it to my API. I get this warning for a post:

`WARN : org.springframework.web.servlet.PageNotFound - Request method 'POST' not supported`

Same thing with the others request methods PUT, DELETE. ONLY the GET method works.

Does someone have an idea on what I'm doing wrong? Because I do have a POST, PUT and DELETE @RequestMapping in my API. And I use the ROLE_ADMIN. Should I necessarily have to add an access_token @jricher  ?
( I usually speak french, forgive my english )

**Comment by Jokenbol** [comment]
This is a screenshot of the http://localhost:8080/openid-connect-server-webapp/manage/admin/users

![admin_users](https://user-images.githubusercontent.com/7669319/36914135-437bf8da-1e1a-11e8-91a7-8565c5d2b97a.png)

This is a screenshot of the http://localhost:8080/openid-connect-server-webapp/manage/admin/user/2
![manage_admin_user_2](https://user-images.githubusercontent.com/7669319/36914233-981d84e4-1e1a-11e8-9c15-e55bea342654.png)

**Comment by avanibhatnagar** [comment]
Hey @Jokenbol ! Did you ever solve this?

**Comment by Jokenbol** [comment]
No I don't. I was tryin to change the code itself and I encounter a lot of problems as I said. But it's not the way to go. What you have to do instead, is to use the overlay. You have an exemple here : https://github.com/mitreid-connect/example-openid-connect-overlay
It's better because you can override a lot of functions in the oidc server without even touch the main. It's a bad idea to try to change the server code.

So to answer your question, I did solve this by using the overlay. I connect another database for my users in the overlay project. An I can manage my users by using my databse instead of trying to query the database that come with oidc server. Hope I answer your question.
