### ISSUE TITLE
Refresh Token request via OpenID Connect Client

### ISSUE THREAD

**Issue by kcjavaman** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1372]
I am using the MITREId Connect client - version 1.3.1.  I am trying to understand if the API handles refreshing tokens.  If so, how does the application use the API to send a refresh token request.  I have searched the documentation, but I am unable to find this information. 

I see from the Open ID Connect specification the following request parameters are sent to the token endpoint:
client_id=some_client_id
&client_secret=some_secret
&grant_type=refresh_token
&refresh_token=existing_refresh_token
&scope=openid%20profile

Is there a simple way to do this in the API, or must I code my own method to send this request?

**Comment by jricher** [comment]
You do not use the server API to refresh an access token, you use the token endpoint as you list above from OIDC (which is actually specified in OAuth, RFC6749).

**Comment by kcjavaman** [comment]
Thank you for the quick response.
