### ISSUE TITLE
Running with Oracle Database pre 12.2 throws identifier too long exceptions

### ISSUE THREAD

**Issue by gresham-Carling** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1373]
There's an [issue](https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:9522337900346184952) with Oracle Databases pre version 12.2 only having column identifiers of up to 30 characters in length of which there are a couple occurrences.

Is there a recommended way to mitigate this?

**Comment by jricher** [comment]
The oracle support on this project should already be set up to use different column lengths and a special mapping file to take care of connecting the entities to the tables. If something is missing there please file a pull request to patch it.

**Comment by gresham-Carling** [comment]
Ah yes, missed the mappings file, tracked that down and it's working fine, thanks.
