### ISSUE TITLE
Does the OIDC parameter "prompt=select_account" have any impact?

### ISSUE THREAD

**Issue by smorandi** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1374]
I don't think this is currently evaluated in any way in MitreID connect.
The question I raise with this is more targeted to a use case of ours, where we actually have more than one identity per user. Meaning we should support multiple sets of different attributes for a user.

there are different ways how one could achieve this, but i was wondering if prompt=select_account could playa role in that.

To my knowledge, only google uses this for their IDP. And i am not even sure whether they use it in a way as to distinguish accounts on a per client/login base.

Or would there be a better way, to achieve multiple identities per "account" short of massive refactoring?

**Comment by jricher** [comment]
This parameter value is currently ignored by the server, as it is silent about how users log in in the first place. If you deploy a version with an account selector, this can be checked by your login process.
