### ISSUE TITLE
How to enable PKCE in version miterid-connect v. 1.3

### ISSUE THREAD

**Issue by ewilansky** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1379]
I see that the OIDCAuthenticationFilter class looks for the code_verifier request parameter in the simple web app client. However, I don't see any way to configure the use of PKCE by the client. In the client registration on the op, I have enabled the Crypto option: Proof Key for Code Exchange (PKCE) Code Challenge Method and set it to Plain Text Challenge (for now). Please explain how I should go about configuring the simple web app to submit a code_verifier on the authorization request. 

Thanks,
Ethan

**Comment by jricher** [comment]
You need to set the "codeChallengeMethod" parameter of your Client configuration inside the filter to one of the PKCE values.

**Comment by jricher** [comment]
Relevant line from the filter that you need to trigger is here: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-client/src/main/java/org/mitre/openid/connect/client/OIDCAuthenticationFilter.java#L276

Also, don't use the "Plain" method if you can avoid it, it doesn't add much if any security. (The PKCE spec even says as much.)

**Comment by ewilansky** [comment]
Thanks for the quick response. Agreed on the use of Plain. I will definitely change that once I get this wired-up.
