### ISSUE TITLE
Wrong Redirect with Apache HTTPS with "www"

### ISSUE THREAD

**Issue by lofidewanto** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1380]
I have following problem with MITREId (installed with context-path: openid-connect-server-webapp):

If I make a request as follow:
`https://test.com/openid-connect-server-webapp/authorize?response_type=code&client_id=client&scope=address+phone+openid+profile+email&redirect_uri=https%3A%2F%2Ftest.com%2Fmywebapp%2Fcontext%2Fo`

I always get following response:
`https://www.test.com/openid-connect-server-webapp/login`

Response Headers:
`Location: https://www.test.com/openid-connect-server-webapp/login`

My problem is that I always get the prefixed "www". I expected to have something like this as a response:
`https://test.com/openid-connect-server-webapp/login`

Running MITREId local or internal without Apache and HTTPS works fine.

Could you give me any hints?

Thanks,
Lofi

**Comment by jricher** [comment]
That sounds like a problem with your Apache configuration, then, and not the server. Check your rewrite rules. Also make sure your `issuer` field is set properly (without the www part).

**Comment by lofidewanto** [comment]
It's working with moving all to www.xxx. 

Thanks,
Lofi
