### ISSUE TITLE
Prevent brute force login attempts

### ISSUE THREAD

**Issue by col-panic** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1388]
Would a patch for implementing a brute force login filter be welcome (as described in http://www.baeldung.com/spring-security-block-brute-force-authentication-attempts)? 

As far as I see there is no such functionality implemented.

**Comment by jricher** [comment]
We could take a look at it, but for the most part we assume that people are going to tear out the whole login and user model when they install and customize this project, so we haven't put a ton into it.

**Comment by col-panic** [comment]
Ah ok. I have already added 2FA in my project and going to add this brute-force filter, but now I understand your approach! Thanks a lot for your answer!

**Comment by sail76** [comment]
@jricher  
For what you mentioned " people are going to tear out the whole login and user model when they install and customize this project"  , where can I find more guideline/instructions for this ?  
I am new to MITREid. 
Thanks.

**Comment by col-panic** [comment]
These modifications are done using maven overlays, a sample project is provided here https://github.com/mitreid-connect/example-openid-connect-overlay. The overlay project I created, including the TOTP can be found here https://github.com/elexis/elexis-openid-connect-overlay
