### ISSUE TITLE
openid Why is it slow?

### ISSUE THREAD

**Issue by liloong** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1413]
I changed the database to MySQL. When I landed on my application, it was very slow to return to my application. The data are very few, and why? Who can help me, thank you.

**Comment by liloong** [comment]
My program is developed by Java, but the time required for openid authentication to return is more than ten seconds. What should I do to make it respond quickly?

**Comment by liloong** [comment]
[图片]

**Comment by liloong** [comment]
![default](https://user-images.githubusercontent.com/30423256/42417152-c6bc2220-82b4-11e8-9d41-ed7d8f087da8.png)

**Comment by liloong** [comment]
@jricher Can you analyze it for me? I'm a beginner, thank you.

**Comment by bejondshao** [comment]
Are you using openid-connect-server-webapp? I see you change the IdP port to 8082, you need to change server-config.xml, chang the `issuer` to
```
<property name="issuer" value="http://localhost:8082/openid-connect-server-webapp/" />
```
