### ISSUE TITLE
Overlay Example

### ISSUE THREAD

**Issue by JoellyR** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1417]
Hi,

The overlay example doesn't have a issues section so I hope it's okay to create this one here. 

My issue is, once cloning the repo overlay example repo, running git submodules, creating the proper files in etc/mitreid-connect, running mvn package and deploying the war using apache tomcat, I seem to get the page loading without any style sheets loaded... and also when i click on any of the link i get a 404 and its seems like the context-root is something different then the initial page I landed on. It changes from **my-openid-connect-server** to **openid-connect-server-webapp**. Now I have gone through the project before and made all the paths match... and it started working. Though I was wondering am I doing something wrong? Shouldn't the example project work without me having to go and change the paths everywhere?

Thanks.

**Comment by hir0pr0tagonist** [comment]
I had the same problem. In the child project , you have to change the server-config.xml file (under src\main\webapp\WEB-INF) and adapt this tag:


		<property name="issuer" value="http://localhost:8080/your-cloned-openid-connect-server/" />

obviously adapting your-cloned-openid-connect-server to something sensible.
Hope this helps.
