### ISSUE TITLE
Getting an OPTIONS 401 error while calling the token end point after authorization from web app

### ISSUE THREAD

**Issue by dorg-niyer** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1421]
We are prototyping with Mitre OpenID-Connect to use it as a centralized IdP server that would serve multiple applications to provide common OpenId/OAuth authentication/authorization services. 

As part of the prototype, we have configured the OpenId Connect server & call from it from an sample Angular 6 application.  The OpenId Connect (IdP) server was brought up on localhost:8080 while the sample web app that redirects to the IdP server for authentication/authorization is brought up on localhost:4200.  The IdP server has been configured with a client with a redirect uri of http://localhost:4200/authorize

The Angular 6 application redirects to the IdP server login page correctly & goes through the authentication (i.e. checking & loading user profile based on the credentials) flow correctly. However, it is throwing a OPTIONS 401 error when it redirects back to the application. We tried configuring a custom CORS filter to circumvent the OPTIONS error but didn't help. I am attaching a screenshot of the error.

Apologize for bring this up as an issue, but I could not find any other forum that could provide an answer/solution. Will greatly appreciate any help.  Thanks in advance!

![options-401-error](https://user-images.githubusercontent.com/37546568/43661659-18af20b0-9731-11e8-9772-48c4da97033d.jpg)

Also, here is the client side code that calls the token end point:

    const body = new URLSearchParams();
    body.append('grant_type', 'authorization_code');
    body.append('code', code);
    body.append('redirect_uri', 'http://localhost:4200/authorize');
    body.append('client_id', environment.CLIENT_ID);
    const options = {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        'Access-Control-Allow-Origin': '*'
      }
    };

    return this.http.post<OAuthToken>(`${environment.IDP_BASE_URL}/token`, body, options).
      pipe(map(data => {
                          console.log('token = ' + data);
      }));
    }

**Comment by dorg-niyer** [comment]
We were able to resolve the issue by creating a custom web security configuration & overriding the default CorsFilter for the token end point. Closing this issue.

**Comment by exodussystem** [comment]
@dorg-niyer 

I encountered the same issue. After creating a custom web security configuration & overriding the default CorsFilter for the token end point like you mentioned above, it is still not working.
The client got 200 OK for the OPTIONS request but the POST is not shown. I suspect that Mitre OIDC does handle POST for /token endpoint.

I m using https://github.com/damienbod/angular-auth-oidc-client integrating with Mitre OIDC using Code + PKCE flow

From **_Angular App [localhost:3000]_** to **_STS [OIDC-ISSUER-URL]_**
```
[OIDC-ISSUER-URL]/authorize?
client_id=angular_code_client
&redirect_uri=https%3A%2F%2Flocalhost%3A3000
&response_type=code
&scope=openid%20profile
&nonce=N0.55639781033142241546880026878
&state=15468798618260.8857500931703779
&code_challenge=vBcZBGqBEcQAA3HYf_nSWy6jViRjtGQyiqrrZYUdHHU
&code_challenge_method=S256
```
The STS redirects back to the Angular application with the code and state.
```

http://localhost:3000/?
code=2ee056b556db7dcd5c936686c4b30056e7efd78046eb4e8d4f57c3f6cc638449
&scope=openid%20profile%20dataEventRecords%20securedFiles
&state=15468798618260.8857500931703779
```

However, it fails to POST to **_[OIDC-ISSUER-URL]/token_**
with form data

```
grant_type: authorization_code
client_id: angular_code_client
code_verifier: C0.8965378500073793157246352748415724635274840.61565522116883
code: 2ee056b556db7dcd5c936686c4b30056e7efd78046eb4e8d4f57c3f6cc638449
redirect_uri: http://localhost:3000
```

How did you overcome this issue?
