### ISSUE TITLE
PlainAuthRequestUrlBuilder ignores responseType

### ISSUE THREAD

**Issue by afousk** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1439]
Hi,

I came to notice that the `PlainAuthRequestUrlBuilder` is ignoring the response types set in the given `RegisteredClient`. It hardcoded sets the `response_type` parameter to _"code"_.

Is there a specific reason for this behavior that I have missed or is this just a bug?

**Comment by jricher** [comment]
This is intentional: the client library is a web-server-app and made for the code flow only, it doesn't know how to do implicit (which would require a javascript app, which this isn't), and even the hybrid flows would require a javascript component.
