### ISSUE TITLE
account disabled

### ISSUE THREAD

**Issue by jolina099** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1449]
I tried to enter the web but everytime it shows that "account disabled". The company don't know what happened and the IT confirmed that there's no login problem with my account. I don't know what happened and I'm looking for the solution. Someone could help me?

**Comment by jricher** [comment]
This sounds like a problem with your company's identity systems, not with the underlying IdP software which is what this github project is for. Contacting your IT support is the best route to find help with your company's instance.
