### ISSUE TITLE
jwk should return "use" element

### ISSUE THREAD

**Issue by vanwobe** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1454]
although it is optional, https://mitreid.org/jwk better return the "use" element.
This element is required by the spring-security-oauth. See also:
https://github.com/spring-projects/spring-security-oauth/pull/1348

**Comment by jricher** [comment]
If the generated key has the `use` element in it in the keystore, then it will be propagated by the server. The key example server on `mitreid.org` wasn't configured with that.

It is an error for spring-security-oauth to require the parameter.
