### ISSUE TITLE
What is the format of the sub identifier in the users.sql example?

### ISSUE THREAD

**Issue by crush83** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1461]
The users.sql for hsqldb has a sub of `90342.ASDFJWFA` by default for the admin account.

I was wondering if this format has a name. I thought at first it was some kind of pairwise identifier, but there is a table for that. Furthermore, it wouldn't make sense to have a 1:1 relationship with the id of the user if my understanding of PPID is correct.

I'd like to know more about what this format represents, and how I might go about generating subs in similar fashion.

Thanks.

**Comment by jricher** [comment]
It's a random string.
