### ISSUE TITLE
No client configuration found for issuer error

### ISSUE THREAD

**Issue by edmundday** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1464]
I am getting this error:
`ERROR 9800 --- [io-8080-exec-10] o.m.o.c.client.OIDCAuthenticationFilter  : No client configuration found for issuer: http:/myserver:8080/openid-connect-server-webapp/
`
Now I found this error message in the server but it is not hitting that as I added a display.
I am pretty sure there is a client with correct secret etc registered.

So can you point to me about how to debug this, as I cannot see any code in the simple-webapp that handles it.

**Comment by edmundday** [comment]
Server throws:
` SEVERE [http-nio-8080-exec-16] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [spring] in context with path [/openid-connect-server-webapp] threw exception
 org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized.
`

**Comment by jricher** [comment]
Your issuer URL is malformed, I believe it should be `http://myserver:8080/openid-connect-server-webapp/` (with two slashes)

**Comment by edmundday** [comment]
No sorry that was just a typo.

**Comment by edmundday** [comment]
I think maybe it is my boot version of simple-web-app not doing the normalization. Maybe.
