### ISSUE TITLE
midreid-oidc server support for Implicit and Hybrid OIDC flows

### ISSUE THREAD

**Issue by athulrl** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1475]
Could you please confirm whether midreid-oidc server has any recent changes for support implicit or hybrid flow? Or still it doesn't support those?

**Comment by dare2try** [comment]
I know for certain the implicit flow is supported... I'm not so certain about hybrid, but I can test it out and confirm.

**Comment by jricher** [comment]
Hybrid flows are not supported due to limitations in some of the underlying libraries. There are several issues filed to take out those dependencies but the work is substantial and hasn't been taken on yet.
