### ISSUE TITLE
Export all configuration and data to import to another installation

### ISSUE THREAD

**Issue by erev0s** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1481]
Hello
I would like to export all configuration and data that I have in one instance of the server running and import them to a different one. Is this possible, if yes could you please indicate how?

**Comment by dare2try** [comment]
Take a look here https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/API#data, this should effectively be what you need, but milage may vary.

**Comment by erev0s** [comment]
@dare2try thank you very much. Worked like a charm
