### ISSUE TITLE
Dynamic Client Registration - confirmation of official feature and support in the future

### ISSUE THREAD

**Issue by Barteus** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1487]
Dynamic Client Registration is not described in official documentation.

Can you confirm that Dynamic Client Registration is official feature and will not be removed?
We would like to construct solution based on this functionality and this information is essential for us.

**Comment by srmoore** [comment]
It is listed in the list of Currently supported features: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Features 

Since this is a reference implementation, I don't see that feature going away.

**Comment by Barteus** [comment]
Thanks, I must have missed it.
