### ISSUE TITLE
Extend ApproveSite with custom fields

### ISSUE THREAD

**Issue by kfirsztPgs** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1491]
Is it possible to extend ApproveSite entity & business logic to handle custom fields (e.g. custom1, custom2 etc) in context of remebering approved site by custom field.

We need to enhance "remember me" logic with one extra factor without the need to rewrite whole logic.

**Comment by jricher** [comment]
It's not an official extension point, but it should be fine for a local fork to do that, but you'd need to update the databases for storage as well as the import/export API if you plan to use it for local upgrades.
