### ISSUE TITLE
OIDC client in plain old Java Servlet programming model

### ISSUE THREAD

**Issue by krumft** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1523]
Hello,

Are there any plans to showcase in your project an OIDC client integration that hooks under plain old Java Servlet programming model? That would be extremely useful for OIDC client apps that are not designed to use the Spring ecosystem and cannot afford a full rewrite to Spring. Perhaps a good choice here would be to use the Servlet Filter as a pattern on how/where to place the OIDC client logic.

Thank you,
Krum.

**Comment by jricher** [comment]
The client library has been written as a Spring Security filter and we don't currently have plans to tie to plain Servlets ourselves.

**Comment by krumft** [comment]
Thank you for this clarification.
