### ISSUE TITLE
Build JWE Encryption/Decryption service

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#153]

**Comment by pkaival** [comment]
Hi, UserInfoJWTView supports both Signing and Encryption of response message at a time? 
As of now code for Encryption and Signing was mentioned in different if-else block, and for encryption it is checking for 'IdTokenEncryptedResponseAlg' it should refer 'userInfoEncryptedResponseAlg'. 
I want to apply both Signing and Encryption before sending user info response message.
Can you please guide me?

**Comment by jricher** [comment]
Please submit these comments as new, separate issues.
