### ISSUE TITLE
Set the correct principal name

### ISSUE THREAD

**Issue by mazenaissa** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1549]
The principal name is set in the form of {sub=......,issuer=....}
Can you please change the behavior to set the user name in the principal object, so authentication.getPrincipal() returns the username if it is an OIDCAuthenticationToken.
Thanks,

**Comment by jricher** [comment]
No, the username is a secondary field from the federation perspective. This is explained in the OIDC spec:

https://openid.net/specs/openid-connect-core-1_0.html#ClaimStability
