### ISSUE TITLE
Error while trying to launch application

### ISSUE THREAD

**Issue by thuann-vn** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1556]
My application return the error page while trying to launch an application? Could you help me to see why?
![image](https://user-images.githubusercontent.com/29191978/121826215-6a2f8c00-cc6b-11eb-8fb0-98524423ba72.png)

**Comment by jricher** [comment]
When you see an error like this, there's some kind of internal error like a server crash. As the text says, check your server's logs to see what's going on.
