### ISSUE TITLE
Email case in-sensitive

### ISSUE THREAD

**Issue by anandmohan777** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1558]
I have a scenario to make email case in-sensitive. Please suggest me to check in mitreid-connect email in lowercase like 

`select * 
from account 
where lower(email) := lower(inputEmail)`

or can I implement any filter like 

`	<security:authentication-manager alias="authenticationManager">
		<security:authentication-provider>
			??
		</security:authentication-provider>
	</security:authentication-manager>
`

**Comment by anandmohan777** [comment]
@jricher Any suggestions around this?

**Comment by shrexster42** [comment]
@anandmohan777 

You can use `users-by-username-query` to customize your query as below

```
<security:authentication-manager id="authenticationManager">
		<security:authentication-provider>
			<security:jdbc-user-service data-source-ref="dataSource" users-by-username-query=""/>
		</security:authentication-provider>
	</security:authentication-manager>
```
I also suggest to use stackoverflow for questions and open issues only if they are relevant to the project/code
