### ISSUE TITLE
Authentication with Client Secret Basic and Client Secret POST are interchangeable

### ISSUE THREAD

**Issue by jamietanna** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1563]
With a client registered with `client_secret_basic`, authenticating via `client_secret_post` succeeds:

```
curl 'http://localhost:8080/openid-connect-server-webapp/token' -d client_id=... -d client_secret=... -d grant_type=client_credentials
```

As does vice versa - being registered with `client_secret_post` but authenticating with `client_secret_basic`.

This may be intended - and I've seen some servers allow this - but thought I'd flag in case it's a problem.

**Comment by jricher** [comment]
This is intentional behavior from the server. The rationale being that in both cases, the client is using a client secret sent directly to the server, just sending it in different places.
