### ISSUE TITLE
OIDC certication website: No client configuration found for issuer

### ISSUE THREAD

**Issue by anderspitman** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1593]
I'm trying to use a custom OIDC provider to log in to the certification website (https://www.certification.openid.net), which I believe is backed by mitreid, but getting the following error:

There was an error logging you in: No client configuration found for issuer:

Initially I guessed there's something missing from my `./well-known/openid-configuration`, but that endpoint isn't even getting hit. Is there something special needed in my webfinger file beyond the basics?

Sorry if this is the wrong place to ask this.

**Comment by jricher** [comment]
You need to file this issue with the OpenID Foundation's certification team.
