### ISSUE TITLE
Use spring-configuration for entity manager (get rid of persistence.xml)

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#194]
More information here:

http://static.springsource.org/spring/docs/3.1.x/javadoc-api/org/springframework/orm/jpa/LocalContainerEntityManagerFactoryBean.html#setPackagesToScan%28java.lang.String...%29

**Comment by thomasmey** [comment]
Hi,

why did this commit disabled the EclipseLink shared object cache? Was this change intentional?

**Comment by jricher** [comment]
Yes, it was intentional. The server is often deployed in clusters, so the cache at that level was turned off to allow the server instances to share a database without consistency issues.
