### ISSUE TITLE
Structured Scopes

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#384]
Adopt structured scopes from BB+

**Comment by bodewig** [comment]
@jricher is there any pointer as to what "structured scopes" used to be? I've seen your comments in #1129 and know it hasn't been used widely. https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/API contains a few examples, but they don't really explain much.

For my current project I seem to be requiring something that could very well be similar to the "structured scopes" (called them hierarchical, though) and for now seem to be getting along with replacing `SystemScopeService`. For reference I'd like to see what other changes have been necessary while the feature lasted. My context won't require support for them inside the (admin) API at all.

**Comment by jricher** [comment]
Structured scopes were basically scope strings that were processed in a special way by the AS. They had a "base" string and then a variable "parameter" that was presented as "base:parameter" to the server. The client would register for the "base" string and be allowed to ask for any parameter, like "base:foo", "base:bar", etc. Each of these parameterized scopes would be considered a separte scope. The main difference was in allowing the client to ask for these, and the admin UI to allow that. You could also prompt the user for the parameter value during the authorization page, if the client didn't supply one.

**Comment by bodewig** [comment]
Yes, that's pretty close to what I have in mind. I would probably have missed the admin UI - as I haven't used that so far. Many thanks.
