### ISSUE TITLE
Add issuer fields and signature to refresh token JWTs

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#407]
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L128

**Comment by jricher** [comment]
Since these are only ever sent back to the AS, we don't really need the signature and issuer fields. Closing for now, may re-visit.
