### ISSUE TITLE
Implement access token assertion handling in JwtAssertionTokenGranter

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#411]
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/token/JwtAssertionTokenGranter.java

**Comment by kmkamruzzaman** [comment]
Leave a comment
jricher
thank you dear sir!
I have pleased for your kindness.i want to create your help support & an open id.
