### ISSUE TITLE
Make JSON object handling more robust

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#421]
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/openid/connect/view/UserInfoView.java#L100

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/openid/connect/view/UserInfoView.java#L206

**Comment by jricher** [comment]
I think this has been closed by various refactorings already.
