### ISSUE TITLE
Implement c_hash

### ISSUE THREAD

**Issue by aanganes** [mitreid-connect/OpenID-Connect-Java-Spring-Server#437]
ID tokens do not currently contain the c_hash field; we need to calculate this value and include it.

**Comment by ajadex** [comment]
Generating the `c_hash` was implemented, but there's no indication that it's been added to the JWT. The method `getCodeHash` is never invoked.

**Comment by jricher** [comment]
That's because we don't yet support the `code idtoken` response type that would use this.

**Comment by ajadex** [comment]
Make sense, thanks.
