### ISSUE TITLE
Clients with no registered scopes should produce a warning to users

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#499]
clients without registered scopes can ask for any scopes. This should produce a warning on the user's approval page, especially if the client is asking for non system scopes.

**Comment by col-panic** [comment]
As the current behaviour for users seems to be the same (it is not possible to define "registered scopes" for a user) I link this to https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/351
