### ISSUE TITLE
JWT authorization grant support

### ISSUE THREAD

**Issue by alimfeld** [mitreid-connect/OpenID-Connect-Java-Spring-Server#616]
Is there a plan to support the JWT authorization grant with an Identity assertion issued in another security domain (in conformance with http://tools.ietf.org/html/draft-ietf-oauth-jwt-bearer-09).

I had a look at https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/mitreid-connect-1.1.7/openid-connect-server/src/main/java/org/mitre/oauth2/token/JwtAssertionTokenGranter.java and it seems to me it only supports the use case with an ID token issued by the OIDC Server (together with an access token).

This would require prior exchange of key material between the identity assertion issuer and the OIDC Server in order for the OIDC Server to be able to verify the identity assertion.

**Comment by lomori** [comment]
Just to help pushing: this feature would be extremely useful to us for implementing SSO. We have a use case where users login to a legacy application and launch a "plugin" that communicates to some components that are secured through OAuth2. We can extend it to generate a signed JWT token which potentially could be exchanged (changes to plugin code required) by a MitreId access_token.

**Comment by jricher** [comment]
Version 1.3.x of the server now has hooks for implementing custom assertion processing
