### ISSUE TITLE
DefaultUserInfoUserDetailsService uses userInfo.getSub() instead of username

### ISSUE THREAD

**Issue by woltere** [mitreid-connect/OpenID-Connect-Java-Spring-Server#642]
spring-security requires the actual username that was used to login to be used in the User object.
currently the sub attribute is returned as the username breaking for example the UserCache. The User object is put in the cache with the sub attribute but is retrieved on the username entered.

---8<---------
http://docs.spring.io/spring-security/site/docs/3.1.6.RELEASE/apidocs/
public User(String username,
            String password,
...
Parameters:
username - the username presented to the DaoAuthenticationProvider
---8<---------

**Comment by jricher** [comment]
Class has been removed in 63dd7c0b2524df10a5c3b536d0906eba3ee2a94d
