### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by cupps101** [mitreid-connect/OpenID-Connect-Java-Spring-Server#660]
Hi, 
We have a requirement to provide a registration form so when the end user comes to our site he can begin registering his/her information (first/last name/userid and password), they then get logged in automatically and is redirected to their profile page provided with an openId URL for single sign on, as well as showing their profile information . We would like to use OpenID Java Server as IDP (OpenID-Connect-Java-Spring-Server). But, I had read on one of your threads that you guys don't support or use user management and the users are already pre-populated into the database. If we were to provide a registration page so the end user can register and then gets logged in by entering their firstname, lastname, usrename and password, could this be possible? I was thinking of creating a registration controller in an overlay and then login the user calling the login functionality used in the OpenID-Connect-Java-Spring-Server. But I ma not sure where to start. Please advise and let me know what the best step or procedure to take. 

Thanks,
Kevin

**Comment by sjlongland** [comment]
Hi,

Silly question, has there been any further thoughts on this?  I'm looking around for a replacement for CommunityID which has served me okay, but is only OpenID 1.0 (and slightly broken too, doesn't play nice with StackExchange for example) and is no longer supported.  ("Keyboard Monkeys", who produced it, seem to have evaporated.)

I managed to get MITREid (built from git HEAD this evening) going on a LXC instance with Tomcat 8 on Gentoo.  It looks good, but no username/password combination I can think of gets me in, it gives me a "403" error message every time.  I can't see a register link anywhere and I don't see any instructions on how to add users.  I'm using PostgreSQL as the back-end.

Not being particularly familiar to Spring, I'm finding the documentation for MITREid a little vague and I'm a little lost as to where to proceed next.  Is there some procedure I can run from the SQL command line that will inject a user for me to test with?

**Comment by praseodym** [comment]
Yes there is: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server-webapp/src/main/resources/db/users.sql

**Comment by sjlongland** [comment]
Ahh, thanks praseodym, however that script seems to be broken:
```
openid ~ # wget -O /tmp/users.sql https://raw.githubusercontent.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/master/openid-connect-server-webapp/src/main/resources/db/users.sql
--2015-12-21 04:30:59--  https://raw.githubusercontent.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/master/openid-connect-server-webapp/src/main/resources/db/users.sql
Resolving raw.githubusercontent.com... 103.245.222.133
Connecting to raw.githubusercontent.com|103.245.222.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2076 (2.0K) [text/plain]
Saving to: ‘/tmp/users.sql’

/tmp/users.sql                         100%[===========================================================================>]   2.03K  --.-KB/s   in 0s     

2015-12-21 04:31:01 (56.7 MB/s) - ‘/tmp/users.sql’ saved [2076/2076]

openid ~ # fg
su postgres -c 'psql mitreid'


mitreid=# \i /tmp/users.sql 
psql:/tmp/users.sql:5: ERROR:  syntax error at or near "FALSE"
LINE 1: SET AUTOCOMMIT FALSE;
                       ^
START TRANSACTION
psql:/tmp/users.sql:15: ERROR:  relation "users_temp" does not exist
LINE 1: INSERT INTO users_TEMP (username, password, enabled) VALUES
                    ^
psql:/tmp/users.sql:21: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/tmp/users.sql:26: ERROR:  current transaction is aborted, commands ignored until end of transaction block
psql:/tmp/users.sql:37: ERROR:  syntax error at or near "MERGE"
LINE 1: MERGE INTO users 
        ^
psql:/tmp/users.sql:43: ERROR:  syntax error at or near "MERGE"
LINE 1: MERGE INTO authorities 
        ^
psql:/tmp/users.sql:49: ERROR:  syntax error at or near "MERGE"
LINE 1: MERGE INTO user_info 
        ^
ROLLBACK
psql:/tmp/users.sql:58: ERROR:  syntax error at or near "TRUE"
LINE 1: SET AUTOCOMMIT TRUE;
                       ^
mitreid=# 
```

**Comment by praseodym** [comment]
The script is written for HSQLDB, but you can just edit it to work with PostgreSQL.

**Comment by sjlongland** [comment]
I think it needs more than an edit, it references a `users` table that doesn't exist in the PostgreSQL schema (https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server-webapp/src/main/resources/db/tables/psql_database_tables.sql).

The password seems to be stored in cleartext (!) in this schema too -- given how that practice is generally frowned upon in the IT security world, I have trouble believing this script is anything more than for use with the in-memory based HSQLDB backend intended for initial evaluation.

**Comment by praseodym** [comment]
Ah true, you need [security-schema.xml](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server-webapp/src/main/resources/db/tables/security-schema.sql) as well. But indeed, this is not something you should be using in production.

**Comment by break35** [comment]
Hi,
I have 2 questions, I would be appreciated if you can help me.
     1) Do you have any support or improvement about "User Management" in recent version?
     2) How can I add a user to a newly created client?

**Comment by preston** [comment]
Are there any other existing apps that implement this? I'd be great for people to have a go-to user management solution for standalone deployments, as opposed to all writing our own. Something similar to what Gluu does would probably be sufficient for most folks.
