### ISSUE TITLE
"prompt" error conditions not returned to client

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#667]
Error conditions for the "prompt" parameter are supposed to be returned to the client via redirect, but the server currently returns a 403 to the browser.

Needs to touch: PromptFilter, OAuthConfirmationController

**Comment by ngriesser** [comment]
would not it be enough to replace
response.sendError(HttpServletResponse.SC_FORBIDDEN, "Access Denied");
by
response.sendRedirect(authRequest.getRedirectUri() + "?error=login_required");
on line 131 of AuthorizationRequestFilter ?

**Comment by jricher** [comment]
That's fine for the prompt=none condition but isn't sufficient for others.

**Comment by ngriesser** [comment]
Would it be possible to integrate this change?
It would at least help people needing promt=none to check for existing authentication / consent.

**Comment by jricher** [comment]
this handling is done, leaving the issue open for the other parts of the overall problem

**Comment by ngriesser** [comment]
Thanks a lot :)
