### ISSUE TITLE
DynamicServerConfiguration Google

### ISSUE THREAD

**Issue by zeitiger** [mitreid-connect/OpenID-Connect-Java-Spring-Server#683]
org.mitre.openid.connect.client.service.impl.DynamicServerConfigurationService.OpenIDConnectServiceConfigurationFetcher 
had an issue to load iss "accounts.google.com" that https:// is missing an so the load failed. If a take as iss "https://accounts.google.com" than it failed because of a dismatch between iss parameter vs. iss from loaded configuration.

**Comment by morungos** [comment]
Any plans for these changes to make their way into some release? At the moment it's missing from all tagged versions as far as I can find.

**Comment by jricher** [comment]
Is this still required? Google's been doing work to make their implementation compliant, so this might be OBE now. Can someone test?

**Comment by morungos** [comment]
We'll try without, and see where we get. Suffice to say that https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Sample-Static-Configuration-for-using-Google-Authentication isn't working great for us yet.

**Comment by jricher** [comment]
I just successfully tried the client using a minimal configuration, without the "useNonce" parameter. It uses the issuer `https://accounts.google.com`, dynamic server configuration, and a static client configuration (keyed on the issuer above). I'm using the hybrid issuer service, but you need to send in the issuer as the `iss` parameter, not the `identifier` parameter for it to work there, thanks to some odd behavior in the Webfinger lookup.

I'll be removing the `useNonce` functionality from the code now that it's no longer needed to connect to a non-compliant service.

I'll also be sure to update the documentation for Google now that it's much simpler.

**Comment by morungos** [comment]
Great! Good to know we can use this directly. Thanks.

**Comment by jricher** [comment]
Documentation has been updated and the "nonceEnabled" hack has been removed from the code.
