### ISSUE TITLE
Authority mapper in RP should have access to user info

### ISSUE THREAD

**Issue by alimfeld** [mitreid-connect/OpenID-Connect-Java-Spring-Server#699]
The authority mapper used in [OIDCAuthenticationProvider](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/f974f9513854a72adb8bc1d38cd0dfd13fc02965/openid-connect-client/src/main/java/org/mitre/openid/connect/client/OIDCAuthenticationProvider.java) only has access to 'sub' and 'issuer'.

Granted authorities may be based on additional information returned from the user info endpoint (such as role/privileges information; see also discussion here: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/681).

I propose to also make the user info available to the authority mapper (e.g. by adding the user info to the [SubjectIssuerGrantedAuthority](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/f974f9513854a72adb8bc1d38cd0dfd13fc02965/openid-connect-client/src/main/java/org/mitre/openid/connect/client/SubjectIssuerGrantedAuthority.java)).

**Comment by jricher** [comment]
@alimfeld please check to see if the changes in d1e8529 are sufficient to carry this functionality.
