### ISSUE TITLE
When registering a new client, scope don't autocomplete (via mouse click)

### ISSUE THREAD

**Issue by jmandel** [mitreid-connect/OpenID-Connect-Java-Spring-Server#737]
Adding a new scope to a client, there's an autocomplete box. Keyboard shortcuts work, but clicking a scope does not -- and it fails in a misleading way.

E.g. 

1. I type `o`
2. Autocomplete 1st suggestion is `openid`
3. I click `openid`
4. A new scope is added called `o`

**Comment by michelemottini** [comment]
I ran into the exact same problem

**Comment by jricher** [comment]
Autocomplete now obsoleted by checkboxes, e963c3c1ecf083e975ad1fe9e00f9094c2dde57a
