### ISSUE TITLE
openid-connect-server-webapp: SQL table definition inconsistency

### ISSUE THREAD

**Issue by juan-m-medina** [mitreid-connect/OpenID-Connect-Java-Spring-Server#746]
As of commit in master branch ada1b0d24ea374cef77e19176282746a2d1451a1

---

The "User_Info" table defines "preferred_username" as a 256 character string. The "Users" table (and others) define "username" as a 50 character string.

Came accross an issue where the preferred_name ends up being set to something like "{sub=12346549878798764, iss=longblahblah.blah.com}", which in my case is over the 50 characters (still checking why this is the case).

Because of this, the server application fails to start due to a truncation error when handling the data. Not a huge issue, but something that may need fixing to avoid possible issues.

**Comment by PrivateMeggido** [comment]
Yes, that is correct, in this case the use is to make the server rely on another provider for Authentication, then use the library just for authorization.
As noted, this is not a major issue, but one that causes the provided application to fail. I will provide updates if I find the reason why, but the case here is that the server ends up assigning the preferred name from what looks to be an undesirable field when using Google for authentication.
