### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by ngriesser** [mitreid-connect/OpenID-Connect-Java-Spring-Server#748]
Hi,
Can the OpenID Connect Java Spring Server be clustered to achieve highly available authentication / authorization and business continuity?
Kind regards

**Comment by jricher** [comment]
Yes, both the server and the database components can be deployed in a cluster. I don't have direct personal experience in doing this but I know of several who have.

To cluster the server, you'll need to set up Spring in a clustered environment with session sharing, and Tomcat should have full support for that. The server code is written in a way that generally assumes a distributed environment.

To cluster the database, you'll need to switch to using MySQL (instructions in data-context.xml) and set up your replication there.

**Comment by ngriesser** [comment]
This is good news. Thank you.
