### ISSUE TITLE
Refresh tokens are not returned by token end point

### ISSUE THREAD

**Issue by karuatcsg** [mitreid-connect/OpenID-Connect-Java-Spring-Server#751]
Token end point is returning all but refresh tokens for a client that is supposed to issue refresh tokens. Please see a sample output from token end point

{
  "access_token" : "eyJhbGciOiJSUzI....",
  "token_type" : "Bearer",
  "expires_in" : 3599,
  "scope" : "email openid",
  "id_token" : "eyJhbGci..."
}

Do we need to do anything specific to obtain refresh tokens?

**Comment by jricher** [comment]
Yes, you must request the "offline_access" scope in order to obtain a refresh token.

**Comment by karuatcsg** [comment]
Thank you, that solved it. Now it is dropping id_token. How can we get id_token also?

**Comment by jricher** [comment]
To get the id token, you have to include the "openid" scope. To get both the id token and refresh token, you have to include both the "openid" and "offline_access" scopes in the request.

**Comment by karuatcsg** [comment]
Thank you, appreciate your help.
