### ISSUE TITLE
Client id comparation while processing referesh token request

### ISSUE THREAD

**Issue by mmkrystek** [mitreid-connect/OpenID-Connect-Java-Spring-Server#752]
Class: org.mitre.oauth2.service.impl.DefaultOAuth2ProviderTokenService, line 241
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/3e7ade9a67f6caf5fa96a97fe12573bea1bb9a30/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultOAuth2ProviderTokenService.java#L241

Both methods requestingClient.getClientId() and client.getClientId() return different instances of String object. In such case != operator returns true even if both strings contains the same value.
The condition should be changed to:
if (!requestingClient.getClientId().equals(client.getClientId())) {

**Comment by jricher** [comment]
You're right, that does look like it's a bug (and and old one at that).
