### ISSUE TITLE
Scope subsets problems

### ISSUE THREAD

**Issue by michelemottini** [mitreid-connect/OpenID-Connect-Java-Spring-Server#755]
My understanding is that the scopes defined here:
![image](https://cloud.githubusercontent.com/assets/1046280/6085837/1e7596cc-ae0b-11e4-8956-f0bd996c1d11.png)

are all the possible scopes for the client app - and that the app specifies the actual scopes it needs as part of the authorization process - but if the app specifies `user/*.read` the server returns an invalid scope error (even if `user/*.read` is a subset of `user/*.*`)

**Comment by jricher** [comment]
@jmandel : This is also a SMART issue, I believe, as this seems specific to the SMART scope handler. I've copied and referenced it on the SMART project.
