### ISSUE TITLE
Server always prompt the user to select a patient

### ISSUE THREAD

**Issue by michelemottini** [mitreid-connect/OpenID-Connect-Java-Spring-Server#756]
..event if there is no `launch\patient`' scope

**Comment by jricher** [comment]
This sounds like it might be something specific to the SMART overlay, @jmandel can you look at this?

**Comment by jmandel** [comment]
@michelemottini Thanks Michel - I've added smart-on-fhir/auth-server/issues/1 to capture this. Let's discuss there!

**Comment by jmandel** [comment]
@jricher Can you close this issue? (I don't have permission.)
