### ISSUE TITLE
Question: Availability of Getting Started and Status

### ISSUE THREAD

**Issue by lofidewanto** [mitreid-connect/OpenID-Connect-Java-Spring-Server#757]
Sorry for make a question in this issue tracker (I'm waiting for my access in the mailing list). 

1. Is there any "Getting Started" doc? With all the binaries that can be downloaded, instead of building my own package? Maybe in Maven Central, also for the webapp? 

2. Is this product production-ready? If I want to use it should I use the 1.1.x or 1.2 branch?

3. Does this product support LDAP / Active Directory? I saw this project https://github.com/mitreid-connect/ldap-openid-connect-server but found no doc...

Thanks a lot,
Lofi.

**Comment by jricher** [comment]
The mailing list gets stuck sometimes, I'll poke the list administrator. 

1. The best place for getting started is the [project wiki](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki), which has information about the [maven artifacts](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Maven-Dependency) linked right from the main page.

2. Yes, this software is used in production at a number of different organizations, and there's even [commercial support](http://bspk.io/) (customization, deployment, enhancements) available if you're interested. For a production instance, we say just use the 1.1 version currently, as the 1.2 version is in active development and is likely to break without notice. Additionally, there aren't any maven artifacts for the 1.2 version yet, so if you want to run the dev version you do have to build it yourself.

3. Yes, that project shows how to build an overlay for connecting the server (the production 1.1 branch in particular) to LDAP, for both user authentication and profile information. We haven't yet produced full documentation for this, but there are notes on maven overlays and server configuration in the project wiki.

**Comment by lofidewanto** [comment]
Thanks for your fast response.

I'll try to collect all the things I need and document the stuffs. I'll come back to you later.
