### ISSUE TITLE
unable to run simple-web-app with 1.2 version

### ISSUE THREAD

**Issue by jefimm** [mitreid-connect/OpenID-Connect-Java-Spring-Server#758]
Trying to experiment with the https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Sample-Static-Configuration-for-using-Google-Authentication but found out that the simple-web-app does not work with 1.2.0-SNAPSHOT - spring context org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: You cannot use a spring-security-2.0.xsd or spring-security-3.0.xsd or spring-security-3.1.xsd schema with Spring Security 3.2. Please update your schema declarations to the 3.2 schema.|Offending resource: ServletContext resource [/WEB-INF/spring/root-context.xml]

Suggestion -remove xsd version numbers

**Comment by jricher** [comment]
Yes, the spring configuration needs to be updated to Spring 3.2 in Simple Web App, not just in the configuration files but in the pom.xml dependencies as well. With those changes in place it will run under 1.2, and it will be updated once 1.2 is released. We might push a "1.2" branch of SWA to help people who are doing this.
