### ISSUE TITLE
suggestion to refactor OIDCAuthenticationProvider

### ISSUE THREAD

**Issue by jefimm** [mitreid-connect/OpenID-Connect-Java-Spring-Server#761]
I would suggest to refactor the OIDCAuthenticationProvider and extract reusable base class to allow custom role logic

```java

public abstract class OIDCAuthenticationProviderBase implements AuthenticationProvider {
    protected UserInfoFetcher userInfoFetcher = new UserInfoFetcher();

    @Override
    public Authentication authenticate(final Authentication authentication)
            throws AuthenticationException {

        if (!supports(authentication.getClass())) {
            return null;
        }

        if (authentication instanceof OIDCAuthenticationToken) {
            return getAuthentication((OIDCAuthenticationToken) authentication);
        }

        return null;
    }

    protected Authentication getAuthentication(OIDCAuthenticationToken token) {
        UserInfo userInfo = userInfoFetcher.loadUserInfo(token);

        if (userInfo == null) {
            throw new UsernameNotFoundException("failed to fetch user details");
        } else {
            if (!Strings.isNullOrEmpty(userInfo.getSub()) && !userInfo.getSub().equals(token.getSub())) {
                // the userinfo came back and the user_id fields don't match what was in the id_token
                throw new UsernameNotFoundException("user_id mismatch between id_token and user_info call: " + token.getSub() + " / " + userInfo.getSub());
            }
        }

        return handleUserInfo(userInfo, token);
    }

    protected abstract Authentication handleUserInfo(UserInfo userInfo, OIDCAuthenticationToken token);

    /*
 * (non-Javadoc)
 *
 * @see
 * org.springframework.security.authentication.AuthenticationProvider#supports
 * (java.lang.Class)
 */
    @Override
    public boolean supports(Class<?> authentication) {
        return OIDCAuthenticationToken.class.isAssignableFrom(authentication);
    }
}

**Comment by jricher** [comment]
You can add customized role logic by plugging in to the `GrantedAuthoritiesMapper` component. Users are by default given a SubjectIssuerGrantedAuthority that can then be used to map into more traditional spring `ROLE_` roles. Today, we use this to map everyone to `ROLE_USER` and specific named users (uniquely identified by their `iss`/`sub` pair) to `ROLE_ADMIN` as well. But any custom implementation of `GrantedAuthoritiesMapper` would be able to read the `iss`/`sub` values coming in and map them to other roles as required. 

If this isn't flexible enough for what you're trying to do, can you please help us understand what it is you're after? Thanks!

**Comment by jefimm** [comment]
The issue I'm trying to solve  is that in my app the returned Authorization object is different from the is OIDCAuthenticationToken and is based on both UserInfo and initial token, and more precisely - user email is used to look  for permissions.

**Comment by jricher** [comment]
OK, so you really want a custom auth provider (since the token's different) but would like to be able to re-use some components from the library. And it looks like this lines up with #699 as well, so we'll see if we can combine the two concerns.

**Comment by jefimm** [comment]
You may also take a look at the org.springframework.security.openid.OpenIDAuthenticationProvider and its use of authenticationUserDetailsService

**Comment by jricher** [comment]
Thanks for the pointer. The `UserDetailsService` ties you to Spring's `UserDetails` object model, which isn't necessarily the right path here. However, having it pluggable in a similar fashion is a good idea, so we'll likely end up with something similar.

**Comment by jricher** [comment]
@jefimm Please check d1e8529 to see if these changes expose enough hooks for your work. You should be able to override both the authorities mapper (which now sees the ID Token and the UserInfo) as well as the Authentication construction itself.

**Comment by ppawel** [comment]
I ended up here looking for a clean way to make `OIDCAuthenticationToken` play nice with Spring Security and especially with jHipster's default "current user login" logic which is:

```
public static String getCurrentUserLogin() {
        SecurityContext securityContext = SecurityContextHolder.getContext();
        Authentication authentication = securityContext.getAuthentication();
        String userName = null;
        if (authentication != null) {
            if (authentication.getPrincipal() instanceof UserDetails) {
                UserDetails springSecurityUser = (UserDetails) authentication.getPrincipal();
                userName = springSecurityUser.getUsername();
            } else if (authentication.getPrincipal() instanceof String) {
                userName = (String) authentication.getPrincipal();
            }
        }
        return userName;
    }
```

Principal in `OIDCAuthenticationToken` is a map, not sure why...

> The UserDetailsService ties you to Spring's UserDetails object model, which isn't necessarily the right path here.

But `OIDCAuthenticationToken` already is in Spring Security model (implements `Authentication`) so why not make it more Spring-friendly and have `getPrincipal` return something which is based on `UserDetails`?

**Comment by jricher** [comment]
The principal is a map because of the nature of the OIDC spec: the only guaranteed unique identifier for a user is a combination of `iss` and `sub`, and an `ImmutableMap` of those two fields gives us the desired stability.
