### ISSUE TITLE
Consider X-Frame-Options header to prevent clickjacking

### ISSUE THREAD

**Issue by jmandel** [mitreid-connect/OpenID-Connect-Java-Spring-Server#762]
The authorize screen in particular might want to  include a  X-Frame-Options header. Perhaps `SAMEORIGIN` or `DENY` would be a sane default value?

Details: https://tools.ietf.org/html/rfc6819#section-5.2.2.6

**Comment by jricher** [comment]
Seems reasonable, we'll look into incorporating that. Thanks!

**Comment by praseodym** [comment]
This one is fixed now that #822 is merged.
