### ISSUE TITLE
SimpleDateFormat isn't thread safe.

### ISSUE THREAD

**Issue by woltere** [mitreid-connect/OpenID-Connect-Java-Spring-Server#778]
SimpleDateFormat isn't thread safe.

I suggest dropping class DateUtil and instead use org.springframework.format.datetime.DateFormatter.

    DateFormatter formatter = new DateFormatter();
    formatter.setIso(DATE_TIME);
    DateFormat df = formatter.getDateFormat(Locale.ENGLISH);

The only difference would be that an invalid date would give an exception, not return null like the current implementation. I would prefer to fail the parsing of the datetime and not return null.

**Comment by woltere** [comment]
created pull request https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/779

**Comment by jricher** [comment]
closed by pull request #779
