### ISSUE TITLE
unable to access static resources when not deployed on localhost

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#782]
When I deploy openid-connect-server-webapp to a server not on localhost, I can access the home page but no css or javascript seems gets loaded. The weird thing is that *sometimes* the css and javascript do get loaded, and i cant figure out how to reliably reproduce this error.

I first get these errors in the console:
ReferenceError: $ is not defined
http://url.example.com:8080/openid-connect-server-webapp/
Line 40
ReferenceError: $ is not defined
http://url.example.com:8080/openid-connect-server-webapp/
Line 213

And when I have this problem, the Net panel of my browser debugger shows that it is trying unsuccessfully to retrieve the various css and javascript files from localhost:8080 instead of the domain where the openid-connect-server-webapp is deployed to.

The times that the css and js do get loaded, then no console errors but the NET panel shows aborted calls toh GET summary, and two OPTIONS calls to messages.json (also trying to reach localhost:8080 when the original URL accessed was not localhost).

Is this a configuration issue that I am overlooking somewhere?

**Comment by wikkim** [comment]
Interestingly, when I use the "back" and "forward" buttons in my firefox browser to the url that the openid-connect-server-webapp is on, then it appears that the css/js get loaded successfully (but not when i go to the URL directly).

**Comment by jricher** [comment]
Sounds like you've failed to set the `issuer` variable as described in the documentation: 

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Server-configuration#server-configxml

The positive results you're getting are likely due to cached copies showing up with the forward/backward processing in the browser.

**Comment by wikkim** [comment]
Ok, that was exactly it. My bad for overlooking something that was clearly documented..

I did see that configuration bit before, but I goofed somewhere along the way and the server.xml on the server was still pointing to localhost.

Thanks for the help and the quick response.
