### ISSUE TITLE
Can Mitreid-Connect be used with a federation of client RPs ???

### ISSUE THREAD

**Issue by jayonline9** [mitreid-connect/OpenID-Connect-Java-Spring-Server#785]

**Comment by jricher** [comment]
I don't understand the question: what do you mean by "a federation of client RPs"? If you mean "can the server be used with multiple RPs", then yes, definitely. Can you please clarify your question, perhaps with an example of what you're looking for?

**Comment by jayonline9** [comment]
I meant a federation or group of Service providers. A scenario where a group of service providers can share a single access token

**Comment by jricher** [comment]
Oh sure, the deployment of your resource servers tied to the authorization server is up to you. You can definitely share a single access token shared between multiple services, and then they can all verify the token back at the MITREid server (through introspection or reading the token itself). You can have one token that's good at multiple services and a client that's smart enough to talk to them all with that token. That said, the fewer places you use a single high-access token the less of an attack vector you have. Depending on your setup, you might want to have different scopes for each service, and if you're doing service chaining you might want to look into token redelegation as well (it lets one resource server fetch a sub-scoped token to access another resource server).
