### ISSUE TITLE
make /authorize accept cors requests

### ISSUE THREAD

**Issue by ngriesser** [mitreid-connect/OpenID-Connect-Java-Spring-Server#790]
What is the best way to enable cors for the /authorize endpoint? extend AuthorizationRequestFilter?

**Comment by jricher** [comment]
Just configure the included CORSFilter to sit in front of /authorize as well. That said, the /authorize page needs to be protected from cross-site scripting, so why would it need CORS settings in front of it? What are you trying to do?

**Comment by ngriesser** [comment]
we are calling a url via ajax 
the resource is protected by  the OIDCAuthenticationFilter

The positition where corsFilter is usually configured (after="SECURITY_CONTEXT_FILTER") is already occupied.

<security:http disable-url-rewriting="true" use-expressions="true"> 
		<security:form-login login-page="/login" authentication-failure-url="/login?error=failure" authentication-success-handler-ref="authenticationTimeStamper" />
		<security:intercept-url pattern="/**" access="permitAll" />
		<security:custom-filter ref="authRequestFilter" after="SECURITY_CONTEXT_FILTER" />
		<security:logout logout-url="/logout" />
		<security:anonymous />
		<security:expression-handler ref="oauthWebExpressionHandler" />
	</security:http>

**Comment by jricher** [comment]
I think I still don't quite understand your use case. You shouldn't ever be calling the authorization endpoint via AJAX because it requires direct user authentication and interaction. By doing so, you're likely bypassing the separation of security that OAuth and OIDC are built on.

**Comment by ngriesser** [comment]
You are right... we will try to put the resource behind oauth and not oidc...

**Comment by jricher** [comment]
Right: OIDC is for user login, OAuth is for API access. An OAuth client just needs to be able to send the user in a browser to the authorization endpoint and shouldn't ever access it directly. 

I'm closing this issue, feel free to re-open it if there are more questions.
