### ISSUE TITLE
Uma configuration

### ISSUE THREAD

**Issue by ross-freeman-jerichosystems** [mitreid-connect/OpenID-Connect-Java-Spring-Server#793]
The well known uma configuration replicates the base url for the rpt_endpoint, see example below:

"rpt_endpoint":"https://healthauth.org/https://healthauth.org/authz_request"

**Comment by jricher** [comment]
The `issuer` field is listed twice in this string:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/uma/openid-connect-server/src/main/java/org/mitre/discovery/web/DiscoveryEndpoint.java#L380
