### ISSUE TITLE
Regarding Protected resource 

### ISSUE THREAD

**Issue by VinothrajaJ** [mitreid-connect/OpenID-Connect-Java-Spring-Server#807]
I hope OIDC should map the client with the protected resource(PR) during client registration. The PR details should be added in the token. So that PR can verify the same in the token when client tries to access the same. Do we have this mapping in OIDC? First of all, do we need this to be implemented?

**Comment by jricher** [comment]
OpenID Connect (OIDC) as a protocol defines only one protected resource, the User Info Endpoint. This is "mapped" by use of the `openid` scope inside the token. There's not a mechanism in OAuth to tie to a specific resource in the token request apart from a scope.

**Comment by VinothrajaJ** [comment]
Thanks jricher.. we do have a menu under "developer"  self service protected resource registration. What is the purpose of it... If OIDC don't have a protected resource configured for the client.

**Comment by jricher** [comment]
That menu in MITREid Connect is to register protected resources that are able to do token introspection but not having tokens issued to them directly.

**Comment by VinothrajaJ** [comment]
As per your comment, OIDC registered client do use their access token to access other resource which are not registered (might be other client or API service). Only then they need to introspect right?
Does not this go against your previous comment ..quoting "OpenID Connect (OIDC) as a protocol defines only one protected resource, the User Info Endpoint. This is "mapped" by use of the openid scope inside the token. There's not a mechanism in OAuth to tie to a specific resource in the token request apart from a scope"..

Please correct if my missing something here...

**Comment by jricher** [comment]
The other protected resources would be the ones doing introspection, not the clients. The clients are accessing the protected resources. This is a little confusing because in order to do introspection, you need to authenticate to the server, which requires a "special client" in the server's registration. This still doesn't tie a specific resource to a specific token. The resource introspects the token to find out if it has the right scopes (and other properties) in order for it to fulfill the request.

**Comment by kakashi2018** [comment]
Hi Richer,
Can you suggest me some links for self service protected resource registration which is under developer in mitreid. Couldn't find any use cases or anything related to it.
