### ISSUE TITLE
ldap overlay, email_verified is false

### ISSUE THREAD

**Issue by patfrat** [mitreid-connect/OpenID-Connect-Java-Spring-Server#809]
Hello, 

i have succesfully installed an instance of OpenID Connect server with ldap overlay and mysql persistence. Then i have configured a Wordpress with an openid plugin to connect users through OpenID server.

But the callback on wordpress tell me this:
Your email address has not been verified with your provider.

How to fix this with a LDAP user backend ?
Is it a MitreID issue or not ?

thanks in advance !

**Comment by patfrat** [comment]
I see in ldap overlay in this file
https://github.com/mitreid-connect/ldap-openid-connect-server/blob/master/ldap-server-overlay/src/main/java/edu/mit/kit/repository/impl/LdapUserInfoRepository.java

if this domain also provisions email addresses, this should be set to true

row 69:
```java
// email address
if (attr.get("mail") != null) {
	ui.setEmail(attr.get("mail").get().toString());
	// if this domain also provisions email addresses, this should be set to true
	ui.setEmailVerified(false);
}
```

So i have to change manually this source code to have my email_verified true with my ldap openid connect server ?

**Comment by patfrat** [comment]
It could be great to have this value configurable in user-context.xml !

**Comment by jricher** [comment]
Yes, at the moment you'll need to change the source code to get different behavior. If you'd like to submit a pull request to make it configurable, we'll look at it and pull it in.

**Comment by patfrat** [comment]
ok thanks ! i will try to do it configurable !
