### ISSUE TITLE
Documentation: Gradle War Overlay

### ISSUE THREAD

**Issue by jimmytheneutrino** [mitreid-connect/OpenID-Connect-Java-Spring-Server#814]
Hi, I accidentally (did not expect that I was allowed to) added a page describing how to create a war overlay project using Gradle. 
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Gradle-Overlay-How-To

Anyway, perhaps, it could be linked from the main Wiki page?

**Comment by jricher** [comment]
Thanks for the documentation! I've linked it from the Maven Overlay page.
