### ISSUE TITLE
Partially overriding messages.json

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#817]
Would it be possible to partially override `messages.json` in a WAR overlay, i.e. without creating a verbatim copy of unchanged messages in the file?

**Comment by jricher** [comment]
At the moment, not really -- the localization system currently pulls in only a single file. That said, you could always create a "custom" locale with your additional or changed messages, and the software will automatically fall back to the english translation.

**Comment by praseodym** [comment]
Creating a custom locale sounds like a fair workaround, as far as I can see there is no locale detection going on at the moment?

**Comment by jricher** [comment]
That's correct, the locale is configured entirely by the ConfigurationPropertiesBean object, everything else is currently based on that for both the Java system and the JavaScript system. We don't have enough translations to make automatic locale detection worthwhile.

**Comment by strangeweaver** [comment]
This could also be done by specifying your own MessageSource and making the org.mitre.openid.connect.config.JsonMessageSource it's parent message source.

**Comment by jricher** [comment]
You can now do this by setting the "languageNamespaces" property on the configuration bean and adding your own JSON files to the locale directory.

For instance, if you wanted to add a local set of strings "foo" in your overlay, you set the namespace property to `["foo", "messages"]` and create `en/foo.json` next to `en/messages.json` in the directory structure.

**Comment by praseodym** [comment]
Cheers :)
