### ISSUE TITLE
Switch to better connection pool

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#821]
We should consider switching to [HikariCP](https://github.com/brettwooldridge/HikariCP), which is a faster and more stable (and overall nicer) connection pool than Apache DBCP.

Furthermore, we can use JBDC4.1 drivers when the connection pool is upgraded (either to HikariCP or a newer DBCP version).

I'd be willing to submit a pull request if it has a chance of being merged.

**Comment by jricher** [comment]
I've got no particular attachment to the current connection pool layer. If I'm reading this right, it would be effectively a drop-in replacement? The JDBC and JPA layers wouldn't need to change at all, right? My concern is continuing support for deployed MySQL and HSQL databases, so existing JDBC drivers would need to work with it.

**Comment by praseodym** [comment]
It should be drop-in replacement, only the Spring datasource bean configuration will change slightly. That's easy to document though.

**Comment by jricher** [comment]
OK, that sounds reasonable to me. Please drop another pull request with that configuration and I'll review it for inclusion into the main branch.

Thank you!

**Comment by praseodym** [comment]
Cheers!
