### ISSUE TITLE
How to access UserInfo from IntrospectionAuthorityGranter

### ISSUE THREAD

**Issue by httpants** [mitreid-connect/OpenID-Connect-Java-Spring-Server#828]
Hi All,

This is my first post here so i'd firstly like to thank the team that have developed the OpenID-Connect-Java-Spring-Server.  I have been through an evaluation process for openid connect servers and this is by far the best solution i have seen.  The use of the war overlay is brilliant and makes for very easy customization.

I am at the point now of deploying a stand alone resource server that needs to accept a Bearer token and authorize a client to secure some restful endpoints.  I have configured the introspectingService and have got the authentication of the token working as expected.  I now want to assign more fine grained roles to the user, so have implemented my own IntrospectionAuthorityGranter.

I initially hoped that the UserInfo would be passed into the public List<GrantedAuthority> getAuthorites(JsonObject introspectionResponse) method.  But that was probably misunderstanding on my part.  The object i'm receiving looks like this...

{"active":true,"scope":"phone openid address email profile","expires_at":"2015-05-29T14:24:11+1000","exp":1432873451,"sub":"1017713335","user_id":"1017713335","client_id":"clubapp","token_type":"Bearer"}

I want to assign roles based on the UserInfo, so was wondering what should I do from here?  I was thinking maybe I can inject some service into the IntrospectionAuthorityGranter that could perform a UserInfo request and then assign the roles from the UserInfo response?

I'm basically after some advice here.  Perhaps the outcome of this could be a new InstrospectionAuthorityGranter implementation class (called UserInfoAuthorityGranter?) that could be used for this purpose?

**Comment by jricher** [comment]
The Token Introspection call is used by *protected resources* to determine what a token is good for, and it's defined here (you'll see the JSON structure that you're getting there): 

https://tools.ietf.org/html/draft-ietf-oauth-introspection

The UserInfo call is used by *clients* to get attributes about the current user, and it's defined here:

http://openid.net/specs/openid-connect-core-1_0.html#UserInfo

The authorization server serves both endpoints, but they're used for different things by different parts of the system. However, for your purposes, I would recommend customizing the IntrospectionResultsAssembler on the server. This is the default implementation, for reference:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-server/src/main/java/org/mitre/oauth2/service/impl/DefaultIntrospectionResultAssembler.java

On line 89, you can see that you'll (sometimes) have access to the UserInfo object. You could either add the UserInfo into the result here and have your protected resource do the rights processing based on that, or you could have the auth server process the UserInfo and inject a role or other claim that the protected resource can read. It all depends on how centralized you want that decision to be, but I think the latter is cleaner and more in the spirit of token introspection. 

Bear in mind that the UserInfo object contains potentially privacy-sensitive user information, so you might not want to pass all of it around all the time.

**Comment by praseodym** [comment]
I'm wondering how the following would work. Say we have a webapp that is an OIDC client that has access to UserInfo. Now, we also want to have a mobile app, and for that we extend the webapp with an OIDC protected API (i.e. a resource server). The mobile app will then function as the OIDC client, and will get a token and UserInfo when a user logs in. To access the API, it passes its token to our resource server. Now, how would the resource server know who the user is? Because we can't fully trust the mobile app, we cannot pass required UserInfo values through the API. I'd say the resource server would thus need access to the UserInfo, or is there a better solution?

**Comment by jricher** [comment]
You'll have access to at least the user's unique identifier and set of scopes, and if that's not enough, I would recommend extending the introspection response with a custom assembler as suggested above.  You certainly can't trust the mobile app to pass this information directly, it should be pulled from the context of the token. It's more than likely, though, that only some fields from the userinfo would be needed. Right now, the server spits out the subject value and the username, but a custom assembler can add other extension fields that your resource servers know to look for.

**Comment by httpants** [comment]
I've successfully made the changes so that the introspection response includes the userinfo.  It turned out to be very simple to do.  I created a CustomIntrospectionResultAssembler class...

```java
@Service("introspectionResultAssembler")
public class CustomIntrospectionResultAssember extends
		DefaultIntrospectionResultAssembler implements
		IntrospectionResultAssembler {

	@Override
	public Map<String, Object> assembleFrom(
			OAuth2AccessTokenEntity accessToken, UserInfo userInfo) {
		Map<String, Object> result = super.assembleFrom(accessToken, userInfo);
		result.put("userinfo", userInfo);
		return result;
	}

	@Override
	public Map<String, Object> assembleFrom(
			OAuth2RefreshTokenEntity refreshToken, UserInfo userInfo) {
		Map<String, Object> result = super.assembleFrom(refreshToken, userInfo);
		result.put("userinfo", userInfo);
		return result;
	}
}
```

Then I just overrode the local-config.xml file to make spring scan that component...

```
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:mvc="http://www.springframework.org/schema/mvc"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:tx="http://www.springframework.org/schema/tx"
	xmlns:context="http://www.springframework.org/schema/context"
	xmlns:security="http://www.springframework.org/schema/security"
	xmlns:oauth="http://www.springframework.org/schema/security/oauth2"
	xsi:schemaLocation="http://www.springframework.org/schema/security/oauth2 http://www.springframework.org/schema/security/spring-security-oauth2-2.0.xsd
		http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.2.xsd
		http://www.springframework.org/schema/security http://www.springframework.org/schema/security/spring-security-3.1.xsd
		http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.2.xsd
		http://www.springframework.org/schema/tx http://www.springframework.org/schema/tx/spring-tx-3.2.xsd
		http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-3.2.xsd">

   <!-- Scan the CustomIntrospectionResultAssembler -->
   <context:component-scan base-package="com.virginaustralia.oauth2.service.impl"/>

</beans>
```

That's it.  Now in my IntrospectionAuthorityGranter, the JsonObject includes the userinfo and i can assign roles accordingly.

**Comment by jricher** [comment]
Excellent, glad it works! Feel free to submit your userinfo-based assembler as a pull request, if you think it's general enough.

**Comment by praseodym** [comment]
I would certainly appreciate having this included :smiley:
