### ISSUE TITLE
scope validity is checked before grant type

### ISSUE THREAD

**Issue by wikkim** [mitreid-connect/OpenID-Connect-Java-Spring-Server#831]
The token endpoint will tell me whether my requested scope is invalid even if I use an unauthorized grant type.

I think clients should not get to know scope validity without being authorized to use the token endpoint first.

**Comment by jricher** [comment]
Scopes are tested before grant types are tested. If it were the other way around you'd get the opposite effect, where you'd be able to find out invalid grant types even while asking for the wrong scopes. I'm not sure there's a good way to do both.

**Comment by wikkim** [comment]
My issue was with unnecessary information leakage but apparently having specific error responses *is* prescribed in the specs but not necessarily in any order: https://tools.ietf.org/html/rfc6749#section-5.2

I'm not convinced this is a significant issue anymore, closing.
