### ISSUE TITLE
Scope-based IntrospectionAuthorityGranter

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#835]
If we have a sensitive resource, we might not want to give every client access to it. It seems like the best way to accomplish this would be introducing special scope. The resource server could then check if this scope is set in its IntrospectionAuthorityGranter.

Is this something that would be useful to implement in the openid-connect-client codebase, in addition to the SimpleIntrospectionAuthorityGranter?

**Comment by jricher** [comment]
Yes, that would be very useful. It was on our roadmap when we wrote the original introspection services but it ended up not getting used. (The client code in question just checked the scope directly instead of using Spring's Authorities system.)
