### ISSUE TITLE
openid-connect-client 1.1.16 does not support Server Name Indication (SNI) 

### ISSUE THREAD

**Issue by httpants** [mitreid-connect/OpenID-Connect-Java-Spring-Server#838]
Hi All,

In our environment we have an apache httpd server sitting in front of tomcat which is hosting the openid connect server.  The apache httpd server has a single IP address, multiple virtual hosts configured (one of which is the openid connect server) and a unique SSL certificate configured for each virtual host.

This causes a problem when the openid connect server is not the first virtual host and we try to call the introspection endpoint using openid-connect-client 1.1.16.  It uses the SystemDefaultHttpClient class from the HttpClient library, which doesn't support SNI, so when attempting to authenticate a token, we see errors like this in the log file...

```
[          http-bio-9090-exec-5] IntrospectingTokenService      ERROR validateToken
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://login.va.com/velocity/introspect": Certificate for <login.va.com> doesn't match any of the subject alternative names: [club-test.va.com]; nested exception is javax.net.ssl.SSLException: Certificate for <login.va.com> doesn't match any of the subject alternative names: [club-test.va.com]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:534)[spring-web-3.2.13.RELEASE.jar:3.2.13.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:482)[spring-web-3.2.13.RELEASE.jar:3.2.13.RELEASE]
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:327)[spring-web-3.2.13.RELEASE.jar:3.2.13.RELEASE]
	at org.mitre.oauth2.introspectingfilter.IntrospectingTokenService.parseToken(IntrospectingTokenService.java:199)[openid-connect-client-1.1.16.jar:]
	at org.mitre.oauth2.introspectingfilter.IntrospectingTokenService.loadAuthentication(IntrospectingTokenService.java:249)[openid-connect-client-1.1.16.jar:]
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:70)[spring-security-oauth2-2.0.0.M2.jar:]
```
I have seen that the master version of the IntrospectingTokenService uses the HttpClientBuilder class instead of the SystemDefaultHttpClient.  I’ve tested this and It works and resolves the SSL cert hostname issue.  

My question is, when is the next release expected since it's hard for us to use a SNAPSHOT version of a jar file in production.  I notice the 1.1.16 release was very recent so am thinking the next one might  be a few months away?

**Comment by jricher** [comment]
The 1.2.0 base release is a month or two away, maybe less depending on if we can get a few key features in place and tested.

**Comment by praseodym** [comment]
I think the problem here is that [HttpClient < 4.3.2 doesn't support SNI](https://issues.apache.org/jira/browse/HTTPCLIENT-1119), and the 1.1.x branch is using 4.2.3. Upgrading that dependency might just fix the problem without code changes.

**Comment by jricher** [comment]
Correct, and we try not to change dependencies unless there's a very compelling reason to do so, and even then we try to make sure that it's a transparent and backwards compatible change. I recall there being some code changes required in upgrading that library, but I'll see what it takes to backport this change to the stable branch. Can you confirm everything works as desired against the 1.2 revision?

**Comment by praseodym** [comment]
You might be fine with just a dependency upgrade because [some features have been deprecated but not removed](https://hc.apache.org/news.html#a12_September_2013_-_HttpComponents_HttpClient_4.3_GA_released). Not sure if this is something that needs to be backported to 1.1.x if it can be fixed in a local override.

**Comment by jricher** [comment]
If someone can confirm that SNI works with the 1.2 branch (which is using the 4.3 version of the library), then I'll investigate a backport it to 1.1.

**Comment by httpants** [comment]
Sorry for the delay in responding.  Firstly i did already test just upgrading the HttpClient dependency before.  The problem is the actual code is using the SystemDefaultHttpClient  which is deprecated but still exists in HttpClient 4.3.2, so upgrading that library alone doesn't solve the problem.  It's the code change in the 1.2 branch where it uses HttpClientBuilder instead of SystemDefaultHttpClient that fixes the SNI issue.  I can also confirm using the 1.2 branch version did resolve the issue.  If this change could be backported that would be awesome.

**Comment by jricher** [comment]
We've backported the changes with no noticeable ill effects in limited testing (and it matches the 1.2 branch which is known to work). Closing the issue, this will be in the next release.

**Comment by lgangloff** [comment]
SNI still doesn't work with 1.1 branch. 
As you can see, 1.1 branch still references SystemDefaultHttpClient instead of HttpClientBuilder : https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/1.1.x/openid-connect-common/src/main/java/org/mitre/jwt/signer/service/impl/JWKSetCacheService.java#L108

**Comment by jricher** [comment]
Looks like we missed one, thanks for pointing it out! This will be in the next release.

**Comment by jricher** [comment]
Thanks for the pull request, we should have an updated 1.1 release in the near future.
