### ISSUE TITLE
Documentation for LDAP overlay

### ISSUE THREAD

**Issue by uberfirestone** [mitreid-connect/OpenID-Connect-Java-Spring-Server#840]
I wanted to file this under the ldap-openid-connect-server project but didn't have the option available. Anyways I'm trying to set up this server for evaluation. However, when I try to start the service within tomcat, I'm greeted with errors pertaining to the ldap-related variables in user-context.xml.

I currently have it reading ldap.url, ldap.base, & ldap.server from a properties file. Do you have any docs or guidance on what these variables need to be set to?

**Comment by praseodym** [comment]
`ldap.url` and `ldap.server` should be the same. For LDAP with SSL, use something like `ldaps://ldap-server.example.com`. `ldap.base` is the LDAP base DN, something like `dc=mycompany,dc=example`. I also needed to edit the `userDnPatterns` pattern to match our LDAP setup.
