### ISSUE TITLE
Error while connecting to openid server

### ISSUE THREAD

**Issue by itslogan4u** [mitreid-connect/OpenID-Connect-Java-Spring-Server#841]
Hello,

I am getting the following error when I try to redirect the client application to open id provider.

This request requires HTTP authentication (Authentication Failed: No issuer found.).

I am able to see the JSON response when I launch http://xx.xx.xx.xx:9023/openid-connect-server-webapp/.well-known/openid-configuration

I am using dynamic client registration. Please help me to resolve the issue

**Comment by jricher** [comment]
There are many things that could be going wrong with this setup. Are you sure your server is functioning? Is the issuer URL correct in the openid-configuration JSON document above? Which issuer service are you using to discover the server, and how are you passing the values to it?

**Comment by itslogan4u** [comment]
Yes the server is working properly and able to login to the server. Issuer URL configured on server-config.xml file is proper.

I have not changed anything from openid-connect-client project and modified only the issuer URL in login.jsp file from client application.

Only difference is I have used domain name instead of tomcat server ip and port also changed to 9023.

**Comment by jricher** [comment]
I don't really know what's happening then. The error is coming from whatever `IssuerService` you have configured. Check the logs for the client application and see if you can find out something from there.

**Comment by sdcuike** [comment]
I also have this error.

**Comment by jricher** [comment]
Then you also probably have a misconfiguration in the issuer service or in the server itself. Without more detail we can't help.
