### ISSUE TITLE
Push new update to Maven?

### ISSUE THREAD

**Issue by Jiar** [mitreid-connect/OpenID-Connect-Java-Spring-Server#842]
Hello,

The class `ConnectOAuth2RequestFactory` imports a class called `org.springframework.security.oauth2.provider.DefaultOAuth2RequestFactory`

The class' location apparently changed to `org.springframework.security.oauth2.provider.request.DefaultOAuth2RequestFactory` 
But in the version 1.1.16 the import wasn't changed. I'm sure there are other changes that aren't in v1.1.16. It would be nice to have the newer version pushed.

Thank you in advance,
Jiar

**Comment by jricher** [comment]
We can't change the dependency of Spring Security OAuth for 1.1.16 or below because that would require pulling in an entirely new version of Spring and Spring Security with it, which would break lots of things.

**Comment by jricher** [comment]
That said, we're working on the 1.2.0 release which will have the updated library dependency.
