### ISSUE TITLE
Add parameter to the token request

### ISSUE THREAD

**Issue by ashernave** [mitreid-connect/OpenID-Connect-Java-Spring-Server#845]
Hi,

The openid connect server that I contact expects 'realm' parameter to be added to the token request in code exchange scenario. Currently the client lib doesn't allow this kind of extensibility, unlike the auth request.
As I understand, there are additional IETF specs that support it.

Thanks,
ashernave

**Comment by jricher** [comment]
This functionality is supported in the current master branch (version 1.2.x) but not the production branch. It will not likely be backported. See #803 for more information.
