### ISSUE TITLE
Failed to convert property value of type 'org.mitre.uma.util.ExternalLoginAuthoritiesMapper' to required type 'org.mitre.openid.connect.client.OIDCAuthoritiesMapper' for property 'authoritiesMapper'

### ISSUE THREAD

**Issue by ross-freeman-jerichosystems** [mitreid-connect/OpenID-Connect-Java-Spring-Server#850]
deployment of the UMA webapp server fails on glassfish when attempting to create beans from the user-context.xml.  Stack trace included below, but key line in title.

OS : CentOs 7
Web Server : GF 4.1
JDK: 1.7

[2015-06-22T10:37:22.724-0500] [glassfish 4.1] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=355 _ThreadName=admin-listener(47)] [timeMillis: 1434987442724] [levelValue: 1000] [[
  Exception while loading the app : java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.filterChains': Cannot resolve reference to bean 'org.springframework.security.web.DefaultSecurityFilterChain#16' while setting bean property 'sourceList' with key [16]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.web.DefaultSecurityFilterChain#16': Cannot resolve reference to bean 'externalAuthenticationFilter' while setting constructor argument with key [4]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalAuthenticationFilter' defined in ServletContext resource [/WEB-INF/user-context.xml]: Cannot resolve reference to bean 'externalAuthenticationManager' while setting bean property 'authenticationManager'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalAuthenticationManager': Cannot resolve reference to bean 'externalAuthenticationProvider' while setting constructor argument with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalAuthenticationProvider' defined in ServletContext resource [/WEB-INF/user-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.ConversionNotSupportedException: Failed to convert property value of type 'org.mitre.uma.util.ExternalLoginAuthoritiesMapper' to required type 'org.mitre.openid.connect.client.OIDCAuthoritiesMapper' for property 'authoritiesMapper'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [org.mitre.uma.util.ExternalLoginAuthoritiesMapper] to required type [org.mitre.openid.connect.client.OIDCAuthoritiesMapper] for property 'authoritiesMapper': no matching editors or conversion strategy found]]

**Comment by jricher** [comment]
Looks like this is fallout from the changes in d1e8529a7b23bb07e8d1d17613b0d2350a72e185 that weren't propagated to the UMA branch.
