### ISSUE TITLE
Pre-check login_hint against known users

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#851]
Right now the login form takes any login hint and drops it blindly into the form, whether it's a username or not. By default we should pre-check to see if it's a valid username, but perhaps allow that to be turned off for security purposes.

**Comment by praseodym** [comment]
I would be against this since [it is a security risk](https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)) and it probably isn't even possible to implement this for most authentication backends.

**Comment by jricher** [comment]
Yeah, the username scanning is exactly the security problem I alluded to above, and it's a real threat. The real problem here is a usability one, where a dumb-ish client can drop a value into the form that the user needs to clear out before logging in. I'm going to research what Google and other implementations do with this data.

**Comment by jricher** [comment]
Made this a pluggable service. Default version strips out login hints that start with HTTP, but there's one that checks for users that you can add in if you want.
