### ISSUE TITLE
Does Java Api doc build successful?

### ISSUE THREAD

**Issue by lavadiablo** [mitreid-connect/OpenID-Connect-Java-Spring-Server#855]
Following url such as
http://mitreid-connect.github.io/openid-connect-common/index.html is empty.
I am using Chrome, is it the cause?

**Comment by jricher** [comment]
That URL is not empty for me, using Firefox.

**Comment by dfcoffin** [comment]
Not empty for me either, using Chrome (Version 43.0.2357.130 m).

![image](https://cloud.githubusercontent.com/assets/1829699/8434532/e939700c-1f19-11e5-84ab-13b8ddb75370.png)

**Comment by praseodym** [comment]
But there's no actual javadoc, is there?

**Comment by dfcoffin** [comment]
The website contains JavaDoc files as indicated below:

![image](https://cloud.githubusercontent.com/assets/1829699/8434799/ab2b6732-1f1b-11e5-9ca2-57be14ace65d.png)

To reach them click on "Project Reports" in the menu column on the left.  The above screen appears, which allows you to then click on the JavaDoc report.

**Comment by praseodym** [comment]
You're right, should've taken another coffee before commenting :)

**Comment by lavadiablo** [comment]
Thanks. I remembered it was easier to find java doc before. The issue is closed. It is better that index page can display more meaningful content.

**Comment by jricher** [comment]
These pages are all auto-generated using mvn:site, including the relatively spartan index page.
