### ISSUE TITLE
Friendly error pages

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#858]
Currently, 404 and 500 errors get served the application server's error page instead of a friendly error page.

**Comment by jricher** [comment]
Which ones? There's a friendly error page handler, but it might not be hooked up to everything.

**Comment by praseodym** [comment]
SAML SSO exceptions in our case. It should be hooked up in web.xml to catch all exceptions, but 404 is definitely missing.
