### ISSUE TITLE
DB migration from 1.1 to 1.2

### ISSUE THREAD

**Issue by almalki** [mitreid-connect/OpenID-Connect-Java-Spring-Server#859]
Hi,

In v1.1 of the server there are three columns of type blob in (authentication_holder, client_authority and authorization_code) tables which were apparently removed from v1.2. How this binary data going to be migrated from v1.1 to v1.2?

Also, is there a plan to provide migration scripts between the two versions?

Thanks for the time you spend on writing this great piece of software..

**Comment by jricher** [comment]
From version 1.2 onward, the only supported upgrade path will be to use the data migration API:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Upgrading-1.0-to-1.1#data-importexport

This API will export the binary data from 1.1 into JSON objects which will then be re-imported and rebuilt in 1.2 with the appropriate objects there. 

There will not be a data migration .sql script provided from from 1.0 or 1.1 to 1.2 for this reason, but we will document the difference in the table structure for those who need to do the updates by hand.

**Comment by jricher** [comment]
The upgrade script has been dropped from the codebase and there are new update instructions (based from the old ones):

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Upgrading-to-1.2
