### ISSUE TITLE
MySQL syntax incorrect

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#860]
When running mysql_database_tables.sql listed under ../openid-connect-server-webapp/src/main/resources/db/tables/mysql_database_tables.sql,  there is an extra comma at end of line 315 that should not be there; causing errors on running SQL command.

**Comment by jricher** [comment]
Looks like that happened in ee9413b88261985a60ab6ff1fca3a3069ccad99b, HSQL is more liberal with its table syntax so we didn't notice in testing.
