### ISSUE TITLE
Using mitreid-connect with a backend Oracle DB

### ISSUE THREAD

**Issue by kochsen** [mitreid-connect/OpenID-Connect-Java-Spring-Server#861]
We are using mitreid-connect with a backend Oracle database. To create the database I used the MySQL scripts and converted them into Oracle. I have been troubleshooting with our developer and slowly getting pages to work. Right now we are unable to write/save data in the admin console for new clients, scopes, etc. The current error we are getting is:

==> catalina.out <==
[EL Warning]: 2015-07-08 10:15:43.245--ClientSession(126455678)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

Error Code: 923
Call: SELECT LAST_INSERT_ID()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="SELECT LAST_INSERT_ID()")

==> localhost.2015-07-08.log <==
Jul 08, 2015 10:15:43 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [spring] in context with path [/openid-connect-server-webapp] threw exception [Request processing failed; nested exception is javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.1.v20130918-f2b9fc5): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

Error Code: 923
Call: SELECT LAST_INSERT_ID()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="SELECT LAST_INSERT_ID()")] with root cause
java.sql.SQLSyntaxErrorException: ORA-00923: FROM keyword not found where expected

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
        at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:358

We initially thought it was an issue with the name of a sequence so we changed it. Unfortunately that didn’t resolve it and we're still getting the same error. Can you point us to what statement is being run and from where.

Also, are there Oracle scripts available to create the backend database?

**Comment by jricher** [comment]
We don't have any Oracle scripts for the database, but the development version does have HSQL, MySQL, and PostgreSQL support that you can check out and compare the differences.

The SQL statements are being generated by JPA, not directly in the code, so I can't point them to you directly. The above looks like a misconfiguration in the Oracle configuration of the identity generator for the primary key of the class in question. Unfortunately, I don't have enough direct experience with the Oracle DB to know what it might be doing wrong.

If you do come up with a working Oracle schema, we'd be happy to take it into the project alongside the other flavors.

**Comment by praseodym** [comment]
Just to be sure: did you set the EclipseLink `databasePlatform` property in `data-context.xml` to `org.eclipse.persistence.platform.database.OraclePlatform`?

**Comment by joaotab** [comment]
I got it to work using OracleXE, however some changes are required in the code base due to the 30 character limit on table and field names

**Comment by kochsen** [comment]
I was also able to get it to work with an Oracle DB. I converted the MySQL schemas to Oracle, changed some of the column lengths in the DB and code to reference names less than 30 characters, and set the EclipseLink to org.eclipse.persistence.platform.database.OraclePlatform. Seems to be working okay so far.

**Comment by kiakj** [comment]
@kochsen 
Do you think you can share the code changes did with the group?  We wanted to use an oracle backend, but had a few questions.  How did you implement the AUTO_INCREMENT piece?  Are you using trigger/sequence instead?

**Comment by kochsen** [comment]
Sorry @kiakj I don't have the code anymore. It was a previous project I was working on. I can't remember what we did for the AUTO_INCREMENT piece.

**Comment by tborowiec** [comment]
@kiakj 
Today I put a [pull request](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/1143) that adds Oracle support to mitreid-connect. Hopefully this gets accepted and will be useful for somebody :-).
