### ISSUE TITLE
New attributes not appearing in base 1.1.16

### ISSUE THREAD

**Issue by topperge** [mitreid-connect/OpenID-Connect-Java-Spring-Server#863]
I've made what I think should be the changes to 1.1.16 to add an "eye_color" attribute and am not seeing it at all in the userInfo response. Here's my checkin against 1.1.16 with what appear to be all the changes necessary:
https://github.com/topperge/OpenID-Connect-Java-Spring-Server/commit/14dba20656c357299e7a2febd17d8dc633d4e3df
I've also updated the mysql database underneath to contain data in the eye_color field.  We went so far as to decompile the code and all the changes seem to be there.

**Comment by praseodym** [comment]
You should also add the new property to the `toJson` method to be able to see it in the output.

**Comment by topperge** [comment]
@praseodym yep, forgot that in the code, but still doesn't display

**Comment by praseodym** [comment]
There's also `ScopeClaimTranslationService` (`DefaultScopeClaimTranslationService`) which determines which properties are included for which scopes.

**Comment by topperge** [comment]
@praseodym yep, also made that change as part of the tag I linked

**Comment by jricher** [comment]
@topperge I updated the code to include the `toJson` edit and I'm getting the `eye_color` property over in my local test client (based on the `simple-web-app` project). I've uploaded the code here:

jricher@31ccd84ee80ad01f83e52ee42e713ec68bfc1ddc

**Comment by topperge** [comment]
Let's just say there is a major difference in behavior between mvn install vs mvn package.
