### ISSUE TITLE
New Scope Creation not working in 1.2 RC1

### ISSUE THREAD

**Issue by prabhalar** [mitreid-connect/OpenID-Connect-Java-Spring-Server#867]
Just tried the latest 1.2 RC release. The default scopes no longer appear. But more importantly, unable to enter new "scope value" while creating a new scope. The text box seems non editable. Tried it on both IE 11 and Chrome (latest versions) - same issue.

**Comment by jricher** [comment]
The default scopes got pulled out during testing and were accidentally not put back in, that's fixed now. The editing problem is stranger, as it works in Firefox for me, but not in Safari. As best as I can tell, it's got something to do with the icon-selector popup window being invisible but still overlaying the controls. If you select an icon, the fields become clickable and editable again as the window is properly hidden.

**Comment by prabhalar** [comment]
Thanks Justin. Your suggestion works.

**Comment by jricher** [comment]
I'm going to re-open this because there's got to be a way to make the popup not overlay the page on these other browsers.

**Comment by jricher** [comment]
Please test this fix on your browsers, it fixed the problem on Safari for me.

**Comment by prabhalar** [comment]
Tested. Works in both IE and Chrome. Thanks for the fix
