### ISSUE TITLE
Passing tokens by reference

### ISSUE THREAD

**Issue by uberfirestone** [mitreid-connect/OpenID-Connect-Java-Spring-Server#868]
Are there any plans to build an API endpoint for the server to exchange value tokens for reference ones? It gets mentioned by [this article on OIDC](http://nordicapis.com/api-security-oauth-openid-connect-depth/) as a more secure way to send them into the wild.

**Comment by jricher** [comment]
No plans for that right now. The tokens produced by MITREid are actually a combination of value and reference tokens. They include basic information in the JWT and are protected by a signature, but if you want information about who authorized it and what scopes it carries, you need to call the introspection endpoint.
