### ISSUE TITLE
Issuer setting is not being respected, error with login page

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#870]
When running the OIDC server webapp and setting the issuer with another parent name to the openid-connect-server-webapp directory (ie http://162.243.111.18/uma/openid-connect-server-webapp/), the login page does not function correctly.

When clicking login, I first get an error that 'The requested URL /openid-connect-server-webapp/j_spring_security_check was not found on this server."

If I edit the login.jsp page to prepend the line:
form action="<%=request.getContextPath()%>/j_spring_security_check"
with 
form action="/uma<%=request.getContextPath()%>/j_spring_security_check"

No error is displayed; however, I'm not logged in.  I get redirected back to the home page without any indication of being logged on on the right upper corner.  Is there another configuration file that needs to be set that I'm missing (similar to issue #847)?

The reason for the parent name existing is that I have both Apache and Tomcat installed and running together in the same server and I have a Apache virtual host that is set up with a ProxyPass pointing to the Tomcat server (port 8080).

**Comment by jricher** [comment]
You'll need to include the "/uma" portion in your issuer URL. Basically, whatever the home page of the server is, the full public URL, that's what needs to be in the `issuer` variable in the `ConfigurationPropertiesBean` class. To double check this, go to:

http://162.243.111.18/uma/openid-connect-server-webapp/.well-known/openid-configuration

The values there should line up. Also, if you're trying to deploy the UMA capabilities, you'll need the `uma-server-webapp` project and not the `openid-connect-server-webapp` project.

**Comment by shihjay2** [comment]
I did confirm the openid-configuration to make sure that the issuer
variable is correct with the "/uma" portion prior to deployment.  On the
whole the web page displayed correctly as expected; however the login
function did not work; hence the issue I brought up.

Specifically, in the login.jsp page, the form action URL was referencing
only the openid-connect-server-webapp portion of the URL and not any parent
directories before it so that is causing the 404 errors.  However, when I
hardcoded the login.jsp page to reflect the correct URL, the login process
proceeds but the login status is not registering (it goes back to the home
page but it looks like the login never occurred).

When I reconfigured apache to remove the parent location (removing the
proxy) ie.

http://162.243.111.18:8888/openid-connect-server-webapp/ - all works well
again;

I don't know if it is because the webapp is being set up as a proxy that
screws up the URL references.

**Comment by jricher** [comment]
OK, it looks like this might be a place that needs to be changed to pull the configuration bean directly for this specific setup. Thanks for reporting it, we should even be able to pull this into 1.2.0 final release.

**Comment by jricher** [comment]
To test it, replace `request.getContextPath()` with `config.getIssuer()` above, that should do it. Please report back here if that fixes it, and feel free to send a pull request if it does!

**Comment by shihjay2** [comment]
Tried your solution but I get this error:

Error: JasperException (500)

There was an error processing your request. The server's message was:

*Unable to compile class for JSP: An error occurred at line: 29 in the jsp
file: /WEB-INF/views/login.jsp The method getIssuer() is undefined for the
type ServletConfig 26: 27: <div class="row-fluid"> 28: <div class="span6
offset1 well"> 29: <form
action="<%=config.getIssuer()%>/j_spring_security_check" 30: method="POST">
31: <div> 32: <div class="input-prepend input-block-level"> Stacktrace:*
