### ISSUE TITLE
OpenID Login Form forgets originating redirect URL

### ISSUE THREAD

**Issue by bertramn** [mitreid-connect/OpenID-Connect-Java-Spring-Server#875]
We are encountering a rather significant problem with the login/redirect mechanism. Our observation is as followed: 

1) a user accesses a protected site
2) relying party redirects a user to the mitreid server login page 
3) login page is presented but not submitted by the user straight away
4) say after 45 minutes user enters credentials and presses login
5) mitreid server accepts login form post and authenticates user
6) mitreid server can't remember why it authenticated the user and redirects the user to the root of itself

Most probably the servlet session that is created in step 3) holds the redirect URL but as time goes on the servlet session times out. When the login form is finally posted in step 5), tomcat creates another servlet session which does not have the redirect information hence mitreid forced to present the default page of self.

The login form (hidden form field) or a cookie in the clients user agent should really be holding the target redirect information and not the tomcat servlet session (obviously together with a CSFR token). 

Is that a bug or are we just looking at a configuration issue?

**Comment by jricher** [comment]
This behavior does sound like the backend session is timing out. However: if you were to hold the target URL and CSRF token in the form, you'd still need to have something on the server side to validate that, otherwise you're vulnerable to turning the login page into an open redirector.

An option would be to reject the login submission and force the user to log in again from scratch, which is also not very good UX but perhaps something slightly better. This would basically just require turning on tighter CSRF protection on the login form and its submission page, as I understand it this is a Spring Security configuration error. It would not fix the above behavior, though, since the server no longer has any way of tying the login request to another request.

It would be difficult to differentiate between this condition and the condition where the user just wants to log into the server directly, though.

**Comment by bertramn** [comment]
I am not sure why mitreid would turn into an open redirector if the redirect url is added as a hidden form field to the login screen. Doesn't mitreid check the clientid redirection urls before actually issueing a 302 to the user agent after the login form is finally posted and credentials are checked? Not checking whitelisted redirect uris would be a massive security flaw not just a UX issue.

**Comment by praseodym** [comment]
Spring Security's CSRF protection works using servlet sessions, so when the session expires server-side it should throw a HTTP 403 error. I'd be against storing data in cookies or in the form, since that'd require server-side validation which would be impossible without a session anyway.

**Comment by jricher** [comment]
The authorization endpoint would still have its own redirection protection, but now the login page would have an input parameter that's manipulable by an external party (such as an attacker) to send the user to a page of their own choosing after logging in to the server. That's a dangerous mode.

**Comment by jricher** [comment]
I think the real bug here is that an expired login page still succeeds in logging in at all upon submission, and I'm not sure what's been misconfigured to allow that.

**Comment by bertramn** [comment]
But that would only work if mitreid is not checking the redirect uri submitted with the form against the whitelist uri of the clientid ... oh wait this is probably also not present in the form right?

**Comment by jricher** [comment]
Correct, that's all stored in the session, for security reasons (it prevents external manipulation in the middle of a transaction).

**Comment by praseodym** [comment]
The login form doesn't have any CSRF protection, though.

**Comment by bertramn** [comment]
Hmm just on your last comment re expired login page, the scenario explained above is a very common way people interact with their web sites these days, especially on mobile. If a login screen sits there for 15 minutes until the user gets around to enter their credentials it should still eventually authenticate the user and forward him to the originating location. After all the user attempted to get access to a system protected by the login server and does not expect to end up on the login server itself. At least I have never experienced something like that with any of the websites I use that are protected by social logins like google, github or the like. Google always takes me back to where I originated the login from.

**Comment by jricher** [comment]
Google does that by having very, very, very long sessions and a massive amount of heuristic security associated with devices and browsers. You could plug in the same kind of thing here and get the same behavior.

**Comment by jricher** [comment]
@praseodym: I think that's the right fix to this, then.
