### ISSUE TITLE
Language overrides not flexible

### ISSUE THREAD

**Issue by jricher** [mitreid-connect/OpenID-Connect-Java-Spring-Server#876]
As in #817, the current locale handling system isn't robust against partial replace in an override. So far we use "fake" language files, but this breaks things. In particular, a "fake" language will mess with the moment.js date processing. 

This could be accomplished in several ways:

 - Loading auxiliary files for the "fake" language that seamlessly sit on top of the given language; these overrides would be configured separately
 - Loading several "real" language files from different locations to allow for partial overrides

**Comment by praseodym** [comment]
The "fake" language code will also end up in the `Content-Language` HTTP header, which is far from optimal.
