### ISSUE TITLE
Multiple EntityManager Support

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#877]
Hi,
       I am implementing Openid connect server with overlay. Facing issue like "org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [javax.persistence.EntityManagerFactory] is defined: expected single matching bean but found 3"..
I added unit name in my code like @PersistenceContext(unitName = "ghxPersistenceUnit") but openid connect server module dont have this unit name..becaus eof this not able to use overlay concept.

can you pls add some unit name or give me solution.

Thanks
Selvaraj K

**Comment by jricher** [comment]
Thanks for the pointer. We can add a unit name in a future release.

**Comment by selvarajkumarasamy** [comment]
shall i do it?

Selva

**Comment by jricher** [comment]
If you like, sure. We gladly take tested pull requests.

**Comment by selvarajkumarasamy** [comment]
I observed one more thing.when using multiple transaction manager we should add proper identifier name like . .@Transactional(propagation = Propagation.REQUIRED,value="authTransactionManagerIdentifier")

i worked above all changes and tested in my local.. if you give me permission i will share the code in git.

Thanks 
Selvaraj

**Comment by jricher** [comment]
Just submit it as a pull request, you don't need permission from me. :)

**Comment by selvarajkumarasamy** [comment]
Hello i have done txnmanager related changes and pull request submitted.

**Comment by jricher** [comment]
Closed by c67611e97573a934b249a1571a6295125d21025a
