### ISSUE TITLE
why not we should use cache for client details

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#879]
Hi,
        I observed a few points that cause performance.
        1.when i am login first time client details table loaded more than 4 times
        2.when i go for token(code flow) its loading client details table more than 5 times
        3.when i go for new access token. its loading client details table more than 5 times
        4.etc... every call minimum 4 time connecting db to load client details
shall we have cache management? if we use cache at any no of time we call client not an issue.this will increase the performance.

**Comment by jricher** [comment]
Several of the key deployments of MITREid Connect in the enterprise space used split servers with shared databases, so cacheing was turned off at the database connector layer. At one point, we tried to turn it back on for use in a single-server environment, but behavior was weird and we never found out why. We're tracking that in #582, so I'm going to close this issue as a duplicate.
