### ISSUE TITLE
UMA: setting resource owner authorization policies

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#881]
Is there a feature in the UMA server webapp so that a resource owner that is authenticated to the UMA server webapp can set policies for resource API endpoints for specific users or clients?  Is there an API for the UMA server webapp that provides that functionality?

**Comment by jricher** [comment]
You can add arbitrary UMA claims which can, right now, only be fulfilled by an OpenID Connect login. If you're logged in to the AS, look on the right hand side for the "Manage Protected Resource Policies" link.
