### ISSUE TITLE
Login in Mismatch in two different Tab and Application

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#884]
Hi,
             I observed some issues while login in two tab's. 
Ex : 
Step 1: Logged in two different app in same browser.
Step 2: Clear the session using Ctrl+Shift+Delete.
Step 3: now go to tab 1 type the app1 url and in tab 2 type the app2 url.
Step 4: Both tab will show the Mitreid Login Page.
Step 5: if i login in tab1 it will redirected to app 2 but actually i entered app 1 url in tab1.
Step 6:if i refresh the tab 2 it will redirect to app1.
Can any one give me the solution?.

Thanks
Selvaraj K

**Comment by jricher** [comment]
The spring security form login is stateful, remembering a target URI to go to after the login has been successfully processed. What you're doing above is effectively messing with the state of the login page by doing things above in a very particular order. You're basically telling the server "I'm using app1 -- no wait, I'm using app2 -- ok I'm back on the app1 page but I just told you I'm using app2 -- but now I'm back to using app1" and that's what's causing the redirects above.
