### ISSUE TITLE
Maven Parent-Child jar loading issue

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#885]
I am using maven overlay,in this i used mitreid parent pom it excludes org.springframework.* internally.
here i want spring-context-support jar for my custom cache config,including the spring-context-support depentency to my child pom but not adding to the war or target.

can anybody has solution for this ?

**Comment by selvarajkumarasamy** [comment]
I tried adding other spring jars its downloading and adding to my war and target

**Comment by praseodym** [comment]
Should work just fine, see e.g. https://github.com/mitreid-connect/ldap-openid-connect-server/blob/master/pom.xml#L27-L37

**Comment by selvarajkumarasamy** [comment]
Yes i agree you point its true. But i am saying for some of the depentency not getting added see eg: spring-context-support.

**Comment by selvarajkumarasamy** [comment]
we also using following depentency's its working.
             <dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-ldap</artifactId>
			<version>${spring.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-taglibs</artifactId>
			<version>${spring.security.version}</version>
		</dependency>

**Comment by praseodym** [comment]
What exclude in the parent pom are you referring to? I cannot find it.

**Comment by selvarajkumarasamy** [comment]
i find the root cause of the issue and closing.
