### ISSUE TITLE
Introspection of access token returns 403

### ISSUE THREAD

**Issue by dare2try** [mitreid-connect/OpenID-Connect-Java-Spring-Server#889]
Hi everyone,

If been battling with this for a while now, but I have resigned that I just can't seem to figure out why this isn't working.  My scenario is this... 

1. Using the code flow, Client 1 makes a request to the AS with a scope of "openid api1"
2. A valid identity token and access token are returned by the AS
3. Client 1 sends the access token to the api (RS1)
4. RS validates the token and attempts to call the introspection endpoint based details found here (https://tools.ietf.org/html/draft-richer-oauth-introspection-06)
5. A 403 error is returned

I have gotten this to work when the API uses the same client id and client secret as the client that originally requested the token, but not if the API has a different client id and secret.

Is the simple answer that I just using this wrong? It feels like this is what the point of this endpoint "should" be, especially after reading this article http://www.quora.com/In-OAuth-2-0-how-do-resource-servers-assert-a-token-issued-by-an-authorization-server.

Any help would be greatly appreciated!!

**Comment by jricher** [comment]
In our system, you need to give the RS two key permissions. First, there's the ability to introspect at all, and that's a checkbox on the "Access" tab in the client administration panel. Make sure that one's checked. Second, make sure that the RS is set up to use the same scopes as the AS. If it doesn't, in 1.1 introspecting the token will fail, in 1.2 it will return an empty set of permissions. Finally, while you're there in the access tab, uncheck all the grant types and response types. You don't want the RS getting tokens on its own, most likely. Hope this helps.
