### ISSUE TITLE
Implementation of End Session Endpoint

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#891]
Jricher : we have implemented "end session end point" based on the openid connect specification,but "check session end point" not implemented.
I have following queries in above implementation.
1.whether need to clear the token in database?
2.how to implement single app log out?

Give me details, does anybody implementing the same?.

Thanks 
Selvaraj K

**Comment by jricher** [comment]
Yes, you should delete the ID token from the database. 

To implement single app logout, you need to prompt the user at the end session endpoint and also call all current RP's end session endpoints for that user with their tokens.

**Comment by selvarajkumarasamy** [comment]
Jricher: Thanks for the update..we follow the same.

**Comment by jricher** [comment]
Implemented in 1.3.1
