### ISSUE TITLE
API access issue

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#893]
When I try to access the Server API from the browser after I have authenticated to OpenID-Connect-Webapp-Server or UMA-Webapp-Server, I am successful in getting a response (ie http://xxx.xxx.xx.xx/openid-connect-webserver/api/clients).

However, when I do the same thing via an AJAX call (javascript is coming from the same domain) or a CURL request (ie from PHP), despite being authenticated, I get this response:

{"error":"unauthorized","error_description":"Full authentication is required to access this resource"}

In your documentation:
"The API may be accessed through an active web session within the application (ie, any JavaScript running on the server itself) or through authorizing a client application through OAuth."

Am I missing some sort of configuration to the client parameters or scopes for API access to be successful?

**Comment by jricher** [comment]
The JavaScript has to be coming from the same web app and be able to present the same session cookie, it's not enough that it's in the same domain. For the PHP app, is it getting an OAuth token for an admin user? It will need to present that. If it can, it should work. There's not a special scope for API access yet, though that's being looked at in #543 at some point.

**Comment by shihjay2** [comment]
For the PHP app, it did receive an OAuth token for an admin user.  I still
presents with the same response.  Does the client that the admin user is
associated with need to have special permissions itself?

**Comment by jricher** [comment]
No special permissions should be needed at the moment, as long as it's a valid token from an admin user it should work.

**Comment by shihjay2** [comment]
So the OAuth token for the admin user has the scope of openid; is that all that is needed for it to be valid token?

**Comment by shihjay2** [comment]
I figured out the problem; there was an issue with the PHP library sending out missing Authorization headers for GET requests through CURL; it now works as intended after I modified it.  Thanks for pointing me in the right direction.
