### ISSUE TITLE
context of issuer remains /openid-connect-server-webapp even when changed

### ISSUE THREAD

**Issue by ghchinoy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#894]
Changing `issuer`'s context in the `openid-connect-server-webapp/src/main/webapp/WEB-INF/server-config.xml` to something other than `openid-connect-server-webapp` (ex. `http://SOME_IP:8080/mitreodic/`) doesn't change the web interface's login context, and results in a 404 for the url (ex. `http://SOME_IP:8080/mitreoidc/`).

The base web interface remains `http://SOME_IP:8080/openid-connect-server-webapp/` with broken resource links/urls since other resource references seem to honor the `server-config.xml` `issuer` context (visible via chrome dev tools showing http calls to `/mitreoidc/`, which also 404).

Seems similar to #870 .

Built from source, 1.2.1, launched via `mvn jetty:run` in the `openid-connect-server-webapp` dir.

**Comment by praseodym** [comment]
When you want the app to run with issuer `/mitreodic`, make sure you also set Jetty to run on `/mitreodic` as a context path. See [pom.xml](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/9fe98e0132d09eb304ffbe2585dd2408bd6fc4d3/openid-connect-server-webapp/pom.xml#L77-L85).

**Comment by ghchinoy** [comment]
@praseodym Excellent thank you.

Would the recommended way to change the `issuer` for both `webAppConfig/contextPath` & `server-config.xml` be via a [maven overlay](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Maven-Overlay-Project-How-To)?

**Comment by praseodym** [comment]
I use the default `http://localhost:8080/openid-connect-server-webapp/` issuer for development, and configure a different issuer for production deployment. Since I don't use `mvn jetty:run` for production, it has never been a problem.

**Comment by ghchinoy** [comment]
Ok, thanks will try with the Maven overlay.
