### ISSUE TITLE
org.mitre.openid.connect.model.Address should be an interface

### ISSUE THREAD

**Issue by TonyFNZ** [mitreid-connect/OpenID-Connect-Java-Spring-Server#896]
UserInfo is an interface which is great.  This allows us to implement our own custom implementation without being tied to the default @Entity and @Table declarations.  

However UserInfo has a hard reference to the Address class which contains the @Entity and @Table declarations.  Address should be changed to an interface so that this can be more easily overridden by other parties.

Will try to submit a pull request for this when I can.

**Comment by jricher** [comment]
Sounds reasonable to me. If this can be done without breaking the underlying data model (and existing database schema) then we can target this for inclusion in the current release stream, otherwise it will have to wait until 1.3 (which hasn't started yet).

**Comment by jricher** [comment]
Closed by f43c94314c051d1ca68c916164c0200ad13acad1
