### ISSUE TITLE
UMA resource set registration endpoint returns 404 error

### ISSUE THREAD

**Issue by shihjay2** [mitreid-connect/OpenID-Connect-Java-Spring-Server#898]
Sending a post request to the resource set registration endpoint (ie http://162.243.111.18/uma-server-webapp/resource_set) returns 404 error no matter what request is given (from CURL, Postman, etc)

header: Content-Type: application/json, Authorization: Bearer {access token}
body: {"name":"Binary Files","icon_uri":"http://noshchartingsystem.com/i-file.png","scopes":["http://162.243.111.18/nosh/fhir/Binary"]}

**Comment by jricher** [comment]
The actual URL is  http://162.243.111.18/uma-server-webapp/resource_set/resource_set

The UMA spec has a weird bug (KantaraInitiative/wg-uma#155) that forces you to add an extra resource_set onto the end of the URL.

**Comment by shihjay2** [comment]
The .well-known/uma-configuration page should then also reflect this
different url since it is only referring to one resource_set.

**Comment by jricher** [comment]
The .well-known/uma-configuration page is returning the correct URL with only one `resource_set` in it. The UMA RS needs to add `resource_set` to the end of the resource set registration URL found in the discovery document. 

This is an oddity in the UMA spec that our server is implementing correctly but can still cause confusion.
