### ISSUE TITLE
'kid' field not present in the access_token

### ISSUE THREAD

**Issue by lomori** [mitreid-connect/OpenID-Connect-Java-Spring-Server#899]
The 'kid' field should be in the access_token to allow for example the Resource Server to select the proper Public Key from the returned values of the JWK endpoint. This is used for local signature verification. 

We  experienced this behaviour with version 1.1.16.

**Comment by jricher** [comment]
Thanks. Do you need this backported to 1.1.x or will a fix in 1.2.x suffice?

**Comment by lomori** [comment]
Well, we have a workaround for now so not strictly necessary for 1.1.16, the branch we are using, but if not too much work it would be great.
Regards,Luiz
