### ISSUE TITLE
Common method to remove tokens

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#904]
Hello Jricher,
             Need a method to delete id,access and refresh token when doing end session.
we can add method in JpaOAuth2TokenRepository.java good to handle delete all token's in one place.
Thanks
Selvaraj K

**Comment by jricher** [comment]
That already exists. The service layer has a revoke access token and revoke refresh token call:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-common/src/main/java/org/mitre/oauth2/service/OAuth2TokenEntityService.java#L36

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-common/src/main/java/org/mitre/oauth2/service/OAuth2TokenEntityService.java#L38

ID tokens are (currently) stored as access tokens.

**Comment by selvarajkumarasamy** [comment]
@Jricher Thanks for the update,we have implemented and its working fine.
