### ISSUE TITLE
Can I use this project implements resource server .

### ISSUE THREAD

**Issue by sdcuike** [mitreid-connect/OpenID-Connect-Java-Spring-Server#906]
So,user can get some resource from resource server .

**Comment by jricher** [comment]
Yes, after a fashion. In the "client" package this project includes functions to connect a Spring Security OAuth (SECOAUTH) resource server to a token introspection endpoint. You'd set up your project with a resource server from SECOAUTH and wire in the introspection token service instead of having it call a database.

**Comment by sdcuike** [comment]
Thank you ,I will try it.

**Comment by sdcuike** [comment]
Do you mean IntrospectingTokenService.I see you server-web，Don‘t know where wire the IntrospectingTokenService。

**Comment by sdcuike** [comment]
<oauth:resource-server id="resourceServerFilter" token-services-ref="defaultOAuth2ProviderTokenService" />  change to org.mitre.oauth2.introspectingfilter.IntrospectingTokenService ?

**Comment by sdcuike** [comment]
Do you mean <oauth:resource-server id="resourceServerFilter" token-services-ref="defaultOAuth2ProviderTokenService" />   change to org.mitre.oauth2.introspectingfilter.IntrospectingTokenService ?

**Comment by sdcuike** [comment]
<oauth:resource-server id="resourceServerFilter" token-services-ref="defaultOAuth2ProviderTokenService" />  to org.mitre.oauth2.introspectingfilter.IntrospectingTokenService

**Comment by jricher** [comment]
That's the tag, yes, but don't change it on the MITREid Server. You would wire that into whatever protected resource you're building. See the documentation here:

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Token-Introspecting-Client-Config

**Comment by sdcuike** [comment]
Yes,it works .Thank you. I have two resource server . I want a client  access  a another resource server's  data ,like photos, 

Get resource server's data:
request like:
HttpGet httpGet = new HttpGet("http://localhost:8090/simple-web-app/photo?access_token=" + accessTokenValue);


```
@ResponseBody
	@RequestMapping("/photo")
	public String photo(){
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		if(authentication instanceof OIDCAuthenticationToken){
			OIDCAuthenticationToken oIDCAuthenticationToken = (OIDCAuthenticationToken) authentication;
			String accessTokenValue = oIDCAuthenticationToken.getAccessTokenValue();
			try(CloseableHttpClient httpClient = HttpClients.createDefault()){
				HttpGet httpGet = new HttpGet("http://localhost:8090/simple-web-app/photo?access_token=" + accessTokenValue);
				CloseableHttpResponse response = httpClient.execute(httpGet);
				
				 String content = IOUtils.toString(response.getEntity().getContent());
				
				 return content;
			} catch (Exception e) {
				 
			}
			
		}
		 
		return null;
	}

```
But the result is a login page.The resources server's config is :https://github.com/sdcuike/simple-web-app/blob/master/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml.

<oauth2:resource-server id="resourceServerFilter" token-services-ref="introspectingService" />   is alsoe configed.

**Comment by jricher** [comment]
Are you trying to build an OAuth client, an OpenID Connect client, or an OAuth protected resource? Those are all different things and I think that you're confusing them.

**Comment by sdcuike** [comment]
Where I can get example. I confused them.
