### ISSUE TITLE
Multiple Audience in Access Token ?

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#909]
Hi 
   Can you please tell me,how to add multiplke audience in access token?
Right now RP idendifier only available in Access Token,its good when Access Token contains PR indentifier also.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
You'll need to implement a custom token enhancer or token service to add additional or altered fields to the token during creation.

**Comment by selvarajkumarasamy** [comment]
Yes. Thanks for update.
