### ISSUE TITLE
'updated_time' claim should be 'updated_at'

### ISSUE THREAD

**Issue by cjrowe** [mitreid-connect/OpenID-Connect-Java-Spring-Server#910]
Having looked at the most recent version of the OpenID specification, it appears that the date/time the user's profile was updated should be returned under the 'updated_at' claim. The server seems to be returning it as 'updated_time' (the previous name, changed as of Draft 9 of the spec).

Additionally, the 'last update' value is returned as a String (org.mitre.openid.connect.model.UserInfo) - as the value should is number of seconds since epoch, should this a Long?

(For background, I'm currently working on a service that will support Mobile Connect - 'updated_at' is a mandatory value in that specification).

**Comment by jricher** [comment]
Closed by #912
