### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by pashtika** [mitreid-connect/OpenID-Connect-Java-Spring-Server#911]
Could you please guide on issue? http://stackoverflow.com/questions/32725249/cors-filter-issue-for-authentrypoint

**Comment by praseodym** [comment]
What has this issue got to do with this project?

**Comment by pashtika** [comment]
Right, It's nothing to do with this example.. But whatever you've implemented same I'm trying, but found that issue, I am really block on this issue. Could you please guide me?
