### ISSUE TITLE
Signing and Encrypting Response message

### ISSUE THREAD

**Issue by pkaival** [mitreid-connect/OpenID-Connect-Java-Spring-Server#914]
While testing 'OpenID-Connect-Java-Spring-Server' modules on op.certification.openid.net, I encounter with following errors for signed and encrypted UserInfo response
> error message "status: WARNING info: string indices must be integers, not str" 
for Test description: Can provide signed and encrypted UserInfo response.

> error message "status: ERROR	info: OP is not supporting none according to 'userinfo_signing_alg_values_supported' in the provider configuration"
for Test description: Can provide encrypted UserInfo response it is returning with

Can you please guide what I am missing in my configuration?

**Comment by jricher** [comment]
I don't know what the first error message is, but the second is caused because you can't use a dynamically registered client with "none" for any of the signature methods. Only statically registered clients have that option available at the moment.

**Comment by jricher** [comment]
Closing issue due to lack of additional information.
