### ISSUE TITLE
How do I create a local user registry in the OpenID-Connect-Server to test the Sample Web App ?

### ISSUE THREAD

**Issue by vbhadrir** [mitreid-connect/OpenID-Connect-Java-Spring-Server#919]
I have both the mitreid-connect server and client setup in Tomcat 7 on my local host and would like to test it for a few users from the servers local user registry.  Which xml configuration files do I need to add or create a local user registry for mitreid-connect server. For instance I can create local user registry in IBM Liberty Profile Server which also support OID Connect Server and Client using the following XML. How do I do something similar in mitreid-connect server also please provide the XML for it as I am new to Spring Framework. Thanks.

	<basicRegistry id="basic" realm="OpBasicRealm">
		<user name="user1" password="passw0rd" />
		<user name="user2" password="passw0rd" />
	</basicRegistry>

**Comment by jricher** [comment]
MITREid Connect was created to be used with an external user store in most deployments, but if you need to use internal users you can add them to the local database in the default configuration. The file `users.sql` in the webapp project has the two default users, admin and user, that you can edit and augment. Don't forget to add in UserInfo to any additional users, including a randomly generated subject identifier.
