### ISSUE TITLE
Signing and Encryption of response message

### ISSUE THREAD

**Issue by pkaival** [mitreid-connect/OpenID-Connect-Java-Spring-Server#921]
Hi, Does UserInfoJWTView supports both Signing and Encryption of response message at a time? 
As of now code in UserInfoJWTView.java for Encryption and Signing was mentioned in different if-else block, and for encryption it is checking for 'IdTokenEncryptedResponseAlg' it should refer 'userInfoEncryptedResponseAlg'. 
I want to apply both Signing and Encryption before sending user info response message.
Can you please guide me?

**Comment by jricher** [comment]
As to the second point for using the "ID Token" fields, that was a bug that's been fixed. Thanks! We don't have code to do serial signing and then encryption of the tokens. All JWE objects are integrity protected, though, so it should be fine as I understand it.
