### ISSUE TITLE
in DefaultOAuth2ProviderTokenService, clearExpiredTokens() has a race condition with createAccessToken()

### ISSUE THREAD

**Issue by thorie7912** [mitreid-connect/OpenID-Connect-Java-Spring-Server#927]
In clearExpiredTokens(), any orphaned authentication holders are removed. However, when createAccessToken() is called, it will initially create an authentication holder (which initially does not have it's corresponding access token created yet) and after a few more lines of code, will create the token. There is a reasonable possibility that on some request (and I have seen it happen) that the initial auth holder gets deleted as if it was an orphan.

To reproduce this issue, simply add a Thread.sleep() on createAccessToken() between the auth holder and the access token creation. Then, have the scheduled cleanup happen at frequent enough interval to execute during that sleep. You will see that the perfectly valid auth holder will get deleted by an orphan due to the timing/race issue.

In task-config.xml:
```
<task:scheduled ref="defaultOAuth2ProviderTokenService" method="clearExpiredTokens" fixed-delay="10000" initial-delay="2"/>
```

In DefaultOAuth2ProviderTokenService.java:
```
			OAuth2AccessTokenEntity enhancedToken = (OAuth2AccessTokenEntity) tokenEnhancer.enhance(token, authentication);

			// Added this sleep to increase the likelihood of the race condition described.
			try {
				Thread.sleep(30000);                 //1000 milliseconds is one second.
			} catch(InterruptedException ex) {
				Thread.currentThread().interrupt();
			}

			OAuth2AccessTokenEntity savedToken = tokenRepository.saveAccessToken(enhancedToken);
```

**Comment by thorie7912** [comment]
Hmm, interestingly enough even though the auth holder gets created, and the clearExpiredTokens deletes that particular auth holder as an orphan, when the createAccessToken function completes, the auth holder appears in the DB again so somehow it's surviving. I'm going to have to trace more of this code.

**Comment by jricher** [comment]
The authorization holder is attached to another entity and is persisted through that relationship. The extra call to the auth holder repository is likely spurious but harmless. Your proposed fix above would just be delaying a race condition, not fixing it.

**Comment by thorie7912** [comment]
I didn't propose any fix.
