### ISSUE TITLE
WebfingerIssuerService creates unhelpful login_hint

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#936]
[WebfingerIssuerService passes `identifier` as  `login_hint`](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/8b362f23f350e93c418126cf18929e6266f69515/openid-connect-client/src/main/java/org/mitre/openid/connect/client/service/impl/WebfingerIssuerService.java#L108), which is not useful when `identifier` is an URL (the issuer) instead of a username.

In practice, with the simple-web-app, we end up with the OIDC server url in the Username box of the server login page, because that is what was passed as a `login_hint`. We'd be better off not providing any `login_hint` in this case.

**Comment by jricher** [comment]
This is related to #851

**Comment by jricher** [comment]
Closed by 98e1d261340b2c6419a109485621e8704bd4fe21
