### ISSUE TITLE
Impersonation implementaion

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#939]
Hello Jricher,
                    We are planing to implement impersonation with in the application.One user can access the resources on behalf of others,this is what our requirement.

We are planing to do in following way.

           • RP should be able to send request to AS to get impersonatee tokens
             (can we use client_credential flow along with subject).
           • RP should get exception if it doesnt meets the policies.
           • RP should maintain token contexts of Impersonator and Impersonatee.
           • RP should be able to manage these context in same browser cookie.
           • RP should be able to clean context of Impersonatee on termination.
           • AS should be able to clear the token when termination or expiration.
    
Could you please give your suggestion and thoughts.

Thanks
Selvaraj.K

**Comment by jricher** [comment]
Not sure what you're looking for in terms of impersonation. OAuth is specifically about getting a token on behalf of the resource owner, so isn't that covered? 

You might want to look at the https://github.com/idbind/ project for binding multiple identities at an RP and into token chaining for getting a new token based on an existing token.
