### ISSUE TITLE
checkForPreApproval does not check if the prompt value is 'consent'

### ISSUE THREAD

**Issue by ivardatdatacom** [mitreid-connect/OpenID-Connect-Java-Spring-Server#940]
The 'checkForPreApproval' method in the 'TofuUserApprovalHandler' class does not check if the prompt value is 'consent' but instead checks for value PROMPT_SEPARATOR.
So:
if (!prompts.contains(PROMPT_SEPARATOR)) {...}
Should be:
if (!prompts.contains(PROMPT_CONSENT)) {...}

**Comment by jricher** [comment]
Thanks, looks like we pulled the wrong constant when we factored out the bare strings.

**Comment by ivardatdatacom** [comment]
Thanks so much for the quick turn-around!

**Comment by jricher** [comment]
You got lucky in that I saw this just before a release cycle and it was an easy fix. :)
