### ISSUE TITLE
relation "at_tv_idx" already exists

### ISSUE THREAD

**Issue by sdoxsee** [mitreid-connect/OpenID-Connect-Java-Spring-Server#942]
We need to check if indexes already exist before creating them.

org.postgresql.util.PSQLException: ERROR: relation "at_tv_idx" already exists

ref:
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/commit/9117e7fe31363fa0991d89a154e5032ca5d17507

for PSQL, seems there are a few solutions depending on your version: http://dba.stackexchange.com/questions/35616/create-index-if-it-does-not-exist

**Comment by praseodym** [comment]
In what situation would the indexes already exist?

**Comment by sdoxsee** [comment]
The first time I start the server, the indexes are created from psql_database_tables.sql

The second time I start the server, the indexes already exist and the exception occurs

**Comment by jricher** [comment]
If you're running postgres, why are you running the schema file every time? You should really only do that offline before the server starts for the first time. Same with MySQL. HSQLDB's in-memory DB is a different case as things need to be booted from scratch, so the schema gets run every time.

**Comment by jricher** [comment]
We could potentially pull the indexes into separate files instead of having them at the bottom of the schema files, which might be safer.

**Comment by sdoxsee** [comment]
You make a good point that running the schema file every time doesn't make sense. I suppose I'm used to liquibase where there are db revisions that are only applied if they haven't already been run. I like having my WAR create and update my db schema automatically i've I've added a new revision without having to manually apply change revisions.

However, the rest of psql_database_tables.sql has these kinds of checks everywhere else ```CREATE TABLE IF NOT EXISTS```. Why bother with "IF NOT EXISTS" at all then? I'd lean towards being consistent and having SQL that would protect itself from being run multiple times.

**Comment by jricher** [comment]
We don't change the structure of the schema files within a revision stream (1.2 stable for instance). Adding indexes and constraints in ways that don't break existing implementations is generally seen as OK.

We leave the "IF NOT EXISTS" in the MySQL and PGSQL files for two reasons: consistency with the HSQL version (which is where DB changes usually start and we need the diffs to be very light or else things get lost) and to add a measure of safety in the rare cases where someone drops most of the DB but leaves some parts of it standing and needs to re-run the schema file. It's a corner case, but it was common enough at one of the early deployments of this software that it was codified.

**Comment by jricher** [comment]
All that said, if it's as simple as "CREATE INDEX IF NOT EXISTS" across all three DB flavors then I'm fine with putting that in there. From what I read that's only a very recent PGSQL addition, and I don't think HSQL supports it at all.

**Comment by sdoxsee** [comment]
Thanks @jricher and @praseodym . I can work with things as there are. I'd prefer IF NOT EXISTS or revisions but that simple syntax doesn't exist until postgresql 9.5 (which is currently in beta). I'll leave the issue in your court to close or work on. Thanks for your comments and great work.

**Comment by jricher** [comment]
I'll close it for now, if there's a better solution out there in the future we can open up a new issue for it.
