### ISSUE TITLE
OIDCAuthenticationFilter and the JWKSetCacheService

### ISSUE THREAD

**Issue by thomas-hofer** [mitreid-connect/OpenID-Connect-Java-Spring-Server#945]
I am quite new to Spring and set-up a Spring Boot application using the OIDC Server. I configured an OIDCAuthenticationFilter, using javaconfig and not XML style, on my RP to work together with the OpenID-Connect-Java-Spring-Server I deployed. So far so good.

```java
    public OIDCAuthenticationFilter openIdConnectAuthenticationFilter() throws Exception {
        OIDCAuthenticationFilter oidcFilter = new OIDCAuthenticationFilter();

        oidcFilter.setAuthenticationManager(authenticationManager());

        oidcFilter
                .setServerConfigurationService(new StaticServerConfigurationService() {
                    @Override
                    public ServerConfiguration getServerConfiguration(
                            String issuer) {
                        ServerConfiguration server = new ServerConfiguration();
                        server.setAuthorizationEndpointUri(oidcEndpoint
                                + "/authorize");
                        server.setIssuer(issuer);
                        server.setTokenEndpointUri(oidcEndpoint + "/token");
                        server.setRevocationEndpointUri(oidcEndpoint
                                + "/revoke");
                        server.setIntrospectionEndpointUri(oidcEndpoint + "/introspect");
                        server.setTokenEndpointAuthMethodsSupported(Arrays.asList("SECRET_BASIC"));
                        server.setJwksUri(oidcEndpoint + "/jwk");
                        server.setUserInfoUri(oidcEndpoint + "/userinfo");
                        return server;
                    }
                });
        oidcFilter
                .setClientConfigurationService(new StaticClientConfigurationService() {

                    @Override
                    public RegisteredClient getClientConfiguration(
                            ServerConfiguration issuer) {
                        RegisteredClient client = new RegisteredClient();
                        client.setClientId(oidcClientId);
                        client.setClientSecret(oidcClientSecret);

                        client.setScope(new HashSet<String>(Arrays.asList("openid",
                                "email", "phone", "address", "offline_access",
                                "profile")));
                        HashSet<String> redirect = new HashSet<String>();
                        redirect.add(oidcClientRedirectUri);
                        client.setRedirectUris(redirect);

                        client.setTokenEndpointAuthMethod(AuthMethod.SECRET_BASIC);

                        return client;
                    }
                });

        StaticSingleIssuerService issuer = new StaticSingleIssuerService();
        issuer.setIssuer(oidcEndpoint + "/");
        oidcFilter.setIssuerService(issuer);
        oidcFilter.setValidationServices(jwkSetCacheService());

        oidcFilter.setAuthRequestOptionsService(new StaticAuthRequestOptionsService());
        oidcFilter.setAuthRequestUrlBuilder(new PlainAuthRequestUrlBuilder());

        return oidcFilter;
    }
```

When I wanted to login to my page I got properly redirected and entered the user credentials. Afterwards I got a NullPointerException fired in the OIDCAuthenticationFilter
<pre>
java.lang.NullPointerException: null
        at org.mitre.openid.connect.client.OIDCAuthenticationFilter.handleAuthorizationCodeResponse(OIDCAuthenticationFilter.java:511)
        at org.mitre.openid.connect.client.OIDCAuthenticationFilter.attemptAuthentication(OIDCAuthenticationFilter.java:185)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:211)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
...
</pre>

I figured out if you set in the <i>ServerConfiguration</i> a JwksUri
```java
ServerConfiguration server = new ServerConfiguration();
server.setAuthorizationEndpointUri(oidcEndpoint + "/authorize");
server.setIssuer(issuer);
server.setTokenEndpointUri(oidcEndpoint + "/token");
server.setRevocationEndpointUri(oidcEndpoint + "/revoke");
server.setIntrospectionEndpointUri(oidcEndpoint + "/introspect");
server.setTokenEndpointAuthMethodsSupported(Arrays.asList("SECRET_BASIC"));
server.setJwksUri(oidcEndpoint + "/jwk");
server.setUserInfoUri(oidcEndpoint + "/userinfo");
```
the handling of the JWT requires a <i>JWKSetCacheService</i> even if in the preamble of the class says
```java
...
// fetches and caches public keys for servers
@Autowired(required=false)
private JWKSetCacheService validationServices;

// creates JWT signer/validators for symmetric keys
@Autowired(required=false)
private SymmetricKeyJWTValidatorCacheService symmetricCacheService;

// signer based on keypair for this client (for outgoing auth requests)
@Autowired(required=false)
private JWTSigningAndValidationService authenticationSignerService;
...
```
In <i>OIDCAuthenticationFilter.afterPropertiesSet()</i> this issue is addressed and defaults are instantiated but it seems that it doesn't get executed. After I added a <i>JWKSetCacheService</i> manually to the Filter it worked fine.
```java
@Override
public void afterPropertiesSet() {
	super.afterPropertiesSet();

	// if our JOSE validators don't get wired in, drop defaults into place

	if (validationServices == null) {
		validationServices = new JWKSetCacheService();
	}

	if (symmetricCacheService == null) {
		symmetricCacheService = new SymmetricKeyJWTValidatorCacheService();
	}
}
```

Maybe I did something wrong, but it's working now. If it addresses an real issue that the afterPropertiesSet() method isn't executed  in a certain setting I'm happy to help, otherwise close this issue ;-)

**Comment by praseodym** [comment]
Thanks for the good issue breakdown!

The [sample XML config also contains a `JWKSetCacheService` bean](https://github.com/praseodym/simple-web-app/blob/520f537935ab62af73417cb3b91d3a35fe424d01/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml#L409), but I agree that it shouldn't break without it being in there. Either `OIDCAuthenticationFilter` should require the bean when it expects it to be there, or we should ensure it is automatically instantiated.

Without the `JWKSetCacheService` bean in the XML, `afterPropertiesSet()` does instantiate the bean just fine (verified with a debugger). I can also not reproduce the `NullPointerException`. Could you verify whether the `afterPropertiesSet()` method is called?

**Comment by thomas-hofer** [comment]
Thanks for answering.

I played around with the possible ways of adding the `OIDCAuthenticatinFilter`. When I do not add the `JWKSetCacheService` to the filter, a `NullPointerException` is thrown (verfied with a debugger), again. 
But, if I annotate the method `OIDCAuthenticatioFilter openIdConnectAuthenticationFilter()` as `Bean` the setting works.
```java
@Bean
public OIDCAuthenticationFilter openIdConnectAuthenticationFilter() throws Exception {
    OIDCAuthenticationFilter oidcFilter = new OIDCAuthenticationFilter();
    oidcFilter.setAuthenticationManager(authenticationManager());
    ...
```
Maybe another useful detail is that I use Spring Boot and my security configuration looks like this:
```java
@Configuration
@EnableWebMvcSecurity
@Order(SecurityProperties.ACCESS_OVERRIDE_ORDER)
public class MySecurityConfiguration extends WebSecurityConfigurerAdapter {
    ...
    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.addFilterAfter(openIdConnectAuthenticationFilter(),
                AbstractPreAuthenticatedProcessingFilter.class)
                .exceptionHandling()
                .authenticationEntryPoint(authenticationEntryPoint())
                .and()
                .authorizeRequests()
                .anyRequest().authenticated();
}
```

As I mentioned in the previous post, I'm quite new to Spring, but maybe you can elaborate this behavior to me?

I have another question, which is not part of this issue and not worth an issue. I want to access the `OIDCAuthenticationToken` in my controller. Can I somehow inject the one created during the `securityFilterChain`.

Thanks for helping.

**Comment by praseodym** [comment]
Ah I see now. `OIDCAuthenticationFilter` is an `InitializingBean` and needs to be initialised as a Spring bean (using the `@Bean` annotation) or its `afterPropertiesSet()` method will not be called.

If you're using Spring MVC, you can get the `Principal` object as a method parameter and check if it is an `instanceof OIDCAuthenticationToken`.

**Comment by thomas-hofer** [comment]
Thank you so much! Working like a charm.
