### ISSUE TITLE
Unexpected exception in client when session is lost mid-authentication

### ISSUE THREAD

**Issue by praseodym** [mitreid-connect/OpenID-Connect-Java-Spring-Server#949]
Steps to reproduce are as follows:

1. Have OIDC client application running on localhost
2. Go to 127.0.0.1:8080, session is now bound to this address
3. Login using OIDC, redirects back to localhost:8080
4. Session is empty (no cookie on "localhost:8080") and unexpected exception occurs

The exception is a NPE or whitelist error in DynamicServerConfigurationService.

We found the root cause to be in [the OIDCAuthenticationFilter](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/5f24685f1786a4556ba8e101e1ae1028d1e89ec7/openid-connect-client/src/main/java/org/mitre/openid/connect/client/OIDCAuthenticationFilter.java#L285-L297): when the session does not contain the `state` or `issuer` attributes (i.e. they are null), the state check does not fail and a null `issuer` is passed down to the `ServerConfiguration` class and causes an NPE there.

We should ensure that the state check fails when the `state` attribute is not empty or null; can it disappear for a legitimate reason?

**Comment by jricher** [comment]
The state cannot disappear for a legitimate reason, so we should fail the authentication transaction at that point. So far this is behaving as designed, but I'm not against failing even faster in this case.
