### ISSUE TITLE
High Availability and scheduled tasks

### ISSUE THREAD

**Issue by bjornlalin** [mitreid-connect/OpenID-Connect-Java-Spring-Server#955]
Hi,

we're trying to setup the application on two servers behind a load balancer. We've seen the remarks regarding this setup in issue #748 but have a few additional questions. 

In particular we would like to understand if the tasks configured in task-config.xml are important to the correct functioning of the application/protocol/tokens, or if it's purely cleanup tasks to remove anyway obsolete tokens and clients from the database?

**Comment by jricher** [comment]
Right now they're only cleanup tasks, and they should be run by only one copy of the server.
