### ISSUE TITLE
Spring Qualifiers for injected components

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#957]
Plenty of components in the codebase are picked by auto-wiring. Could qualifiers be selected and used instead? 

For example,

``` java
@Autowire
@Qualifier("BlacklistedSiteRepository")
private BlacklistedSiteRepository repository;
```

Then annotate the JpaBlacklistedSiteRepository with a "JpaBlacklistedSiteRepository". 

In the configuration, define an alias that maps JpaBlacklistedSiteRepository to BlacklistedSiteRepository. 

So that if I write my own, I'll just have to change the alias.

**Comment by mmoayyed** [comment]
To clarify: my use case requires that I entirely move away from db-persistence. So I need an implementation for all such repositories. But I cant simply write one and have it be available in the context, because Spring will run into conflicts with multiple beans. I could annotate my own with Primary, but I think using qualifiers would be best.

**Comment by jricher** [comment]
We've traditionally solved this by using @Primary on the replacement annotations, and occasionally by removing classes in the overlay used for custom deployments. We could potentially go the @Qualifier route, we'll look into it.

**Comment by praseodym** [comment]
Not using qualifiers but just overriding all configuration would have the same effect. (With any component scanning disabled)

**Comment by mmoayyed** [comment]
Yes, Primary is also what I am using for now.
