### ISSUE TITLE
Could Address expose a getId()?

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#958]
Writing my own impl of AddressRepository. There is no way I can simply rely on the Address interface to look up addresses based on id. Because that method is not available to me. Example:

```
public class StaticAddressRepository implements AddressRepository {

    private final Set<DefaultAddress> addresses = new HashSet<>();

    @Override
    public Address getById(final Long aLong) {
        for (DefaultAddress address : addresses) {
            if (address.getId().equals(aLong)) {
                return address;
            }
        }
        return null;
    }
}
```

So I am forced to use DefaultAddress. Would be better if I didnt have to use the actual impl.

**Comment by jricher** [comment]
So far, addresses have only been tied to UserInfo objects and haven't needed to be grabbed separately. We can look at opening this up.

**Comment by mmoayyed** [comment]
Happy to submit a PR.

**Comment by praseodym** [comment]
If you want to provide your own Address class you're going to have to override the DefaultUserInfo class as well, which requires replacing all components that use the AddressRepository anyway. If we want to improve this situation it's going to have to be something bigger than just improving the AdressRepository.

**Comment by jricher** [comment]
There have been a couple of requests in the past to loosen the dependency on JPA at the data layer, but we haven't yet been able to do that without making the base project very complicated as a result. I'm open to suggestions in rearchitecting the data model for 1.3.

**Comment by mmoayyed** [comment]
>There have been a couple of requests in the past to loosen the dependency on JPA at the data layer, but we haven't yet been able to do that without making the base project very complicated as a result. I'm open to suggestions in rearchitecting the data model for 1.3.

:+1: 

I am completely moving away from the JPA layer, and this would tremendously help. I have so far tried to re-implement all JPA-based repositories and things work fine, but I obviously wouldnt object to making this even simpler :) 

Just for reference, I am working on adding OIDC support to the Shibboleth IdP. JPA could be an option, but certainly not the default option there.

**Comment by jricher** [comment]
You would still need all new custom repositories in whatever new setup were to be built, since the default will likely remain JPA based. The real question is about decoupling the entities themselves; at least, that's what tripped us up before.

**Comment by jricher** [comment]
Functionality added as it's relatively harmless from first look. We can back it out if this breaks too many implementations. 

The kind of functionality asked about in this thread would still need custom userinfo as well, which is a bigger issue.
