### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by oharsta** [mitreid-connect/OpenID-Connect-Java-Spring-Server#959]
Currently the sql scripts in OpenID-Connect-Java-Spring-Server/openid-connect-server-webapp/src/main/resources/db/tables contain all tables / indexes needed for the OIDC Server functionality. However when I deploy to production or acceptance and later changes are committed to the sql files there is no way to update the database with only the changes (e.g. alter scripts) other than manually diffing the changes and writing the delta myself.

Would it be possible to commit future changes to the sql structure in the form of versioned alter scripts? This would also make it possible to introduce something like Flyway to manage the database migrations. I don't mind working on a pull request for this, but I first want to ensure this is something you would agree with?

**Comment by jricher** [comment]
We make it a point not to change the database tables within a versioned release channel. Occasionally we'll add non-breaking constraints, indexes, or things of that nature that don't change the schema.

In between versions, the only supported method for upgrades to preserve data is to use the import/export API. We used to provide an ALTER script for 1.0 -> 1.1, but that wasn't able to preserve data so we eventually discontinued its recommendation.

For the pre-release development version (we don't have one right now, but 1.3 will start that way at some point), the database tends to change too quickly and randomly to make data preservation via ALTER scripts a reasonable prospect.
