### ISSUE TITLE
Create new Protected Resource

### ISSUE THREAD

**Issue by GLE81** [mitreid-connect/OpenID-Connect-Java-Spring-Server#960]
Hi,

I'm trying to register a new protected resource, I have the OIC/Oauth2 server running but when I try to create a new one using the web interface the server generate all the necessary information like the clientId, but after that this "protected resource" appear listed in the "Manage Clients" like another client and using the "Manage Protected Resource" in UMA server I don't see this new protected resource, do I missing something? ... sorry but I'm new with oauth2 and I'm not sure about how this should be work.

Another thing is that I'm trying to secure a service like a "protected resource" but doing what you said in the wiki is not working for me, the service never request for the token or anything else, these are my web.xml and spring security.xml

web.xml

    <?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
    <web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.5" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">   
    <display-name>UtilsApi</display-name>    
    <description>Roo generated UtilsApi application</description>   
    <context-param>
    param-name>contextConfigLocation</param-name>
    <param-value>classpath*:META-INF/spring/applicationContext*.xml</param-value>
    </context-param>    
    
	<filter>
	    <filter-name>springSecurityFilterChain</filter-name>
	    <filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
	     <init-param>
	        <param-name>contextAttribute</param-name>
	        <param-value>org.springframework.web.servlet.FrameworkServlet.CONTEXT.UtilsApi</param-value>
	    </init-param>
	</filter>	
	<filter-mapping>
	    <filter-name>springSecurityFilterChain</filter-name>
	    <url-pattern>/*</url-pattern>
	</filter-mapping>   
    
    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>    
    
    <servlet>
        <servlet-name>UtilsApi</servlet-name>
        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>
        <init-param>
            <param-name>contextConfigLocation</param-name>
            <param-value>WEB-INF/spring/webmvc-config.xml</param-value>
        </init-param>
        <load-on-startup>1</load-on-startup>
    </servlet>    
    <servlet-mapping>
        <servlet-name>UtilsApi</servlet-name>
        <url-pattern>/</url-pattern>
    </servlet-mapping>
    </web-app>

Security.xml

           
    <security:global-method-security pre-post-annotations="enabled"/>
	<security:http auto-config="false" use-expressions="true"
		disable-url-rewriting="true" entry-point-ref="oauthAuthenticationEntryPoint"
		pattern="/**">
	    		<security:custom-filter before="PRE_AUTH_FILTER" ref="resourceServerFilter" />
		<security:logout />
      </security:http>  
    <bean id="oauthAuthenticationEntryPoint" class="org.springframework.security.oauth2.provider.error.OAuth2AuthenticationEntryPoint">
        <property name="realmName" value="theRealm" />
    </bean>	
    <security:authentication-manager alias="authenticationManager" />        	
        
    <oauth2:resource-server id="resourceServerFilter" token-services-ref="introspectingService" />
    <bean id="introspectingService" class="org.mitre.oauth2.introspectingfilter.IntrospectingTokenService">
    <property name="introspectionConfigurationService">
    <bean class="org.mitre.oauth2.introspectingfilter.service.impl.StaticIntrospectionConfigurationService" id="introspectionConfigurationService">
    <property name="introspectionUrl" value="http://127.0.0.1:9090/ldap-openid-connect-server-webapp/introspect" />
    <property name="clientConfiguration">
     <bean class="org.mitre.oauth2.model.RegisteredClient">
       <property name="clientId" value="b8784964-2b34-444c-8dea-5d6f25522caa"/>
       <property name="clientSecret" value="dMSHb4qqhltO5-GHHlqMYYfDI9EqQQ4AK6kSXUNZyrDiID8aYvZQ_6fKHaF06Ja1ZbAw0wZLmZ6qdz3qyZI1sw"/>
     </bean>
    </property>
     </bean>
     </property>
     </bean>

Do you have any example of how to implement a "protected resource"?

**Comment by jricher** [comment]
When you register a "protected resource" on the server, it's stored as a client. This may be a little bit confusing but it's due to the data model and the fact that a protected resource needs to be able to access the authorization server in particular ways. 

The UMA "manage protected resources" really needs to be renamed to "manage sharing policies" or something like that. Only resources that use UMA to connect to the AS will show up here, and that's only after they register resource sets. This is completely separate from the developer self-service resource set registration. 

For the other part of your question (and please use separate issues to discuss separate things in the future), protected resources don't request tokens. Clients request tokens and then present them to protected resources, which need to look them up, perhaps using token introspection which is what our token service and its attendant filter implement.

**Comment by GLE81** [comment]
OK. Thanks for the answer, I was confused about protected resources.
