### ISSUE TITLE
redirect_uri matching is inexact

### ISSUE THREAD

**Issue by jmandel** [mitreid-connect/OpenID-Connect-Java-Spring-Server#961]
This may be by design, but I found it surprising (and *undesirable*):

When using the authorization code flow, `redirect_uri` values are "matched" in a very flexible way, so that a URI with a different port still counts as a match, and a URI with a different path (specifically, a subpath of the expected one) still matches.

Is there any interest in a stricter matching scheme (whether as the only scheme, or as an option)? For [SMART on FHIR's use case](http://docs.smarthealthit.org/authorization/), we restrict to exact matches — no variations.

**Comment by jricher** [comment]
This was handled in #700 and can be enabled by setting `strictMatch=true` on the `BlacklistAwareRedirectUriResolver` bean. It's off by default to match previous behavior of the class and not surprise anyone.

**Comment by jmandel** [comment]
Thanks @jricher! Would it make sense to document this flag at https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Server-configuration ?

**Comment by jricher** [comment]
Probably. Thanks for volunteering to update the wiki. ;)

In all seriousness there are a few new flags and features in 1.2 that we should write up.
