### ISSUE TITLE
spring:message default text behaviour broken by JsonMessageSource 

### ISSUE THREAD

**Issue by strangeweaver** [mitreid-connect/OpenID-Connect-Java-Spring-Server#964]
spring:message is supposed to output the resolved code or, failing resolution, should output the value in the text attribute. should both be empty it will output null.

This behaviour is broken by the current implementation of JsonMessageSource.resolveCode method which returns the code if the code fails to resolve contrary to the Javadoc in AbstractMessageSource which specifies.

@return the MessageFormat for the message, or {@code null} if not found

this can be resolved by using the following resolveCode method body

        JsonObject lang = getLanguageMap(locale);

        String value = getValue(code, lang);

        if (value == null) {
            // if we haven't found anything, try the default locale
            lang = getLanguageMap(fallbackLocale);
            value = getValue(code, lang);
        }

        return value == null ? null : new MessageFormat(value, locale);

**Comment by jricher** [comment]
Interesting, I hadn't noticed that part of the contract. I've worked with other messaging systems that passthrough the input code in situations like this so that at least *something* is displayed to the user. What's the purpose of returning null here, is it handled specially?

**Comment by strangeweaver** [comment]
returning null means default message behaviour is handled from the AbstractMessageSource class this can be affected by for example setting the useCodeAsDefaultMessage however if the useCodeAsDefaultMessage is set false it will hand message resolution to the renderDefaultMessage which causes the spring:message tag to provide the default behaviour as specified in the spring.tld file.

...\org\springframework\spring-webmvc\4.1.7.RELEASE\spring-webmvc-4.1.7.RELEASE.jar!\META-INF\spring.tld

**Comment by jricher** [comment]
OK, that makes sense then. Thanks, we'll patch that (unless you want to just send a pull request with your change above).

**Comment by strangeweaver** [comment]
Thanks much appreciated, I'm happy enough to leave it in your hands.
