### ISSUE TITLE
Support for additional information / extensions in user_info

### ISSUE THREAD

**Issue by oharsta** [mitreid-connect/OpenID-Connect-Java-Spring-Server#965]
Hi,

In our implementation of the MITREid Connect / OpenID Connect server we provision users into the user_info table based on a SAML response. We would like to store additional attributes for the user (and subsequently use this in the UserInfo endpoint and JWT). 

Therefore I would like to add getAdditionalInformation / setAdditionalInformation to the UserInfo interface and implement it in DefaultUserInfo with a Map<String, Serializable> (very much like the extensions in AuthenticationHolderEntity). I don't mind making a pull request, but is this something which would be accepted? Of course I could also name it extensions or something else...

The other way for us to implement this would be to implement a custom UserInfo and a custom UserInfoService (the latter we already have to insert a DefaultUserInfo into the user_info table for provisioning), but then I would need to cast on many different places (and do many @Primary overrides of components).

**Comment by praseodym** [comment]
Implementing a custom `UserInfo` class is currently the way to go. It doesn't actually require adjustments in too many places (see e.g. [our overlay](https://github.com/WISVCH/connect)).

I do agree that this could be nicer. On one hand, having an own implementation of `UserInfo` has the advantage that the same class can be used in client code. On the other hand, implementing the entire class as a Map might not be too bad and provide easier JSON serialization.
