### ISSUE TITLE
Registration Access Token

### ISSUE THREAD

**Issue by JustUser13** [mitreid-connect/OpenID-Connect-Java-Spring-Server#966]
Hi
I have test openid server and i have conifugred it but  i can't connect register my client application in openid server. Server has gave me "Client id" , "Client Secret", but i don't understand what do i have to do with "Client Configuration URL" and "Registration Access Token", when i send "localhost/register/client-id" server answers this Full authentication is required to access this resource
Can you explain me what i do wrong?

**Comment by jricher** [comment]
The client configuration URL and registration access token are part of dynamic client registration: https://tools.ietf.org/html/rfc7592
