### ISSUE TITLE
Invalid CSRF Token

### ISSUE THREAD

**Issue by JustUser13** [mitreid-connect/OpenID-Connect-Java-Spring-Server#967]
I connected to server but when i send my credentials i'm getting this error.
Invalid CSRF Token 'bd0fbc56-2310-4871-b77d-1f17fd1f8bc1' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.

Thanks for responding to my stupid answers

**Comment by praseodym** [comment]
Did you use the back button while in the signin process?

**Comment by JustUser13** [comment]
Yes, i did

**Comment by jricher** [comment]
Don't do that.

**Comment by JustUser13** [comment]
ok)), thanks
