### ISSUE TITLE
Expected CSRF token not found. Has your session expired?

### ISSUE THREAD

**Issue by GLE81** [mitreid-connect/OpenID-Connect-Java-Spring-Server#973]
Hi,

I'm making a new application with spring boot and trying to use the mitre oic client but I have a problem with the authentication. The thing is, I have a link from the application to the oic server for login, when I use this link, the login page in the oic server is loaded and request the username and password, after enter the data and pushing "login" the oic show me this error "Error: 403 Forbidden There was an error processing your request. The server's message was: Expected CSRF token not found. Has your session expired?" (this error is generated by http://localhost:9090/openid-connect-server-webapp/j_spring_security_check)

I'm not sure about what is wrong in my implementation, I checked my configuration and it seem to be correct, and if I look the source of the login page of the oic server the param csrf is there. Any idea where I can see to find the problem? have you had this problem before?

And of course, the login from the oic server works when I try to login directly.

**Comment by jricher** [comment]
Are you directing the user to `/login` or to `/authorization` during the process? Which version are you using? There are a lot of variables that could mess this up, but it's something that's tripping up the Spring CSRF checking.

**Comment by GLE81** [comment]
I'm redirecting to /login from the link of the client.

This are the calls that client make when redirect:

http://127.0.0.1:8080/openid_connect_login?identifier=localhost%3A9090%2Fopenid-connect-server-webapp%2F&_csrf=43dc3446-ef68-4147-999e-7bcba23c8e9f

http://127.0.0.1:9090/openid-connect-server-webapp/authorize?response_type=code&client_id=db0bab89-bffb-428d-bde5-98effa6b4542&scope=phone+openid+profile&redirect_uri=http%3A%2F%2F127.0.0.1%3A8080%2Fsample&nonce=57d8e91f169a&state=3e495b3c85fa3

After this the login page is loaded containing the csrf "<input type="hidden" name="_csrf" value="2e8426df-129c-4bd4-b301-b6407d544c00" />"

if I enter the username and passwor and click in login button the message appear (Expected CSRF token not found....)

In the client, I'm using springboot 1.2.7.Release with the mitre oicclient 1.1.15 and java 1.8 ... well the thing is I'm creating a lib who implement the use of the mitre oicclient because I need to implement other funtionalities for the applications.

In the server, I'm using mitre 1.2.3-SNAPSHOT by default.

I'm not sure if a have to put my configuration files here because they are large.

**Comment by jricher** [comment]
That's strange, it looks like there's a potential misconfiguration or bug on the server side if it's the server login that's causing the issue. I haven't seen this problem though.

However, I'm seeing the openid_connect_login call above being passed a _csrf parameter. This isn't usually the case as this URL needs to be reachable from an external redirect, and this might be the cause of your issue. Try turning off Spring's CSRF protection on just the openid_connect_login URL on the client software and see if that helps.

**Comment by jricher** [comment]
Have you tried this yet? Any luck?
