### ISSUE TITLE
Implicit Flow - no id_token in redirect

### ISSUE THREAD

**Issue by MartinFranzl** [mitreid-connect/OpenID-Connect-Java-Spring-Server#974]
Hey guys, 

I never get a id_token back using the latest sources from here.
I made a custom overlay which uses an apache DS as user repository. Everything really works fine. Also I did some customizations according the customs scopes / claims which I successfully mapped in the id_token. The database also shows me that two tokens (id and access) are created. (oic.access_token)
But I can not finde the place where the id_token is appended to the redirect url. 
Can anyone please give me a sign? :-) 

This is an example request:
/authorize?response_type=token%20id_token&scope=openid+profile+email+vk-roles&client_id=5eabb014-b730-4989-a346-443fc859101c&redirect_uri=http%3A%2F%2Flocalhost%3A63342%2Fsw.bpm.ProcessManager%2Findex.html%3Flogin_response&nonce=abc&state=123

And this is my client configuration:

```json
[  
   {  
      "id":1,
      "clientId":"5eabb014-b730-4989-a346-443fc859101c",
      "clientSecret":null,
      "redirectUris":[  
         "http://localhost:63342/sw.bpm.ProcessManager/index.html?login_response"
      ],
      "clientName":"FM3",
      "clientUri":null,
      "logoUri":null,
      "contacts":[  

      ],
      "tosUri":null,
      "tokenEndpointAuthMethod":"NONE",
      "scope":[  
         "vk-roles",
         "openid",
         "email",
         "profile"
      ],
      "grantTypes":[  
         "implicit"
      ],
      "responseTypes":[  
         "token id_token"
      ],
      "policyUri":null,
      "jwksUri":null,
      "jwks":null,
      "applicationType":"WEB",
      "sectorIdentifierUri":null,
      "subjectType":null,
      "requestObjectSigningAlg":null,
      "userInfoSignedResponseAlg":null,
      "userInfoEncryptedResponseAlg":null,
      "userInfoEncryptedResponseEnc":null,
      "idTokenSignedResponseAlg":null,
      "idTokenEncryptedResponseAlg":null,
      "idTokenEncryptedResponseEnc":null,
      "tokenEndpointAuthSigningAlg":null,
      "defaultMaxAge":60000,
      "requireAuthTime":true,
      "defaultACRvalues":[  

      ],
      "initiateLoginUri":null,
      "postLogoutRedirectUris":[  

      ],
      "requestUris":[  

      ],
      "authorities":[  

      ],
      "accessTokenValiditySeconds":3600,
      "refreshTokenValiditySeconds":null,
      "resourceIds":[  

      ],
      "clientDescription":null,
      "reuseRefreshToken":true,
      "dynamicallyRegistered":true,
      "allowIntrospection":true,
      "idTokenValiditySeconds":600,
      "createdAt":"2015-11-23T14:48:57+0100",
      "clearAccessTokensOnRefresh":true,
      "claimsRedirectUris":[  

      ]
   }
]
```

**Comment by jricher** [comment]
If you're using the implicit flow (the `token` response type) then you'll get the ID token back as part of the hash/fragment in the return URL. If you're using the code flow, it comes back from the token endpoint along with the access token.

**Comment by MartinFranzl** [comment]
Hey jricher,

Yes, that should ne the default behavior.

I have tried all These oprtions but I always get a #access_token no #id_token.

What version are you using? How is your client configured? I am using 1.2.3 Snapshot.

Best regards,

Martin

**Comment by jricher** [comment]
I'm using the current master branch build and running with the simple-web-app demo client, using the code flow. If I try the implicit flow in a browser it also works just fine. Are you sure you're asking for the `openid` scope? Are you looking for the `id_token` member? Note that it's not `#id_token`, the hash part of the URL is actually formatted as an HTTP query parameter set, so you need to parse it.

**Comment by MartinFranzl** [comment]
... member? Note that it's not #id_token, the hash part of the URL is actually formatted as an HTTP query parameter set, so you need to parse it....

Ah ok. So I need to look for: ?id_token=...
I did not try this jet as the spec told me that I have to look for # ...

I'll try this. Thanks a lot!

**Comment by MartinFranzl** [comment]
jricher! You are absolutely right! Thanks a lot. The id_token is served as ?id_token.

Thank you very much!!!

**Comment by jricher** [comment]
Not quite. The `id_token` is served as part of the hash string which is in query parameter format. It could come back as `#id_token=...&access_token=...` or as `#access_token=....&id_token=...`, the order isn't guaranteed. What you need to do is take the whole hash string and put it through a URL query parameter parser (split on `&`, then split on `=`), then pull the values out.
