### ISSUE TITLE
Login to server using email instead of username

### ISSUE THREAD

**Issue by jtaylor10** [mitreid-connect/OpenID-Connect-Java-Spring-Server#975]
Bear with me as I've just started using this library this week!

I am in the process of configuring an overlay for server setup. I have everything working as expected when using usernames (just using the default users for now). What I want to do is to use the email address instead of the username.

What I've done so far:
- Changed the `username` values in `users` and `authorities` tables to be email addresses
  - This works to log in but the userInfo object is not set so no user details are ever shown

I see there is a `UserInfoInterceptor.java` which is registered in `applicationContext.xml` which appears to the item that populates this but it's only looking up by username. 
I also found that there is a `LoginHintExtracter` interface with one implementation `MatchLoginHintsAgainstUsers` which does a lookup based on either the username or email. 

Without knowing the exact purpose of the LoginHintExtracter interfaces, should the UserInfoInterceptor leverage that interface to get the true username after it makes a call to `auth.getName()` so it can support both usernames or email addresses? 

Or is there a much simpler way of doing?

**Comment by praseodym** [comment]
You should probably accept both email and username in your Spring Security AuthenticationProvider/AuthenticationManager. Make sure the resulting UserInfo subject name (`sub`) is static for both login options and you're set.

**Comment by jtaylor10** [comment]
My plan was to never use username at all and just use email.  Usernames are just another thing to remember for a user which already have a unique login which they already remember (email). So I guess the question is.... is there a way to do this with just configuration or do I have to override code to somehow link the UserInfo object by email?

**Comment by praseodym** [comment]
I don't think anything in the codebase assumes something about the format of the username, so I think you should be able to just use email addresses as usernames.

**Comment by jricher** [comment]
Closing this issue as it should be possible with a custom authentication manager or custom login page.
