### ISSUE TITLE
Support for .net client application

### ISSUE THREAD

**Issue by selvarajkumarasamy** [mitreid-connect/OpenID-Connect-Java-Spring-Server#976]
Hi Jricher,
        Please confirm do we have any support for .net client(RP) application or any users using mitreid-connect/OpenID-Connect-Java-Spring-Server as server for client platform apart from java.

Thanks & Regards
Selvaraj.K

**Comment by jricher** [comment]
Any compliant RP can connect to the server regardless of what language the client is implemented in.

**Comment by srmoore** [comment]
Just to confirm... at one point I had an embedded C application talking to the OpenID connect Java Spring Server... as @jricher said, as long as the client is compliant with the spec it should work.

**Comment by selvarajkumarasamy** [comment]
Thanks for the update.
