### ISSUE TITLE
Security: Information leakage via REST API

### ISSUE THREAD

**Issue by TonyFNZ** [mitreid-connect/OpenID-Connect-Java-Spring-Server#978]
The OpenID-Connect-Java-Spring-Server project (openid-connect-server) contains a number of REST API endpoints that are available to all logged in users.

GET /api/clients will return a list of all registered clients
GET /api/scopes will return a list of all available scopes

While there is no direct security risk in the information exposed, there is no default reason to allow any users to enumerate all known clients and scopes.

If the GET /api/approved endpoint is expanded to return the same data fields as GET /api/clients then it should be possible to limit users to only seeing the clients they have approved, and then limit the full list of clients and scopes to only be visible by admin users.

**Comment by jricher** [comment]
You are correct that there's no direct security risk based on the information exposed, and having the information available helps the UI function more smoothly. There is no reason to preemptively filter this.
