### ISSUE TITLE
Getting ID_Token back on request to authorise

### ISSUE THREAD

**Issue by camomiles** [mitreid-connect/OpenID-Connect-Java-Spring-Server#981]
Good afternoon!

I am having troubles getting id_token back from the request to authorise endpoint.
I follow example for OpenID Connect from here -> http://brentertainment.com/oauth2/

On my client I only receive auth_code and state back when user authorises my application, even if I request auth_code and id_token like example above.

How can I get id_token back after that point so I can parse it and get user role out on the front end? 

Thank you!

**Comment by jricher** [comment]
You need to send the `code` to the token endpoint to complete the transaction. This will return the tokens. Alternatively, if you have a completely in-browser client (IE, javascript running inside a browser, not a website served from a server), you could use the implicit flow, but that's got limited applicability and is less secure for non-browser-embedded clients
