### ISSUE TITLE
Deleting refresh token corrupts access_token table

### ISSUE THREAD

**Issue by mtommila** [mitreid-connect/OpenID-Connect-Java-Spring-Server#982]
The access token entity has a unidirectional many-to-one association to refresh token. There are many ways to just delete refresh tokens, this can leave the data in the access_token table in a corrupted state. I.e. the refresh_token_id column contains a value that does not actually exist in the refresh_token table.

Maybe the refresh token entity should also have an association back to the access token entity. This way, when the refresh token is deleted, the link from access_token would be set to null.

Or, alternatively, this would have to be done manually when a refresh token is deleted (find access tokens that point to the refresh token, set the association to null, then delete the refresh token).

Database foreign key constraints would also be one way to enforce that this cannot happen. But there are no foreign key constraints.

**Comment by jricher** [comment]
Where in the code can you delete a refresh token without its attendant access tokens? The token services should take care of this automatically. I'm happy to have it be double-checked though.

**Comment by mtommila** [comment]
We had a data corruption although I'm not entirely sure how it happened. I suspect (since we had two servers running in a cluster) that the clean-up jobs happened to run in parallel. So both servers get a list of access tokens / refresh tokens / authentication holders / authorization codes to be cleaned up, and then start cleaning them up. Only it would happen so that both servers get the same list of entities to be deleted, and then have a race who happens to delete them. The other then fails as the token is already deleted by the other server. At a suitable point of time things end up so that only partial deletion occurs and data is left in a corrupted state.

DefaultOAuth2ProviderTokenService.clearExpiredTokens() removes access tokens, refresh tokens and authentication holders.

DefaultOAuth2AuthorizationCodeService.clearExpiredAuthorizationCodes() removes authorization codes.

We have since configured the clean-up to only run on one of the cluster nodes, and I'm not sure if the data corruption can occur anymore.

One suggestion to possibly make things more robust would be to use bulk deletes instead of a select and then looping through the results and deleting each entity individually.

Also we use Hibernate as the persistence provider instead of EclipseLink. There may be some assumptions that EclipseLink makes that do not hold in Hibernate.

**Comment by jricher** [comment]
Yeah, if you have the cleanup tasks running on two servers like that then things can get weird. We don't do bulk deletes precisely to allow for this type of measured cleanup and deletion to occur.
