### ISSUE TITLE
Forbidden userinfo for authenticated clients

### ISSUE THREAD

**Issue by jimmytheneutrino** [mitreid-connect/OpenID-Connect-Java-Spring-Server#985]
Currently a client authenticated with client credentials 
(see, e.g., http://connect2id.com/blog/client-credentials-grant-support) 
is forbidden to access /userinfo endpoint. 

It seems that there is nothing in the spec (http://openid.net/specs/openid-connect-core-1_0.html#UserInfo) that should forbid it. Or am I wrong?

Implementation details (if you agree that this is a bug):
This is because DefaultClientUserDetailsService (used by clientAuthenticationManager) only gives ROLE_CLIENT to the client authentication (which ends up associated with the issued access token) but UserInfoEndpoint expects the authentication associated with the access token to have ROLE_USER.

The fix would be, e.g., to also allow ROLE_CLIENT in UserInfoEndpoint.

**Comment by jricher** [comment]
You are mistaken in your interpretation -- it makes no sense for a client without a user to get user information. Which user would it be representing? OpenID Connect does not define any action for the client_credentials grant type. We support it in the MITREid Connect server because this is also a general OAuth2 server. I can't speak for the features of the Connect2ID product.

**Comment by jimmytheneutrino** [comment]
Ok but then, what is the proper way for a device without an end-user, say a fridge or some automation server, to get access tokens to access resource servers on its own? 
Ideally, the resource server would employ the same technique for the usual case and for the described case, which would include getting userinfo.

**Comment by jricher** [comment]
You're using OAuth not OpenID connect, then. In which case you want to use either the client credentials flow like you said, or use the device flow, which we don't support yet bc either way you'll not be using the user into endpoint to get things done.

**Comment by chazt3n** [comment]
how would you determine which client is calling your protected resource in this case? Is there a way?

**Comment by jansinger** [comment]
MITREid sets the "azp" claim of the generated Access Token to the Client ID. If this is not sufficient you may either override the ConnectTokenEnhancer and add the needed information as an additional claim or call the Clients API for the details of the Client.
 
azp
OPTIONAL. Authorized party - the party to which the ID Token was issued. If present, it MUST contain the OAuth 2.0 Client ID of this party. This Claim is only needed when the ID Token has a single audience value and that audience is different than the authorized party. It MAY be included even when the authorized party is the same as the sole audience. The azp value is a case sensitive string containing a StringOrURI value.
