### ISSUE TITLE
There is a typo which is causing error when loading clients

### ISSUE THREAD

**Issue by misugijunz** [mitreid-connect/OpenID-Connect-Java-Spring-Server#991]
In my instance, there is a typo cause an error to underscore.js when it is parsing thus we are not able to load manage clients (the progress bar is shown indefinitely). Please check my PR to see the typo.
#990

**Comment by jricher** [comment]
Good catch, I have no idea how my tests worked with this in place!

**Comment by misugijunz** [comment]
I was like have no idea at first (why the progress bar went forever) as well as we just evaluated this to build our own open id system but then I and my friend went through all sources related to client and found this.
