### ISSUE TITLE
Simple Identity provider example with Spring security + Spring REST API

### ISSUE THREAD

**Issue by heditr** [mitreid-connect/OpenID-Connect-Java-Spring-Server#994]
Is there a simple example to see how to use mitreid connect to provide a valid ID token, and of course use this token to make a bearer authentication to call a spring REST operation??
I need really a basic example to understand what are the main components to use in mitreid-connect (for generating an identity) and in spring security to validate the bearer authentication and handle it to execute the operation and return a HTTP response.
Thanks. 

PS: i can't find the full documentation of mitreid-connect project this link [Documentation for the Maven project and Java API](http://mitreid-connect.github.io/)

Another question: Is mitreid-connect a war package that i should deploy to provide identities or its an openid SDK ??

**Comment by jricher** [comment]
The documentation for the project is linked from the main page: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki

As it's a wiki, we welcome contributions to make it better. There you'll see that the project contains both an SDK for a server and client as well as a packaged server that can be built and deployed as a .war file. There are also projects for demonstration clients (simple-web-app) and demonstration custom servers (example-maven-overlay) in the project root: https://github.com/mitreid-connect/

Hope this helps.
