### ISSUE TITLE
ldap-overlay fixed  to v1.1.15, possible to update ?

### ISSUE THREAD

**Issue by patfrat** [mitreid-connect/OpenID-Connect-Java-Spring-Server#995]
I have build a docker image based on ldap-openid-connect-server but it is fixed to v1.1.15 since 8 months ... is it possible to update to the last openid-connect-server v1.2.3 or not ?

**Comment by jricher** [comment]
Sure, it should be fine to update it. That project was put together as an example and it's not really been kept current with releases. We'd be happy to take a patch to the project to put it against the latest 1.2 release (1.2.4 as of this writing).

**Comment by daimor** [comment]
Is there any progress with it, we already have 1.3 release, but ldap-overlay still so old

**Comment by jricher** [comment]
It just needs to be upgraded along with several of the other example projects. Happy to take a pull request but it's low priority at the moment.

**Comment by daimor** [comment]
Well, I have tried to do it by myself, but faced with one error, which I don't know how to solve. daimor/ldap-openid-connect-server@b11ec709358d2380a81cf39cc72d53b8e1f8a283
When I try to authentificate I'm getting this error
```
No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken
```
And I don't understand how to solve it.
