### ISSUE TITLE
zoneinfo claim is converted to JSON as "zone_info"

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#996]
See https://openid.net/specs/openid-connect-basic-1_0.html#zoneinfo

Running conformance tests against openid produces a warning because the expected claim is "zoneinfo" and yet mitreid connect returns "zone_info". 

Reviewing DefaultUserInfo, turns out the JSON rendered explicitly turns that claim into "zone_info"

**Comment by jricher** [comment]
Thanks, looks like nobody's used that claim in production before.

**Comment by mmoayyed** [comment]
Happy to provide a patch. Is this something that can be included in the next patch release? and when might that be, by the way?

**Comment by jricher** [comment]
A patch would be appreciated! It can definitely be in the next release (and likely backported to 1.1), and no precise timeline for that at the moment.

**Comment by mmoayyed** [comment]
Happy to do. PR upcoming. 

Context: I would need this patch to complete the work presented here https://github.com/uchicago/shibboleth-oidc In order for this project to finalize, I'd need it to pass conformance tests which presently issue a warning for the missing claim. It would be great if you could finalize the release plan soon, as time permits. 

It's my understanding that mitreid is also listed as an impl that passes those tests, though I don't see how that might be possible with this issue?

**Comment by jricher** [comment]
Merged and will be included in release, 1.2.4 out shortly.
